/**
 * Khoá Hướng dẫn — Sự kiện, Chat, Bảng tin & Ghi âm (5 trụ).
 */
const { quizItem } = require('./_helpers');
const q = quizItem;

const mkQuiz = (rows) => {
  const n = rows.length;
  const per = Math.max(2, Math.floor(n / 5));
  return {
    tt: rows.slice(0, per),
    td: rows.slice(per, per * 2),
    nl: rows.slice(per * 2, per * 3),
    vh: rows.slice(per * 3, per * 4),
    bc: rows.slice(per * 4),
  };
};

const LESSON_SPECS = [
  {
    num: 1,
    title: 'TT 1: Vì sao cần 4 kênh nội bộ trên CRM',
    summary: 'Sự kiện, chat, bảng tin, ghi âm — một hệ sinh thái, không thay bằng Zalo riêng.',
    pillar: {
      hook: 'Anh Tuấn hỏi giá trên Zalo cá nhân — đồng nghiệp không thấy, sếp không đo KPI. **Mọi việc quan trọng phải trên app.**',
      tuTuong: {
        vaiTro: 'Bạn là **mắt xích** giữa khách hàng và công ty — ghi nhận trên hệ thống = minh bạch.',
        ynghia: [
          '**Sự kiện** — lịch gặp khách, họp, khảo sát có chứng cứ.',
          '**Chat** — trao đổi nhanh, gắn Lead/Deal, không mất tin.',
          '**Bảng tin** — thông báo chính thức, văn hóa công ty.',
          '**Ghi âm** — cuộc gọi có file, đối soát tranh chấp.',
        ],
      },
      tuDuy: {
        mentalModel: 'Zalo cá nhân = **sổ tay riêng**; CRM = **sổ công ty** — hai thứ khác nhau.',
        phanBiet: ['**Trang đầy đủ** _(menu Sidebar)_ vs **Bong bóng / thanh nhanh** _(góc màn hình)_'],
      },
      nguonLuc: {
        manHinh: 'Sidebar CRM → **Sự kiện · Nhóm chat · Bảng tin nội bộ · Cuộc gọi & ghi âm**',
        congCu: ['Sidebar trái', 'Thanh nhanh (SX/VC)', 'Bong bóng chat góc phải', 'Thông báo chuông'],
      },
      vanHanh: {
        steps: [
          'Mở CRM → nhìn Sidebar — tìm 4 mục trên.',
          'Hỏi bản thân: việc này thuộc **Sự kiện**, **Chat**, **Bảng tin** hay **Ghi âm**?',
          'Ghi trên app **trước khi** chuyển sang Zalo cá nhân.',
        ],
        mentor: 'Quy tắc 30 giây: không tìm thấy trên CRM trong 30 giây → hỏi mentor đường menu.',
      },
      baoCaoSua: {
        loiHay: ['Chỉ chat Zalo, không ghi CRM.', 'Tạo sự kiện ngoài lịch công ty.'],
        kpi: 'Tỉ lệ cuộc gọi có ghi âm gắn Lead; sự kiện hoàn thành đúng hạn.',
      },
      tomTat: '4 kênh nội bộ thay Zalo riêng — mọi việc quan trọng trên CRM.',
    },
    quiz: mkQuiz([
      ['Vì sao dùng kênh nội bộ CRM?', ['Lưu lịch sử công ty, handover', 'Chỉ giám sát', 'Tốn pin', 'Không lý do'], [0], 'Tư tưởng.'],
      ['Zalo cá nhân thay CRM?', ['Mất minh bạch team', 'Tốt hơn', 'Bắt buộc', 'Thưởng'], [0], 'Tư tưởng.'],
      ['Ghi âm cuộc gọi giúp?', ['Đối soát nội dung, tranh chấp', 'Nghe nhạc', 'Xóa Lead', 'In BG'], [0], 'Tư tưởng.'],
      ['Trang đầy đủ vs bong bóng?', ['Cùng dữ liệu, khác cách mở', 'Khác hệ thống', 'Không liên quan', 'Chỉ admin'], [0], 'Tư duy.'],
      ['Bảng tin dùng cho?', ['Thông báo chính thức công ty', 'Chat khách', 'In HĐ', 'Xóa Deal'], [0], 'Tư duy.'],
      ['4 mục Sidebar?', ['Sự kiện, Nhóm chat, Bảng tin, Ghi âm', 'Lead, Deal, KPI, BG', 'Chỉ chat', 'Chỉ email'], [0], 'Nguồn lực.'],
      ['Bong bóng chat ở?', ['Góc phải màn hình', 'Giữa', 'Sidebar', 'Email'], [0], 'Nguồn lực.'],
      ['Thanh nhanh SX/VC có?', ['Bảng tin, Sự kiện, Tin nhắn', 'Chỉ thùng rác', 'Chỉ KPI', 'Không có'], [0], 'Nguồn lực.'],
      ['Việc quan trọng — làm trước?', ['Ghi trên CRM', 'Zalo riêng', 'Sổ tay', 'Bỏ qua'], [0], 'Vận hành.'],
      ['Không tìm thấy menu — sửa?', ['Hỏi mentor / Sidebar', 'Xóa app', 'Đổi pass', 'Thua Lead'], [0], 'Vận hành.'],
      ['Chỉ Zalo không CRM — hậu quả?', ['Đồng nghiệp mù, KPI không đối soát', 'Tốt', 'Thưởng', 'Nhanh hơn'], [0], 'Báo cáo.'],
      ['Tự kiểm bài 1?', ['Biết 4 kênh + đường Sidebar', 'Chỉ biết chat', 'Chỉ biết Lead', 'Không cần'], [0], 'Báo cáo.'],
    ]),
    checklist: [
      'Mở Sidebar CRM — chỉ ra 4 mục: Sự kiện, Nhóm chat, Bảng tin, Ghi âm.',
      'Giải thích cho đồng nghiệp khác biệt trang đầy đủ vs bong bóng.',
    ],
  },
  {
    num: 2,
    title: 'TT 2: Đường vào — Sidebar và thanh nhanh',
    summary: 'Menu trái CRM; thanh nhanh ở dashboard SX/VC.',
    pillar: {
      hook: 'Cùng một tính năng — mở được từ **Sidebar** hoặc **icon hàng loạt** trên dashboard Xưởng.',
      tuTuong: { vaiTro: 'Biết **2 đường vào** = tiết kiệm thời gian mỗi ngày.', ynghia: ['Sidebar ổn định trên mọi trang CRM.'] },
      tuDuy: {
        bang: '| Cách mở | Khi nào dùng |\n|---|---|\n| **Sidebar → Sự kiện** | Làm việc sâu, lọc lịch |\n| **Thanh nhanh (icon)** | Đang ở dashboard SX/VC, cần mở nhanh |',
      },
      nguonLuc: {
        manHinh: '**CRM → Sidebar** hoặc **Xưởng SX / VC → Dashboard → thanh icon**',
        congCu: ['Sự kiện', 'Bảng tin', 'Tin nhắn', 'Có gì mới (cập nhật phần mềm)'],
      },
      vanHanh: {
        steps: ['Sidebar → **Sự kiện** (`/crm/events`).', 'Sidebar → **Nhóm chat** (`/crm/messenger`).', 'Sidebar → **Bảng tin nội bộ** (`/social`).', 'Sidebar → **Cuộc gọi & ghi âm** (`/tools/voice-recordings`).', 'Thử **Xưởng VC → Dashboard** → icon Bảng tin / Sự kiện.'],
        mentor: 'Bookmark 4 URL trên trình duyệt nếu hay dùng.',
      },
      baoCaoSua: { loiHay: ['Tìm mãi vì không biết Sidebar.'], tomTat: 'Sidebar = đường chính; thanh nhanh = shortcut trên dashboard khối.' },
      tomTat: 'Sidebar CRM + thanh nhanh SX/VC — cùng 4 kênh.',
    },
    quiz: mkQuiz([
      ['Sidebar Sự kiện mở?', ['/crm/events', '/social', '/login', '/kpi'], [0], 'Nguồn lực.'],
      ['Nhóm chat trang đầy đủ?', ['/crm/messenger', '/social', '/events', '/tools'], [0], 'Nguồn lực.'],
      ['Bảng tin nội bộ?', ['/social', '/crm/leads', '/updates', '/login'], [0], 'Nguồn lực.'],
      ['Ghi âm?', ['/tools/voice-recordings', '/crm/events', '/messenger', '/kpi'], [0], 'Nguồn lực.'],
      ['Thanh nhanh có ở?', ['Dashboard SX/VC', 'Chỉ mobile', 'Email', 'Blocklist'], [0], 'Tư duy.'],
      ['Icon Bảng tin thanh nhanh?', ['Mở /social', 'Xóa Lead', 'In BG', 'Đăng xuất'], [0], 'Vận hành.'],
      ['Sidebar vs thanh nhanh?', ['Cùng đích, khác vị trí', 'Khác app', 'Không liên quan', 'Chỉ admin'], [0], 'Tư duy.'],
      ['Bookmark URL?', ['Vào nhanh', 'Cấm', 'Xóa CRM', 'Thua'], [0], 'Mẹo.'],
      ['Không thấy menu?', ['Cuộn Sidebar / App Switcher', 'Cài Windows', 'Xóa Deal', 'Thua'], [0], 'Báo cáo.'],
      ['Có gì mới (Megaphone)?', ['Release notes phần mềm', 'Bảng tin nội bộ', 'Ghi âm', 'Lead'], [0], 'Phân biệt.'],
      ['2 đường vào giúp?', ['Tiết kiệm click', 'Tranh KPI', 'Xóa chat', 'In PDF'], [0], 'Tư tưởng.'],
      ['Tự kiểm bài 2?', ['Mở được 4 URL từ Sidebar', 'Chỉ 1 URL', 'Không cần', 'Chỉ mobile'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Mở lần lượt 4 URL từ Sidebar.', 'Mở dashboard VC → bấm icon Bảng tin → vào /social.'],
  },
  {
    num: 3,
    title: 'TT 3: Sự kiện — trang đầy đủ & lịch tháng',
    summary: 'CRM → Sự kiện; tab Lịch; lọc khối Kinh doanh / SX / VC.',
    pillar: {
      hook: 'Sáng mai có **3 cuộc khảo sát** — mở **Sự kiện → Lịch** là thấy cả tuần.',
      tuTuong: { vaiTro: 'Sự kiện = **cam kết thời gian** với khách và nội bộ — có ngày giờ, có người tham gia.', ynghia: ['Không dùng lịch giấy — tránh trùng lịch team.'] },
      tuDuy: { phanBiet: ['**Lịch tháng** _(nhìn tổng)_ vs **Feed danh sách** _(lọc chi tiết)_'] },
      nguonLuc: {
        manHinh: '**CRM → Sự kiện** (`/crm/events`)',
        congCu: ['Tab Lịch', 'Lọc khối (Kinh doanh, SX, VC, Chung)', 'Lọc công ty / nhân viên (admin)', 'Tìm kiếm'],
      },
      vanHanh: {
        steps: ['Sidebar → **Sự kiện**.', 'Tab **Lịch** — xem tháng hiện tại.', 'Lọc **Khối Kinh doanh** nếu bạn sales.', 'Click một ô ngày — xem sự kiện trong ngày.', 'Badge màu = trạng thái (kế hoạch / đang / xong).'],
        mentor: 'Màu đỏ / quá hạn — xử lý trước khi tạo sự kiện mới.',
      },
      baoCaoSua: { loiHay: ['Không lọc khối — nhầm sự kiện xưởng.'], kpi: 'Sự kiện hoàn thành đúng trạng thái.' },
      tomTat: 'Sự kiện → Lịch tháng + lọc khối — biết việc cả tuần.',
    },
    quiz: mkQuiz([
      ['Sự kiện dùng để?', ['Lên lịch gặp khách, họp, khảo sát', 'Chat Zalo', 'In BG', 'Xóa Lead'], [0], 'Tư tưởng.'],
      ['Trang Sự kiện?', ['/crm/events', '/social', '/crm/messenger', '/kpi'], [0], 'Nguồn lực.'],
      ['Tab mặc định hay dùng?', ['Lịch tháng', 'Chỉ chat', 'Chỉ KPI', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Lọc khối Kinh doanh?', ['Chỉ sự kiện CRM/sales', 'Chỉ SX', 'Chỉ VC', 'Xóa hết'], [0], 'Vận hành.'],
      ['Trạng thái «Đã lên kế hoạch»?', ['Chưa bắt đầu', 'Đã hủy', 'Đã xong', 'Lead mới'], [0], 'Tư duy.'],
      ['Click ô ngày trên lịch?', ['Xem sự kiện ngày đó', 'Xóa tháng', 'Đăng xuất', 'In PDF'], [0], 'Vận hành.'],
      ['Sự kiện trùng lịch giấy?', ['Dễ trùng, mất đồng bộ', 'Tốt hơn', 'Bắt buộc', 'Thưởng'], [0], 'Tư tưởng.'],
      ['Admin lọc công ty?', ['Xem sự kiện theo công ty', 'Xóa user', 'In lương', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Feed vs Lịch?', ['Lịch = tổng tháng; feed = danh sách lọc', 'Giống hệt', 'Không liên quan', 'Chỉ mobile'], [0], 'Tư duy.'],
      ['Quá hạn — ưu tiên?', ['Xử lý / cập nhật trạng thái trước', 'Bỏ qua', 'Tạo mới', 'Xóa CRM'], [0], 'Báo cáo.'],
      ['Không lọc khối — lỗi?', ['Nhầm sự kiện khối khác', 'Tốt', 'Thưởng', 'Nhanh hơn'], [0], 'Báo cáo.'],
      ['Tự kiểm bài 3?', ['Mở Lịch + lọc khối', 'Chỉ feed', 'Không cần', 'Chỉ chat'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Mở /crm/events → tab Lịch.', 'Lọc khối Kinh doanh → xem sự kiện hôm nay.'],
  },
  {
    num: 4,
    title: 'TT 4: Sự kiện — tạo, tham gia, bình luận',
    summary: 'Tạo sự kiện; xác nhận tham gia; bình luận; đổi trạng thái.',
    pillar: {
      hook: 'Khách hẹn **14h khảo sát** — tạo sự kiện gắn địa chỉ, mời đồng nghiệp, họ **xác nhận tham gia** trên app.',
      tuTuong: { vaiTro: 'Người tạo sự kiện **chịu trách nhiệm** cập nhật trạng thái sau khi làm xong.', ynghia: ['Bình luận trên sự kiện = biên bản ngắn, không mất trên Zalo.'] },
      tuDuy: { phanBiet: ['**planned** → **in_progress** → **completed** / **cancelled**'] },
      nguonLuc: { manHinh: 'Trang Sự kiện — nút **+ Tạo sự kiện**', congCu: ['Form tạo', 'Danh sách tham gia', 'Bình luận', 'Gắn Lead/Deal (khi có)'] },
      vanHanh: {
        steps: ['**+ Tạo sự kiện** — tiêu đề, giờ, địa điểm, khối.', 'Chọn **người tham gia**.', 'Gửi — thành viên nhận thông báo.', 'Người được mời → **Xác nhận / Từ chối**.', 'Sau buổi gặp → đổi **Hoàn thành** + ghi **bình luận** kết quả.'],
        mentor: 'Hủy sự kiện phải ghi lý do — tránh hiểu nhầm với khách.',
      },
      baoCaoSua: { loiHay: ['Quên đổi trạng thái completed.', 'Chỉ chat, không bình luận trên sự kiện.'], tomTat: 'Tạo → mời → xác nhận → làm → completed + comment.' },
      tomTat: 'Tạo sự kiện, mời người, xác nhận, hoàn thành + bình luận.',
    },
    quiz: mkQuiz([
      ['Tạo sự kiện cần tối thiểu?', ['Tiêu đề + thời gian', 'Chỉ ảnh', 'Chỉ chat', 'MST'], [0], 'Vận hành.'],
      ['Người được mời làm gì?', ['Xác nhận / Từ chối trên app', 'Chỉ Zalo', 'In PDF', 'Xóa Lead'], [0], 'Vận hành.'],
      ['Sau buổi gặp?', ['Đổi Hoàn thành + bình luận', 'Bỏ qua', 'Xóa sự kiện', 'Chỉ KPI'], [0], 'Vận hành.'],
      ['Bình luận sự kiện lưu ở?', ['Trên app, gắn sự kiện', 'Zalo riêng', 'Sổ tay', 'Email cá nhân'], [0], 'Tư tưởng.'],
      ['Hủy sự kiện?', ['Ghi lý do (cancelled)', 'Im lặng', 'Xóa Lead', 'Thưởng'], [0], 'Báo cáo.'],
      ['Gắn Lead lên sự kiện?', ['Liên kết CRM khi có', 'Cấm', 'Chỉ Deal', 'Chỉ admin'], [0], 'Nguồn lực.'],
      ['in_progress nghĩa?', ['Đang thực hiện', 'Đã hủy', 'Lead mới', 'Đã xong'], [0], 'Tư duy.'],
      ['Người tạo chịu trách nhiệm?', ['Cập nhật trạng thái cuối', 'Không ai', 'Chỉ admin', 'Khách hàng'], [0], 'Tư tưởng.'],
      ['Thông báo mời sự kiện?', ['Chuông / thông báo app', 'Chỉ email ngoài', 'Không có', 'SMS bắt buộc'], [0], 'Nguồn lực.'],
      ['Comment thay Zalo?', ['Lịch sử tập trung', 'Không nên', 'Cấm', 'Chậm hơn'], [0], 'Tư duy.'],
      ['Quên completed?', ['Báo cáo sai, đồng nghiệp mù', 'Không sao', 'Thưởng', 'Tự xóa'], [0], 'Báo cáo.'],
      ['Tự kiểm bài 4?', ['Tạo + mời + đổi trạng thái', 'Chỉ xem lịch', 'Không cần', 'Chỉ chat'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Tạo sự kiện thử (ngày mai).', 'Thêm bình luận sau khi đổi Hoàn thành.'],
  },
  {
    num: 5,
    title: 'TT 5: Cuộc gọi & ghi âm — trang đầy đủ',
    summary: 'Sidebar → Cuộc gọi & ghi âm; danh sách file; lọc theo nhân viên.',
    pillar: {
      hook: 'Khách khiếu nại «anh hứa giá X» — mở **Ghi âm**, nghe lại, **đối soát** trong 1 phút.',
      tuTuong: { vaiTro: 'Ghi âm bảo vệ **bạn và công ty** — không phải để «bắt bẻ» nhau.', ynghia: ['Cuộc gọi quan trọng nên có file trên hệ thống.'] },
      tuDuy: { phanBiet: ['**Ghi trực tiếp trên web** vs **Upload file** từ máy / tổng đài'] },
      nguonLuc: {
        manHinh: '**Cuộc gọi & ghi âm** (`/tools/voice-recordings`)',
        congCu: ['Danh sách bản ghi', 'Nghe / tải', 'Ghi mới (mic)', 'Upload', 'Lọc nhân viên (admin)'],
      },
      vanHanh: {
        steps: ['Sidebar → **Cuộc gọi & ghi âm**.', 'Xem danh sách — sắp xếp mới nhất.', 'Bấm **Play** nghe thử.', 'Admin: lọc theo **nhân viên** để hỗ trợ.', 'Ghi chú SĐT / hướng gọi đến-đi nếu có.'],
        mentor: 'Sau cuộc gọi quan trọng — upload hoặc ghi ngay, đừng để cuối ngày.',
      },
      baoCaoSua: { loiHay: ['Không ghi âm — tranh cãi không chứng cứ.'], kpi: 'Tỉ lệ cuộc gọi sales có file gắn Lead.' },
      tomTat: 'Trang ghi âm — danh sách, nghe, ghi/upload; admin lọc NV.',
    },
    quiz: mkQuiz([
      ['Ghi âm giúp?', ['Đối soát nội dung cuộc gọi', 'Nghe nhạc', 'Xóa Lead', 'In BG'], [0], 'Tư tưởng.'],
      ['Đường dẫn trang?', ['/tools/voice-recordings', '/social', '/crm/events', '/kpi'], [0], 'Nguồn lực.'],
      ['Admin lọc?', ['Theo nhân viên', 'Theo màu tóc', 'Theo Lead only', 'Không lọc'], [0], 'Nguồn lực.'],
      ['Ghi trên web vs upload?', ['Cùng lưu danh sách', 'Khác app', 'Upload cấm', 'Chỉ mobile'], [0], 'Tư duy.'],
      ['Sau cuộc gọi quan trọng?', ['Ghi/upload sớm', 'Chờ tuần sau', 'Chỉ Zalo', 'Xóa'], [0], 'Vận hành.'],
      ['Play trên trang?', ['Nghe trực tiếp', 'Chỉ tải về', 'Chỉ admin', 'Cấm'], [0], 'Vận hành.'],
      ['Không ghi âm — rủi ro?', ['Tranh cãi không bằng chứng', 'Tốt hơn', 'Thưởng', 'Nhanh'], [0], 'Báo cáo.'],
      ['Menu Sidebar?', ['Cuộc gọi & ghi âm', 'Chỉ Deal', 'Chỉ chat', 'Chỉ KPI'], [0], 'Nguồn lực.'],
      ['Ghi chú SĐT?', ['Tìm lại dễ hơn', 'Cấm', 'Chỉ admin', 'Không cần'], [0], 'Vận hành.'],
      ['Gọi đến / gọi đi?', ['Phân loại hướng cuộc gọi', 'Không có', 'Chỉ chat', 'Lead stage'], [0], 'Tư duy.'],
      ['Cuối ngày mới upload?', ['Dễ quên — nên làm ngay', 'Tốt', 'Bắt buộc', 'Thưởng'], [0], 'Báo cáo.'],
      ['Tự kiểm bài 5?', ['Mở trang + nghe 1 file', 'Chỉ sidebar', 'Không cần', 'Chỉ chat'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Mở /tools/voice-recordings.', 'Nghe thử một bản ghi (hoặc xem danh sách).'],
  },
  {
    num: 6,
    title: 'TT 6: Ghi âm — gắn Lead, lịch âm thanh',
    summary: 'Liên kết bản ghi với Lead/Deal; lịch theo ngày; quét SĐT.',
    pillar: {
      hook: 'File ghi âm **không gắn Lead** = đồng nghiệp mở Lead không nghe được cuộc gọi đó.',
      tuTuong: { vaiTro: 'Gắn Lead = **nối giọng nói với hành trình khách**.', ynghia: ['Một khách — một timeline: nhiệm vụ + ghi âm + sự kiện.'] },
      tuDuy: { mentalModel: 'Ghi âm là **Hoạt động có file đính kèm** — phải nằm đúng Lead.' },
      nguonLuc: { manHinh: 'Trang ghi âm — cột **Gắn Lead** / **Liên kết CRM**', congCu: ['Tìm Lead theo SĐT', 'Lịch âm thanh (calendar panel)', 'Ghi chú cuộc gọi'] },
      vanHanh: {
        steps: ['Sau ghi/upload → **Gắn Lead** (tìm mã hoặc SĐT).', 'Mở Lead → tab **Hoạt động** — thấy file.', 'Dùng **lịch** trên trang ghi âm xem theo ngày.', 'Ghi **ghi chú** ngắn: khách hỏi gì, cam kết gì.'],
        mentor: 'Quét SĐT trùng Lead trước khi gắn — tránh gắn nhầm khách.',
      },
      baoCaoSua: { loiHay: ['File nổi không gắn Lead.', 'Gắn nhầm SĐT.'], tomTat: 'Ghi → gắn Lead → kiểm trên tab Hoạt động.' },
      tomTat: 'Gắn mọi file quan trọng vào Lead; kiểm trên Hoạt động.',
    },
    quiz: mkQuiz([
      ['Gắn Lead để?', ['Đồng nghiệp thấy trên timeline KH', 'Xóa file', 'In BG', 'Thưởng'], [0], 'Tư tưởng.'],
      ['Xem file từ Lead?', ['Tab Hoạt động / Tài liệu', 'Chỉ chat', 'Chỉ KPI', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Lịch trên trang ghi âm?', ['Xem bản ghi theo ngày', 'Tạo sự kiện', 'Chat', 'In lương'], [0], 'Nguồn lực.'],
      ['File không gắn Lead?', ['Mất ngữ cảnh', 'Tốt', 'Bắt buộc', 'Thưởng'], [0], 'Báo cáo.'],
      ['Gắn nhầm SĐT?', ['Sửa link — gắn đúng Lead', 'Xóa Lead', 'Bỏ qua', 'Thua'], [0], 'Báo cáo.'],
      ['Ghi chú sau gọi?', ['Cam kết / câu hỏi khách', 'Không cần', 'Chỉ emoji', 'MST'], [0], 'Vận hành.'],
      ['Timeline KH gồm?', ['NV + ghi âm + sự kiện', 'Chỉ chat Zalo', 'Chỉ BG', 'Chỉ email'], [0], 'Tư duy.'],
      ['Tìm Lead gắn?', ['SĐT / mã Lead', 'Chỉ tên công ty', 'Chỉ KPI', 'Random'], [0], 'Vận hành.'],
      ['Deal cũng gắn được?', ['Có — pipeline Deal', 'Không', 'Chỉ admin', 'Chỉ SX'], [0], 'Nguồn lực.'],
      ['Quét SĐT trước gắn?', ['Tránh nhầm khách', 'Cấm', 'Chậm', 'Không cần'], [0], 'Vận hành.'],
      ['File nổi — sửa?', ['Gắn lại đúng Lead', 'Xóa CRM', 'Bỏ qua', 'Chat Zalo'], [0], 'Báo cáo.'],
      ['Tự kiểm bài 6?', ['Gắn thử 1 file + xem trên Lead', 'Chỉ nghe', 'Không cần', 'Chỉ lịch'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Gắn một bản ghi (hoặc mô phỏng) vào Lead.', 'Mở Lead → kiểm tra tab Hoạt động/Tài liệu.'],
  },
  {
    num: 7,
    title: 'TT 7: Nhóm chat — trang đầy đủ',
    summary: '/crm/messenger — danh sách hội thoại, nhóm, tìm kiếm.',
    pillar: {
      hook: 'Cần hỏi kỹ thuật **ngay** — mở **Nhóm chat** toàn màn hình, tìm nhóm «Kỹ thuật Q7», gửi ảnh hiện trường.',
      tuTuong: { vaiTro: 'Chat nội bộ **không thay** ghi chú trên Lead — bổ sung trao đổi nhanh.', ynghia: ['Tin quan trọng vẫn tóm tắt lên Lead sau chat.'] },
      tuDuy: { phanBiet: ['**Trang /crm/messenger** _(nhiều hội thoại)_ vs **Bong bóng** _(1–2 cửa sổ nhỏ)_'] },
      nguonLuc: {
        manHinh: '**Nhóm chat** (`/crm/messenger`) — layout 3 cột',
        congCu: ['Danh sách hội thoại', 'Khung chat giữa', 'Panel thành viên / media', 'Tìm kiếm', 'Ghim hội thoại'],
      },
      vanHanh: {
        steps: ['Sidebar → **Nhóm chat**.', 'Chọn hội thoại bên trái.', 'Gõ tin + **Enter** gửi.', 'Đính kèm **ảnh / file** (icon kẹp).', '**Ghim** hội thoại hay dùng lên đầu.'],
        mentor: 'Tên nhóm rõ ràng — «Kỹ thuật Q7» tốt hơn «Nhóm 1».',
      },
      baoCaoSua: { loiHay: ['Chỉ chat, không tóm tắt lên Lead.'], tomTat: 'Trang messenger — chọn hội thoại, gửi tin/file, ghim.' },
      tomTat: 'Nhóm chat toàn màn — 3 cột; gửi tin, file, ghim.',
    },
    quiz: mkQuiz([
      ['Trang chat đầy đủ?', ['/crm/messenger', '/social', '/events', '/voice'], [0], 'Nguồn lực.'],
      ['Chat thay ghi chú Lead?', ['Không — bổ sung, vẫn tóm tắt Lead', 'Thay hoàn toàn', 'Cấm Lead', 'Chỉ admin'], [0], 'Tư tưởng.'],
      ['Layout 3 cột?', ['Danh sách | chat | info', 'Chỉ 1 cột', 'Chỉ KPI', 'Chỉ lịch'], [0], 'Nguồn lực.'],
      ['Ghim hội thoại?', ['Lên đầu danh sách', 'Xóa nhóm', 'Khóa Lead', 'In PDF'], [0], 'Vận hành.'],
      ['Gửi ảnh hiện trường?', ['Đính kèm file trong chat', 'Chỉ email', 'Chỉ bảng tin', 'Cấm'], [0], 'Vận hành.'],
      ['Trang vs bong bóng?', ['Trang = nhiều room; bong bóng = nhanh', 'Khác app', 'Không liên quan', 'Chỉ mobile'], [0], 'Tư duy.'],
      ['Tìm kiếm trên trang?', ['Tìm nhân viên / nhóm', 'Tìm Lead only', 'Không có', 'Chỉ admin'], [0], 'Nguồn lực.'],
      ['Enter gửi tin?', ['Gửi message', 'Đăng xuất', 'Xóa Deal', 'In BG'], [0], 'Vận hành.'],
      ['Tên nhóm mơ hồ?', ['Khó tìm — đặt tên rõ', 'Tốt', 'Bắt buộc', 'Thưởng'], [0], 'Báo cáo.'],
      ['Tin quan trọng sau chat?', ['Tóm tắt lên Lead', 'Bỏ qua', 'Chỉ Zalo', 'Xóa chat'], [0], 'Báo cáo.'],
      ['Sidebar mở chat?', ['Nhóm chat', 'Chỉ Deal', 'Chỉ KPI', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Tự kiểm bài 7?', ['Mở /crm/messenger + gửi tin thử', 'Chỉ bong bóng', 'Không cần', 'Chỉ bảng tin'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Mở /crm/messenger.', 'Gửi một tin (hoặc mở hội thoại có sẵn).'],
  },
  {
    num: 8,
    title: 'TT 8: Chat Lead, phòng ban & trạng thái online',
    summary: 'Chat gắn Lead; chat phòng ban; chấm xanh online; thông báo.',
    pillar: {
      hook: 'Mở Lead **Chị Lan** → tab chat — thấy **online** → gửi tin ngay, khách không bị bỏ rơi.',
      tuTuong: { vaiTro: 'Chat Lead = **trao đổi trong ngữ cảnh khách** — không lẫn nhóm chém gió.', ynghia: ['Online/offline giúp biết ai phản hồi được.'] },
      tuDuy: { phanBiet: ['**Chat Lead** _(gắn mã Lead)_ · **Chat phòng ban** _(theo phòng ban)_ · **Nhóm nội bộ** _(tự tạo)_'] },
      nguonLuc: { manHinh: 'Lead detail → chat · Messenger → **Phòng ban** · **Đang hoạt động**', congCu: ['Lead chat tab', 'Dept chat', 'Online dot xanh', 'Thông báo push/chuông'] },
      vanHanh: {
        steps: ['Mở **Lead** → panel/tab chat.', 'Hoặc Messenger → chọn **Lead** / **Phòng ban**.', 'Nhìn **chấm xanh** = đang online.', 'Đọc **thông báo** — bấm mở đúng hội thoại.', 'Trả lời trong **5–15 phút** giờ hành chính.'],
        mentor: 'Không spam @all — chỉ khi khẩn cấp thật.',
      },
      baoCaoSua: { loiHay: ['Chat Lead nhưng không cập nhật stage Lead.'], tomTat: 'Lead chat + dept chat + online + thông báo.' },
      tomTat: 'Phân loại chat Lead/dept/nhóm; online; trả lời qua thông báo.',
    },
    quiz: mkQuiz([
      ['Chat Lead mở từ?', ['Trang chi tiết Lead', 'Chỉ bảng tin', 'Chỉ KPI', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Chấm xanh?', ['Đang online', 'Offline', 'Lead Hot', 'Deal thua'], [0], 'Nguồn lực.'],
      ['Chat phòng ban?', ['Theo phòng ban công ty', 'Theo khách hàng', 'Chỉ admin', 'Chỉ Zalo'], [0], 'Tư duy.'],
      ['Thông báo tin nhắn?', ['Mở đúng hội thoại', 'Xóa Lead', 'In PDF', 'KPI'], [0], 'Vận hành.'],
      ['Chat Lead vs nhóm chung?', ['Lead = ngữ cảnh KH cụ thể', 'Giống hệt', 'Không liên quan', 'Cấm Lead'], [0], 'Tư duy.'],
      ['Trang Đang hoạt động?', ['Ai online trong công ty', 'Chỉ KPI', 'Chỉ BG', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Spam @all?', ['Chỉ khi khẩn cấp', 'Luôn luôn', 'Cấm chat', 'Thưởng'], [0], 'Báo cáo.'],
      ['Chat xong — Lead?', ['Cập nhật stage/ghi chú nếu cần', 'Bỏ qua', 'Xóa Lead', 'Chỉ chat'], [0], 'Báo cáo.'],
      ['Offline đồng nghiệp?', ['Để tin — họ đọc sau', 'Gọi liên tục', 'Xóa nhóm', 'Thua'], [0], 'Vận hành.'],
      ['3 loại chat?', ['Lead, phòng ban, nhóm', 'Chỉ Zalo', 'Chỉ email', 'Chỉ bảng tin'], [0], 'Tư duy.'],
      ['Phản hồi giờ HC?', ['5–15 phút mục tiêu', '1 tuần', 'Không cần', '1 năm'], [0], 'Vận hành.'],
      ['Tự kiểm bài 8?', ['Mở chat Lead + thấy online', 'Chỉ trang messenger', 'Không cần', 'Chỉ ghi âm'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Mở một Lead → tìm chat.', 'Xem trang Đang hoạt động (Sidebar).'],
  },
  {
    num: 9,
    title: 'TT 9: Bong bóng chat — MessengerDock',
    summary: 'Icon góc phải; mở nhiều cửa sổ nhỏ; không rời trang Lead.',
    pillar: {
      hook: 'Đang kéo Kanban — khách nhắn **Zalo nội bộ app** — bong bóng **bật lên góc phải**, trả lời **không mất Kanban**.',
      tuTuong: { vaiTro: 'Bong bóng = **đa nhiệm** — CRM vẫn mở phía sau.', ynghia: ['Dùng khi cần trả lời nhanh, không cần full messenger.'] },
      tuDuy: { mentalModel: 'Bong bóng giống **Facebook Messenger mini** — cùng tin nhắn với trang đầy đủ.' },
      nguonLuc: {
        manHinh: 'Góc **phải dưới** — icon tròn chat + thanh dock',
        congCu: ['Launcher «Tìm nhân viên & nhóm chat»', 'Cửa sổ thu nhỏ', 'Lead chat bubble', 'Dept bubble', 'Toast tin mới'],
      },
      vanHanh: {
        steps: ['Ở bất kỳ trang CRM → bấm **icon chat góc phải**.', 'Tìm nhân viên / nhóm → mở **cửa sổ bong bóng**.', '**Thu nhỏ / đóng** từng cửa sổ.', 'Kéo nhiều bong bóng — xếp cạnh nhau.', '**Mở rộng** → sang trang /crm/messenger nếu cần.'],
        mentor: 'Đóng bong bóng không = rời phòng chat — tin vẫn lưu.',
      },
      baoCaoSua: { loiHay: ['Tưởng đóng bong bóng = mất tin.', 'Không thấy icon — bị che modal.'], tomTat: 'Icon góc phải → bong bóng → thu nhỏ/ mở rộng.' },
      tomTat: 'MessengerDock góc phải — chat nhanh không rời trang.',
    },
    quiz: mkQuiz([
      ['Bong bóng ở đâu?', ['Góc phải màn hình', 'Sidebar trái', 'Giữa Kanban', 'Email'], [0], 'Nguồn lực.'],
      ['Cùng dữ liệu trang đầy đủ?', ['Cùng hệ thống chat', 'Khác app', 'Không sync', 'Chỉ admin'], [0], 'Tư duy.'],
      ['Launcher mở?', ['Danh sách NV & nhóm', 'Chỉ Lead', 'Chỉ KPI', 'Blocklist'], [0], 'Vận hành.'],
      ['Đóng bong bóng?', ['Tin vẫn lưu', 'Mất hết tin', 'Xóa Lead', 'Đăng xuất'], [0], 'Tư duy.'],
      ['Khi nào dùng bong bóng?', ['Đa nhiệm trên Kanban/Lead', 'Chỉ in PDF', 'Chỉ KPI', 'Không bao giờ'], [0], 'Tư tưởng.'],
      ['Mở rộng từ bong bóng?', ['Sang /crm/messenger', 'Sang Zalo', 'Xóa chat', 'Blocklist'], [0], 'Vận hành.'],
      ['Nhiều cửa sổ?', ['Xếp cạnh nhau được', 'Chỉ 1', 'Cấm', 'Chỉ admin'], [0], 'Vận hành.'],
      ['Toast tin mới?', ['Thông báo nhanh', 'Xóa Lead', 'In BG', 'KPI'], [0], 'Nguồn lực.'],
      ['Icon bị che?', ['Đóng modal/popup trước', 'Cài lại Windows', 'Xóa Deal', 'Thua'], [0], 'Báo cáo.'],
      ['Dept bubble?', ['Chat phòng ban thu nhỏ', 'Chỉ bảng tin', 'Chỉ ghi âm', 'KPI'], [0], 'Nguồn lực.'],
      ['Kanban + chat?', ['Bong bóng giữ Kanban', 'Phải thoát CRM', 'Cấm', 'Chỉ mobile'], [0], 'Vận hành.'],
      ['Tự kiểm bài 9?', ['Mở launcher + 1 bong bóng', 'Chỉ trang messenger', 'Không cần', 'Chỉ sự kiện'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Bấm icon chat góc phải → mở launcher.', 'Mở một bong bóng → thu nhỏ → mở lại.'],
  },
  {
    num: 10,
    title: 'TT 10: Bảng tin nội bộ — trang đầy đủ',
    summary: '/social — feed công ty; lọc phạm vi; đọc thông báo chính thức.',
    pillar: {
      hook: 'Công ty đăng **chính sách nghỉ Tết** trên **Bảng tin** — ai không vào đọc = lỡ thông tin chính thức.',
      tuTuong: { vaiTro: 'Bảng tin = **loa phường có lưu lịch sử** — khác chat riêng.', ynghia: ['HR / admin đăng; nhân viên đọc và tương tác.'] },
      tuDuy: { phanBiet: ['**Bảng tin /social** _(post công ty)_ vs **Có gì mới /updates** _(cập nhật phần mềm)_'] },
      nguonLuc: {
        manHinh: '**Bảng tin nội bộ** (`/social`)',
        congCu: ['Feed bài viết', 'Lọc công ty (admin)', 'Hồ sơ xã hội /social/u/…', 'Sidebar Kiến thức'],
      },
      vanHanh: {
        steps: ['Sidebar → **Bảng tin nội bộ**.', 'Cuộn feed — đọc bài **ghim / mới**.', 'Admin: lọc **công ty** nếu nhiều chi nhánh.', 'Bấm **avatar** → xem hồ sơ đồng nghiệp.', 'Check **1 lần/ngày** đầu ca.'],
        mentor: 'Bài quan trọng — reaction hoặc comment «Đã đọc» để admin biết.',
      },
      baoCaoSua: { loiHay: ['Nhầm /updates với /social.'], tomTat: 'Bảng tin = thông báo công ty; /social; đọc đầu ca.' },
      tomTat: '/social = bảng tin công ty; khác «Có gì mới» phần mềm.',
    },
    quiz: mkQuiz([
      ['Bảng tin URL?', ['/social', '/updates', '/crm/events', '/messenger'], [0], 'Nguồn lực.'],
      ['Bảng tin vs Có gì mới?', ['Social = công ty; Updates = tính năng app', 'Giống nhau', 'Không liên quan', 'Chỉ admin'], [0], 'Tư duy.'],
      ['Ai thường đăng?', ['HR / admin / lãnh đạo', 'Chỉ khách', 'Chỉ bot', 'Không ai'], [0], 'Tư tưởng.'],
      ['Đọc khi nào?', ['Đầu ca hàng ngày', '1 năm/lần', 'Không cần', 'Chỉ Tết'], [0], 'Vận hành.'],
      ['Feed gồm?', ['Bài viết + media', 'Chỉ chat', 'Chỉ KPI', 'Chỉ Lead'], [0], 'Nguồn lực.'],
      ['Hồ sơ đồng nghiệp?', ['/social/u/{id}', '/crm/leads', '/login', '/kpi'], [0], 'Nguồn lực.'],
      ['Admin lọc công ty?', ['Xem đúng chi nhánh', 'Xóa user', 'In lương', 'Blocklist'], [0], 'Vận hành.'],
      ['Bỏ lỡ bảng tin?', ['Lỡ chính sách công ty', 'Thưởng', 'Thăng chức', 'KPI tăng'], [0], 'Báo cáo.'],
      ['Sidebar mở?', ['Bảng tin nội bộ', 'Chỉ Deal', 'Chỉ ghi âm', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Loa phường có lịch sử?', ['Bài cũ vẫn xem được', 'Xóa hết', 'Chỉ 1 ngày', 'Chỉ chat'], [0], 'Tư duy.'],
      ['Nhầm /updates?', ['Đọc thêm /social', 'Bỏ qua', 'Xóa app', 'Thua'], [0], 'Báo cáo.'],
      ['Tự kiểm bài 10?', ['Mở /social + đọc 1 bài', 'Chỉ updates', 'Không cần', 'Chỉ chat'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Mở /social — đọc 1 bài mới nhất.', 'Phân biệt với /updates (Có gì mới).'],
  },
  {
    num: 11,
    title: 'TT 11: Bảng tin — đăng bài, reaction, chia sẻ chat',
    summary: 'Tạo post; ảnh/video; reaction; comment; share sang messenger.',
    pillar: {
      hook: 'Xưởng hoàn thành **20 bộ tủ** — đăng ảnh lên bảng tin + **share vào nhóm chat** — cả công ty vui.',
      tuTuong: { vaiTro: 'Đăng bài **đúng chuẩn công ty** — văn hóa tích cực, không lộ bí mật khách.', ynghia: ['Reaction giúp admin đo mức độ tiếp cận.'] },
      tuDuy: { phanBiet: ['**Comment** _(thảo luận)_ · **Reaction** _(cảm xúc nhanh)_ · **Share chat** _(đẩy sang nhóm)_'] },
      nguonLuc: { manHinh: 'Ô **Tạo bài viết** đầu feed', congCu: ['Text + ảnh/video', 'Reaction (👍❤️…)', 'Comment', 'Share to Messenger', 'Ẩn bài / báo cáo (nếu cần)'] },
      vanHanh: {
        steps: ['**Tạo bài viết** — nội dung + ảnh (nếu có).', 'Chọn **phạm vi** (công ty / nhóm).', 'Đăng → đồng nghiệp **reaction / comment**.', 'Menu **⋯** → **Chia sẻ sang chat** nếu cần.', 'Không đăng **SĐT khách / giá kín**.'],
        mentor: 'Ảnh nén vừa — feed load nhanh hơn.',
      },
      baoCaoSua: { loiHay: ['Lộ SĐT khách trên bảng tin.', 'Comment toxic — dùng báo cáo.'], tomTat: 'Đăng → reaction/comment → share chat; không lộ KH.' },
      tomTat: 'Đăng bài, tương tác, share chat — bảo mật khách hàng.',
    },
    quiz: mkQuiz([
      ['Tạo bài ở?', ['Ô đầu feed /social', 'Chỉ admin PC', 'Chỉ KPI', 'Lead form'], [0], 'Nguồn lực.'],
      ['Reaction để?', ['Phản hồi nhanh', 'Xóa bài', 'In PDF', 'KPI'], [0], 'Tư duy.'],
      ['Share sang chat?', ['Đẩy link/post vào nhóm chat', 'Xóa post', 'Chỉ email', 'Cấm'], [0], 'Vận hành.'],
      ['Không đăng?', ['SĐT khách, giá kín, bí mật', 'Ảnh team building', 'Thành tích', 'Chính sách'], [0], 'Báo cáo.'],
      ['Comment vs reaction?', ['Comment dài; reaction nhanh', 'Giống nhau', 'Không liên quan', 'Cấm comment'], [0], 'Tư duy.'],
      ['Phạm vi bài?', ['Công ty / nhóm chọn được', 'Chỉ public internet', 'Chỉ admin', 'Random'], [0], 'Vận hành.'],
      ['Ảnh quá nặng?', ['Feed chậm — nén ảnh', 'Tốt', 'Thưởng', 'Bắt buộc'], [0], 'Báo cáo.'],
      ['Bài toxic?', ['Ẩn / báo cáo admin', 'Share thêm', 'Thưởng', 'In ra'], [0], 'Báo cáo.'],
      ['Share messenger modal?', ['Chọn nhóm gửi', 'Tự gửi khách', 'Xóa Lead', 'KPI'], [0], 'Nguồn lực.'],
      ['Văn hóa đăng?', ['Tích cực, không lộ KH', 'Đăng pass', 'Spam', 'Chửi'], [0], 'Tư tưởng.'],
      ['Admin đo tiếp cận?', ['Reaction / comment count', 'Chỉ chat', 'Chỉ KPI Lead', 'Không'], [0], 'Báo cáo.'],
      ['Tự kiểm bài 11?', ['Reaction 1 bài + xem share chat', 'Chỉ đọc', 'Không cần', 'Chỉ ghi âm'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Reaction hoặc comment một bài.', 'Mở menu share → xem chia sẻ sang chat (không bắt gửi).'],
  },
  {
    num: 12,
    title: 'TT 12: Tổng hợp — 4 kênh trên một ca làm việc',
    summary: 'Checklist ca làm: sự kiện → chat → bảng tin → ghi âm.',
    pillar: {
      hook: 'Một **ca sales điển hình**: đọc bảng tin → xem lịch sự kiện → gọi khách (ghi âm) → chat kỹ thuật bong bóng.',
      tuTuong: { vaiTro: 'Pro dùng **cả 4 kênh** trong ngày — không bỏ sót.', ynghia: ['Mỗi kênh một việc — không trùng lặp Zalo riêng.'] },
      tuDuy: {
        bang: '| Việc | Kênh |\n|---|---|\n| Hẹn khảo sát | **Sự kiện** |\n| Hỏi nhanh đồng nghiệp | **Chat / bong bóng** |\n| Thông báo công ty | **Bảng tin** |\n| Gọi khách | **Ghi âm + gắn Lead** |',
      },
      nguonLuc: { manHinh: 'Sidebar + thanh nhanh + bong bóng', congCu: ['4 URL đã học', 'Thông báo chuông', 'ModuleQuickActions'] },
      vanHanh: {
        steps: ['**Đầu ca:** /social — 2 phút.', '**Lịch:** /crm/events — sự kiện hôm nay.', '**Làm việc:** Lead + bong bóng chat.', '**Sau gọi:** ghi âm gắn Lead.', '**Cuối ca:** cập nhật sự kiện completed.'],
        mentor: 'In checklist này dán cạnh màn hình tuần đầu.',
      },
      baoCaoSua: { tuKiem: ['Đủ 4 kênh trong ngày?', 'File ghi âm đã gắn Lead?', 'Sự kiện đã completed?'], tomTat: 'Checklist ca: bảng tin → sự kiện → chat → ghi âm.' },
      tomTat: '4 kênh phối hợp trong một ca — checklist đầu/cuối ca.',
    },
    quiz: mkQuiz([
      ['Hẹn khảo sát — kênh?', ['Sự kiện', 'Chỉ chat', 'Chỉ bảng tin', 'Chỉ KPI'], [0], 'Tư duy.'],
      ['Thông báo công ty?', ['Bảng tin', 'Chat Lead', 'Ghi âm', 'Deal'], [0], 'Tư duy.'],
      ['Gọi khách — kênh?', ['Ghi âm + Lead', 'Chỉ chat', 'Chỉ sự kiện', 'Blocklist'], [0], 'Tư duy.'],
      ['Hỏi nhanh đồng nghiệp?', ['Chat / bong bóng', 'Bảng tin', 'Chỉ KPI', 'Email ngoài'], [0], 'Tư duy.'],
      ['Đầu ca đọc?', ['/social', '/login', '/blocklist', '/trash'], [0], 'Vận hành.'],
      ['Sau gọi?', ['Ghi âm gắn Lead', 'Chỉ Zalo', 'Xóa Lead', 'In BG'], [0], 'Vận hành.'],
      ['Cuối ca sự kiện?', ['Completed + comment', 'Bỏ qua', 'Xóa', 'Chỉ chat'], [0], 'Vận hành.'],
      ['Thanh nhanh VC?', ['Icon Bảng tin, Sự kiện, Chat', 'Chỉ thùng rác', 'Chỉ KPI', 'Không'], [0], 'Nguồn lực.'],
      ['4 kênh + Zalo riêng?', ['CRM trước, Zalo bổ sung', 'Chỉ Zalo', 'Bỏ CRM', 'Cấm chat'], [0], 'Tư tưởng.'],
      ['Pro bỏ sót bảng tin?', ['Lỡ chính sách', 'Thưởng', 'KPI tăng', 'Nhanh hơn'], [0], 'Báo cáo.'],
      ['Checklist cuối ca?', ['Sự kiện + ghi âm + Lead', 'Chỉ chat', 'Không cần', 'Chỉ login'], [0], 'Báo cáo.'],
      ['Tự kiểm bài 12?', ['Làm checklist 1 ca thật', 'Chỉ đọc', 'Không cần', 'Chỉ thi'], [0], 'Báo cáo.'],
    ]),
    checklist: [
      'Một ca: đọc /social → xem /crm/events → dùng bong bóng chat → kiểm ghi âm.',
      'Tick đủ 4 kênh trên checklist giấy.',
    ],
  },
];

const FINAL_EXAM = [
  ['4 kênh nội bộ gồm?', ['Sự kiện, Chat, Bảng tin, Ghi âm', 'Lead, Deal, KPI, BG', 'Chỉ Zalo', 'Email'], [0], 'Tổng hợp.'],
  ['Trang Sự kiện?', ['/crm/events', '/social', '/tools/voice-recordings', '/kpi'], [0], 'Sự kiện.'],
  ['Trang chat đầy đủ?', ['/crm/messenger', '/social', '/events', '/login'], [0], 'Chat.'],
  ['Bong bóng chat?', ['Góc phải — MessengerDock', 'Sidebar', 'Giữa Kanban', 'Email'], [0], 'Chat.'],
  ['Bảng tin nội bộ?', ['/social', '/updates', '/crm/leads', '/tools'], [0], 'Bảng tin.'],
  ['Ghi âm?', ['/tools/voice-recordings', '/social', '/events', '/messenger'], [0], 'Ghi âm.'],
  ['Bảng tin vs Có gì mới?', ['Social=công ty; Updates=app', 'Giống nhau', 'Không liên quan', 'Chỉ admin'], [0], 'Phân biệt.'],
  ['Sau cuộc gọi quan trọng?', ['Ghi âm + gắn Lead', 'Chỉ chat', 'Chỉ bảng tin', 'Bỏ qua'], [0], 'Ghi âm.'],
  ['Sự kiện sau buổi gặp?', ['Completed + bình luận', 'Xóa', 'Chỉ Zalo', 'KPI'], [0], 'Sự kiện.'],
  ['Chat Lead mở từ?', ['Chi tiết Lead', 'Chỉ bảng tin', 'Chỉ KPI', 'Blocklist'], [0], 'Chat.'],
  ['Thanh nhanh dashboard VC?', ['Bảng tin, Sự kiện, Chat', 'Chỉ thùng rác', 'Chỉ Lead', 'Không có'], [0], 'Nguồn lực.'],
  ['Đóng bong bóng?', ['Tin vẫn lưu', 'Mất tin', 'Xóa Lead', 'Logout'], [0], 'Chat.'],
  ['Không ghi CRM — hậu quả?', ['Mất minh bạch team', 'Thưởng', 'Nhanh hơn', 'KPI tăng'], [0], 'Tư tưởng.'],
  ['Reaction bảng tin?', ['Phản hồi nhanh', 'Xóa post', 'In PDF', 'KPI Lead'], [0], 'Bảng tin.'],
  ['Share post sang chat?', ['Chọn nhóm messenger', 'Gửi khách SMS', 'Xóa Deal', 'Blocklist'], [0], 'Bảng tin.'],
  ['Tab Lịch sự kiện?', ['Xem tháng', 'Chỉ chat', 'Chỉ KPI', 'In lương'], [0], 'Sự kiện.'],
  ['Online dot xanh?', ['Đang hoạt động', 'Lead Hot', 'Deal thua', 'Offline forever'], [0], 'Chat.'],
  ['Không lộ trên bảng tin?', ['SĐT khách, giá kín', 'Ảnh team', 'Chính sách', 'Thành tích'], [0], 'Bảo mật.'],
  ['Checklist đầu ca?', ['Đọc /social + /crm/events', 'Chỉ login', 'Chỉ KPI', 'Blocklist'], [0], 'Vận hành.'],
  ['Điều kiện thi tổng kết?', ['Đạt bài tập các bài trước', 'Chỉ login', 'Chỉ admin', 'Không cần'], [0], 'Quy định.'],
];

module.exports = { LESSON_SPECS, FINAL_EXAM, q };
