/**
 * Khoá Deal — 12 bài + thi tổng kết (5 trụ).
 */
const { quizItem } = require('./_helpers');
const q = quizItem;

const mkQuiz = (rows) => {
  const tt = rows.slice(0, 2);
  const td = rows.slice(2, 5);
  const nl = rows.slice(5, 8);
  const vh = rows.slice(8, 12);
  const bc = rows.slice(12, 15);
  return { tt, td, nl, vh, bc };
};

const LESSON_SPECS = [
  {
    num: 1,
    title: 'Bài 1: Vai trò Deal — Sau khi khách đã chốt mua',
    summary: 'Vì sao có giai đoạn Deal, trách nhiệm sales và mục tiêu ký HĐ + thu tiền.',
    pillar: {
      hook: 'Anh Minh đã chốt 2 bộ cửa nhôm 38 triệu — đây là **Deal**: không còn "hỏi giá", mà là **hoàn tất hợp đồng và thu tiền**.',
      tuTuong: { vaiTro: 'Deal = bạn chịu trách nhiệm đưa khách từ **lời hứa mua** đến **tiền vào công ty**.', ynghia: ['Lead = nuôi cơ hội; Deal = thu hoạch.', 'Deal Thua cũng có giá trị — giúp công ty học vì sao mất khách.'] },
      tuDuy: { phanBiet: ['**Deal** _(đã thống nhất mua, đang làm HĐ)_', '**Lead** _(chưa chốt)_', '**Thắng** _(đã HĐ + cọc, bàn giao xưởng)_'], mentalModel: 'Deal như **đường đua cuối** — Lead đã vào vòng trong, giờ về đích (Thắng) hoặc trượt (Thua).' },
      nguonLuc: { manHinh: '**CRM → Bảng Deal**', congCu: ['Kanban Deal', 'Chi tiết Deal (tab Báo giá, HĐ, Tài liệu)', 'Pipeline 6 giai đoạn mẫu'], duLieu: 'Giá chốt, phạm vi SP, người phụ trách.' },
      vanHanh: { steps: ['Sau **Chuyển Deal** từ Lead → mở **Bảng Deal**.', 'Tìm Deal của bạn (bộ lọc tương tự Lead).', 'Đọc lịch sử Lead đã chuyển sang — không bắt đầu lại từ đầu.'], mentor: 'Deal kế thừa toàn bộ lịch sử Lead — đừng hỏi khách lại thông tin đã trao đổi.' },
      baoCaoSua: { tuKiem: ['Tôi biết Deal khác Lead?', 'Tôi mở được Bảng Deal?'], kpi: 'Tỉ lệ Thắng/Thua, doanh số Deal.' },
      tomTat: 'Deal = giai đoạn sau chốt mua; mục tiêu HĐ + tiền; kế thừa lịch sử Lead.',
    },
    quiz: mkQuiz([
      ['Vì sao tách Deal khỏi Lead?', ['Quản lý giai đoạn HĐ và thu tiền riêng', 'Làm khó nhân viên', 'Xóa Lead', 'Chỉ admin'], [0], 'Tư tưởng.'],
      ['Deal Thua có giá trị?', ['Có — phân tích lý do mất', 'Không', 'Chỉ Thắng', 'Xóa luôn'], [0], 'Tư tưởng.'],
      ['Deal là gì?', ['Đã thống nhất mua, đang hoàn tất HĐ', 'Khách mới hỏi giá', 'Đã SX xong', 'Nhân viên mới'], [0], 'Tư duy.'],
      ['Deal khác Lead?', ['Deal sau chốt mua', 'Giống hệt', 'Lead sau Deal', 'Không liên quan'], [0], 'Tư duy.'],
      ['Thắng nghĩa là?', ['HĐ + cọc, bàn giao xưởng', 'Mới hỏi giá', 'Chưa gọi', 'Blocklist'], [0], 'Tư duy.'],
      ['Bảng Deal ở?', ['CRM → Bảng Deal', 'Công việc', 'Kiến thức', 'Lương'], [0], 'Nguồn lực.'],
      ['Deal kế thừa?', ['Lịch sử Lead', 'Không gì', 'Chỉ chat', 'Chỉ KPI'], [0], 'Nguồn lực.'],
      ['Pipeline Deal mẫu?', ['6 giai đoạn đến Thắng/Thua', 'Không có', '1 cột', 'Chỉ Lead'], [0], 'Nguồn lực.'],
      ['Sau Chuyển Deal mở?', ['Bảng Deal', 'Blocklist', 'Lương', 'Chat công ty'], [0], 'Vận hành.'],
      ['Mục tiêu Deal?', ['Ký HĐ + thu tiền', 'Chỉ hỏi giá', 'Xóa khách', 'Tạo Lead mới'], [0], 'Vận hành.'],
      ['Hỏi lại thông tin Lead cũ?', ['Không — đọc lịch sử trước', 'Nên hỏi lại', 'Xóa Lead', 'Tạo mới'], [0], 'Vận hành.'],
      ['Deal ảo (chưa chốt)?', ['Trừ KPI, sửa ngay', 'Tốt', 'Thưởng', 'Không sao'], [0], 'Vận hành.'],
      ['KPI Deal gồm?', ['Thắng/Thua, doanh số', 'Chỉ màu tủ', 'Chỉ giờ nghỉ', 'Chỉ Facebook'], [0], 'Báo cáo.'],
      ['Deal Thua — làm gì?', ['Ghi lý do', 'Im lặng', 'Xóa', 'Tạo Lead trùng'], [0], 'Báo cáo.'],
    ]),
  },
  {
    num: 2,
    title: 'Bài 2: Pipeline Deal — Sáu giai đoạn trên bảng',
    summary: 'Kanban Deal, 6 cột mẫu, kéo thẻ đúng giai đoạn, gate nhiệm vụ.',
    pillar: {
      hook: 'Deal mới → Báo giá → Đàm phán → Ký HĐ → **Thắng** hoặc **Thua**. Mỗi cột = một việc bạn phải làm thật.',
      tuTuong: { vaiTro: 'Pipeline Deal là **bản đồ tiền** — sếp và bạn biết doanh số đang ở đâu.', ynghia: ['Kéo Thắng sớm = báo cáo doanh thu ảo.', 'Thua có lý do = công ty cải thiện giá/dịch vụ.'] },
      tuDuy: { bang: '| Giai đoạn | Việc thường làm |\n|---|---|\n| Deal mới | Kiểm tra hồ sơ chuyển từ Lead |\n| Báo giá | Gửi BG chính thức PDF |\n| Đàm phán | Điều chỉnh giá/phụ kiện |\n| Ký HĐ | Soạn HĐ, thu cọc |\n| Thắng | Bàn giao xưởng |\n| Thua | Chọn lý do mất |', mentalModel: 'Mỗi cột = **cổng kiểm** — có thể bị chặn nếu nhiệm vụ/báo giá chưa xong.' },
      nguonLuc: { manHinh: '**CRM → Bảng Deal → Kanban**', congCu: ['Kéo thẻ', 'Tab chi tiết Deal', 'Gate nhiệm vụ'], duLieu: 'Giai đoạn, giá, file HĐ.' },
      vanHanh: { steps: ['Mở Kanban Deal.', 'Kéo thẻ **sau** khi hoàn thành việc cột hiện tại.', 'Đọc thông báo nếu bị chặn.', 'Thua: **bắt buộc** chọn lý do.'], mentor: 'Thắng chỉ khi **đã thu cọc** và upload chứng từ — không kéo cho "đẹp bảng".' },
      baoCaoSua: { loiHay: ['Kéo Thắng chưa cọc.', 'Thua không lý do.'], kpi: 'Tỉ lệ thắng, thời gian mỗi giai đoạn.' },
      tomTat: '6 giai đoạn mẫu; kéo = việc đã làm; Thắng/Thua có quy tắc.',
    },
    quiz: mkQuiz([
      ['Pipeline Deal giúp?', ['Theo dõi tiến độ HĐ và tiền', 'Tính lương', 'Chat', 'Xóa Deal'], [0], 'Tư tưởng.'],
      ['Thua có lý do — vì sao?', ['Phân tích cải thiện', 'Làm khó', 'Xóa KPI', 'Không cần'], [0], 'Tư tưởng.'],
      ['Kéo thẻ Deal để?', ['Đổi giai đoạn', 'Xóa', 'In lương', 'Tạo Lead'], [0], 'Tư duy.'],
      ['Thắng khi?', ['HĐ + cọc đủ quy định', 'Mới chuyển Deal', 'Chưa báo giá', 'Chưa gọi'], [0], 'Tư duy.'],
      ['Thua phải?', ['Chọn lý do', 'Im lặng', 'Xóa Deal', 'Tạo Lead trùng'], [0], 'Tư duy.'],
      ['Kanban Deal ở?', ['Bảng Deal', 'Bảng Lead', 'Lương', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Gate nhiệm vụ trên Deal?', ['Có — giống Lead', 'Không bao giờ', 'Chỉ admin', 'Chỉ chat'], [0], 'Nguồn lực.'],
      ['6 giai đoạn mẫu kết thúc?', ['Thắng hoặc Thua', 'Chỉ Thắng', 'Chỉ Lead', 'Không kết thúc'], [0], 'Nguồn lực.'],
      ['Kéo Thắng chưa cọc?', ['Sai — báo cáo ảo', 'Đúng', 'Bắt buộc', 'Tốt'], [0], 'Vận hành.'],
      ['Bị chặn khi kéo?', ['Đọc thông báo, hoàn thành nhiệm vụ', 'Bỏ qua', 'Xóa Deal', 'Đổi pass'], [0], 'Vận hành.'],
      ['Thua — bước bắt buộc?', ['Chọn lý do', 'Xóa', 'Tạo Lead mới', 'Chat nội bộ'], [0], 'Vận hành.'],
      ['Deal mới cột đầu?', ['Kiểm tra hồ sơ từ Lead', 'Thắng ngay', 'Thua ngay', 'Xóa'], [0], 'Vận hành.'],
      ['Kéo ảo — sửa?', ['Kéo lại đúng + bổ sung minh chứng', 'Giữ nguyên', 'Xóa Deal', 'Báo cáo giả'], [0], 'Báo cáo.'],
      ['Thua không lý do — hậu quả?', ['Mất dữ liệu phân tích', 'Thưởng', 'Không sao', 'Tự thăng chức'], [0], 'Báo cáo.'],
    ]),
  },
  {
    num: 3,
    title: 'Bài 3: Báo giá chính thức trên Deal',
    summary: 'Tạo/gửi báo giá PDF, lưu tab Báo giá & Tài liệu, version và xác nhận khách.',
    pillar: {
      hook: 'Sau đo đạc — gửi **báo giá chính thức PDF** cho chị Lan. File này là cơ sở pháp lý và KPI.',
      tuTuong: { vaiTro: 'Báo giá = **cam kết số liệu** giữa bạn và khách — sai một dòng, tranh cãi cả đơn.', ynghia: ['BG miệng không đủ — cần PDF trên hệ thống.', 'BG trên Deal liên kết với HĐ sau này.'] },
      tuDuy: { phanBiet: ['**Báo giá sơ bộ** (Lead) vs **Báo giá chính thức** (Deal, sau đo đạc)'], mentalModel: 'BG chính thức = **hợp đồng nháp** — mọi thứ phải khớp HĐ.' },
      nguonLuc: { manHinh: 'Chi tiết Deal → tab **Báo giá** / **Tài liệu**', congCu: ['Tạo báo giá', 'Upload PDF', 'Gửi link/email (nếu có)'], duLieu: 'Diện tích, vật liệu, phụ kiện, tổng tiền, điều khoản cọc.' },
      vanHanh: { steps: ['Tab **Báo giá** → tạo hoặc upload PDF.', 'Tên file rõ: `BG_ChịLan_2026-03.pdf`.', 'Ghi **Hoạt động**: "Đã gửi BG, KH xác nhận qua Zalo".', 'Kéo cột **Báo giá** khi KH đã nhận.'], mentor: 'Sau khi KH đồng ý BG — screenshot Zalo đính kèm Deal (minh chứng).' },
      baoCaoSua: { loiHay: ['BG miệng không lưu file.', 'Số tiền BG khác HĐ.'], kpi: 'Thời gian từ Deal mới → Báo giá.' },
      tomTat: 'BG chính thức = PDF trên Deal; khớp HĐ; minh chứng gửi/nhận.',
    },
    quiz: mkQuiz([
      ['BG chính thức quan trọng vì?', ['Cam kết số liệu, cơ sở HĐ', 'Trang trí', 'Chỉ admin', 'Không cần'], [0], 'Tư tưởng.'],
      ['BG miệng — rủi ro?', ['Tranh cãi, không đối soát', 'Tốt hơn PDF', 'Tự thưởng', 'Khách vui'], [0], 'Tư tưởng.'],
      ['BG sơ bộ vs chính thức?', ['Chính thức sau đo đạc trên Deal', 'Giống nhau', 'Chỉ Lead', 'Không có'], [0], 'Tư duy.'],
      ['BG khớp HĐ?', ['Bắt buộc', 'Không cần', 'Chỉ tên', 'Chỉ ngày'], [0], 'Tư duy.'],
      ['File BG lưu?', ['Tab Báo giá / Tài liệu Deal', 'Chat riêng', 'Email cá nhân', 'Không lưu'], [0], 'Tư duy.'],
      ['Tên file BG tốt?', ['BG_ChịLan_2026-03.pdf', 'a.pdf', '1.jpg', 'tmp'], [0], 'Nguồn lực.'],
      ['Tab Báo giá trên?', ['Chi tiết Deal', 'Bảng Lead', 'Lương', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Minh chứng gửi BG?', ['Screenshot Zalo / Hoạt động', 'Không cần', 'Chỉ miệng', 'Xóa Deal'], [0], 'Nguồn lực.'],
      ['Sau gửi BG — ghi?', ['Hoạt động + file', 'Im lặng', 'Xóa Deal', 'Thua ngay'], [0], 'Vận hành.'],
      ['Kéo cột Báo giá khi?', ['KH đã nhận BG', 'Chưa tạo BG', 'Mới Lead', 'Blocklist'], [0], 'Vận hành.'],
      ['Số tiền BG khác HĐ — sửa?', ['Sửa BG hoặc HĐ cho khớp trước ký', 'Bỏ qua', 'Ký luôn', 'Xóa Deal'], [0], 'Báo cáo.'],
      ['Không lưu PDF — sửa?', ['Upload + ghi hoạt động', 'BG miệng', 'Thua', 'Tạo Lead mới'], [0], 'Báo cáo.'],
    ]),
  },
  {
    num: 4,
    title: 'Bài 4: Đàm phán và điều chỉnh trên Deal',
    summary: 'Giảm giá, tặng phụ kiện, ghi nhận đàm phán, cập nhật BG và timeline.',
    pillar: {
      hook: 'KH muốn giảm 2 triệu hoặc tặng thêm bản lề — mọi thỏa thuận phải **ghi trên Deal**, không chỉ nói miệng.',
      tuTuong: { vaiTro: 'Đàm phán = cân **lợi nhuận công ty** và **chốt đơn** — ghi sai = xưởng làm sai, lỗ vốn.', ynghia: ['Thay đổi giá phải có phê duyệt (nếu quy định) và file cập nhật.'] },
      tuDuy: { mentalModel: 'Mỗi lần đàm phán = **phiên bản mới** của BG — version cũ vẫn lưu để đối chiếu.' },
      nguonLuc: { manHinh: 'Chi tiết Deal — Báo giá, Hoạt động, Chat nội bộ', congCu: ['Cập nhật BG', '@mention sếp phê duyệt', 'Timeline đàm phán'], duLieu: 'Giá cũ/mới, phụ kiện tặng, người duyệt.' },
      vanHanh: { steps: ['Ghi **Hoạt động** mỗi vòng đàm phán.', 'Cập nhật BG PDF hoặc bản revision.', 'Cần phê duyệt → chat @sếp trước khi hứa khách.', 'Kéo **Đàm phán** khi đang trao đổi.'], mentor: 'Không hứa giảm giá trên điện thoại trước khi sếp OK — ghi chú "chờ duyệt".' },
      baoCaoSua: { loiHay: ['Hứa miệng không ghi.', 'BG cũ và mới lẫn lộn.'], kpi: 'Tỉ lệ chốt sau đàm phán.' },
      tomTat: 'Đàm phán = ghi hoạt động + BG cập nhật + phê duyệt khi cần.',
    },
    quiz: mkQuiz([
      ['Đàm phán phải ghi vì?', ['Xưởng và kế toán cần số đúng', 'Không cần', 'Chỉ chat riêng', 'Xóa Deal'], [0], 'Tư tưởng.'],
      ['Hứa giảm giá miệng — rủi ro?', ['Lỗ vốn, tranh cãi', 'Tốt', 'Thưởng', 'Khách vui'], [0], 'Tư tưởng.'],
      ['Mỗi vòng đàm phán?', ['Ghi Hoạt động + BG nếu đổi', 'Im lặng', 'Thua ngay', 'Xóa'], [0], 'Tư duy.'],
      ['BG revision?', ['Lưu version, khớp HĐ cuối', 'Xóa bản cũ', 'Chỉ miệng', 'Không cần'], [0], 'Tư duy.'],
      ['Giảm giá lớn?', ['Phê duyệt sếp trước', 'Tự quyết', 'Không ghi', 'Blocklist'], [0], 'Tư duy.'],
      ['Ghi đàm phán ở?', ['Hoạt động Deal', 'Chỉ sổ tay', 'Blocklist', 'Lương'], [0], 'Nguồn lực.'],
      ['@mention sếp khi?', ['Cần duyệt giá/ tặng', 'Mọi lúc', 'Không bao giờ', 'Cuối năm'], [0], 'Nguồn lực.'],
      ['Cột Đàm phán khi?', ['Đang trao đổi giá/phụ kiện', 'Đã Thắng', 'Mới Lead', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Chưa duyệt — hứa khách?', ['Ghi "chờ duyệt", chưa chốt', 'Hứa luôn', 'Thua', 'Xóa'], [0], 'Vận hành.'],
      ['Sau thỏa thuận?', ['Cập nhật BG + hoạt động', 'Im lặng', 'Thua', 'Lead mới'], [0], 'Vận hành.'],
      ['BG cũ/mới lẫn — sửa?', ['Đánh dấu version, file rõ tên', 'Xóa Deal', 'BG miệng', 'Bỏ qua'], [0], 'Báo cáo.'],
      ['Không ghi đàm phán — sửa?', ['Bổ sung timeline + BG', 'Thua', 'Xóa', 'Báo cáo giả'], [0], 'Báo cáo.'],
    ]),
  },
  {
    num: 5,
    title: 'Bài 5: Ký hợp đồng và thu cọc',
    summary: 'Soạn HĐ, thu cọc (vd 50%), upload chứng từ, cột Ký HĐ.',
    pillar: {
      hook: 'Chị Lan ký HĐ, chuyển 50% cọc — upload **ảnh chuyển khoản + HĐ scan** lên Deal trước khi kéo **Thắng**.',
      tuTuong: { vaiTro: 'Cọc = **cam kết pháp lý** — không cọc mà kéo Thắng = xưởng làm hàng không tiền.', ynghia: ['HĐ + cọc bảo vệ công ty và khách.'] },
      tuDuy: { phanBiet: ['**Ký HĐ** _(cột pipeline)_ vs **Thắng** _(đủ cọc + bàn giao SX)_'], mentalModel: 'Cọc như **cọc giữ chỗ** — chưa cọc = chưa chắc chắn.' },
      nguonLuc: { manHinh: 'Deal → Tài liệu (HĐ, chứng từ cọc)', congCu: ['Upload HĐ scan', 'Upload ảnh CK', 'Tab báo giá đối chiếu'], duLieu: 'Số tiền cọc, % theo quy định công ty, ngày ký.' },
      vanHanh: { steps: ['Soạn/ký HĐ — số khớp BG.', 'Thu cọc theo % công ty (vd 50%).', 'Upload HĐ + chứng từ lên **Tài liệu**.', 'Ghi Hoạt động ngày ký + số tiền.', 'Kéo **Ký HĐ** — chưa Thắng nếu chưa đủ cọc.'], mentor: 'Ảnh chuyển khoản mờ — yêu cầu KH gửi lại; không kéo Thắng.' },
      baoCaoSua: { loiHay: ['Thắng chưa cọc.', 'HĐ khác BG.'], kpi: 'Doanh số cọc tháng.' },
      tomTat: 'HĐ khớp BG; cọc có chứng từ; Thắng chỉ khi đủ điều kiện công ty.',
    },
    quiz: mkQuiz([
      ['Cọc quan trọng vì?', ['Cam kết pháp lý, bảo vệ công ty', 'Trang trí', 'Không cần', 'Chỉ admin'], [0], 'Tư tưởng.'],
      ['Thắng chưa cọc?', ['Sai — rủi ro tài chính', 'Đúng', 'Bắt buộc', 'Tốt'], [0], 'Tư tưởng.'],
      ['Ký HĐ vs Thắng?', ['Thắng sau khi đủ cọc + điều kiện', 'Giống nhau', 'Thắng trước HĐ', 'Không liên quan'], [0], 'Tư duy.'],
      ['HĐ số tiền?', ['Khớp BG cuối', 'Tùy ý', 'Chỉ miệng', 'Không cần'], [0], 'Tư duy.'],
      ['Chứng từ cọc lưu?', ['Tài liệu Deal', 'Chat riêng', 'Xóa', 'Email cá nhân'], [0], 'Tư duy.'],
      ['Upload HĐ scan ở?', ['Tài liệu Deal', 'Lead', 'Lương', 'Blocklist'], [0], 'Nguồn lực.'],
      ['% cọc theo?', ['Quy định công ty', 'Tùy nhân viên', 'Không cần', '100% luôn'], [0], 'Nguồn lực.'],
      ['Ảnh CK mờ?', ['Yêu cầu KH gửi lại', 'Vẫn Thắng', 'Xóa Deal', 'Thua'], [0], 'Nguồn lực.'],
      ['Sau thu cọc?', ['Upload + ghi Hoạt động', 'Im lặng', 'Thua', 'Lead mới'], [0], 'Vận hành.'],
      ['Kéo Thắng khi?', ['Đủ cọc + HĐ theo quy định', 'Mới Deal', 'Chưa BG', 'Blocklist'], [0], 'Vận hành.'],
      ['HĐ khác BG — sửa?', ['Sửa cho khớp trước ký', 'Ký luôn', 'Thua', 'Xóa'], [0], 'Báo cáo.'],
      ['Thắng ảo — sửa?', ['Kéo lại + bổ sung cọc', 'Giữ Thắng', 'Báo cáo giả', 'Xóa KPI'], [0], 'Báo cáo.'],
    ]),
  },
  {
    num: 6,
    title: 'Bài 6: Deal Thắng — Tạo dự án sản xuất',
    summary: 'Popup tạo dự án xưởng, bàn giao BOM/bản vẽ, checklist Thắng.',
    pillar: {
      hook: 'Kéo **Thắng** — popup **tạo dự án sản xuất**. Sales chấm dứt, xưởng bắt đầu — handoff phải đủ file.',
      tuTuong: { vaiTro: 'Thắng = bạn **bàn giao** trách nhiệm cho xưởng — thiếu bản vẽ = delay SX.', ynghia: ['Handoff tốt = khách hài lòng, ít khiếu nại.'] },
      tuDuy: { mentalModel: 'Thắng như **passing baton** — chạy đến đích và đưa gậy cho xưởng.' },
      nguonLuc: { manHinh: 'Popup Thắng + module **Xưởng / Dự án**', congCu: ['Tạo dự án từ Deal', 'Upload bản vẽ, BOM', 'Chat @xưởng'], duLieu: 'HĐ, cọc, bản vẽ, lịch giao.' },
      vanHanh: { steps: ['Kiểm tra checklist: HĐ, cọc, BG, bản vẽ.', 'Kéo **Thắng** → điền popup tạo dự án.', 'Upload đủ file kỹ thuật.', '@mention bộ phận SX trong chat Deal.'], mentor: 'Gọi cho xưởng 2 phút sau Thắng — xác nhận đã nhận đủ file.' },
      baoCaoSua: { loiHay: ['Thắng thiếu bản vẽ.', 'Không tạo dự án popup.'], kpi: 'Doanh số Thắng, thời gian handoff.' },
      tomTat: 'Thắng = đủ cọc/HĐ + popup dự án + file kỹ thuật + thông báo xưởng.',
    },
    quiz: mkQuiz([
      ['Thắng — vai trò sales?', ['Bàn giao đủ cho xưởng', 'Xóa Deal', 'Lead mới', 'Blocklist'], [0], 'Tư tưởng.'],
      ['Handoff kém?', ['Delay SX, khiếu nại', 'Tốt', 'Thưởng', 'Không sao'], [0], 'Tư tưởng.'],
      ['Thắng giống?', ['Passing baton cho xưởng', 'Kết thúc CRM', 'Xóa khách', 'Chỉ KPI'], [0], 'Tư duy.'],
      ['Popup Thắng?', ['Tạo dự án SX', 'Xóa Deal', 'Tạo Lead', 'Lương'], [0], 'Tư duy.'],
      ['File kỹ thuật?', ['Bản vẽ, BOM trên Deal/Tài liệu', 'Chỉ miệng', 'Chat riêng', 'Không cần'], [0], 'Tư duy.'],
      ['Sau Thắng — module?', ['Xưởng / Dự án', 'Chỉ Lead', 'Blocklist', 'Lương'], [0], 'Nguồn lực.'],
      ['@xưởng khi?', ['Sau Thắng + upload file', 'Không bao giờ', 'Trước Lead', 'Cuối năm'], [0], 'Nguồn lực.'],
      ['Checklist Thắng gồm?', ['HĐ, cọc, BG, bản vẽ', 'Chỉ SĐT', 'Chỉ chat', 'Không cần'], [0], 'Nguồn lực.'],
      ['Thiếu bản vẽ — kéo Thắng?', ['Không — bổ sung trước', 'Vẫn kéo', 'Thua', 'Xóa'], [0], 'Vận hành.'],
      ['Sau popup?', ['Xác nhận xưởng nhận', 'Im lặng', 'Lead mới', 'Blocklist'], [0], 'Vận hành.'],
      ['Thắng thiếu file — sửa?', ['Upload + thông báo xưởng', 'Bỏ qua', 'Thua', 'Báo cáo giả'], [0], 'Báo cáo.'],
      ['Không tạo dự án — sửa?', ['Chạy lại popup / liên hệ admin', 'Bỏ qua', 'Xóa Deal', 'Lead mới'], [0], 'Báo cáo.'],
    ]),
    checklist: ['HĐ + cọc đủ trên Tài liệu', 'Đã kéo Thắng + popup dự án', 'Bản vẽ/BOM đã upload', 'Đã @xưởng hoặc gọi xác nhận'],
  },
  {
    num: 7,
    title: 'Bài 7: Deal Thua — Ghi lý do và học từ thất bại',
    summary: 'Chọn lý do thua, phân tích, không xóa Deal, báo cáo cho team.',
    pillar: {
      hook: 'KH chọn đối thủ rẻ hơn — kéo **Thua**, chọn lý do **Giá cao**. Dữ liệu này giúp công ty điều chỉnh chiến lược.',
      tuTuong: { vaiTro: 'Thua trung thực = **bảo vệ uy tín** — Deal ảo Thắng tệ hơn Thua thật.', ynghia: ['Lý do Thua = feedback cho sản phẩm và pricing.'] },
      tuDuy: { phanBiet: ['**Thua có lý do** vs **Deal bỏ quên** (không cập nhật)'], mentalModel: 'Thua = **kết thúc có học** — không phải thất bại cá nhân.' },
      nguonLuc: { manHinh: 'Kanban Deal → cột **Thua**', congCu: ['Popup chọn lý do', 'Ghi chú chi tiết', 'Báo cáo thua theo tháng'], duLieu: 'Lý do chuẩn: giá, đối thủ, timing, khác…' },
      vanHanh: { steps: ['Xác nhận KH không mua.', 'Kéo **Thua** → chọn **lý do** từ danh sách.', 'Ghi Hoạt động chi tiết (đối thủ, giá, phản hồi KH).', 'Không xóa Deal.'], mentor: 'Thua vì giá — ghi rõ đối thủ báo bao nhiêu; marketing cần số liệu thật.' },
      baoCaoSua: { loiHay: ['Thua không lý do.', 'Giữ Deal mãi ở Đàm phán.'], kpi: 'Tỉ lệ thua theo lý do.' },
      tomTat: 'Thua = lý do bắt buộc + ghi chú + giữ lịch sử.',
    },
    quiz: mkQuiz([
      ['Thua trung thực?', ['Tốt hơn Deal ảo Thắng', 'Xấu', 'Xóa ngay', 'Không ghi'], [0], 'Tư tưởng.'],
      ['Lý do Thua giúp?', ['Công ty cải thiện giá/SP', 'Làm khó', 'Xóa KPI', 'Không cần'], [0], 'Tư tưởng.'],
      ['Thua vs bỏ quên?', ['Thua = cập nhật lý do', 'Giống nhau', 'Bỏ quên tốt hơn', 'Xóa Deal'], [0], 'Tư duy.'],
      ['Thua — bắt buộc?', ['Chọn lý do', 'Im lặng', 'Xóa', 'Lead mới'], [0], 'Tư duy.'],
      ['Ghi chi tiết Thua?', ['Đối thủ, giá, phản hồi KH', 'Chỉ "thua"', 'Không ghi', 'Blocklist'], [0], 'Tư duy.'],
      ['Popup Thua ở?', ['Kéo cột Thua Kanban', 'Lead', 'Lương', 'Chat công ty'], [0], 'Nguồn lực.'],
      ['Lý do chuẩn?', ['Giá, đối thủ, timing…', 'Chỉ "khác"', 'Không có', 'Tùy ý text'], [0], 'Nguồn lực.'],
      ['Deal Thua có xóa?', ['Không — giữ lịch sử', 'Xóa ngay', 'Tạo Lead trùng', 'Blocklist'], [0], 'Nguồn lực.'],
      ['KH chọn đối thủ — làm?', ['Thua + lý do + ghi giá đối thủ', 'Thắng', 'Im lặng', 'Xóa'], [0], 'Vận hành.'],
      ['Deal nằm Đàm phán 2 tháng?', ['Cập nhật Thua hoặc tiếp tục có kế hoạch', 'Bỏ quên', 'Thắng ảo', 'Xóa'], [0], 'Vận hành.'],
      ['Thua không lý do — sửa?', ['Mở Deal, chọn lý do', 'Xóa', 'Thắng', 'Báo cáo giả'], [0], 'Báo cáo.'],
      ['Giữ Deal ảo Thắng — sửa?', ['Kéo lại + sửa trạng thái thật', 'Giữ nguyên', 'Thưởng', 'Không sao'], [0], 'Báo cáo.'],
    ]),
  },
  {
    num: 8,
    title: 'Bài 8: Nhiệm vụ và gate trên Deal',
    summary: 'Task Deal, gate trước khi kéo cột, minh chứng tương tự Lead.',
    pillar: {
      hook: 'Deal cũng có **nhiệm vụ gate** — chưa upload cọc thì không kéo sang cột tiếp theo.',
      tuTuong: { vaiTro: 'Gate Deal bảo vệ **doanh thu thật** — không cho nhảy cóc Thắng.', ynghia: ['Task Deal: "Thu cọc", "Gửi bản vẽ", "Xác nhận ngày giao".'] },
      tuDuy: { mentalModel: 'Giống Lead — **nhiệm vụ = hẹn**, **hoàn thành = minh chứng**.' },
      nguonLuc: { manHinh: 'Chi tiết Deal → tab **Nhiệm vụ**', congCu: ['Tạo/hoàn thành task', 'Gate khi kéo Kanban'], duLieu: 'Hạn, file đính kèm, ghi chú.' },
      vanHanh: { steps: ['Tạo nhiệm vụ theo từng giai đoạn Deal.', 'Hoàn thành + ghi chú + file.', 'Kéo cột sau khi gate OK.'], mentor: 'Deal phức tạp hơn Lead — luôn có 2–3 task mở cho đến Thắng.' },
      baoCaoSua: { loiHay: ['Tick task chưa thu cọc.'], kpi: 'Đúng hạn task Deal.' },
      tomTat: 'Task Deal + gate + minh chứng — song song quy tắc Lead.',
    },
    quiz: mkQuiz([
      ['Gate Deal bảo vệ?', ['Doanh thu và quy trình thật', 'Chỉ admin', 'Chat', 'Màu tủ'], [0], 'Tư tưởng.'],
      ['Task Deal ví dụ?', ['Thu cọc, gửi bản vẽ', 'Tính lương', 'Blocklist', 'Lead mới'], [0], 'Tư tưởng.'],
      ['Gate giống Lead?', ['Có — nhiệm vụ chặn kéo cột', 'Không bao giờ', 'Chỉ Thua', 'Chỉ chat'], [0], 'Tư duy.'],
      ['Hoàn thành task Deal?', ['Ghi chú + file nếu cần', 'Chỉ tick', 'Xóa Deal', 'Thua'], [0], 'Tư duy.'],
      ['Nhiệm vụ vs hoạt động Deal?', ['Task = sắp làm; Hoạt động = đã làm', 'Giống hệt', 'Không dùng', 'Chỉ admin'], [0], 'Tư duy.'],
      ['Tab nhiệm vụ Deal?', ['Chi tiết Deal', 'Lead', 'Lương', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Gate chặn khi?', ['Task bắt buộc chưa xong', 'Trời mưa', 'VIP', 'Cuối tuần'], [0], 'Nguồn lực.'],
      ['File cọc gắn?', ['Task thu cọc / Tài liệu', 'Chat riêng', 'Xóa', 'Email cá nhân'], [0], 'Nguồn lực.'],
      ['Chưa cọc — kéo Thắng?', ['Không — hoàn thành task trước', 'Vẫn kéo', 'Thua', 'Lead mới'], [0], 'Vận hành.'],
      ['Bị chặn — làm?', ['Đọc thông báo, làm task', 'Bỏ qua', 'Xóa Deal', 'Báo cáo giả'], [0], 'Vận hành.'],
      ['Tick giả task — sửa?', ['Mở lại + minh chứng thật', 'Giữ tick', 'Thưởng', 'Không sao'], [0], 'Báo cáo.'],
      ['KPI task Deal?', ['Đúng hạn', 'Màu sơn', 'Giờ nghỉ', 'Facebook'], [0], 'Báo cáo.'],
    ]),
  },
  {
    num: 9,
    title: 'Bài 9: Tài liệu Deal — HĐ, vẽ, cọc, phân loại',
    summary: 'Lưu đúng loại file, tên chuẩn, tập trung hồ sơ một Deal.',
    pillar: {
      hook: 'Một Deal có thể có 10+ file — **HĐ**, **BG**, **ảnh đo**, **CK cọc**. Sai tab = xưởng không tìm thấy.',
      tuTuong: { vaiTro: 'Tài liệu Deal = **hồ sơ pháp lý và kỹ thuật** — thiếu file = rủi ro tranh chấp.', ynghia: ['Tập trung một Deal — không rải email cá nhân.'] },
      tuDuy: { bang: '| Loại | Ví dụ | Tab |\n|---|---|---|\n| Báo giá | BG_*.pdf | Báo giá/Tài liệu |\n| HĐ | HD_*.pdf | Tài liệu |\n| Cọc | CK_*.jpg | Tài liệu |\n| Bản vẽ | VE_*.pdf | Tài liệu |' },
      nguonLuc: { manHinh: 'Deal → **Tài liệu** (+ tab Báo giá)', congCu: ['Upload', 'Phân loại', 'Tải xuống cho xưởng'], duLieu: 'Tên file có nghĩa, ngày version.' },
      vanHanh: { steps: ['Mỗi file upload ngay khi có.', 'Đặt tên: `Loại_TênKH_YYYY-MM.ext`.', 'Không lưu chat riêng làm kho chính.'], mentor: 'Cuối tuần: mở 3 Deal đang chạy — kiểm tra đủ 4 loại file chưa.' },
      baoCaoSua: { loiHay: ['File trong chat, không Tài liệu.', 'Tên a.pdf.'], kpi: 'Handoff đủ file.' },
      tomTat: 'Mọi file Deal trên Tài liệu — tên rõ — đủ loại trước Thắng.',
    },
    quiz: mkQuiz([
      ['Tài liệu Deal quan trọng?', ['Hồ sơ pháp lý + kỹ thuật', 'Trang trí', 'Chỉ admin', 'Không cần'], [0], 'Tư tưởng.'],
      ['File rải email cá nhân?', ['Mất tập trung, handoff khó', 'Tốt', 'Thưởng', 'Bắt buộc'], [0], 'Tư tưởng.'],
      ['HĐ scan lưu?', ['Tài liệu Deal', 'Chat riêng', 'Lead', 'Xóa'], [0], 'Tư duy.'],
      ['Tên file tốt?', ['HD_ChịLan_2026-03.pdf', 'a.pdf', '1.jpg', 'tmp'], [0], 'Tư duy.'],
      ['BG vs HĐ tab?', ['Cùng hồ sơ Deal — Báo giá/Tài liệu', 'Không lưu', 'Chỉ miệng', 'Blocklist'], [0], 'Tư duy.'],
      ['Upload khi?', ['Ngay khi có file', 'Cuối năm', 'Sau Thua', 'Không'], [0], 'Nguồn lực.'],
      ['Bản vẽ cho xưởng?', ['Tài liệu Deal', 'Zalo riêng', 'Không gửi', 'Lead'], [0], 'Nguồn lực.'],
      ['4 loại file trước Thắng?', ['BG, HĐ, cọc, bản vẽ (theo SP)', 'Chỉ SĐT', 'Chỉ chat', 'Không cần'], [0], 'Nguồn lực.'],
      ['File mới từ KH?', ['Upload + ghi hoạt động', 'Im lặng', 'Thua', 'Xóa Deal'], [0], 'Vận hành.'],
      ['Xưởng không thấy file?', ['Kiểm tra Tài liệu Deal + @mention', 'Bỏ qua', 'Thắng lại', 'Lead mới'], [0], 'Vận hành.'],
      ['a.pdf — sửa?', ['Đổi tên có nghĩa', 'Giữ', 'Xóa Deal', 'Thua'], [0], 'Báo cáo.'],
      ['File chỉ trong chat — sửa?', ['Upload lại Tài liệu', 'Bỏ qua', 'Báo cáo giả', 'Blocklist'], [0], 'Báo cáo.'],
    ]),
  },
  {
    num: 10,
    title: 'Bài 10: KPI Deal — Doanh số, tỉ lệ thắng, đúng hạn',
    summary: 'Đọc Scorecard Deal, Ledger, kế hoạch cải thiện tỉ lệ thắng.',
    pillar: {
      hook: 'Tháng này: 5 Deal Thắng, 3 Thua (2 vì giá) — **Bảng điểm** cho bạn biết chỗ cần đàm phán tốt hơn.',
      tuTuong: { vaiTro: 'KPI Deal đo **kết quả kinh doanh** — không chỉ số cuộc gọi.', ynghia: ['Thua có lý do giúp bạn và công ty học — không che giấu.'] },
      tuDuy: { phanBiet: ['**Doanh số Thắng**', '**Tỉ lệ thắng** (Thắng / (Thắng+Thua))', '**Thời gian chu kỳ Deal**'] },
      nguonLuc: { manHinh: '**CRM → Bảng điểm** (lọc Deal)', congCu: ['Scorecard', 'Báo cáo Thua theo lý do'], duLieu: 'Số tiền cọc, ngày Thắng, lý do Thua.' },
      vanHanh: { steps: ['Cuối tuần xem KPI Deal.', 'Thua vì giá → trao đổi team giải pháp.', 'Không kéo Thắng ảo để đẹp số.'], mentor: 'So sánh tỉ lệ thắng theo **nguồn Lead** — kênh nào cần lọc sớm.' },
      baoCaoSua: { loiHay: ['Chỉ nhìn doanh số, bỏ qua tỉ lệ thua.'], kpi: 'Doanh số, tỉ lệ thắng, SLA giai đoạn.' },
      tomTat: 'Bảng điểm Deal = doanh số + tỉ lệ thắng + thời gian; Thua có lý do = dữ liệu vàng.',
    },
    quiz: mkQuiz([
      ['KPI Deal đo?', ['Kết quả kinh doanh', 'Chỉ màu tủ', 'Giờ nghỉ', 'Facebook'], [0], 'Tư tưởng.'],
      ['Thua có lý do — KPI?', ['Dữ liệu để cải thiện', 'Vô dụng', 'Xóa', 'Phạt cá nhân'], [0], 'Tư tưởng.'],
      ['Tỉ lệ thắng?', ['Thắng / (Thắng+Thua)', 'Chỉ Lead', 'Chỉ chat', 'Không có'], [0], 'Tư duy.'],
      ['Doanh số Thắng?', ['Tiền cọc/HĐ đã ghi nhận', 'BG miệng', 'Lead mới', 'Blocklist'], [0], 'Tư duy.'],
      ['Thắng ảo KPI?', ['Làm sai số liệu — tránh', 'Tốt', 'Thưởng', 'Bắt buộc'], [0], 'Tư duy.'],
      ['Xem KPI Deal?', ['Bảng điểm CRM', 'Chỉ sếp', 'Zalo', 'Không'], [0], 'Nguồn lực.'],
      ['Báo cáo Thua theo?', ['Lý do', 'Màu mắt', 'Giờ nghỉ', 'Chat'], [0], 'Nguồn lực.'],
      ['Ledger Deal?', ['Sự kiện cộng/trừ điểm', 'Loại cửa', 'Mã HĐ', 'Tên KH'], [0], 'Nguồn lực.'],
      ['Thua vì giá — hành động?', ['Trao đổi team, điều chỉnh chiến lược', 'Bỏ qua', 'Thắng ảo', 'Xóa'], [0], 'Vận hành.'],
      ['Cuối tuần Deal KPI?', ['Xem Scorecard + kế hoạch', 'Bỏ qua', 'Tick giả', 'Tắt CRM'], [0], 'Vận hành.'],
      ['Chỉ nhìn doanh số — thiếu?', ['Tỉ lệ thua và thời gian chu kỳ', 'Không thiếu', 'Chat', 'Lead'], [0], 'Báo cáo.'],
      ['KPI thấp — sửa?', ['Kế hoạch hành vi cụ thể', 'Báo cáo giả', 'Tắt CRM', 'Thua không lý do'], [0], 'Báo cáo.'],
    ]),
  },
  {
    num: 11,
    title: 'Bài 11: Bàn giao xưởng — Đủ thông tin trước sản xuất',
    summary: 'BOM, bản vẽ, lịch giao, liên hệ lắp đặt — checklist handoff.',
    pillar: {
      hook: 'Xưởng hỏi: "Bản vẽ đâu? Ngày giao đâu?" — checklist bàn giao tránh delay 2 tuần.',
      tuTuong: { vaiTro: 'Sales **không kết thúc** ở Thắng — hỗ trợ xưởng đến khi hàng giao đúng hẹn.', ynghia: ['Handoff kém = sales bị KH gọi la dù đã cọc.'] },
      tuDuy: { mentalModel: 'Handoff = **biên bản bàn giao** — thiếu mục nào ký nhận mục đó.' },
      nguonLuc: { manHinh: 'Deal Thắng + **Dự án xưởng**', congCu: ['Chat @xưởng', 'Upload BOM/bản vẽ', 'Lịch giao trong dự án'], duLieu: 'Địa chỉ lắp, SĐT lắp, ngày hẹn, yêu cầu đặc biệt.' },
      vanHanh: { steps: ['Checklist: bản vẽ, BOM, HĐ, cọc, địa chỉ lắp, ngày giao.', 'Tạo dự án popup đầy đủ.', 'Gọi/ chat xưởng xác nhận.', 'Theo dõi đến khi giao — cập nhật KH.'], mentor: 'Copy địa chỉ lắp từ Lead — đã có sẵn nếu đủ 6 trường từ đầu.' },
      baoCaoSua: { loiHay: ['Thiếu địa chỉ lắp.', 'Không ngày giao.'], kpi: 'Thời gian handoff, khiếu nại sau giao.' },
      tomTat: 'Checklist handoff đủ kỹ thuật + logistics; xác nhận xưởng; theo dõi đến giao hàng.',
    },
    quiz: mkQuiz([
      ['Sales kết thúc ở Thắng?', ['Không — hỗ trợ đến giao hàng', 'Có', 'Xóa Deal', 'Lead mới'], [0], 'Tư tưởng.'],
      ['Handoff kém?', ['KH gọi la, delay', 'Tốt', 'Thưởng', 'Không sao'], [0], 'Tư tưởng.'],
      ['Handoff giống?', ['Biên bản bàn giao', 'Chat riêng', 'Blocklist', 'Thua'], [0], 'Tư duy.'],
      ['Địa chỉ lắp từ?', ['Lead (6 trường) nếu đã nhập', 'Đoán', 'Không cần', 'Blocklist'], [0], 'Tư duy.'],
      ['BOM là?', ['Danh mục vật tư sản xuất', 'Mã Lead', 'Chat', 'KPI'], [0], 'Tư duy.'],
      ['Handoff file?', ['Bản vẽ, BOM, HĐ, cọc', 'Chỉ SĐT', 'Chỉ chat', 'Không'], [0], 'Nguồn lực.'],
      ['Xác nhận xưởng?', ['Chat/call sau Thắng', 'Không cần', 'Cuối năm', 'Thua'], [0], 'Nguồn lực.'],
      ['Lịch giao ghi?', ['Dự án / Deal hoạt động', 'Miệng', 'Xóa', 'Lead'], [0], 'Nguồn lực.'],
      ['Thiếu bản vẽ — giao xưởng?', ['Bổ sung trước handoff', 'Vẫn giao', 'Thua', 'Blocklist'], [0], 'Vận hành.'],
      ['Sau handoff — sales?', ['Theo dõi tiến độ, cập nhật KH', 'Im lặng', 'Xóa CRM', 'Lead mới'], [0], 'Vận hành.'],
      ['Thiếu ngày giao — sửa?', ['Thỏa thuận KH + ghi dự án', 'Bỏ qua', 'Thắng lại', 'Báo cáo giả'], [0], 'Báo cáo.'],
      ['Xưởng không nhận file — sửa?', ['Upload Tài liệu + @mention lại', 'Thua', 'Xóa Deal', 'Lead mới'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Bản vẽ + BOM trên Deal', 'Địa chỉ + SĐT lắp đúng', 'Ngày giao đã thỏa thuận', 'Xưởng xác nhận đã nhận'],
  },
  {
    num: 12,
    title: 'Bài 12: Ôn tập Deal — Từ chuyển Lead đến Thắng/Thua',
    summary: 'Hành trình Deal end-to-end qua 5 trụ; checklist tổng.',
    pillar: {
      hook: 'Một Deal đi trọn: **Chuyển từ Lead** → BG → Đàm phán → HĐ + cọc → **Thắng** + xưởng — hoặc **Thua** có lý do.',
      tuTuong: { vaiTro: 'Bạn nắm **dòng tiền** — mỗi cột pipeline gắn với hành động và file.', ynghia: ['Deal sai một bước = delay cả chuỗi SX.'] },
      tuDuy: { mentalModel: 'Lead (nuôi) → Deal (thu hoạch) → Thắng (bàn giao) hoặc Thua (học).' },
      nguonLuc: { manHinh: 'Bảng Deal + Chi tiết + Bảng điểm + Dự án xưởng', congCu: ['Kanban', 'Tài liệu', 'Task', 'Scorecard'] },
      vanHanh: {
        steps: [
          'Chuyển Deal (đủ điều kiện Lead).',
          'BG chính thức → Đàm phán → HĐ + cọc.',
          'Thắng + popup dự án + handoff xưởng.',
          'Hoặc Thua + lý do.',
        ],
      },
      baoCaoSua: { tuKiem: ['Làm end-to-end được?', 'Đọc KPI Deal?', 'Handoff checklist?'], kpi: 'Toàn bộ chỉ số Deal.' },
      tomTat: 'Deal = 5 trụ từ pipeline đến Thắng/Thua; file và KPI không tách rời.',
    },
    quiz: mkQuiz([
      ['Deal — dòng tiền?', ['Mỗi cột gắn hành động + file', 'Chỉ Kanban', 'Chỉ chat', 'Lead'], [0], 'Tư tưởng.'],
      ['Deal sai bước?', ['Delay cả chuỗi SX', 'Không sao', 'Thưởng', 'Khách vui'], [0], 'Tư tưởng.'],
      ['Hành trình Deal?', ['Lead→BG→HĐ→Thắng/Thua', 'Thắng→Lead', 'Chỉ chat', 'Blocklist'], [0], 'Tư duy.'],
      ['Thua cuối hành trình?', ['Lý do bắt buộc', 'Xóa', 'Im lặng', 'Lead trùng'], [0], 'Tư duy.'],
      ['Thắng cuối?', ['Handoff xưởng', 'Xóa CRM', 'Chỉ KPI', 'Blocklist'], [0], 'Tư duy.'],
      ['Công cụ end-to-end?', ['Bảng Deal + Tài liệu + Scorecard', 'Excel', 'Zalo', 'Sổ tay'], [0], 'Nguồn lực.'],
      ['Popup Thắng?', ['Tạo dự án SX', 'Xóa Deal', 'Lead', 'Lương'], [0], 'Nguồn lực.'],
      ['File trước Thắng?', ['BG, HĐ, cọc, bản vẽ', 'Chỉ SĐT', 'Không', 'Chat'], [0], 'Nguồn lực.'],
      ['Bước 1 Deal?', ['Kiểm tra hồ sơ chuyển từ Lead', 'Thắng ngay', 'Thua', 'Blocklist'], [0], 'Vận hành.'],
      ['Thiếu cọc — Thắng?', ['Không — bổ sung trước', 'Vẫn Thắng', 'Thua', 'Lead'], [0], 'Vận hành.'],
      ['KPI thấp — sửa?', ['Bảng điểm + hành vi', 'Thắng ảo', 'Báo cáo giả', 'Tắt CRM'], [0], 'Báo cáo.'],
      ['Thua không lý do — sửa?', ['Chọn lý do + ghi chú', 'Xóa', 'Thắng', 'Lead mới'], [0], 'Báo cáo.'],
    ]),
  },
];

const FINAL_EXAM = [
  ['Deal là gì?', ['Đã thống nhất mua, đang HĐ', 'Khách mới hỏi giá', 'Đã SX xong', 'Lead'], [0], 'Tư duy.'],
  ['Thắng khi?', ['HĐ + cọc + handoff', 'Mới Deal', 'Chưa BG', 'Blocklist'], [0], 'Vận hành.'],
  ['Thua phải?', ['Lý do', 'Im lặng', 'Xóa', 'Lead mới'], [0], 'Báo cáo.'],
  ['BG chính thức?', ['PDF trên Deal sau đo', 'Miệng', 'Lead only', 'Không'], [0], 'Vận hành.'],
  ['Cọc chứng từ?', ['Tài liệu Deal', 'Chat riêng', 'Xóa', 'Email'], [0], 'Nguồn lực.'],
  ['Pipeline Deal mẫu?', ['6 giai đoạn', 'Không', '1 cột', 'Lead'], [0], 'Tư duy.'],
  ['Gate Deal?', ['Task chặn kéo cột', 'Không', 'Chỉ admin', 'Chat'], [0], 'Vận hành.'],
  ['Handoff gồm?', ['Bản vẽ, BOM, lịch giao', 'Chỉ SĐT', 'Chat', 'Blocklist'], [0], 'Vận hành.'],
  ['Popup Thắng?', ['Tạo dự án SX', 'Xóa Deal', 'Lead', 'Lương'], [0], 'Nguồn lực.'],
  ['KPI Deal?', ['Doanh số, tỉ lệ thắng', 'Màu tủ', 'Giờ nghỉ', 'Facebook'], [0], 'Báo cáo.'],
  ['HĐ khớp BG?', ['Bắt buộc', 'Không', 'Tùy ý', 'Miệng'], [0], 'Tư duy.'],
  ['Đàm phán ghi?', ['Hoạt động + BG cập nhật', 'Im lặng', 'Thua', 'Xóa'], [0], 'Vận hành.'],
  ['Thắng ảo?', ['Sai KPI — tránh', 'Tốt', 'Thưởng', 'Bắt buộc'], [0], 'Báo cáo.'],
  ['Bảng Deal?', ['CRM → Bảng Deal', 'Lead', 'Lương', 'Blocklist'], [0], 'Nguồn lực.'],
  ['Deal kế thừa?', ['Lịch sử Lead', 'Không', 'Chat', 'KPI only'], [0], 'Tư duy.'],
  ['File tên a.pdf?', ['Sửa tên có nghĩa', 'OK', 'Xóa Deal', 'Thua'], [0], 'Báo cáo.'],
  ['Giảm giá lớn?', ['Phê duyệt sếp', 'Tự ý', 'Không ghi', 'Blocklist'], [0], 'Vận hành.'],
  ['Sales sau Thắng?', ['Theo dõi đến giao hàng', 'Xóa CRM', 'Lead mới', 'Im lặng'], [0], 'Tư tưởng.'],
  ['Thua vì giá — dùng?', ['Phân tích pricing', 'Xóa', 'Thắng', 'Báo cáo giả'], [0], 'Báo cáo.'],
  ['5 trụ Deal?', ['TT, TD, NL, VH, BC', 'Chỉ Kanban', 'Chỉ chat', 'Lead only'], [0], 'Tư tưởng.'],
];

module.exports = { LESSON_SPECS, FINAL_EXAM, q, mkQuiz };
