/**
 * Khoá Hướng dẫn CRM — thao tác phần mềm (5 trụ).
 */
const { quizItem } = require('./_helpers');
const q = quizItem;

const mkQuiz = (rows) => {
  const n = rows.length;
  const per = Math.max(2, Math.floor(n / 5));
  return {
    tt: rows.slice(0, per),
    td: rows.slice(per, per * 2),
    nl: rows.slice(per * 2, per * 3),
    vh: rows.slice(per * 3, per * 4),
    bc: rows.slice(per * 4),
  };
};

const LESSON_SPECS = [
  {
    num: 1,
    title: 'HD 1: Vì sao phải thao tác trên phần mềm CRM',
    summary: 'Tư tưởng: mọi việc quan trọng ghi trên hệ thống — không sổ tay.',
    pillar: {
      hook: 'Buổi sáng đồng nghiệp nghỉ — bạn mở CRM là thấy hết lịch sử khách của họ. Đó là lý do **phải dùng app**.',
      tuTuong: { vaiTro: 'Phần mềm CRM là **công cụ làm việc chính** — không phải phụ trợ.', ynghia: ['Ghi trên app = KPI công bằng, handover dễ.', 'Thao tác ngoài app = dữ liệu công ty bị thiếu.'] },
      tuDuy: { mentalModel: 'CRM = **sổ công ty** — ai cũng đọc được phần mình có quyền.' },
      nguonLuc: { manHinh: 'Trình duyệt → địa chỉ công ty → **Đăng nhập**', congCu: ['App Switcher', 'Sidebar', 'Module CRM'] },
      vanHanh: { steps: ['Đăng nhập tài khoản **cá nhân**.', 'App Switcher → **CRM**.', 'Ghim (Pin) module CRM.'], mentor: 'Mỗi thao tác quan trọng — hỏi: "Đã ghi trên CRM chưa?"' },
      baoCaoSua: { loiHay: ['Ghi sổ tay riêng.', 'Dùng chung tài khoản.'], tomTat: 'CRM = công cụ chính; đăng nhập → CRM → mọi thao tác trên app.' },
      tomTat: 'Phần mềm CRM là nơi làm việc chính — không thay bằng sổ tay.',
    },
    quiz: mkQuiz([
      ['Vì sao thao tác trên CRM?', ['Lưu lịch sử, KPI, handover', 'Chỉ giám sát', 'Tốn thời gian', 'Không lý do'], [0], 'Tư tưởng.'],
      ['Ghi sổ tay thay CRM?', ['Mất minh bạch', 'Tốt hơn', 'Bắt buộc', 'Thưởng'], [0], 'Tư tưởng.'],
      ['CRM giống?', ['Sổ công ty dùng chung', 'Chat riêng', 'Excel cá nhân', 'Blocklist'], [0], 'Tư duy.'],
      ['Thao tác ngoài app?', ['Dữ liệu công ty thiếu', 'Tốt', 'Thưởng', 'Bắt buộc'], [0], 'Tư duy.'],
      ['Module CRM mở qua?', ['App Switcher', 'Email', 'Zalo', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Sidebar?', ['Menu trái', 'Giữa màn hình', 'Dưới', 'Không có'], [0], 'Nguồn lực.'],
      ['Pin module?', ['Vào thẳng lần sau', 'Xóa CRM', 'Khóa', 'Đổi pass'], [0], 'Nguồn lực.'],
      ['Đăng nhập dùng?', ['Tài khoản cá nhân', 'Chung team', 'Khách hàng', 'Không cần'], [0], 'Vận hành.'],
      ['Sau đăng nhập — CRM?', ['App Switcher → CRM', 'Tắt máy', 'Chỉ chat', 'Blocklist'], [0], 'Vận hành.'],
      ['Thao tác quan trọng — tự hỏi?', ['Đã ghi CRM chưa?', 'In PDF chưa?', 'Nghỉ chưa?', 'Chat chưa?'], [0], 'Vận hành.'],
      ['Dùng chung tài khoản?', ['Vi phạm — không biết ai làm', 'Tốt', 'Thưởng', 'Bắt buộc'], [0], 'Báo cáo.'],
      ['Quên ghi CRM — sửa?', ['Bổ sung ngay trên app', 'Bỏ qua', 'Xóa khách', 'Báo cáo giả'], [0], 'Báo cáo.'],
    ]),
  },
  {
    num: 2,
    title: 'HD 2: Đăng nhập và làm quen giao diện',
    summary: 'Sidebar, App Switcher, ba vùng màn hình, ghim module.',
    pillar: {
      hook: 'Lần đầu vào CRM — đừng lo "mất menu". **App Switcher** (biểu tượng lưới) mở mọi module.',
      tuTuong: { vaiTro: 'Biết đường trong app = **tiết kiệm 10 phút mỗi ngày**.', ynghia: ['Giao diện ổn định — học một lần, dùng lâu dài.'] },
      tuDuy: {
        bang: '| Vùng | Việc bạn làm |\n|---|---|\n| Sidebar trái | Chọn CRM, Cài đặt |\n| Thanh trên | Tìm, thông báo, tài khoản |\n| Giữa | Bảng Lead, chi tiết… |',
        phanBiet: ['**Sidebar** _(menu trái)_', '**App Switcher** _(lưới góc trên — chuyển module)_'],
      },
      nguonLuc: { manHinh: 'Toàn màn hình sau đăng nhập', congCu: ['Sidebar', 'App Switcher', 'Pin module', 'Thanh tìm kiếm'] },
      vanHanh: { steps: ['Nhập URL công ty → **Đăng nhập** (email + mật khẩu).', '**App Switcher** → **CRM**.', '**Pin** module CRM.', '**CRM → Bảng Lead** — thấy Kanban.'], mentor: 'Bookmark URL CRM trên trình duyệt — vào nhanh hơn.' },
      baoCaoSua: { loiHay: ['Tưởng mất menu — không biết App Switcher.'], tomTat: 'Đăng nhập → App Switcher → CRM → Pin → Bảng Lead.' },
      tomTat: 'Ba vùng màn hình; App Switcher mở CRM; Pin tiết kiệm thao tác.',
    },
    quiz: mkQuiz([
      ['App Switcher dùng để?', ['Chuyển module (CRM, Công việc…)', 'Đăng xuất', 'In BG', 'Xóa Lead'], [0], 'Tư duy.'],
      ['Sidebar ở?', ['Bên trái', 'Giữa', 'Phải', 'Dưới'], [0], 'Nguồn lực.'],
      ['Pin module?', ['Vào thẳng lần sau', 'Xóa', 'Khóa', 'Đổi email'], [0], 'Nguồn lực.'],
      ['Nội dung giữa hiển thị?', ['Trang đang chọn (vd Bảng Lead)', 'Chỉ logo', 'Chỉ chat', 'Chỉ KPI'], [0], 'Tư duy.'],
      ['Vào CRM lần đầu?', ['App Switcher → CRM', 'Cài đặt trước', 'Tắt trình duyệt', 'Chỉ mobile'], [0], 'Vận hành.'],
      ['Xác nhận CRM OK?', ['Mở Bảng Lead thấy Kanban', 'Chỉ logo', 'Lỗi 404', 'Blocklist'], [0], 'Vận hành.'],
      ['Thanh trên có?', ['Tìm, thông báo, tài khoản', 'Chỉ logo', 'Chỉ chat', 'Không'], [0], 'Nguồn lực.'],
      ['Bookmark URL?', ['Vào nhanh', 'Cấm', 'Xóa CRM', 'Thua'], [0], 'Mẹo mentor.'],
      ['Tưởng mất menu — sửa?', ['Mở App Switcher', 'Cài lại Windows', 'Xóa Lead', 'Thua'], [0], 'Báo cáo.'],
      ['Không Pin module?', ['Mất vài click mỗi ngày', 'Không sao', 'Thưởng', 'Bắt buộc'], [0], 'Báo cáo.'],
      ['Đăng nhập cần?', ['Email + mật khẩu công ty', 'Chỉ tên', 'Không', 'SĐT khách'], [0], 'Vận hành.'],
      ['CRM nằm trong?', ['Hệ thống module (App Switcher)', 'Email', 'Zalo', 'Excel'], [0], 'Tư tưởng.'],
    ]),
  },
  {
    num: 3,
    title: 'HD 3: Bảo mật tài khoản',
    summary: 'Mật khẩu mạnh, đổi định kỳ, đăng xuất thiết bị lạ.',
    pillar: {
      hook: 'CRM chứa SĐT khách — lộ mật khẩu = người lạ xem Lead của bạn.',
      tuTuong: { vaiTro: 'Bảo mật = **bảo vệ khách hàng** và uy tín cá nhân.', ynghia: ['Một tài khoản một người — không chia sẻ.'] },
      tuDuy: { mentalModel: 'Mật khẩu CRM như **chìa khóo kho** — không dán lên màn hình.' },
      nguonLuc: { manHinh: '**Cài đặt → Đổi mật khẩu / Thiết bị đăng nhập**', congCu: ['Đổi mật khẩu', 'Danh sách thiết bị', 'Đăng xuất thiết bị lạ'] },
      vanHanh: { steps: ['Mật khẩu ≥ **8 ký tự**, hoa + thường + số.', '**Cài đặt → Đổi mật khẩu** khi nghi ngờ lộ.', '**Thiết bị đăng nhập** → đăng xuất thiết bị lạ.', 'Không gửi mật khẩu qua Zalo.'], mentor: 'Đổi mật khẩu 3 tháng/lần — đặt nhắc trên điện thoại.' },
      baoCaoSua: { loiHay: ['Ghi pass trên giấy dán màn hình.', 'Chia sẻ pass qua chat.'], tomTat: 'Pass riêng, ≥8 ký tự, kiểm tra thiết bị lạ, không chia sẻ.' },
      tomTat: 'Mật khẩu riêng — đổi định kỳ — kiểm tra thiết bị — không chia sẻ.',
    },
    quiz: mkQuiz([
      ['CRM chứa dữ liệu nhạy cảm?', ['SĐT, lịch sử KH', 'Chỉ logo', 'Chỉ ảnh SP', 'Video'], [0], 'Tư tưởng.'],
      ['Chia sẻ pass Zalo?', ['Vi phạm bảo mật', 'OK', 'Thưởng', 'Bắt buộc'], [0], 'Tư tưởng.'],
      ['Mật khẩu CRM như?', ['Chìa khóa kho', 'Tên KH', 'Mã Lead', 'BG'], [0], 'Tư duy.'],
      ['Một tài khoản?', ['Một người', 'Cả team', 'Khách', 'Không giới hạn'], [0], 'Tư duy.'],
      ['Pass tối thiểu?', ['8 ký tự', '4', '6', '2'], [0], 'Nguồn lực.'],
      ['Đổi pass ở?', ['Cài đặt → Đổi mật khẩu', 'Bảng Lead', 'Kanban', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Thiết bị lạ — làm?', ['Đăng xuất + đổi pass', 'Bỏ qua', 'Tạo Lead', 'Thua'], [0], 'Vận hành.'],
      ['Nghi ngờ lộ pass?', ['Đổi ngay', 'Chờ năm sau', 'Chat pass mới', 'Xóa CRM'], [0], 'Vận hành.'],
      ['Ghi pass giấy dán màn hình?', ['Không', 'Nên', 'Bắt buộc', 'Thưởng'], [0], 'Báo cáo.'],
      ['Pass trên chat — sửa?', ['Đổi pass ngay', 'Giữ', 'Chia tiếp', 'Bỏ qua'], [0], 'Báo cáo.'],
      ['Đổi pass định kỳ?', ['3 tháng hoặc khi nghi ngờ', 'Không bao giờ', '10 năm', 'Mỗi giờ'], [0], 'Vận hành.'],
      ['Thiết bị đăng nhập xem ở?', ['Cài đặt', 'Lead', 'Deal', 'Chat'], [0], 'Nguồn lực.'],
    ]),
  },
  {
    num: 4,
    title: 'HD 4: Bảng Lead — Kanban, lọc, tìm kiếm',
    summary: 'Menu CRM → Bảng Lead; kéo thẻ; Lead của tôi; badge SLA.',
    pillar: {
      hook: 'Sáng vào ca — **Bảng Lead → Kanban → Lead của tôi** — 3 click, thấy việc cả ngày.',
      tuTuong: { vaiTro: 'Bảng Lead là **bàn làm việc hàng ngày** của sales.', ynghia: ['Kanban = biết khách đang ở giai đoạn nào.'] },
      tuDuy: { phanBiet: ['**Kanban** _(kéo thẻ)_ vs **Danh sách** _(xem nhanh nhiều dòng)_'] },
      nguonLuc: { manHinh: '**CRM → Bảng Lead**', congCu: ['Tab Kanban', 'Bộ lọc Lead của tôi', 'Ô tìm kiếm', 'Tab Deadline'] },
      vanHanh: { steps: ['**Menu → CRM → Bảng Lead**.', 'Tab **Kanban**.', 'Lọc **Lead của tôi**.', 'Click thẻ → chi tiết.', 'Kéo thẻ khi đủ điều kiện.'], mentor: 'Badge đỏ = ưu tiên — xử lý trước cafe sáng.' },
      baoCaoSua: { loiHay: ['Không lọc Lead của tôi — nhầm Lead người khác.'], tomTat: 'Bảng Lead → Kanban → Lọc của tôi → click/kéo; đỏ = SLA.' },
      tomTat: 'Bảng Lead = bàn làm việc; Kanban + lọc + badge đỏ SLA.',
    },
    quiz: mkQuiz([
      ['Bảng Lead là?', ['Bàn làm việc sales hàng ngày', 'Chỉ KPI', 'Chỉ chat', 'Lương'], [0], 'Tư tưởng.'],
      ['Kanban giúp?', ['Biết giai đoạn khách', 'Tính lương', 'Xóa', 'Blocklist'], [0], 'Tư tưởng.'],
      ['Kanban vs Danh sách?', ['Kanban kéo thẻ; Danh sách xem nhiều dòng', 'Giống', 'Không có', 'Lead only'], [0], 'Tư duy.'],
      ['Mỗi thẻ Kanban?', ['Một Lead', 'Một NV', 'Một file', 'KPI tháng'], [0], 'Tư duy.'],
      ['Vào Bảng Lead?', ['CRM → Bảng Lead', 'Công việc', 'Kiến thức', 'Xưởng'], [0], 'Nguồn lực.'],
      ['Lọc Lead của tôi?', ['Lead bạn phụ trách', 'Ẩn hết', 'Xóa', 'In HĐ'], [0], 'Nguồn lực.'],
      ['Badge đỏ?', ['Sắp/quá hạn SLA', 'Đã ký HĐ', 'VIP', 'Đã xóa'], [0], 'Nguồn lực.'],
      ['Click thẻ?', ['Mở chi tiết Lead', 'Xóa', 'Email auto', 'Tạo NV'], [0], 'Vận hành.'],
      ['Kéo thẻ?', ['Đổi giai đoạn', 'In PDF', 'Chat', 'Lương'], [0], 'Vận hành.'],
      ['Tab Deadline?', ['Nhóm theo hạn', 'Xóa', 'BG', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Nhầm Lead người khác — sửa?', ['Bật lọc Lead của tôi', 'Sửa Lead họ', 'Xóa', 'Thua'], [0], 'Báo cáo.'],
      ['Tìm Lead theo?', ['Tên, SĐT, mã', 'Chỉ màu', 'Không', 'Email công ty'], [0], 'Vận hành.'],
    ]),
  },
  {
    num: 5,
    title: 'HD 5: Tạo Lead mới và Quét trùng SĐT',
    summary: 'Nút + Lead mới, form, Quét trùng, Lưu.',
    pillar: {
      hook: 'Chị Hoa nhắn Zalo — **+ Lead mới** nhưng **Quét trùng** trước — SĐT đã có Lead cũ.',
      tuTuong: { vaiTro: 'Tạo Lead đúng = **một khách một luồng** trên hệ thống.', ynghia: ['Trùng SĐT → KPI và chăm sóc loạn.'] },
      tuDuy: { mentalModel: 'Quét trùng = **tra cứu thư viện** trước khi thêm sách mới.' },
      nguonLuc: { manHinh: '**Bảng Lead → + Lead mới**', congCu: ['Form tiêu đề + Khách hàng', 'Quét trùng', 'Nguồn, Loại SP'] },
      vanHanh: { steps: ['**+ Lead mới**.', 'Tiêu đề: Tên — Khu vực — SP.', 'SĐT → **Quét trùng**.', 'Trùng → mở cũ; không trùng → Nguồn, Loại SP → **Lưu**.'], mentor: 'Copy tiêu đề mẫu từ Lead đẹp — paste sửa nhanh.' },
      baoCaoSua: { loiHay: ['Bỏ qua Quét trùng.', 'Tiêu đề trống.'], tomTat: 'Quét trùng → tiêu đề rõ → Nguồn → Lưu.' },
      tomTat: '+ Lead mới → Quét trùng bắt buộc → tiêu đề rõ → Lưu.',
    },
    quiz: mkQuiz([
      ['Quét trùng vì?', ['Một KH một luồng', 'Làm khó', 'In PDF', 'Blocklist'], [0], 'Tư tưởng.'],
      ['Trùng SĐT — KPI?', ['Loạn nếu tạo mới', 'Tốt', 'Thưởng', 'Không'], [0], 'Tư tưởng.'],
      ['Quét trùng như?', ['Tra thư viện trước thêm sách', 'Xóa KH', 'Thua', 'Chat'], [0], 'Tư duy.'],
      ['Trùng — làm?', ['Mở Lead cũ', 'Tạo mới', 'Đổi SĐT giả', 'Xóa'], [0], 'Tư duy.'],
      ['+ Lead mới ở?', ['Thanh trên Bảng Lead', 'Footer', 'Cài đặt', 'SX'], [0], 'Nguồn lực.'],
      ['Tối thiểu form?', ['Tiêu đề + Khách hàng', 'MST', 'HĐ', '3D'], [0], 'Nguồn lực.'],
      ['Trước Lưu?', ['Quét trùng', 'In PDF', 'Ký HĐ', 'SX'], [0], 'Vận hành.'],
      ['Tiêu đề tốt?', ['Tên + khu vực + SP', 'Trống', '"KH"', 'Chỉ ngày'], [0], 'Vận hành.'],
      ['Sau Lưu — cột?', ['Mới (đầu pipeline)', 'Thắng', 'Xóa', 'Deal'], [0], 'Vận hành.'],
      ['Bỏ Quét trùng — sửa?', ['Gộp Lead trùng + ghi chú', 'Giữ 2 Lead', 'Xóa', 'Thua'], [0], 'Báo cáo.'],
      ['Tiêu đề trống — sửa?', ['Sửa trong chi tiết Lead', 'Bỏ qua', 'Xóa', 'Blocklist'], [0], 'Báo cáo.'],
      ['Nguồn + Loại SP?', ['Chọn trước Lưu', 'Không cần', 'Sau 1 năm', 'Admin only'], [0], 'Vận hành.'],
    ]),
    checklist: ['Quét trùng trước Lưu', 'Tiêu đề rõ', 'SĐT 10 số', 'Nguồn + Loại SP', 'Lead ở cột Mới'],
  },
  {
    num: 6,
    title: 'HD 6: Chi tiết Lead — Bốn tab trên phần mềm',
    summary: 'Tổng quan, Nhiệm vụ, Hoạt động, Tài liệu; nút header.',
    pillar: {
      hook: 'Click thẻ Lead — **4 tab** như 4 ngăn tủ. Ghi nhầm ngăn = đồng nghiệp không tìm file.',
      tuTuong: { vaiTro: 'Chi tiết Lead = **màn hình làm việc chính** với một khách.', ynghia: ['Đúng tab = handover và KPI đúng.'] },
      tuDuy: { bang: '| Tab | Dùng cho |\n|---|---|\n| Tổng quan | 6 trường, phụ trách |\n| Nhiệm vụ | Việc có hạn |\n| Hoạt động | Gọi/gặp đã làm |\n| Tài liệu | PDF, ảnh |' },
      nguonLuc: { manHinh: 'Click thẻ → Chi tiết Lead', congCu: ['4 tab', 'Nút Chuyển Deal, Sửa, Mất/Mở lại'] },
      vanHanh: { steps: ['**Tổng quan**: kiểm 6 trường.', '**Nhiệm vụ**: tạo/hoàn thành task.', '**Hoạt động**: ghi gọi/gặp.', '**Tài liệu**: upload PDF/ảnh.', '**Chuyển Deal** header khi đủ (khoá nghiệp vụ).'], mentor: 'Phím tắt: bookmark chi tiết Lead hay dùng.' },
      baoCaoSua: { loiHay: ['Ghi gọi vào Tài liệu.', 'Không đọc Hoạt động trước gọi.'], tomTat: '4 tab — đúng chỗ; header = Chuyển Deal / Mất.' },
      tomTat: 'Tổng quan / Nhiệm vụ / Hoạt động / Tài liệu — đúng tab đúng việc.',
    },
    quiz: mkQuiz([
      ['Chi tiết Lead?', ['Màn hình chính với 1 KH', 'Chỉ KPI', 'Chat', 'Lương'], [0], 'Tư tưởng.'],
      ['Sai tab?', ['Handover khó', 'Tốt', 'Thưởng', 'Bắt buộc'], [0], 'Tư tưởng.'],
      ['Ghi chú gọi?', ['Hoạt động / Nhiệm vụ', 'Tài liệu', 'Blocklist', 'Xóa'], [0], 'Tư duy.'],
      ['HĐ PDF?', ['Tài liệu', 'Chat', 'Không lưu', 'Email'], [0], 'Tư duy.'],
      ['Tab Tổng quan?', ['6 trường + phụ trách', 'Chỉ chat', 'KPI năm', 'Logo'], [0], 'Nguồn lực.'],
      ['Chuyển Deal nút?', ['Header chi tiết', 'Footer', 'Cài đặt', 'Báo cáo'], [0], 'Nguồn lực.'],
      ['Tab Nhiệm vụ?', ['Tạo/hoàn thành task', 'Tính lương', 'Xóa', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Trước gọi — tab?', ['Hoạt động', 'Blocklist', 'Lương', 'Chat cty'], [0], 'Vận hành.'],
      ['Upload ảnh đo?', ['Tài liệu', 'Chat riêng', 'Xóa', 'Lead khác'], [0], 'Vận hành.'],
      ['Mất Lead nút?', ['Header (tùy quyền)', 'Footer', 'SX', 'Blocklist'], [0], 'Vận hành.'],
      ['Ghi gọi vào Tài liệu — sửa?', ['Chuyển Hoạt động', 'Giữ', 'Xóa Lead', 'Thua'], [0], 'Báo cáo.'],
      ['Không đọc lịch sử — sửa?', ['Mở Hoạt động trước gọi', 'Bỏ qua', 'Xóa', 'Lead mới'], [0], 'Báo cáo.'],
    ]),
  },
  {
    num: 7,
    title: 'HD 7: Nhiệm vụ và Hoạt động — Thao tác trên app',
    summary: 'Tạo task, hoàn thành + popup ghi chú, timeline hoạt động.',
    pillar: {
      hook: 'Bấm **Hoàn thành** nhiệm vụ — popup bắt ghi chú. Đây là **minh chứng** trên phần mềm.',
      tuTuong: { vaiTro: 'App **bắt buộc** ghi kết quả — không tick cho qua.', ynghia: ['Popup = nhắc bạn làm đúng quy trình.'] },
      tuDuy: { phanBiet: ['**+ Hoạt động** _(ghi việc đã làm)_ vs **Nhiệm vụ** _(việc sắp làm)_'] },
      nguonLuc: { manHinh: 'Tab **Nhiệm vụ** và **Hoạt động**', congCu: ['+ Tạo nhiệm vụ', 'Hoàn thành + popup', '+ Hoạt động', 'Đính kèm file'] },
      vanHanh: { steps: ['Nhiệm vụ: **+ Tạo** → hạn → **Hoàn thành** → điền popup.', 'Hoạt động: **+ Hoạt động** → loại Gọi/Gặp → nội dung.', 'Đính kèm ảnh/Zalo nếu cần.', 'Kiểm tra timeline đã hiện.'], mentor: 'Sau mỗi cuộc gọi — 1 phút ghi Hoạt động, không tích tụ cuối ngày.' },
      baoCaoSua: { loiHay: ['Tick xong không ghi popup.', 'Gom ghi cuối ngày — hay quên.'], tomTat: 'Task + popup; Hoạt động ngay sau gọi; file đính kèm.' },
      tomTat: 'Hoàn thành task = popup ghi chú; Hoạt động ngay sau gọi/gặp.',
    },
    quiz: mkQuiz([
      ['Popup hoàn thành?', ['Nhắc minh chứng', 'Làm khó', 'Xóa', 'Blocklist'], [0], 'Tư tưởng.'],
      ['Tick không ghi?', ['Vi phạm quy trình', 'OK', 'Thưởng', 'Bắt buộc'], [0], 'Tư tưởng.'],
      ['Hoạt động vs Nhiệm vụ?', ['Đã làm vs sắp làm', 'Giống', 'Không dùng', 'Admin'], [0], 'Tư duy.'],
      ['+ Hoạt động dùng?', ['Ghi gọi/gặp đã xong', 'Tạo Lead', 'Thua', 'Lương'], [0], 'Tư duy.'],
      ['Tạo nhiệm vụ tab?', ['Nhiệm vụ', 'Blocklist', 'Lương', 'Chat cty'], [0], 'Nguồn lực.'],
      ['Popup yêu cầu?', ['Ghi chú (+ file nếu cấu hình)', 'Chỉ tick', 'Xóa', 'Pass'], [0], 'Nguồn lực.'],
      ['Timeline ở?', ['Tab Hoạt động', 'Tài liệu', 'Blocklist', 'Lương'], [0], 'Nguồn lực.'],
      ['Sau gọi — làm?', ['+ Hoạt động ngay', 'Cuối tuần', 'Không ghi', 'Thua'], [0], 'Vận hành.'],
      ['Hoàn thành task?', ['Popup + ghi chú', 'Chỉ tick', 'Xóa Lead', 'Blocklist'], [0], 'Vận hành.'],
      ['Ảnh Zalo?', ['Đính kèm task/tài liệu', 'Chat riêng', 'Xóa', 'Email'], [0], 'Vận hành.'],
      ['Gom ghi cuối ngày?', ['Hay quên — ghi ngay', 'Tốt', 'Thưởng', 'Bắt buộc'], [0], 'Báo cáo.'],
      ['Tick giả — sửa?', ['Mở lại + ghi thật', 'Giữ', 'Thưởng', 'Thua'], [0], 'Báo cáo.'],
    ]),
    checklist: ['Tạo nhiệm vụ có hạn', 'Hoàn thành + điền popup', 'Ghi hoạt động sau gọi', 'Timeline hiển thị đúng'],
  },
  {
    num: 8,
    title: 'HD 8: Bảng Deal và Kanban Deal',
    summary: 'CRM → Bảng Deal, kéo thẻ, Thắng/Thua popup.',
    pillar: {
      hook: 'Sau **Chuyển Deal** — mở **Bảng Deal**. Kanban Deal có cột **Thắng / Thua** — thao tác khác Lead.',
      tuTuong: { vaiTro: 'Bảng Deal = **bàn làm việc giai đoạn HĐ và tiền**.', ynghia: ['Thắng/Thua có popup riêng — không kéo bừa.'] },
      tuDuy: { phanBiet: ['Kanban **Deal** vs Kanban **Lead** — pipeline khác nhau'] },
      nguonLuc: { manHinh: '**CRM → Bảng Deal → Kanban**', congCu: ['Kéo thẻ Deal', 'Popup Thắng (dự án SX)', 'Popup Thua (lý do)'] },
      vanHanh: { steps: ['**CRM → Bảng Deal**.', 'Lọc Deal của tôi.', 'Kéo theo giai đoạn.', 'Thắng → popup tạo dự án.', 'Thua → chọn lý do.'], mentor: 'Deal và Lead — bookmark cả hai menu.' },
      baoCaoSua: { loiHay: ['Kéo Thắng chưa popup.', 'Thua không chọn lý do.'], tomTat: 'Bảng Deal → Kanban → Thắng popup / Thua lý do.' },
      tomTat: 'Bảng Deal Kanban; Thắng = popup dự án; Thua = lý do bắt buộc.',
    },
    quiz: mkQuiz([
      ['Bảng Deal?', ['Bàn việc HĐ + tiền', 'Lead', 'Lương', 'Chat'], [0], 'Tư tưởng.'],
      ['Thắng/Thua?', ['Popup riêng', 'Kéo bừa', 'Không có', 'Lead'], [0], 'Tư tưởng.'],
      ['Kanban Deal vs Lead?', ['Pipeline khác', 'Giống', 'Không có', 'Blocklist'], [0], 'Tư duy.'],
      ['Sau Chuyển Deal mở?', ['Bảng Deal', 'Lead only', 'Blocklist', 'Lương'], [0], 'Tư duy.'],
      ['Bảng Deal menu?', ['CRM → Bảng Deal', 'Công việc', 'Kiến thức', 'SX'], [0], 'Nguồn lực.'],
      ['Thắng popup?', ['Tạo dự án SX', 'Xóa', 'Lead', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Thua popup?', ['Chọn lý do', 'Im lặng', 'Xóa', 'Lead mới'], [0], 'Nguồn lực.'],
      ['Kéo Deal?', ['Đổi giai đoạn', 'Xóa', 'In lương', 'Blocklist'], [0], 'Vận hành.'],
      ['Lọc Deal?', ['Deal của tôi', 'Ẩn hết', 'Xóa', 'Thua'], [0], 'Vận hành.'],
      ['Thắng không popup?', ['Sai — chạy popup', 'OK', 'Thưởng', 'Bắt buộc'], [0], 'Báo cáo.'],
      ['Thua không lý do — sửa?', ['Mở Deal chọn lý do', 'Xóa', 'Thắng', 'Lead'], [0], 'Báo cáo.'],
      ['Gate task Deal?', ['Có thể chặn kéo', 'Không', 'Lead only', 'Chat'], [0], 'Vận hành.'],
    ]),
  },
  {
    num: 9,
    title: 'HD 9: Chi tiết Deal — Báo giá, Tài liệu, Thắng/Thua',
    summary: 'Tab trên Deal, upload HĐ/cọc, thao tác header.',
    pillar: {
      hook: 'Chi tiết Deal — tab **Báo giá**, **Tài liệu** (HĐ, CK), **Nhiệm vụ**. Upload **trước** kéo Thắng.',
      tuTuong: { vaiTro: 'Deal chi tiết = **hồ sơ pháp lý + kỹ thuật** trên app.', ynghia: ['Thiếu file trên app = xưởng không thấy.'] },
      tuDuy: { phanBiet: ['Tab **Báo giá** vs tab **Tài liệu** — BG có thể tạo trong app; HĐ/cọc thường upload Tài liệu'] },
      nguonLuc: { manHinh: 'Click thẻ Deal → chi tiết', congCu: ['Tab Báo giá', 'Tài liệu upload', 'Nhiệm vụ gate', 'Header Thắng/Thua'] },
      vanHanh: { steps: ['Tạo/upload **BG** tab Báo giá.', 'Upload **HĐ + CK** tab Tài liệu.', 'Hoàn thành **nhiệm vụ** gate.', 'Kéo **Thắng** + popup.'], mentor: 'Tên file: `HD_TenKH_YYYY-MM.pdf` — xưởng tìm nhanh.' },
      baoCaoSua: { loiHay: ['Thắng trước upload.', 'File chỉ gửi Zalo không lên app.'], tomTat: 'BG + HĐ + cọc trên app → task → Thắng popup.' },
      tomTat: 'Upload đủ trên Deal → task → Thắng popup; Thua = lý do.',
    },
    quiz: mkQuiz([
      ['Deal chi tiết?', ['Hồ sơ pháp lý + kỹ thuật', 'Chỉ chat', 'Lead', 'Lương'], [0], 'Tư tưởng.'],
      ['File chỉ Zalo?', ['Xưởng không thấy trên app', 'Tốt', 'Thưởng', 'Bắt buộc'], [0], 'Tư tưởng.'],
      ['BG tab?', ['Báo giá', 'Blocklist', 'Lương', 'Chat cty'], [0], 'Tư duy.'],
      ['HĐ scan tab?', ['Tài liệu', 'Lead', 'Chat', 'Xóa'], [0], 'Tư duy.'],
      ['Trước Thắng?', ['Upload HĐ + cọc', 'Kéo luôn', 'Thua', 'Lead'], [0], 'Vận hành.'],
      ['Popup Thắng sau?', ['Tạo dự án', 'Xóa Deal', 'Blocklist', 'Lead'], [0], 'Vận hành.'],
      ['Nhiệm vụ Deal?', ['Gate kéo cột', 'Không', 'Lead only', 'Chat'], [0], 'Nguồn lực.'],
      ['Tên file HĐ?', ['HD_TenKH_YYYY-MM.pdf', 'a.pdf', '1.jpg', 'tmp'], [0], 'Vận hành.'],
      ['Thắng trước upload — sửa?', ['Upload + kéo lại đúng', 'Giữ Thắng', 'Thua', 'Xóa'], [0], 'Báo cáo.'],
      ['CK ảnh mờ?', ['Yêu cầu KH gửi lại', 'Vẫn Thắng', 'Xóa', 'Lead'], [0], 'Báo cáo.'],
      ['Tab Nhiệm vụ Deal?', ['Task gate', 'Lương', 'Blocklist', 'Lead'], [0], 'Nguồn lực.'],
      ['Thua trên app?', ['Kéo cột + chọn lý do', 'Xóa', 'Im lặng', 'Lead mới'], [0], 'Vận hành.'],
    ]),
    checklist: ['BG trên tab Báo giá/Tài liệu', 'HĐ + CK uploaded', 'Nhiệm vụ gate xong', 'Thắng + popup dự án'],
  },
  {
    num: 10,
    title: 'HD 10: Dashboard CRM — Đọc số liệu nhanh',
    summary: 'Tab Lead/Deal, KPI tổng, lọc thời gian — báo cáo trên app.',
    pillar: {
      hook: 'Sếp hỏi "Tháng này bao nhiêu Lead mới?" — **Dashboard CRM** trả lời trong 10 giây.',
      tuTuong: { vaiTro: 'Dashboard = **bảng tin số liệu** — biết mình đang đi nhanh hay chậm.', ynghia: ['Số trên dashboard lấy từ CRM — ghi đúng app thì dashboard đúng.'] },
      tuDuy: { mentalModel: 'Dashboard phản ánh **hành vi trên app** — garbage in, garbage out.' },
      nguonLuc: { manHinh: '**CRM → Dashboard** (hoặc từ App Switcher)', congCu: ['Tab Lead/Deal', 'Lọc tháng/quý', 'Ô KPI', 'Link "Xem tất cả" → Bảng Lead/Deal'] },
      vanHanh: { steps: ['Mở Dashboard đầu tuần.', 'Xem Lead mới, Deal Thắng, SLA.', 'Click **Xem tất cả** → sang Bảng chi tiết.', 'So sánh với **Bảng điểm** cá nhân.'], mentor: 'Dashboard team — đừng so sánh số người khác để tranh; dùng để tự cải thiện.' },
      baoCaoSua: { loiHay: ['Số dashboard thấp vì không ghi CRM.', 'Chỉ nhìn tổng không drill-down.'], tomTat: 'Dashboard = ảnh từ CRM; drill-down Bảng Lead/Deal; khớp Bảng điểm.' },
      tomTat: 'Dashboard đọc nhanh KPI; click xem chi tiết; số đúng khi ghi CRM đúng.',
    },
    quiz: mkQuiz([
      ['Dashboard phản ánh?', ['Hành vi ghi trên CRM', 'Sổ tay', 'Zalo', 'Blocklist'], [0], 'Tư tưởng.'],
      ['Số dashboard sai?', ['Thường do ghi CRM sai/thiếu', 'Lỗi trời', 'Thưởng', 'Bắt buộc'], [0], 'Tư tưởng.'],
      ['Garbage in garbage out?', ['Ghi sai → dashboard sai', 'Không', 'Chat', 'Lead'], [0], 'Tư duy.'],
      ['Dashboard vs Bảng Lead?', ['Dashboard tổng; Bảng chi tiết', 'Giống', 'Không', 'Blocklist'], [0], 'Tư duy.'],
      ['Dashboard menu?', ['CRM → Dashboard', 'Lead', 'Lương', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Xem tất cả Lead?', ['Link sang Bảng Lead', 'Xóa', 'Thua', 'Chat'], [0], 'Nguồn lực.'],
      ['Lọc thời gian?', ['Tháng/quý', 'Không', 'Màu tủ', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Đầu tuần nên?', ['Mở Dashboard + Bảng điểm', 'Bỏ qua', 'Xóa CRM', 'Thua'], [0], 'Vận hành.'],
      ['SLA trên Dashboard?', ['Có thể hiện Lead trễ', 'Không', 'Lead only', 'Chat'], [0], 'Vận hành.'],
      ['Số thấp — sửa?', ['Ghi CRM đúng + xử Lead trễ', 'Báo cáo giả', 'Tắt CRM', 'Thua'], [0], 'Báo cáo.'],
      ['Chỉ nhìn tổng — thiếu?', ['Drill-down Bảng chi tiết', 'Không thiếu', 'Chat', 'Blocklist'], [0], 'Báo cáo.'],
      ['Bảng điểm cá nhân?', ['So với Dashboard tuần', 'Không liên quan', 'Xóa', 'Lead'], [0], 'Vận hành.'],
    ]),
  },
  {
    num: 11,
    title: 'HD 11: Chat, Sự kiện và Đang hoạt động',
    summary: 'Chat theo Lead/Deal, lịch nội bộ, ai đang online.',
    pillar: {
      hook: '@mention đồng nghiệp trong **chat Deal** — họ thấy ngay context khách, không cần kể lại.',
      tuTuong: { vaiTro: 'Chat CRM gắn **Lead/Deal** — không thay thế ghi chú chính thức.', ynghia: ['Quyết định giá/HĐ vẫn phải lên tab Tài liệu/Hoạt động.'] },
      tuDuy: { phanBiet: ['**Chat nội bộ** _(trao đổi nhanh)_ vs **Hoạt động/Tài liệu** _(hồ sơ chính thức)_'] },
      nguonLuc: { manHinh: 'Panel chat trên chi tiết Lead/Deal; menu **Sự kiện**; **Đang hoạt động**', congCu: ['@mention', 'RSVP sự kiện', 'Danh sách online'] },
      vanHanh: { steps: ['Chat hỏi nội bộ — @tên.', 'Thỏa thuận với KH → ghi **Hoạt động** + file.', 'Sự kiện: RSVP đúng hạn.', 'Online: biết ai đang hỗ trợ KH.'], mentor: 'Chat "chốt giá 65tr" — copy sang Hoạt động + BG, không để chỉ trong chat.' },
      baoCaoSua: { loiHay: ['Chỉ chat, không ghi hồ sơ chính.', 'Bỏ lỡ RSVP.'], tomTat: 'Chat = nội bộ nhanh; quyết định KH → Hoạt động/Tài liệu.' },
      tomTat: 'Chat @mention tiện nội bộ; cam kết KH phải lên Hoạt động/Tài liệu.',
    },
    quiz: mkQuiz([
      ['Chat CRM gắn?', ['Lead/Deal context', 'Chỉ công ty', 'Blocklist', 'Lương'], [0], 'Tư tưởng.'],
      ['Chat thay hồ sơ chính?', ['Không', 'Có', 'Bắt buộc', 'Thưởng'], [0], 'Tư tưởng.'],
      ['Chat vs Hoạt động?', ['Chat nội bộ nhanh; Hoạt động hồ sơ KH', 'Giống', 'Không', 'Blocklist'], [0], 'Tư duy.'],
      ['Chốt giá trong chat?', ['Copy sang Hoạt động + BG', 'Đủ rồi', 'Xóa', 'Thua'], [0], 'Tư duy.'],
      ['@mention dùng?', ['Hỏi đồng nghiệp trên Deal', 'Xóa', 'Blocklist', 'Lương'], [0], 'Nguồn lực.'],
      ['Sự kiện nội bộ?', ['RSVP trên app', 'Không cần', 'Lead', 'Thua'], [0], 'Nguồn lực.'],
      ['Đang hoạt động?', ['Ai online/xử lý KH', 'Lương', 'Blocklist', 'BG'], [0], 'Nguồn lực.'],
      ['Thỏa thuận KH sau chat?', ['Ghi Hoạt động + file', 'Chỉ chat', 'Thua', 'Xóa'], [0], 'Vận hành.'],
      ['Bỏ RSVP — sửa?', ['RSVP trễ + tham dự nếu còn', 'Bỏ qua', 'Thua', 'Lead'], [0], 'Báo cáo.'],
      ['Chỉ chat không hồ sơ — sửa?', ['Bổ sung Hoạt động/Tài liệu', 'OK', 'Thưởng', 'Blocklist'], [0], 'Báo cáo.'],
      ['Chat trên chi tiết Deal?', ['Có panel chat', 'Không', 'Lead only', 'Blocklist'], [0], 'Nguồn lực.'],
      ['Online list giúp?', ['Biết ai hỗ trợ', 'Lương', 'Thua', 'Xóa'], [0], 'Vận hành.'],
    ]),
  },
  {
    num: 12,
    title: 'HD 12: CRM Mobile và Ôn tập thao tác',
    summary: 'App di động cơ bản; checklist end-to-end Lead + Deal trên app.',
    pillar: {
      hook: 'Đi khảo sát — **CRM Mobile**: ghi Hoạt động + chụp ảnh upload ngay tại hiện trường.',
      tuTuong: { vaiTro: 'Mobile = **CRM trong túi** — không đợi về văn phòng mới ghi.', ynghia: ['Ghi muộn = hay quên, KPI và KH đều thiệt.'] },
      tuDuy: { mentalModel: 'Mobile và web **cùng dữ liệu** — ghi mobile, đồng nghiệp web thấy ngay.' },
      nguonLuc: { manHinh: 'App CRM Mobile (iOS/Android)', congCu: ['Xem Lead/Deal', 'Ghi hoạt động', 'Chụp ảnh upload', 'Nhiệm vụ'] },
      vanHanh: {
        steps: [
          '**Checklist ôn tập web**: Đăng nhập → Lead Kanban → Tạo/Quét trùng → 4 tab → Task/Hoạt động.',
          '**Deal**: Bảng Deal → upload → Thắng popup.',
          '**Mobile**: Mở Lead tại hiện trường → Hoạt động + ảnh.',
          '**Báo cáo**: Dashboard + Bảng điểm.',
        ],
        mentor: 'Cuối khoá — tự làm checklist một lần không nhìn tài liệu.',
      },
      baoCaoSua: { tuKiem: ['Làm end-to-end web?', 'Dùng mobile ghi hiện trường?', 'Biết sửa lỗi thường gặp?'], tomTat: 'Mobile = ghi ngay; ôn tập = checklist Lead + Deal + Dashboard.' },
      tomTat: 'Mobile ghi tại chỗ; ôn tập = thuần thao tác web + mobile + báo cáo.',
    },
    quiz: mkQuiz([
      ['Mobile CRM?', ['CRM trong túi', 'Khác hệ', 'Không dùng', 'Blocklist'], [0], 'Tư tưởng.'],
      ['Ghi muộn?', ['Hay quên, KPI/KH thiệt', 'Tốt', 'Thưởng', 'Bắt buộc'], [0], 'Tư tưởng.'],
      ['Mobile vs web?', ['Cùng dữ liệu', 'Riêng', 'Không sync', 'Lead only'], [0], 'Tư duy.'],
      ['Hiện trường nên?', ['Hoạt động + ảnh ngay', 'Về VP', 'Thua', 'Chat riêng'], [0], 'Vận hành.'],
      ['Ôn tập gồm?', ['Lead + Deal + Dashboard', 'Chỉ chat', 'Blocklist', 'Lương'], [0], 'Tư duy.'],
      ['Mobile xem Lead?', ['Có', 'Không', 'Admin only', 'Deal only'], [0], 'Nguồn lực.'],
      ['Ảnh hiện trường?', ['Upload Tài liệu/Hoạt động', 'Chỉ gallery máy', 'Xóa', 'Email'], [0], 'Vận hành.'],
      ['Checklist cuối khoá?', ['Tự làm không nhìn tài liệu', 'Bỏ qua', 'Thua', 'Lead mới'], [0], 'Báo cáo.'],
      ['Quên ghi hiện trường — sửa?', ['Bổ sung ngay khi nhớ', 'Bỏ qua', 'Thua', 'Xóa'], [0], 'Báo cáo.'],
      ['End-to-end Lead?', ['Tạo→tab→task→Kanban', 'Chỉ chat', 'Blocklist', 'Thua'], [0], 'Vận hành.'],
      ['End-to-end Deal?', ['Upload→Thắng popup', 'Lead only', 'Xóa', 'Blocklist'], [0], 'Vận hành.'],
      ['Bảng điểm ôn tập?', ['Xem KPI cá nhân', 'Không', 'Chat', 'Lead'], [0], 'Báo cáo.'],
    ]),
    checklist: [
      'Đăng nhập web + mobile',
      'Tạo Lead + Quét trùng',
      '4 tab + task + hoạt động',
      'Bảng Deal + upload + Thắng popup',
      'Mở Dashboard + Bảng điểm',
    ],
  },
];

const FINAL_EXAM = [
  ['Thao tác quan trọng?', ['Trên CRM', 'Sổ tay', 'Zalo KH', 'Excel'], [0], 'Tư tưởng.'],
  ['App Switcher?', ['Chuyển module', 'Xóa', 'Thua', 'Blocklist'], [0], 'Nguồn lực.'],
  ['Quét trùng?', ['Trước Lưu Lead', 'Sau 1 năm', 'Deal', 'Thua'], [0], 'Vận hành.'],
  ['4 tab Lead?', ['Tổng quan, NV, HD, TL', 'Chỉ chat', '2 tab', 'Blocklist'], [0], 'Nguồn lực.'],
  ['Hoàn thành task?', ['Popup ghi chú', 'Chỉ tick', 'Xóa', 'Thua'], [0], 'Vận hành.'],
  ['Bảng Deal?', ['CRM → Bảng Deal', 'Lead', 'Lương', 'Blocklist'], [0], 'Nguồn lực.'],
  ['Thắng Deal?', ['Popup dự án SX', 'Xóa', 'Lead', 'Blocklist'], [0], 'Vận hành.'],
  ['Thua Deal?', ['Lý do bắt buộc', 'Im lặng', 'Xóa', 'Lead mới'], [0], 'Báo cáo.'],
  ['Pass CRM?', ['Không chia sẻ', 'Zalo OK', 'Dán màn hình', 'Chung team'], [0], 'Báo cáo.'],
  ['Dashboard?', ['Số từ CRM', 'Sổ tay', 'Zalo', 'Blocklist'], [0], 'Báo cáo.'],
  ['Chat vs hồ sơ?', ['Chat nội bộ; KH lên Hoạt động/TL', 'Giống', 'Chỉ chat', 'Blocklist'], [0], 'Tư duy.'],
  ['Mobile?', ['Ghi tại chỗ', 'Khác data', 'Không', 'Lead only'], [0], 'Vận hành.'],
  ['Kanban Lead?', ['Kéo giai đoạn', 'In PDF', 'Lương', 'Blocklist'], [0], 'Vận hành.'],
  ['Badge đỏ?', ['SLA', 'Thắng', 'VIP', 'Xóa'], [0], 'Nguồn lực.'],
  ['Pin module?', ['Vào nhanh', 'Xóa CRM', 'Thua', 'Blocklist'], [0], 'Nguồn lực.'],
  ['Upload HĐ Deal?', ['Tài liệu', 'Chat riêng', 'Lead', 'Xóa'], [0], 'Vận hành.'],
  ['Thiết bị lạ?', ['Đăng xuất + đổi pass', 'Bỏ qua', 'Thua', 'Lead'], [0], 'Báo cáo.'],
  ['5 trụ?', ['TT, TD, NL, VH, BC', 'Chỉ Kanban', 'Chat', 'Lead'], [0], 'Tư tưởng.'],
  ['Ghi sai tab?', ['Sửa đúng tab', 'OK', 'Thưởng', 'Thua'], [0], 'Báo cáo.'],
  ['Ôn tập cuối?', ['Checklist end-to-end', 'Bỏ qua', 'Blocklist', 'Thua'], [0], 'Báo cáo.'],
];

module.exports = { LESSON_SPECS, FINAL_EXAM, q, mkQuiz };
