const uuid=x=>typeof x==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x),hash=x=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x);
function report(x,company,trial){if(!x||x.companyId!==company||x.trialId!==trial||x.status!=='SAVED_OBSERVED_INCOMPLETE'||x.targetStatus!=='NOT_EVALUATED'||x.allowBudgetExecution!==false||!Array.isArray(x.obligations)||!x.counts||!x.spend||!x.period)throw Error('Báo cáo không khớp phạm vi.');const m=x.observedMeasurement;if(!m||m.targetStatus!=='NOT_EVALUATED'||m.allowBudgetExecution!==false||!['AVAILABLE_PROVISIONAL','NO_QUALIFIED_LEADS','UNAVAILABLE'].includes(m.status))throw Error('Chưa xác minh phép đo.');if(m.status==='UNAVAILABLE'){if(m.costPerQualifiedLeadVnd!==null||m.qualifiedLeads!==null||m.spendVnd!==null)throw Error('Số liệu thiếu không thể tính thành 0.');}else if(m.qualifiedLeads!==x.counts.qualified||m.spendVnd!==x.spend.spendVnd||m.costPerQualifiedLeadVnd!==(m.qualifiedLeads?m.spendVnd/m.qualifiedLeads:null))throw Error('Số liệu không khớp.');return x;}
export function snapshotReceipt(x,company,trial,pending=null,actor=null){if(!x||x.policy!=='MARKETING_MEASUREMENT_SNAPSHOT_V1'||x.companyId!==company||x.trialId!==trial||!uuid(x.requestId)||!uuid(x.actorId)||!hash(x.contextVersion)||!hash(x.reportDigest)||typeof x.replayed!=='boolean'||x.allowBudgetExecution!==false||(pending&&(x.requestId!==pending.requestId||x.contextVersion!==pending.contextVersion||x.actorId!==actor)))throw Error('Chưa xác nhận được bản lưu.');report(x.report,company,trial);return x;}
export function snapshotResult(x,actor,company,trial){if(!x||x.policy!=='MARKETING_MEASUREMENT_SNAPSHOT_V1'||x.actorId!==actor||x.companyId!==company||x.trialId!==trial||!hash(x.contextVersion)||x.allowBudgetExecution!==false||!Array.isArray(x.history)||x.history.length>20)throw Error('Phạm vi báo cáo đã đổi.');report(x.preview,company,trial);for(const h of x.history){if(!['UNCHANGED_INPUTS','CHANGED_SINCE_CAPTURE','STALE_AUTHORITY'].includes(h.currentStatus))throw Error('Trạng thái lịch sử chưa rõ.');snapshotReceipt(h.receipt,company,trial);}return x;}
const key=(a,c,t)=>'vpt-measurement-snapshot:v1:'+a+':'+c+':'+t;
function valid(x){return x&&Object.keys(x).length===2&&uuid(x.requestId)&&hash(x.contextVersion);}
export function readPending(storage,a,c,t){const s=storage.getItem(key(a,c,t));if(!s)return null;const x=JSON.parse(s);if(!valid(x))throw Error('Mã yêu cầu lưu chưa hợp lệ.');return x;}
export function savePending(storage,a,c,t,x){if(!valid(x))throw Error('Yêu cầu chưa hợp lệ.');const s=JSON.stringify(x);storage.setItem(key(a,c,t),s);if(storage.getItem(key(a,c,t))!==s)throw Error('Không giữ được mã yêu cầu.');}
export function clearPending(storage,a,c,t){storage.removeItem(key(a,c,t));}

