import {useEffect,useRef,useState} from 'react';
import api from '../../lib/api';
import {CLAIMS,scopeResult,receiptResult,initialManifest,manifestCommand,readPending,savePending,clearPending} from './scopeAcceptanceState.mjs';
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-50';
const input='rounded-lg border p-2 text-sm';
const money=n=>n===null?'Chưa có khách hợp lệ':Math.round(n).toLocaleString('vi-VN')+' đ';
const time=x=>new Date(x).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'});
const label=e=>e.kind==='META_LEAD_ADS'?'Page '+e.pageId+' · Biểu mẫu '+e.formId:e.kind==='NO_LEAD_SOURCE'?'Không có điểm nhận khách · '+e.destination:(e.kind+' · '+(e.destination||e.pageId||''));
const statuses={MISSING:'Chưa xác nhận phạm vi',CURRENT:'Phạm vi đã xác nhận, dữ liệu hiện chưa thay đổi',REVOKED:'Đã thu hồi xác nhận',STALE_AUTHORITY:'Quyền người xác nhận đã thay đổi',CHANGED_SOURCE:'Dữ liệu đã thay đổi; cần đối chiếu lại',SOURCE_UNAVAILABLE:'Chưa đọc được nguồn; kết quả hiện tại được ẩn'};
const gapNames={PERIOD_UNAVAILABLE:'Chưa có ngày hoàn tất để đối chiếu',REGISTRY_NOT_CURRENT:'Danh mục nguồn cần cập nhật',SPEND_UNAVAILABLE:'Thiếu chi tiêu cùng kỳ',SOURCE_AD_GAPS:'Có quảng cáo trong hồ sơ khách chưa thấy trong dữ liệu phân phối',DELIVERY_UNAVAILABLE:'Chưa đối soát được quảng cáo đã phân phối',ENTRYPOINT_NOT_SUPPORTED:'Điểm nhận khách này chưa được nối vào phép đo',CENSUS_NOT_RECONCILED:'Danh sách khách nguồn chưa khớp CRM',FORM_NOT_DISCOVERED:'Chưa tìm được biểu mẫu lịch sử',QUALIFICATION_PENDING:'Còn khách chờ xác minh nhu cầu',CRM_UNRESOLVED:'Còn hồ sơ khách hoặc nguồn chưa đối soát',EXPORT_NOT_RECONCILED:'Tệp nguồn thiếu, đã cũ hoặc chưa khớp',DESTINATION_HISTORY_MISSING:'Chưa khai đủ lịch sử đích đến quảng cáo',PROOF_DESTINATION_MISMATCH:'Đích quảng cáo chưa khớp nguồn khách',PROOF_DELIVERY_METADATA_CONFLICT:'Nhóm hoặc chiến dịch của khách khác dữ liệu quảng cáo'};
export default function ScopeAcceptance(props){if(!props.actorId)return null;return <Panel key={[props.actorId,props.companyId,props.trialId].join(':')} {...props}/>;}
function Report({report:r,historical=false}){return <div className="space-y-2 rounded-lg bg-slate-50 p-3 text-sm"><p className="font-medium">{historical?'Kết quả lịch sử':'Kết quả trong phạm vi đã xác nhận'}</p><p>Từ {time(r.sinceAt)} đến trước {time(r.untilExclusive)} · Kiểm tra khách lúc {time(r.qualificationAsOf)}</p><p>{r.accountIds.length} tài khoản Facebook · Chi tiêu: <strong>{money(r.spendVnd)}</strong> · Khách hợp lệ: <strong>{r.qualifiedLeads}</strong></p><p>Chi phí/khách: <strong>{money(r.costPerQualifiedLeadVnd)}</strong></p><p>{r.targetStatus==='NOT_EVALUATED'?'Chưa có khách hợp lệ để đánh giá.':r.targetStatus==='AT_OR_BELOW_TARGET_IN_SCOPE'?'Trong phạm vi này: không vượt 250.000 đ/khách.':'Trong phạm vi này: vượt 250.000 đ/khách.'}</p><p className="text-slate-600">Dựa trên bằng chứng nguồn người vận hành đã xác nhận và số liệu hệ thống đối soát. Không đại diện mọi kênh; xác nhận này không mở chi quảng cáo.</p></div>;}
function Panel({actorId,companyId,trialId}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[reload,setReload]=useState(0),[pending,setPending]=useState(null),[receipt,setReceipt]=useState(null);
 const [rows,setRows]=useState([]),[reference,setReference]=useState(''),[note,setNote]=useState(''),[claims,setClaims]=useState([]),[file,setFile]=useState(null),[reading,setReading]=useState(false),[fileKey,setFileKey]=useState(0),[reason,setReason]=useState('');
 const seq=useRef(0),fileSeq=useRef(0),lock=useRef(false),pendingRef=useRef(null);
 const path='/crm/marketing-trials/'+trialId+'/scope-acceptance';
 useEffect(()=>{const n=++seq.current,controller=new AbortController();++fileSeq.current;setData(null);setReceipt(null);setError('');setLoading(true);setFile(null);setReading(false);setFileKey(x=>x+1);setClaims([]);
  try{const p=readPending(sessionStorage,actorId,companyId,trialId);pendingRef.current=p;setPending(p);}catch(e){setError(e.message);setLoading(false);return()=>{++seq.current;++fileSeq.current;controller.abort();};}
  api.get(path,{params:{company_id:companyId},signal:controller.signal,timeout:20000}).then(({data:x})=>{if(n!==seq.current)return;const checked=scopeResult(x,actorId,companyId,trialId);setData(checked);setRows(initialManifest(checked.requirements));setReference(checked.requirements?.reference||'');setNote('');setReason('');}).catch(e=>{if(n===seq.current){setData(null);setError(e.response?.data?.error||e.message||'Chưa đọc được phạm vi.');}}).finally(()=>{if(n===seq.current)setLoading(false);});
  return()=>{++seq.current;++fileSeq.current;controller.abort();};
 },[actorId,companyId,trialId,reload,path]);
 async function selectFile(selected){const n=seq.current,k=++fileSeq.current;setFile(null);setReading(true);setError('');try{
  if(!selected||selected.size<1||selected.size>1048576)throw Error('Chọn tệp bằng chứng từ 1 byte đến 1 MB.');
  const bytes=new Uint8Array(await selected.arrayBuffer()),digest=await crypto.subtle.digest('SHA-256',bytes),sha=[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('');
  let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));
  if(n!==seq.current||k!==fileSeq.current)return;const p=pendingRef.current;if(p?.command.action==='ACCEPT'&&(p.fileSha256!==sha||p.fileBytes!==bytes.length))throw Error('Tệp khác yêu cầu đang chờ. Chọn lại đúng tệp đã gửi.');
  setFile({base64:btoa(binary),sha,bytes:bytes.length,name:selected.name});
 }catch(e){if(n===seq.current&&k===fileSeq.current)setError(e.message);}finally{if(n===seq.current&&k===fileSeq.current)setReading(false);}}
 async function submit(action){if(lock.current||loading||reading)return;const n=seq.current;try{
  let p=pendingRef.current;
  if(!p){if(!data)throw Error('Tải lại phạm vi trước khi gửi.');let command;
   if(action==='ACCEPT'){
    if(!file||!data.requirements||data.requirements.gaps.length||claims.length!==CLAIMS.length||reference.trim().length<8||note.trim().length<20)throw Error('Cần đủ bằng chứng, điểm nhận và ba nội dung xác nhận.');
    command={action,expectedRevision:data.revision,contextVersion:data.contextVersion,reference:reference.trim(),note:note.trim(),claims,manifest:manifestCommand(rows),exportClaims:data.requirements.exports.map(e=>({requestId:e.requestId,fileSha256:e.fileSha256,normalizedRowsDigest:e.normalizedRowsDigest}))};
   }else{if(data.history[0]?.action!=='ACCEPT'||reason.trim().length<20)throw Error('Điền lý do thu hồi ít nhất 20 ký tự.');command={action:'REVOKE',expectedRevision:data.revision,targetRequestId:data.history[0].requestId,reason:reason.trim()};}
   p={requestId:crypto.randomUUID(),command,fileSha256:action==='ACCEPT'?file.sha:null,fileBytes:action==='ACCEPT'?file.bytes:null};
   savePending(sessionStorage,actorId,companyId,trialId,p);pendingRef.current=p;setPending(p);
  }
  if(p.command.action==='ACCEPT'&&(!file||file.sha!==p.fileSha256||file.bytes!==p.fileBytes))throw Error('Chọn lại đúng tệp để xác nhận cùng yêu cầu.');
  lock.current=true;setSaving(true);setData(null);setReceipt(null);setError('');
  const body={requestId:p.requestId,command:p.command,...(p.command.action==='ACCEPT'?{artifactBase64:file.base64}:{})};
  const {data:x}=await api.post(path,body,{params:{company_id:companyId},timeout:30000});if(n!==seq.current)return;
  if(!['HISTORICAL_REPLAY','RECORDED_AT_RESPONSE'].includes(x?.currentStatus)||(x.currentStatus==='HISTORICAL_REPLAY')!==(x.receipt?.replayed===true))throw Error('Chưa xác nhận được biên nhận.');
  const r=receiptResult(x.receipt,companyId,trialId,p,actorId);clearPending(sessionStorage,actorId,companyId,trialId);pendingRef.current=null;setPending(null);setReceipt(r);setFile(null);setFileKey(k=>k+1);
 }catch(e){if(n===seq.current){if([400,403,409].includes(e.response?.status)){try{clearPending(sessionStorage,actorId,companyId,trialId);pendingRef.current=null;setPending(null);}catch{}}
  const issues=e.response?.data?.issues?.map(x=>gapNames[x.code]||'Cần kiểm tra bằng chứng').filter((x,i,a)=>a.indexOf(x)===i).join('; ');setError((e.response?.data?.error||e.message||'Chưa rõ kết quả; gửi lại cùng yêu cầu.')+(issues?' '+issues:''));}}
 finally{lock.current=false;if(n===seq.current)setSaving(false);}}
 const locked=loading||saving||!!pending,latest=data?.history[0],q=data?.requirements;
 const updateRow=(index,patch)=>setRows(prev=>prev.map((r,i)=>i===index?{...r,...patch}:r));
 return <section aria-label="Xác nhận phạm vi chi phí khách" className="space-y-4 rounded-xl border border-slate-300 p-4">
  <h3 className="font-semibold">Xác nhận phạm vi tính chi phí/khách</h3><p className="text-sm text-slate-600">Đối chiếu quảng cáo đã phân phối với các điểm nhận khách trong cả kỳ, kể cả quảng cáo không tạo khách. Hệ thống tự tính tiền và số khách từ dữ liệu đã kiểm tra.</p>
  <button type="button" className={button} disabled={loading||saving||reading} onClick={()=>{setData(null);setReceipt(null);setReload(x=>x+1);}}>Tải phạm vi và lịch sử</button>
  {loading&&<p role="status">Đang đối chiếu nguồn, khách và chi tiêu…</p>}{error&&<p role="alert" className="text-sm text-amber-800">{error}</p>}
  {data&&<><p role="status" className="font-medium">{statuses[data.currentStatus]}</p>{data.currentStatus==='CURRENT'&&<Report report={latest.report}/>}
   {!!q?.gaps.length&&<div className="text-sm text-amber-800"><p>Cần xử lý trước khi xác nhận:</p><ul className="list-disc pl-5">{q.gaps.map((g,i)=><li key={i}>{gapNames[g.code]||'Cần kiểm tra cấu hình hoặc dữ liệu nguồn'}{g.scope?' · '+g.scope:''}</li>)}</ul></div>}
   {q&&!q.gaps.length&&!pending&&<div className="space-y-3 border-t pt-3"><p className="text-sm">Tất cả giờ dưới đây là giờ Việt Nam. Chọn đầy đủ điểm nhận của từng quảng cáo trong khoảng thời gian tương ứng. Nếu đích đến thay đổi giữa kỳ, thêm khoảng và sửa thời gian để các khoảng liên tiếp, không chồng nhau.</p>
    <div className="max-h-96 space-y-3 overflow-y-auto">{rows.map((r,i)=><fieldset key={i} className="space-y-2 rounded-lg border p-3" disabled={locked}><legend className="px-1 text-sm font-medium">{r.accountId} · Quảng cáo {r.adId} · Khoảng {i+1}</legend>
     <div className="flex flex-wrap gap-3"><label className="text-sm">Từ (giờ VN)<input aria-label={'Từ quảng cáo '+r.adId+' khoảng '+(i+1)} type="datetime-local" step="1" className={'ml-2 '+input} value={r.from} onChange={e=>updateRow(i,{from:e.target.value})}/></label><label className="text-sm">Đến trước (giờ VN)<input aria-label={'Đến quảng cáo '+r.adId+' khoảng '+(i+1)} type="datetime-local" step="1" className={'ml-2 '+input} value={r.until} onChange={e=>updateRow(i,{until:e.target.value})}/></label></div>
     {q.entries.filter(e=>e.accountId===r.accountId).map(e=><label key={e.key} className="flex gap-2 text-sm"><input type="checkbox" checked={r.destinations.includes(e.key)} onChange={ev=>updateRow(i,{destinations:ev.target.checked?[...r.destinations,e.key]:r.destinations.filter(k=>k!==e.key)})}/>{label(e)}</label>)}
     <div className="flex gap-2"><button type="button" className={button} disabled={rows.length>=1000} onClick={()=>setRows(v=>[...v,{...r,destinations:[...r.destinations]}])}>Thêm khoảng cho quảng cáo này</button><button type="button" className={button} onClick={()=>setRows(v=>v.filter((_,j)=>j!==i))}>Bỏ khoảng này</button></div>
    </fieldset>)}</div>
    <p className="text-sm">Đã đối soát {q.exports.length} tệp biểu mẫu. Xác nhận bên dưới áp dụng đúng các tệp và thời gian sau:</p>
    <ul className="space-y-2 text-sm">{q.exports.map(e=><li key={e.requestId} className="rounded-lg border p-3"><p>Page {e.pageId} · Biểu mẫu {e.formId} · {e.empty?'Tệp không có khách trong kỳ':'Tập mã khách đã khớp'}</p><p>{e.sourceReference} · Xuất lúc {time(e.exportedAt)}</p><details><summary className="cursor-pointer">Xem mã đối chiếu tệp</summary><dl className="mt-2 space-y-1 break-all text-xs"><dt>Biên nhận</dt><dd>{e.requestId}</dd><dt>Mã kiểm tra tệp gốc</dt><dd>{e.fileSha256}</dd><dt>Mã kiểm tra tập khách và thời điểm</dt><dd>{e.normalizedRowsDigest}</dd></dl></details></li>)}</ul>
    <label className="block text-sm">Tên hoặc nơi tham chiếu hồ sơ<input className={'mt-1 block w-full '+input} maxLength={500} value={reference} disabled={locked} onChange={e=>setReference(e.target.value)}/></label>
    <label className="block text-sm">Căn cứ kiểm tra đích đến, bộ lọc xuất và thời gian lưu nguồn<textarea className={'mt-1 block w-full '+input} maxLength={2000} value={note} disabled={locked} onChange={e=>setNote(e.target.value)}/></label>
    {['Tôi đã kiểm tra đầy đủ các điểm nhận khách và thay đổi đích đến quảng cáo trong kỳ.','Tôi đã kiểm tra toàn bộ quảng cáo đã phân phối của các tài khoản, kể cả phần không tạo khách.','Tôi đã kiểm tra nguồn tệp, bộ lọc, thời gian và giới hạn lưu dữ liệu; không bỏ sót khách trong phạm vi xác nhận.'].map((text,i)=><label key={CLAIMS[i]} className="flex gap-2 text-sm"><input type="checkbox" checked={claims.includes(CLAIMS[i])} disabled={locked} onChange={e=>setClaims(v=>e.target.checked?[...v,CLAIMS[i]]:v.filter(x=>x!==CLAIMS[i]))}/>{text}</label>)}
   </div>}
  </>}
  {((q&&!q.gaps.length&&!pending)||pending?.command.action==='ACCEPT')&&<div className="space-y-2"><label className="block text-sm">Tệp bằng chứng tổng hợp (tối đa 1 MB)<input key={fileKey} type="file" className="mt-1 block text-sm" disabled={loading||saving} onChange={e=>selectFile(e.target.files?.[0])}/></label><p className="text-xs text-slate-600">Dùng ảnh/PDF hoặc hồ sơ mô tả đích lịch sử và nguồn xuất; không kèm mật khẩu, token hoặc thông tin liên hệ khách không cần thiết.</p>{reading&&<p role="status">Đang kiểm tra tệp…</p>}{file&&<p className="text-sm">Đã chọn {file.name} · {file.bytes.toLocaleString('vi-VN')} byte.</p>}</div>}
  {pending?<div className="space-y-2"><p role="status" className="text-sm text-amber-800">Có yêu cầu đang chờ xác nhận. Tệp không được lưu trong trình duyệt; nếu tải lại trang, chọn lại đúng tệp đã gửi. Gửi lại giữ nguyên nội dung và mã yêu cầu.</p><button type="button" className={button} disabled={loading||saving||reading||(pending.command.action==='ACCEPT'&&!file)} onClick={()=>submit(pending.command.action)}>Xác nhận lại cùng yêu cầu</button></div>:
   q&&!q.gaps.length&&<button type="button" className={button+' bg-blue-700 text-white'} disabled={locked||reading||!file||claims.length!==3||reference.trim().length<8||note.trim().length<20||rows.some(r=>!r.destinations.length)} onClick={()=>submit('ACCEPT')}>Xác nhận phạm vi và tính kết quả</button>}
  {data&&latest?.action==='ACCEPT'&&!pending&&<div className="space-y-2 border-t pt-3"><label className="block text-sm">Lý do thu hồi xác nhận hiện hành<textarea className={'mt-1 block w-full '+input} maxLength={2000} disabled={locked} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" className={button} disabled={locked||reason.trim().length<20} onClick={()=>submit('REVOKE')}>Thu hồi xác nhận</button></div>}
  {receipt&&<div className="space-y-2"><p role="status">Đã xác nhận biên nhận {receipt.action==='ACCEPT'?'ghi nhận phạm vi':'thu hồi'}. Đây là lịch sử; tải lại để xem trạng thái hiện hành.</p>{receipt.report&&<Report report={receipt.report} historical/>}</div>}
  {!!data?.history.length&&<details><summary className="cursor-pointer text-sm">Lịch sử xác nhận / thu hồi ({data.history.length} gần nhất)</summary><div className="mt-2 space-y-2">{data.history.map(r=><article key={r.requestId} className="rounded-lg border p-3"><p className="text-sm">Lần {r.revision} · {r.action==='ACCEPT'?'Xác nhận phạm vi':'Thu hồi xác nhận'} · {time(r.recordedAt)}</p>{r.report&&<Report report={r.report} historical/>}</article>)}</div></details>}
 </section>;
}
