import{useEffect,useRef,useState}from'react';
import api from '../../lib/api';
import{exportResult,exportReceipt,readPending,storePending,clearPending}from'./sourceExportState.mjs';
const labels={MATCHED_EXPORTED_IDS:'Các mã trong kỳ khớp tập đã quét',DISCREPANCIES:'Có hồ sơ cần đối soát',DUPLICATE_ROWS:'Tệp có dòng trùng cần kiểm tra',EMPTY_COMPARISON:'Hai tập đang rỗng; chưa xác minh không có khách'};
const reasons={NOT_IN_EXPORT:'Đã quét nhưng không thấy trong tệp',NOT_OBSERVED:'Có trong tệp nhưng chưa thấy khi quét',EXPORT_CONFLICT:'Tệp có mã hoặc biểu mẫu mâu thuẫn',SOURCE_CONFLICT:'Biểu mẫu hoặc thời điểm lệch nhau'};
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-50';
export default function SourceExport(props){if(!props.actorId)return null;return <Panel key={`${props.actorId}:${props.companyId}:${props.trialId}`} {...props}/>;}
function Panel({actorId,companyId,trialId}){
 const[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[reload,setReload]=useState(0),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[pending,setPending]=useState(null),[receipt,setReceipt]=useState(null);
 const[form,setForm]=useState(''),[exported,setExported]=useState(''),[reference,setReference]=useState(''),[note,setNote]=useState(''),[delimiter,setDelimiter]=useState(','),[idColumn,setIdColumn]=useState('id'),[timeColumn,setTimeColumn]=useState('created_time'),[formColumn,setFormColumn]=useState('form_id');
 const[file,setFile]=useState(null),[reading,setReading]=useState(false),[confirmed,setConfirmed]=useState(false);const seq=useRef(0),fileSeq=useRef(0),lock=useRef(false),pendingRef=useRef(null);
 useEffect(()=>{const n=++seq.current,controller=new AbortController();setData(null);setReceipt(null);setError('');setLoading(true);
  try{const p=readPending(sessionStorage,actorId,companyId,trialId);pendingRef.current=p;setPending(p);}catch(e){setError(e.message);setLoading(false);return()=>{++seq.current;++fileSeq.current;controller.abort();};}
  api.get(`/crm/marketing-trials/${trialId}/source-exports`,{params:{company_id:companyId},signal:controller.signal,timeout:20000}).then(({data:x})=>{if(n!==seq.current)return;exportResult(x,actorId,companyId,trialId);if(!Array.isArray(x.forms)||!Array.isArray(x.exports))throw Error('Dữ liệu đối soát chưa đầy đủ.');setData(x);}).catch(e=>{if(n===seq.current){setData(null);setError(e.response?.data?.error||e.message||'Chưa đọc được hồ sơ.');}}).finally(()=>{if(n===seq.current)setLoading(false);});
  return()=>{++seq.current;++fileSeq.current;controller.abort();};
 },[actorId,companyId,trialId,reload]);
 async function chooseFile(e){const selected=e.target.files?.[0],n=++fileSeq.current;setFile(null);setReading(true);setError('');try{if(!selected||selected.size>1048576||!selected.size)throw Error('Chọn tệp CSV/TXT tối đa 1 MB.');const bytes=new Uint8Array(await selected.arrayBuffer());const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));if(n===fileSeq.current)setFile({hash:digest,base64:btoa(text)});}catch(x){if(n===fileSeq.current)setError(x.message);}finally{if(n===fileSeq.current)setReading(false);}}
 const ready=data?.registryStatus==='CURRENT'&&data?.census?.state==='SCANNED'&&data?.census?.scopeCurrent===true&&data?.census?.witnessStatus==='TRAVERSED'&&Date.parse(data.census.untilExclusive)>Date.parse(data.census.sinceAt);
 async function submit(e){e.preventDefault();if(lock.current||reading||!file)return;let p=pendingRef.current;const n=seq.current;
  try{if(!p){if(!ready||!confirmed||!form||!exported)throw Error('Cần phạm vi hiện hành, tệp và thông tin xuất.');const[pageId,formId]=form.split(':');p={fileHash:file.hash,request:{requestId:crypto.randomUUID(),contextVersion:data.contextVersion,pageId,formId,delimiter,columns:{id:idColumn.trim(),createdAt:timeColumn.trim(),formId:formColumn.trim()||null},exportedAt:new Date(`${exported}:00+07:00`).toISOString(),sourceReference:reference.trim(),sourceNote:note.trim()}};storePending(sessionStorage,actorId,companyId,trialId,p);pendingRef.current=p;setPending(p);}
   if(p.fileHash!==file.hash)throw Error('Cần chọn lại đúng tệp của yêu cầu đang chờ.');lock.current=true;setSaving(true);setError('');setData(null);setReceipt(null);
   const{data:x}=await api.post(`/crm/marketing-trials/${trialId}/source-exports`,{...p.request,fileBase64:file.base64},{params:{company_id:companyId},timeout:30000});if(n!==seq.current)return;exportReceipt(x,p,actorId,companyId,trialId);clearPending(sessionStorage,actorId,companyId,trialId);pendingRef.current=null;setPending(null);setReceipt(x);setOpen(false);setFile(null);
  }catch(x){if(n===seq.current){if([400,403,409].includes(x.response?.status)){try{clearPending(sessionStorage,actorId,companyId,trialId);pendingRef.current=null;setPending(null);}catch{} }setError(x.response?.data?.error||x.message||'Chưa xác nhận kết quả. Giữ cùng tệp để kiểm tra lại.');}}
  finally{lock.current=false;if(n===seq.current)setSaving(false);}
 }
 const result=r=><div key={r.requestId} className="rounded-lg border p-3 space-y-1 text-sm"><p className="font-medium">{labels[r.status]} · Page {r.pageId} / biểu mẫu {r.formId}</p><p>Trong kỳ: {r.comparison.uniqueExportIds} mã trong tệp · {r.comparison.observedIds} mã đối chiếu · {r.comparison.matched} khớp.</p><p>Ngoài kỳ: {r.comparison.outsidePeriodRows} dòng · Trùng: {r.comparison.duplicateRows} dòng · Mâu thuẫn: {r.comparison.conflicts} mã.</p><p>Hệ thống có, tệp thiếu: {r.comparison.notInExport} · Tệp có, hệ thống thiếu: {r.comparison.notObserved}.</p><p>Nguồn: {r.sourceReference} · Ghi nhận: {new Date(r.recordedAt).toLocaleString('vi-VN')}</p>{!!r.comparison.differences.length&&<ul className="list-disc pl-5">{r.comparison.differences.map(d=><li key={d.id}>Mã {d.id}: {reasons[d.reason]}</li>)}</ul>}{r.comparison.notInExport+r.comparison.notObserved+r.comparison.conflicts>100&&<p>Hiển thị 100 khác biệt đầu; tổng số ở trên vẫn đầy đủ.</p>}</div>;
 return <section aria-label="Đối soát bản xuất nguồn" className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">Đối soát bản xuất nguồn</h3><p className="text-sm text-slate-600">So mã khách và thời điểm gửi với lượt quét của kỳ đo. Khớp tệp chưa chứng minh đủ mọi nguồn khách, chưa xác nhận đạt chi phí mục tiêu.</p>
  <div className="flex gap-3"><button className={button} disabled={loading||saving} onClick={()=>{setData(null);setReceipt(null);setReload(n=>n+1);}}>Tải hồ sơ đối soát</button><button className={button} disabled={saving} onClick={()=>setOpen(x=>!x)}>{open?'Đóng bản xuất':'Đối soát tệp CSV'}</button></div>
  {loading&&<p role="status">Đang đọc phạm vi và bằng chứng quét…</p>}{error&&<p role="alert" className="text-amber-800">{error}</p>}{pending&&<p role="status">Có yêu cầu đang chờ xác nhận cho Page {pending.request.pageId}, biểu mẫu {pending.request.formId}. Chọn đúng tệp để gửi lại cùng yêu cầu; nội dung tệp không được lưu trong trình duyệt.</p>}
  {data?.census&&<p className="text-sm">Đối chiếu từ {new Date(data.census.sinceAt).toLocaleString('vi-VN')} đến trước {new Date(data.census.untilExclusive).toLocaleString('vi-VN')}. Có {data.census.measuredCount} mã trong tập đo.</p>}
  {data&&!ready&&<p className="text-sm text-amber-800">Cần danh mục nguồn hiện hành và lượt quét có đủ bằng chứng trước khi ghi đối soát mới.</p>}
  {receipt&&result(receipt)}{data?.exports.map(e=><div key={e.receipt.requestId}>{e.currentStatus!=='CURRENT'&&<p className="text-amber-800 text-sm">Bằng chứng lịch sử: phạm vi, dữ liệu hoặc quyền đã đổi; cần đối soát lại.</p>}{result(e.receipt)}</div>)}
  {open&&<form onSubmit={submit} className="space-y-3 border-t pt-3"><label className="block text-sm">Tệp CSV/TXT (UTF-8 hoặc UTF-16LE, tối đa 1 MB / 5.000 dòng)<input aria-label="Tệp đối soát" type="file" accept=".csv,.txt,.tsv" disabled={saving} onChange={chooseFile}/></label><p className="text-xs text-slate-600">Tệp được gửi tới máy chủ dự án để đọc. Chỉ lưu mã khách, biểu mẫu, thời điểm và dấu kiểm tệp; bỏ các cột tên, số điện thoại và nội dung khác.</p>
   {!pending&&<><label className="block text-sm">Biểu mẫu trong danh mục<select aria-label="Biểu mẫu đối soát" value={form} onChange={e=>{setForm(e.target.value);setConfirmed(false);}} disabled={!ready||saving}><option value="">Chọn Page / biểu mẫu</option>{data?.forms.map(f=><option key={`${f.pageId}:${f.formId}`} value={`${f.pageId}:${f.formId}`}>{f.pageId} / {f.formId}</option>)}</select></label><label className="block text-sm">Thời điểm xuất tệp (giờ Việt Nam)<input type="datetime-local" required value={exported} onChange={e=>setExported(e.target.value)} disabled={saving}/></label><label className="block text-sm">Dấu phân cột<select value={delimiter} onChange={e=>setDelimiter(e.target.value)}><option value=",">Dấu phẩy</option><option value=";">Dấu chấm phẩy</option><option value={'\t'}>Tab</option></select></label>
    {[['Cột mã khách',idColumn,setIdColumn],['Cột thời điểm gửi',timeColumn,setTimeColumn],['Cột mã biểu mẫu (để trống nếu tệp không có)',formColumn,setFormColumn],['Nguồn tệp / tham chiếu',reference,setReference]].map(([label,value,setter])=><label key={label} className="block text-sm">{label}<input className="ml-2 border p-1" value={value} maxLength={label.includes('tham chiếu')?500:120} disabled={saving} onChange={e=>setter(e.target.value)}/></label>)}<label className="block text-sm">Phạm vi và bộ lọc khi xuất<textarea className="block w-full border p-2" minLength={20} maxLength={2000} required value={note} disabled={saving} onChange={e=>setNote(e.target.value)}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Tôi đã kiểm tra Page, biểu mẫu và ghi rõ bộ lọc của tệp này.</label></>}
   <button className={button} disabled={saving||reading||!file||(!pending&&(!ready||!confirmed||reference.trim().length<8||note.trim().length<20))}>{saving?'Đang ghi đối soát…':pending?'Xác nhận lại cùng tệp':'Đối soát và lưu bằng chứng'}</button>
  </form>}
 </section>;
}
