'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {projectIdentity}=require('../src/modules/crmLeadIdentity/graph');
const dsn=process.env.CRM_IDENTITY_TEST_DATABASE_URL;
test('isolated PostgreSQL non-destructive CRM identity',{skip:!dsn},async t=>{
 const url=new URL(dsn);assert.ok(['127.0.0.1','localhost','[::1]'].includes(url.hostname));assert.equal(url.pathname,'/crm_identity_test');
 const {Client}=require('pg'),db=new Client({connectionString:dsn}),peers=[];await db.connect();
 const company=randomUUID(),other=randomUUID(),tenant=randomUUID(),admin=randomUUID(),sales=randomUUID(),region=randomUUID(),customer=randomUUID(),ids=Array.from({length:5},()=>randomUUID()).sort();
 try{
  assert.equal((await db.query("SELECT count(*)::int n FROM pg_tables WHERE schemaname='public'")).rows[0].n,0,'Requires fresh isolated DB');
  await db.query(`CREATE ROLE anon NOLOGIN;CREATE ROLE authenticated NOLOGIN;CREATE ROLE service_role NOLOGIN;
   CREATE TABLE tenants(id uuid PRIMARY KEY,is_active boolean);CREATE TABLE companies(id uuid PRIMARY KEY,tenant_id uuid,is_active boolean);
   CREATE TABLE users(id uuid PRIMARY KEY,company_id uuid,tenant_id uuid,role text,is_active boolean);
   CREATE TABLE company_regions(id uuid PRIMARY KEY,company_id uuid,is_active boolean,name text,code text);
   CREATE TABLE user_company_regions(user_id uuid,region_id uuid,PRIMARY KEY(user_id,region_id));
   CREATE TABLE customers(id uuid PRIMARY KEY,company_id uuid,full_name text,phone text,email text,address text,city text);
   CREATE TABLE crm_leads(id uuid PRIMARY KEY,company_id uuid,customer_id uuid,region_id uuid,assigned_to uuid,lead_owner_id uuid,type text,title text,description text,lead_type_id uuid,install_address text,phone text,email text);`);
  await db.query('INSERT INTO tenants VALUES($1,true)',[tenant]);await db.query('INSERT INTO companies VALUES($1,$3,true),($2,$3,true)',[company,other,tenant]);
  await db.query("INSERT INTO users VALUES($1,$3,$4,'admin',true),($2,$3,$4,'sales',true)",[admin,sales,company,tenant]);
  await db.query("INSERT INTO company_regions VALUES($1,$2,true,'HCM','HCM')",[region,company]);await db.query('INSERT INTO user_company_regions VALUES($1,$3),($2,$3)',[admin,sales,region]);
  await db.query("INSERT INTO customers VALUES($1,$2,'Khách giả','0901234567',NULL,'HCM','HCM')",[customer,company]);
  for(const id of ids)await db.query("INSERT INTO crm_leads(id,company_id,customer_id,region_id,assigned_to,lead_owner_id,type,title) VALUES($1,$2,$3,$4,$5,$5,'lead','Khách thử')",[id,company,customer,region,admin]);
  for(const file of ['650_crm_lead_qualification.sql','651_crm_lead_identity.sql','654_crm_identity_review.sql','685_crm_identity_review_active_company.sql']){const sql=fs.readFileSync(path.resolve(__dirname,'../../database',file),'utf8');await db.query(sql);await db.query(sql);}
  for(let i=0;i<3;i++){const c=new Client({connectionString:dsn});await c.connect();await c.query('SET ROLE service_role');peers.push(c)}
  const read=(id=ids[0],who=admin,cid=company,c=peers[0])=>c.query('SELECT crm_lead_identity_snapshot($1,$2,$3) r',[who,cid,id]).then(x=>x.rows[0].r);
  const cmd=async(a,b,action='LINK')=>({action,leftLeadId:a,rightLeadId:b,leftToken:(await read(a)).snapshotToken,rightToken:(await read(b)).snapshotToken,evidence:'Đã xác minh qua trao đổi với khách giả về hai hồ sơ này.'});
  const record=(command,key=randomUUID(),who=admin,c=peers[0])=>c.query('SELECT crm_lead_identity_record($1,$2,$3,$4) r',[who,company,key,command]).then(x=>x.rows[0].r);
  const link=async(a,b)=>record(await cmd(a,b));
  await t.test('public roles and direct service writes denied',async()=>{for(const role of ['anon','authenticated','service_role']){await db.query('SET ROLE '+role);await assert.rejects(db.query('DELETE FROM crm_lead_identity_edges'),e=>e.code==='42501');await assert.rejects(db.query('SELECT * FROM crm_lead_identity_events'),e=>e.code==='42501');if(role!=='service_role')await assert.rejects(read(ids[0],admin,company,db),e=>e.code==='42501');await db.query('RESET ROLE');}});
  await t.test('singleton not treated as unique paid customer',async()=>{const r=projectIdentity(await read());assert.equal(r.status,'UNLINKED');assert.equal(r.qualifiedUniquePaidLead,false);});
  await t.test('link retains both original leads and exact retry does not duplicate audit',async()=>{const c=await cmd(ids[0],ids[1]),key=randomUUID();await record(c,key);const r=await record(c,key);assert.equal(r.replayed,true);assert.equal(projectIdentity(r.left).memberCount,2);assert.equal((await db.query('SELECT count(*)::int n FROM crm_leads')).rows[0].n,5);await assert.rejects(record({...c,evidence:'Một nội dung hoàn toàn khác với lần xác nhận trước.'},key),e=>e.code==='23505');});
  await t.test('chain and triangle closure preserve one group after deleting one edge',async()=>{await link(ids[1],ids[2]);await link(ids[0],ids[2]);const r=await record(await cmd(ids[0],ids[1],'UNLINK'));assert.equal(projectIdentity(r.left).memberCount,3);assert.equal(projectIdentity(r.left).status,'NEEDS_REVIEW');});
  await t.test('old link replay after unlink never resurrects active edge',async()=>{const c=await cmd(ids[3],ids[4]),key=randomUUID();await record(c,key);await record(await cmd(ids[3],ids[4],'UNLINK'));const r=await record(c,key);assert.equal(r.replayed,true);assert.equal(projectIdentity(r.left).memberCount,1);assert.equal(projectIdentity(r.left).status,'NEEDS_REVIEW');});
  await t.test('parallel new links against same snapshot only accept one graph revision',async()=>{const c=await cmd(ids[3],ids[4]);const rs=await Promise.allSettled([record(c,randomUUID(),admin,peers[0]),record(c,randomUUID(),admin,peers[1])]);assert.equal(rs.filter(x=>x.status==='fulfilled').length,1);assert.equal(rs.find(x=>x.status==='rejected').reason.code,'40001');});
  await t.test('identity and qualification can execute concurrently without inverted company lock',async()=>{const s=(await peers[2].query('SELECT crm_lead_quality_read($1,$2,$3) r',[admin,company,ids[4]])).rows[0].r;const c=await cmd(ids[0],ids[3]);const d={status:'QUALIFIED',contactVerified:true,demandMatches:true,serviceAreaVerified:true,evidence:'Đã xác minh nhu cầu khách thử và vùng phục vụ.'};await Promise.all([record(c,randomUUID(),admin,peers[0]),peers[2].query('SELECT crm_lead_quality_record($1,$2,$3,$4,$5,$6,$7)',[admin,company,ids[4],randomUUID(),s.revision,s.contextVersion,d])]);});
  await t.test('contact A-B-A leaves the group under review without splitting',async()=>{await db.query("UPDATE customers SET phone='0909999999' WHERE id=$1",[customer]);await db.query("UPDATE customers SET phone='0901234567' WHERE id=$1",[customer]);const r=projectIdentity(await read());assert.equal(r.status,'NEEDS_REVIEW');assert.equal(r.memberCount,5);assert.equal(r.canonicalLeadId,null);});
  await t.test('changing demand and routing does not change identity generation',async()=>{const a=await read();await db.query("UPDATE crm_leads SET description='Nhu cầu được bổ sung',assigned_to=$1 WHERE id=$2",[sales,ids[0]]);const b=await read();assert.deepEqual(a.members.map(x=>x.generation),b.members.map(x=>x.generation));});
  await t.test('permission on root does not grant other members in component',async()=>{await assert.rejects(read(ids[0],sales),e=>e.code==='42501');});
  await t.test('tenant suspension denies a repeated accepted command too',async()=>{const c=await cmd(ids[0],ids[3]),key=randomUUID();await record(c,key);await db.query('UPDATE tenants SET is_active=false WHERE id=$1',[tenant]);await assert.rejects(record(c,key),e=>e.code==='42501');await db.query('UPDATE tenants SET is_active=true WHERE id=$1',[tenant]);});
  await t.test('legacy deletion keeps edge/evidence and remaining group needs review',async()=>{const count=(await db.query('SELECT count(*)::int n FROM crm_lead_identity_events')).rows[0].n;await db.query('DELETE FROM crm_leads WHERE id=$1',[ids[2]]);const r=projectIdentity(await read());assert.equal(r.memberCount,5);assert.equal(r.unavailableMemberCount,1);assert.equal(r.status,'NEEDS_REVIEW');assert.equal((await db.query('SELECT count(*)::int n FROM crm_lead_identity_events')).rows[0].n,count);});
  await t.test('moved member is not silently lost, and new company sees unresolved history without old IDs',async()=>{const newAdmin=randomUUID();await db.query("INSERT INTO users VALUES($1,$2,$3,'admin',true)",[newAdmin,other,tenant]);await db.query('UPDATE crm_leads SET company_id=$1,customer_id=NULL,assigned_to=$2,lead_owner_id=$2 WHERE id=$3',[other,newAdmin,ids[4]]);const old=projectIdentity(await read());assert.equal(old.memberCount,5);assert.equal(old.unavailableMemberCount,2);const moved=projectIdentity(await read(ids[4],newAdmin,other));assert.equal(moved.status,'NEEDS_REVIEW');assert.deepEqual(moved.memberLeadIds,[ids[4]]);assert.ok(moved.reasons.includes('CROSS_COMPANY_HISTORY'));});
  await require('./crmLeadIdentity.review.cases')(t,{db,peers,company,other,admin,sales,region,tenant});
  await require('./facebookDuplicateReview.cases')(t,{db,peers,company,other,admin,sales,region,tenant});
 }finally{await Promise.all(peers.map(c=>c.end()));await db.end();}
});
