'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {createIdentityService}=require('../src/modules/crmLeadIdentity/service');
const id=n=>`11111111-1111-4111-8111-${String(n).padStart(12,'0')}`;
const c={actorId:id(1),companyId:id(2),leadId:id(3)};
const snap=(leadId=c.leadId)=>({companyId:c.companyId,rootLeadId:leadId,graphRevision:0,asOf:'2026-10-02T01:00:00Z',complete:true,snapshotToken:'a'.repeat(32),members:[{leadId,companyId:c.companyId,available:true,generation:0,reviewRequired:false,contextVersion:'v1'}],edges:[],foreignLinkLeadIds:[]});
const body=()=>({requestId:id(9),peerLeadId:id(4),action:'LINK',leftToken:'a'.repeat(32),rightToken:'b'.repeat(32),evidence:'Đã xác minh khách thử và nguồn gốc của hai hồ sơ.'});
function fixture({primary=true,error=null,raw}={}){const calls=[],db={rpc:async(name,args)=>{calls.push({name,args});return{error,data:raw===undefined?(name.endsWith('snapshot')?snap():{replayed:false,left:snap(),right:snap(id(4))}):raw};}};return{db,calls,service:createIdentityService({db,isPrimary:()=>primary})};}
test('service passes only server company/actor and binds URL lead into intent',async()=>{const f=fixture(),r=await f.service.record(c,body());assert.equal(f.calls[0].args.p_actor_id,c.actorId);assert.equal(f.calls[0].args.p_company_id,c.companyId);assert.equal(f.calls[0].args.p_command.leftLeadId,c.leadId);assert.equal(r.left.deduplicationComplete,false);});
test('database concurrency token is separate from domain evidence digest',async()=>{const r=await fixture().service.read(c);assert.equal(r.snapshotToken,'a'.repeat(32));assert.equal(r.evidenceDigest.length,64);});
for(const field of ['actorId','companyId','canonicalLeadId','sourceVerified','leftLeadId','members'])test('client cannot forge '+field,async()=>{const f=fixture();await assert.rejects(f.service.record(c,{...body(),[field]:id(1)}),e=>e.code==='INVALID_IDENTITY');assert.equal(f.calls.length,0);});
for(const patch of [{peerLeadId:c.leadId},{requestId:'bad'},{action:'MERGE_DELETE'},{evidence:'guess'},{evidence:null},{leftToken:''},{rightToken:123}])test('bad identity command rejected '+JSON.stringify(patch),async()=>{const f=fixture();await assert.rejects(f.service.record(c,{...body(),...patch}),e=>e.code==='INVALID_IDENTITY');assert.equal(f.calls.length,0);});
test('failover and malformed authenticated context cannot reach DB',async()=>{for(const f of [fixture({primary:false}),fixture()]){await assert.rejects(f.service.read({...c,actorId:null}));assert.equal(f.calls.length,0);}});
for(const [pg,status] of [['42501',403],['40001',409],['23505',409],['P0002',404],['54000',409],['XX000',503]])test('sanitized database error '+pg,async()=>{await assert.rejects(fixture({error:{code:pg,message:'private upstream'}}).service.read(c),e=>e.status===status&&!e.message.includes('private'));});
test('incomplete graph cannot be published as singleton',async()=>{await assert.rejects(fixture({raw:{...snap(),complete:false}}).service.read(c));});
test('unavailable-member ids are not in public member list or canonical key',async()=>{const raw=snap();raw.edges=[{companyId:c.companyId,leftLeadId:c.leadId,rightLeadId:id(4),leftContext:'v1',rightContext:'v2',revision:1,active:true,evidenceId:'proof'}];const r=await fixture({raw}).service.read(c);assert.deepEqual(r.memberLeadIds,[c.leadId]);assert.equal(r.canonicalLeadId,null);assert.ok(!JSON.stringify(r).includes(id(4)));});
const routeSource=fs.readFileSync(path.resolve(__dirname,'../src/routes/crm/routes/leadIdentity.js'),'utf8');
function router(enabled=true){const f=fixture(),handlers={},req={params:{id:c.leadId},user:{id:c.actorId,userId:c.actorId},crmLeadAccess:{lead:{id:c.leadId,company_id:c.companyId}},body:body()};const deps={express:{Router:()=>({get:(p,h)=>handlers['GET']=h,post:(p,h)=>handlers['POST']=h})},'../../../config/supabase':{supabase:f.db},'../../../config/supabaseRouter':{isFailoverEnabled:()=>false,getActiveTarget:()=> 'primary'},'../../../modules/crmLeadIdentity/service':{createIdentityService}};vm.runInNewContext(routeSource,{require:n=>deps[n],module:{exports:{}},process:{env:{VPT_CRM_LEAD_IDENTITY:enabled?'1':'0'}}});return{...f,req,async invoke(r=req,method='GET'){const res={statusCode:200,set(){return this},status(n){this.statusCode=n;return this},json(b){this.body=b;return this}};await handlers[method](r,res);return res;}};}
test('mounted route defaults off and does not touch DB',async()=>{const f=router(false);assert.equal((await f.invoke()).body.code,'IDENTITY_DISABLED');assert.equal(f.calls.length,0);});
test('actual route requires parent scoped authorization',async()=>{const f=router();assert.equal((await f.invoke({...f.req,crmLeadAccess:null})).statusCode,403);assert.equal(f.calls.length,0);assert.equal((await f.invoke()).statusCode,200);});
test('route mount remains after authentication and existing CRM lead gate',()=>{const s=fs.readFileSync(path.resolve(__dirname,'../src/routes/crm/index.js'),'utf8');assert.ok(s.indexOf('r.use(auth)')<s.indexOf('r.use(leadIdentity)'));assert.ok(s.indexOf('r.use(enforceCrmDealAssigneeAccess)')<s.indexOf('r.use(leadIdentity)'));});
