'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {createFacebookBatchJournal,journalResponse}=require('../src/helpers/facebookBatchJournal');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),actor=id(1),company=id(2),key=id(3),contact=id(4);
const view=()=>({policy:'FACEBOOK_BATCH_JOURNAL_V1',actorId:actor,companyId:company,requestId:key,state:'REVIEW',createdAt:'2026-10-04T00:00:00Z',updatedAt:'2026-10-04T00:00:00Z',items:[{contactId:contact,state:'CANCELLED',result:null}]});
const request=()=>({user:{userId:actor},body:{company_id:company,contact_ids:[contact]},params:{requestId:key}});
function setup({data=view(),error=null,primary=()=>true}={}){const calls=[],db={rpc:async(name,args)=>{calls.push({name,args});return{data,error};}};return{calls,service:createFacebookBatchJournal({db,isPrimary:primary})};}
test('stop binds exact immutable selection to authenticated actor without accepting capability',async()=>{const s=setup(),r=await s.service.stop(request(),key);assert.deepEqual(s.calls,[{name:'crm_facebook_batch_stop',args:{p_actor:actor,p_company:company,p_request:key,p_ids:[contact]}}]);const response=journalResponse(r);assert.equal(response.status,200);assert.equal(response.body.processed,0);assert.equal(response.body.unprocessed,1);assert.equal(response.body.reconciliation_required,false);});
test('stop keeps an already started item unresolved even if a CRM mapping may exist',async()=>{const data=view();data.items[0].state='UNKNOWN';const s=setup({data}),r=journalResponse(await s.service.stop(request(),key));assert.equal(r.status,202);assert.equal(r.body.reconciliation_required,true);assert.equal(r.body.failed,1);});
for(const [label,edit]of [['extra actor',r=>r.body.actor_id=actor],['capability',r=>r.body.token='secret'],['empty IDs',r=>r.body.contact_ids=[]],['duplicate IDs',r=>r.body.contact_ids=[contact,contact]],['too many IDs',r=>r.body.contact_ids=Array(501).fill(contact)],['wrong company',r=>r.body.company_id='all'],['conflicting actor',r=>r.user.id=id(9)]])test('invalid stop '+label+' never reaches SQL',async()=>{const s=setup(),r=request();edit(r);await assert.rejects(s.service.stop(r,key));assert.equal(s.calls.length,0);});
for(const [label,edit]of [['wrong actor',x=>x.actorId=id(8)],['wrong selection',x=>x.items[0].contactId=id(8)],['running state',x=>x.state='RUNNING'],['pending item',x=>x.items[0].state='PENDING'],['running item',x=>x.items[0].state='RUNNING']])test('stop rejects unconfirmed response '+label,async()=>{const data=view();edit(data);await assert.rejects(setup({data}).service.stop(request(),key),e=>e.status===503);});
test('stop requires Primary before and after SQL',async()=>{const denied=setup({primary:()=>false});await assert.rejects(denied.service.stop(request(),key));assert.equal(denied.calls.length,0);let n=0;const changed=setup({primary:()=>++n===1});await assert.rejects(changed.service.stop(request(),key));assert.equal(changed.calls.length,1);});
for(const [code,status]of [['42501',403],['23505',409],['55P03',409],['XX000',503]])test('stop sanitizes SQL failure '+code,async()=>{await assert.rejects(setup({error:{code,message:'PRIVATE'}}).service.stop(request(),key),e=>e.status===status&&!e.message.includes('PRIVATE'));});
test('actual stop endpoint uses authenticated service, no-store and retained partial response',async()=>{
 const source=fs.readFileSync(path.join(__dirname,'../src/routes/facebook.js'),'utf8'),start=source.indexOf("r.post('/batch-create-leads/:requestId/stop'"),end=source.indexOf("r.post('/batch-create-leads',",start);let handler,received;
 vm.runInNewContext(source.slice(start,end),{r:{post(_p,...f){handler=f.at(-1);}},authMiddleware(){},facebookBatchJournal:{stop:async(req,k)=>{received=[req,k];const r=view();r.items[0].state='UNKNOWN';return r;}},journalResponse});
 const res={set(k,v){this.cache=[k,v];return this;},status(n){this.code=n;return this;},json(b){this.body=b;return this;}};await handler(request(),res);
 assert.equal(received[1],key);assert.equal(res.code,202);assert.deepEqual(res.cache,['Cache-Control','no-store']);assert.equal(res.body.journal.items[0].state,'UNKNOWN');
});
