'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {createCareLibrary}=require('../src/modules/marketingAutomation/customerCareLibrary');
const company=randomUUID(),actor=randomUUID(),entry=randomUUID(),region=randomUUID(),token='a'.repeat(32);
function setup({data,error,env={VPT_CARE_LIBRARY_ADMIN:'1'},primary=true}={}){
 const calls=[],s={status:200};
 const res={set(){},status(n){s.status=n;return this},json(x){s.body=x;return this}};
 const service=createCareLibrary({env,isPrimary:()=>primary,now:()=>new Date().toISOString(),db:{async rpc(name,args){calls.push({name,args});return{data,error}}}});
 return{calls,s,run:(operation,body,user={userId:actor})=>service.handle({user,query:body,body},res,operation)};
}
const approved=()=>({companyId:company,entryId:entry,version:token,revision:2,state:'APPROVED',approvedReady:true,sourceReady:true,approvedBy:actor,document:{purpose:'ADVICE',regionIds:[region],channels:['facebook'],validUntil:new Date(Date.now()+3600000).toISOString(),answer:'Thông tin giả đã duyệt: <b>được giữ nguyên dạng chữ</b>.',sourceReference:'Synthetic source, never a production product claim'}});
const preview={companyId:company,entryId:entry,version:token,regionId:region,channel:'facebook'};
test('library is default-off and primary-only before database access',async()=>{for(const settings of[{env:{}},{primary:false}]){const x=setup(settings);await x.run('list',{companyId:company});assert.equal(x.s.status,503);assert.equal(x.calls.length,0)}});
test('library actor derives from authenticated context; spoof/ambiguous actors denied',async()=>{for(const [body,user] of[[{companyId:company,actorId:actor},{userId:actor}],[{companyId:company},{id:actor,userId:randomUUID()}]]){const x=setup();await x.run('list',body,user);assert.ok([400,403].includes(x.s.status));assert.equal(x.calls.length,0)}});
test('library forwards exact change key/body with server actor and verifies receipt',async()=>{const requestId=randomUUID(),command={entryId:entry,action:'SAVE',expectedVersion:null,reason:'Synthetic edit reason with source'};
 const data={companyId:company,entryId:entry,requestId,action:'SAVE',entry:{companyId:company,entryId:entry}};const x=setup({data});await x.run('change',{companyId:company,requestId,command});assert.equal(x.s.status,200);assert.deepEqual(x.calls[0],{name:'crm_care_library_change',args:{p_actor:actor,p_company:company,p_request:requestId,p_command:command}});
 for(const bad of[{...data,requestId:randomUUID()},{...data,action:'APPROVE'},{...data,entry:{companyId:randomUUID(),entryId:entry}}]){const y=setup({data:bad});await y.run('change',{companyId:company,requestId,command});assert.equal(y.s.status,503)}});
test('library preview returns exact approved text and explicit send false',async()=>{const data=approved(),x=setup({data});await x.run('preview',preview);assert.equal(x.s.status,200);assert.equal(x.s.body.text,data.document.answer);assert.equal(x.s.body.send,false);assert.equal(x.calls[0].name,'crm_care_library_read')});
test('library blocks draft/revoked/unverified/expired and wrong audience preview',async()=>{const a=approved();for(const data of[{...a,state:'DRAFT'},{...a,state:'REVOKED'},{...a,approvedReady:false},{...a,sourceReady:false},{...a,approvedBy:null},{...a,document:{...a.document,regionIds:[randomUUID()]}},{...a,document:{...a.document,channels:['zalo']}},{...a,document:{...a.document,validUntil:'2020-01-01T00:00:00Z'}},{...a,document:{...a.document,purpose:'FINAL_QUOTE'}},{...a,document:{...a.document,answer:'Unapproved {{price}}'}}]){const x=setup({data});await x.run('preview',preview);assert.equal(x.s.status,403);assert.equal(x.s.body.text,undefined)}});
test('library rejects stale preview and wrong-company/entry storage replies',async()=>{for(const [data,status]of[[{...approved(),version:'b'.repeat(32)},409],[{...approved(),companyId:randomUUID()},503],[{...approved(),entryId:randomUUID()},503]]){const x=setup({data});await x.run('preview',preview);assert.equal(x.s.status,status);assert.equal(x.s.body.text,undefined)}});
test('library errors remain unavailable, never empty success or internal details',async()=>{for(const[code,status]of[['42501',403],['23505',409],['40001',409],['22007',400],['XX000',503]]){const x=setup({error:{code,message:'SECRET internal detail'}});await x.run('list',{companyId:company});assert.equal(x.s.status,status);assert.equal(JSON.stringify(x.s.body).includes('SECRET'),false)}});
test('library validates pagination and preview arguments before calling storage',async()=>{for(const[op,b]of[['list',{companyId:company,after:'bad'}],['read',{companyId:company,entryId:'bad'}],['preview',{...preview,version:'bad'}],['preview',{...preview,channel:'unknown'}],['preview',{...preview,send:true}]]){const x=setup();await x.run(op,b);assert.equal(x.s.status,400);assert.equal(x.calls.length,0)}});
test('library revocation of primary/feature while storage is in flight hides result',async()=>{let primary=true;const env={VPT_CARE_LIBRARY_ADMIN:'1'},res={set(){},status(n){this.code=n;return this},json(x){this.body=x}};const svc=createCareLibrary({env,isPrimary:()=>primary,db:{async rpc(){primary=false;return{data:approved()}}}});await svc.handle({user:{id:actor},body:preview},res,'preview');assert.equal(res.code,503);assert.equal(res.body.text,undefined)});
