'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {readCensusPage,createLeadCensus}=require('../src/modules/marketingAutomation/facebookLeadCensus');
const {createCensusAdmin}=require('../src/modules/marketingAutomation/facebookLeadCensusAdmin');
const context={pageId:'123',formId:'456',kind:'FORMS',after:null,pageToken:'synthetic-secret'};
const form={id:'456',page_id:'123',status:'ARCHIVED',expired_leads_count:2};
const read=(data,c=context,inspect=()=>{})=>readCensusPage({context:c,version:'v24.0',fetchImpl:async(url,opts)=>{inspect(url,opts);return{ok:true,json:async()=>new URL(url).pathname==='/v24.0/456'?{id:'456',page_id:'123'}:data}}});
test('forms enumeration keeps archived/expired metadata and uses fixed host with header token',async()=>{const r=await read({data:[form]},context,(url,o)=>{assert.equal(new URL(url).pathname,'/v24.0/123/leadgen_forms');assert.equal(new URL(url).searchParams.get('limit'),'100');assert.ok(!url.includes('synthetic-secret'));assert.equal(o.redirect,'error');assert.equal(o.headers.Authorization,'Bearer synthetic-secret');});assert.deepEqual(r,{rows:[{id:'456',status:'ARCHIVED',expiredLeads:2}],next:null,graphVersion:'v24.0'});});
test('lead enumeration projects no contact data and normalizes provider time',async()=>{const r=await read({data:[{id:'789',form_id:'456',created_time:'2026-10-01T00:00:00+0700',field_data:[{secret:'not returned'}]}]},{...context,kind:'LEADS'});assert.deepEqual(r.rows,[{id:'789',acquiredAt:'2026-09-30T17:00:00.000Z'}]);assert.ok(!JSON.stringify(r).includes('secret'));});
test('terminal empty data ends scan, it does not assert coverage completeness',async()=>{const r=await read({data:[],paging:{cursors:{after:'unused'}}});assert.equal(r.next,null);assert.equal(r.complete,undefined);});
test('a known form must belong to the Page before any leads edge is read',async()=>{let calls=0;await assert.rejects(readCensusPage({context:{...context,kind:'LEADS'},version:'v24.0',fetchImpl:async url=>{calls++;assert.equal(new URL(url).pathname,'/v24.0/456');return{ok:true,json:async()=>({id:'456',page_id:'999'})}}}),e=>e.code==='CENSUS_SCOPE_MISMATCH');assert.equal(calls,1);});
test('paging uses validated cursor and never follows returned URL',async()=>{const r=await read({data:[form],paging:{next:'https://graph.facebook.com/v24.0/123/leadgen_forms?after=next&access_token=secret',cursors:{after:'next'}}});assert.equal(r.next,'next');await read({data:[]},{...context,after:'next'},url=>assert.equal(new URL(url).searchParams.get('after'),'next'));});
for(const [name,data,c,code]of[
 ['wrong page',{data:[{...form,page_id:'999'}]},context,'CENSUS_SCOPE_MISMATCH'],
 ['wrong form',{data:[{id:'789',form_id:'999',created_time:'2026-10-01'}]},{...context,kind:'LEADS'},'CENSUS_SCOPE_MISMATCH'],
 ['unknown status',{data:[{...form,status:'OTHER'}]},context,'CENSUS_SCOPE_MISMATCH'],
 ['bad acquired time',{data:[{id:'789',form_id:'456',created_time:'not-date'}]},{...context,kind:'LEADS'},'CENSUS_SCOPE_MISMATCH'],
 ['duplicate id',{data:[form,form]},context,'CENSUS_ROW_INVALID'],
 ['wrong id type',{data:[{...form,id:456}]},context,'CENSUS_ROW_INVALID'],
 ['negative expired count',{data:[{...form,expired_leads_count:-1}]},context,'CENSUS_ROW_INVALID'],
 ['missing data',{},context,'CENSUS_PROVIDER_UNAVAILABLE'],
 ['too many rows',{data:Array.from({length:101},()=>form)},context,'CENSUS_PROVIDER_UNAVAILABLE'],
 ['provider error',{data:[],error:{message:'synthetic-secret'}},context,'CENSUS_PROVIDER_UNAVAILABLE'],
 ['wrong paging type',{data:[],paging:[]},context,'CENSUS_PAGING_INVALID'],
 ['no cursor',{data:[],paging:{next:'https://graph.facebook.com/v24.0/123/leadgen_forms'}},context,'CENSUS_PAGING_INVALID'],
 ['foreign pagination',{data:[],paging:{next:'https://evil.invalid/?after=a',cursors:{after:'a'}}},context,'CENSUS_PAGING_INVALID'],
 ['wrong edge',{data:[],paging:{next:'https://graph.facebook.com/v24.0/999/leads?after=a',cursors:{after:'a'}}},context,'CENSUS_PAGING_INVALID'],
 ['wrong cursor',{data:[],paging:{next:'https://graph.facebook.com/v24.0/123/leadgen_forms?after=b',cursors:{after:'a'}}},context,'CENSUS_PAGING_INVALID'],
 ['repeated cursor',{data:[],paging:{next:'https://graph.facebook.com/v24.0/123/leadgen_forms?after=a',cursors:{after:'a'}}},{...context,after:'a'},'CENSUS_PAGING_LOOP'],
])test('reject '+name,async()=>{await assert.rejects(read(data,c),e=>e.code===code&&!e.message.includes('synthetic-secret'));});
test('network errors never return tokens or provider error text',async()=>{await assert.rejects(readCensusPage({context,version:'v24.0',fetchImpl:async()=>{throw Error('synthetic-secret')}}),e=>e.code==='CENSUS_PROVIDER_UNAVAILABLE'&&!e.message.includes('synthetic-secret'));});

const env=()=>({VPT_FB_LEAD_CENSUS:'1',VPT_META_GRAPH_VERSION:'v24.0',VPT_MARKETING_TRIAL_REPORT:'1',VPT_FB_LEAD_INTAKE_PAGES:'123'});
test('worker commits an exact chunk through RPC and continues until no tasks',async()=>{let claims=0;const calls=[];const db={rpc:async(n,a)=>{calls.push([n,a]);return{data:n.endsWith('_claim')?(claims++?[]:[{id:'task'}]):n.endsWith('_context')?context:{status:'RECORDED'}}}};await createLeadCensus({db,isPrimary:()=>true,pages:new Set(['123']),env:env(),readSource:async()=>({rows:[],next:null,graphVersion:'v24.0'})}).drain();assert.deepEqual(calls.map(x=>x[0]),['marketing_fb_census_claim','marketing_fb_census_context','marketing_fb_census_commit','marketing_fb_census_claim']);assert.equal(calls[2][1].p_token,calls[0][1].p_token);});
test('worker disabled, paused or backup never reads provider or DB',async()=>{for(const [e,p]of[[{},true],[{...env(),VPT_FB_LEAD_INTAKE_WORKER_PAUSED:'1'},true],[env(),false]])await createLeadCensus({db:{rpc:()=>assert.fail('DB')},isPrimary:()=>p,pages:new Set(['123']),env:e,readSource:()=>assert.fail('provider')}).drain();});
test('pause during provider call leaves lease to recover and does not publish',async()=>{const e=env(),calls=[];const db={rpc:async(n)=>{calls.push(n);return{data:n.endsWith('_claim')?[{id:'task'}]:context}}};await createLeadCensus({db,isPrimary:()=>true,pages:new Set(['123']),env:e,readSource:async()=>{e.VPT_FB_LEAD_INTAKE_WORKER_PAUSED='1';return{rows:[],next:null}}}).drain();assert.deepEqual(calls,['marketing_fb_census_claim','marketing_fb_census_context']);});
test('provider failure records a bounded code and no arbitrary text',async()=>{let claims=0;const calls=[];await createLeadCensus({db:{rpc:async(n,a)=>{calls.push([n,a]);return{data:n.endsWith('_claim')?(claims++?[]:[{id:'t'}]):n.endsWith('_context')?context:{status:'FAILED'}}}},isPrimary:()=>true,pages:new Set(['123']),env:env(),readSource:async()=>{throw Error('secret')}}).drain();assert.equal(calls[2][0],'marketing_fb_census_fail');assert.equal(calls[2][1].p_code,'CENSUS_STORAGE_UNAVAILABLE');assert.ok(!JSON.stringify(calls).includes('secret'));});
test('concurrent in-process drains do not issue duplicate claims',async()=>{let release,n=0;const gate=new Promise(r=>release=r);const worker=createLeadCensus({db:{rpc:async()=>{n++;await gate;return{data:[]}}},isPrimary:()=>true,pages:new Set(['123']),env:env()});const a=worker.drain();await worker.drain();release();await a;assert.equal(n,1);});
const request=()=>({user:{userId:randomUUID()},query:{company_id:randomUUID()},params:{trialId:randomUUID()},body:{requestId:randomUUID()}});
const response=()=>({code:200,body:null,set(){return this},status(c){this.code=c;return this},json(v){this.body=v;return this}});
test('admin derives scope and Page allowlist from server, accepts no completeness/cursor inputs',async()=>{const req=request(),res=response(),calls=[];await createCensusAdmin({db:{rpc:async(n,a)=>{calls.push([n,a]);return{data:{id:randomUUID(),state:'RUNNING'}}}},isPrimary:()=>true,env:env()})(req,res,true);assert.equal(res.code,202);assert.equal(calls[0][1].p_actor,req.user.userId);assert.deepEqual(calls[0][1].p_pages,['123']);for(const key of ['companyId','actor','complete','after']){const r=request();r.body[key]='injected';const s=response();await createCensusAdmin({db:{rpc:()=>assert.fail('DB')},isPrimary:()=>true,env:env()})(r,s,true);assert.equal(s.code,400);}});
test('admin rejects missing/conflicting scope, revocation and mismatched status response',async()=>{for(const change of [r=>delete r.query.company_id,r=>r.user.id=randomUUID()]){const r=request();change(r);const s=response();await createCensusAdmin({db:{rpc:()=>assert.fail('DB')},isPrimary:()=>true,env:env()})(r,s);assert.equal(s.code,403);}for(const result of [{error:{code:'42501'}},{data:{companyId:randomUUID(),trialId:randomUUID()}}]){const s=response();await createCensusAdmin({db:{rpc:async()=>result},isPrimary:()=>true,env:env()})(request(),s);assert.equal(s.code,result.error?403:503);}});
