'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),actor=id(1),company=id(2),key=id(3),contacts=[id(4),id(5)];
const modulePromise=import('../../frontend/src/components/facebook/batchRecoveryState.mjs');
const view=(states=['CANCELLED','CANCELLED'])=>({policy:'FACEBOOK_BATCH_JOURNAL_V1',actorId:actor,companyId:company,requestId:key,state:'REVIEW',items:contacts.map((contactId,i)=>({contactId,state:states[i]}))});
const memory=()=>{const map=new Map();return{getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};};
async function setup({storage=memory(),send=async(method)=>method==='POST'?{ok:false,data:{error:'Lost BEGIN'}}:{ok:true,data:{journal:view()}},current=()=>true}={}){
 const api=await modulePromise,calls=[],states=[],controller=api.createRecoveryController({actor,company,storage,newId:()=>key,isCurrent:current,update:s=>states.push(s),send:async(...a)=>{calls.push(a);return send(...a);}});
 return{api,calls,states,storage,controller};
}
test('stop persists exact cancellation intent before network after lost BEGIN',async()=>{const h=await setup({send:async(method,p)=>{if(method==='STOP'){assert.equal(h.api.readPending(h.storage,actor,company).intent,'STOP');assert.deepEqual(p.contactIds,contacts);return{ok:true,data:{journal:view()}};}throw Error('lost');}});await h.controller.start(contacts);await h.controller.stop(key);assert.deepEqual(h.calls.map(x=>x[0]),['POST','STOP']);assert.equal(h.states.at(-1).run.items[0].state,'CANCELLED');h.controller.acknowledge();assert.equal(h.api.readPending(h.storage,actor,company),null);});
test('lost stop and reload only read or resend STOP, never re-dispatch BEGIN',async()=>{const first=await setup({send:async()=>{throw Error('offline');}});await first.controller.start(contacts);await first.controller.stop(key);const next=await setup({storage:first.storage});await next.controller.refresh();await next.controller.resend();assert.deepEqual(next.calls.map(x=>x[0]),['GET','STOP']);assert.equal(next.calls[1][1].requestId,key);});
test('another tab cancellation intent wins over cached begin resend',async()=>{const first=await setup();await first.controller.start(contacts);const second=await setup({storage:first.storage,send:async()=>{throw Error('stop lost');}});await second.controller.stop(key);await first.controller.resend();assert.equal(first.calls.at(-1)[0],'STOP');});
test('history-only stop adopts the exact server selection for reload recovery',async()=>{const h=await setup({send:async()=>({ok:true,data:{journal:view(['UNKNOWN','CANCELLED'])}})});await h.controller.inspect(key);assert.equal(h.api.readPending(h.storage,actor,company),null);await h.controller.stop(key);assert.deepEqual(h.api.readPending(h.storage,actor,company),{actorId:actor,companyId:company,requestId:key,contactIds:contacts,intent:'STOP'});h.controller.acknowledge();assert.ok(h.api.readPending(h.storage,actor,company));});
test('UNKNOWN cannot be acknowledged even when the rest is cancelled',async()=>{const h=await setup({send:async()=>({ok:true,data:{journal:view(['UNKNOWN','CANCELLED'])}})});await h.controller.start(contacts);await h.controller.stop(key);h.controller.acknowledge();assert.ok(h.api.readPending(h.storage,actor,company));});
test('storage failure prevents stop; different run cannot replace the held request',async()=>{const h=await setup();await h.controller.start(contacts);h.storage.setItem=()=>{throw Error('blocked storage');};await assert.rejects(h.controller.stop(key),/blocked storage/);assert.equal(h.calls.length,1);await assert.rejects(h.controller.stop(id(9)),/thay đổi/);assert.equal(h.calls.length,1);});
test('stale confirmation cannot stop a different history row',async()=>{let r=view();const h=await setup({send:async()=>({ok:true,data:{journal:r}})});await h.controller.inspect(key);r={...view(),requestId:id(99)};await h.controller.inspect(id(99));await assert.rejects(h.controller.stop(key),/thay đổi/);assert.equal(h.calls.length,2);assert.equal(h.api.readPending(h.storage,actor,company),null);});
test('failed refresh removes cancelled result and cannot clear the durable stop intent',async()=>{let fail=false;const h=await setup({send:async()=>fail?{ok:false,data:{error:'403'}}:{ok:true,data:{journal:view()}}});await h.controller.start(contacts);await h.controller.stop(key);fail=true;await h.controller.refresh();h.controller.acknowledge();assert.equal(h.states.at(-1).run,null);assert.equal(h.api.readPending(h.storage,actor,company).intent,'STOP');});
test('invalid intent is refused and valid STOP cannot be downgraded through storage writer',async()=>{const h=await setup();await h.controller.start(contacts);await h.controller.stop(key);const p=h.api.readPending(h.storage,actor,company);assert.throws(()=>h.api.validatePending({...p,intent:'BEGIN'},actor,company));const old={...p};delete old.intent;assert.throws(()=>h.api.savePending(h.storage,old,true));});
test('late stop response after scope disposal cannot publish or acknowledge',async()=>{let live=true,resolve;const h=await setup({current:()=>live,send:async(method)=>method==='STOP'?new Promise(r=>resolve=r):{ok:false,data:{error:'lost begin'}}});await h.controller.start(contacts);const wait=h.controller.stop(key),n=h.states.length;live=false;resolve({ok:true,data:{journal:view()}});await wait;assert.equal(h.states.length,n);h.controller.acknowledge();assert.equal(h.api.readPending(h.storage,actor,company).intent,'STOP');});
