'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
module.exports=async(t,{db,peers,query,admin,sales,company,other,region})=>{
 const sql=fs.readFileSync(path.resolve(__dirname,'../../database/662_crm_care_library_console.sql'),'utf8');await db.query(sql);await db.query(sql);
 await db.query("ALTER TABLE company_regions ADD COLUMN name text DEFAULT 'Synthetic region'");
 const choices=(kind,search='',after=null,who=admin,cid=company)=>query('crm_care_library_choices',[who,cid,kind,search,after]);
 const read=id=>query('crm_care_library_read',[admin,company,id]);
 const hist=(id,v,before=null)=>query('crm_care_library_history',[admin,company,id,v,before]);
 await t.test('library console selectors hide foreign/inactive/shared data and internal product fields',async()=>{const a=randomUUID(),b=randomUUID(),c=randomUUID(),d=randomUUID();await db.query("INSERT INTO products VALUES($1,$5,'Unique selector A','active',987654321,clock_timestamp()),($2,$6,'Unique selector B','active',987654321,clock_timestamp()),($3,$5,'Unique selector C','inactive',987654321,clock_timestamp()),($4,NULL,'Unique selector D','active',987654321,clock_timestamp())",[a,b,c,d,company,other]);const x=await choices('product','Unique selector');assert.deepEqual(x.items.map(p=>p.id),[a]);assert.equal(JSON.stringify(x).includes('987654321'),false);assert.deepEqual(Object.keys(x.items[0]).sort(),['code','id','name']);assert.equal((await choices('product','%')).items.length,0);assert.equal((await choices('region')).items.some(x=>x.id===region),true);await assert.rejects(choices('product','',null,sales),e=>e.code==='42501');await assert.rejects(choices('product','',null,admin,other),e=>e.code==='42501')});
 await t.test('library console selector pages are complete and reject a changed cursor',async()=>{for(let i=0;i<55;i++)await db.query("INSERT INTO products VALUES($1,$2,$3,'active',0,clock_timestamp())",[randomUUID(),company,'Paging product '+i]);const seen=new Set();let after=null;do{const p=await choices('product','Paging product',after);assert.ok(p.items.length<=50);for(const x of p.items){assert.equal(seen.has(x.id),false);seen.add(x.id)}after=p.nextAfter}while(after);assert.equal(seen.size,55);const first=await choices('product','Paging product');await db.query("UPDATE products SET status='inactive' WHERE id=$1",[first.nextAfter]);await assert.rejects(choices('product','Paging product',first.nextAfter),e=>e.code==='40001');await assert.rejects(choices('product','Other search',first.nextAfter),e=>e.code==='40001')});
 const id=randomUUID(),document={title:'History console',purpose:'QUALIFY',question:'Synthetic needs question',answer:'Synthetic question only.',sourceReference:'Synthetic source for console history',productId:null,regionIds:[region],channels:['facebook'],validUntil:new Date(Date.now()+3600000).toISOString()};
 const save=async(answer='Synthetic question only.')=>{const existing=(await db.query('SELECT id FROM crm_care_library_entries WHERE id=$1',[id])).rows[0],v=existing?await read(id):null;return query('crm_care_library_change',[admin,company,randomUUID(),{entryId:id,action:'SAVE',expectedVersion:v?.version||null,reason:'Synthetic history console source change',document:{...document,answer}}])};
 await t.test('library console complete history stays historical and detects stale/foreign cursors',async()=>{for(let i=0;i<55;i++)await save('Synthetic history '+i);const current=await read(id),seen=new Set();let before=null;do{const p=await hist(id,current.version,before);assert.equal(p.historical,true);assert.ok(p.items.length<=50);for(const x of p.items){assert.equal(seen.has(x.requestId),false);seen.add(x.requestId);assert.equal(x.document.title,'History console');assert.equal(x.version,undefined);assert.equal(x.approvedReady,undefined)}before=p.nextBefore}while(before);assert.equal(seen.size,55);await assert.rejects(hist(id,current.version,randomUUID()),e=>e.code==='42501');await save('Newer version');await assert.rejects(hist(id,current.version),e=>e.code==='40001')});
 await t.test('library console SQL helpers deny public roles and check current rights on every read',async()=>{const current=await read(id);for(const role of['anon','authenticated']){await db.query('SET ROLE '+role);try{await assert.rejects(query('crm_care_library_choices',[admin,company,'product','',null],db),e=>e.code==='42501');await assert.rejects(query('crm_care_library_history',[admin,company,id,current.version,null],db),e=>e.code==='42501')}finally{await db.query('RESET ROLE')}}await db.query('UPDATE users SET is_active=false WHERE id=$1',[admin]);try{await assert.rejects(choices('product'),e=>e.code==='42501');await assert.rejects(hist(id,current.version),e=>e.code==='42501')}finally{await db.query('UPDATE users SET is_active=true WHERE id=$1',[admin])}});
};
