'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{randomUUID,createHash}=require('crypto');
module.exports=async(t,{db,peers,query,admin,company,other})=>{
 const sql=fs.readFileSync(path.resolve(__dirname,'../../database/660_crm_customer_care_console.sql'),'utf8');await db.query(sql);await db.query(sql);
 let seq=810000;const receive=async(psid,amount=1,intent='MESSAGE')=>{const events=Array.from({length:amount},()=>{const x={pageId:'123',psid,mid:'console-'+seq++,direction:'inbound',intent,content:'Synthetic transcript only',attachments:[],sentAt:new Date(Date.now()-3600000).toISOString()};return{...x,payloadHash:createHash('sha256').update(JSON.stringify(x)).digest('hex')}});for(let n=0;n<events.length;n+=100)await query('crm_care_receive',[JSON.stringify(events.slice(n,n+100))]);return (await db.query("SELECT id FROM crm_care_threads WHERE page_id='123' AND psid=$1",[psid])).rows[0].id;};
 const queue=(mode='WAITING',cursor=null,cid=company)=>query('crm_care_queue',[admin,cid,mode,cursor?.id||null,cursor?.version||null,cursor?.queueVersion||null]);
 const read=id=>query('crm_care_read',[admin,company,id]);
 const history=(id,before,version)=>query('crm_care_history',[admin,company,id,before,version]);
 await t.test('care console RPCs remain service-only',async()=>{for(const role of ['anon','authenticated']){await db.query('SET ROLE '+role);try{await assert.rejects(query('crm_care_queue',[admin,company,'WAITING',null,null],db),e=>e.code==='42501');await assert.rejects(query('crm_care_history',[admin,company,randomUUID(),randomUUID(),'a'.repeat(32)],db),e=>e.code==='42501');}finally{await db.query('RESET ROLE');}}});
 await t.test('care queue filters state, counts across state and sorts earliest human deadline',async()=>{const a=await receive(String(seq++),1,'REQUEST_HUMAN'),b=await receive(String(seq++),1,'REQUEST_HUMAN');await db.query("UPDATE crm_care_threads SET human_deadline='2005-01-01T03:00:00Z' WHERE id=$1",[a]);await db.query("UPDATE crm_care_threads SET human_deadline='2004-01-01T03:00:00Z' WHERE id=$1",[b]);const q=await queue('HUMAN_REQUESTED');assert.equal(q.items[0].id,b);assert.equal(q.items[1].id,a);assert.ok(q.items.every(x=>x.mode==='HUMAN_REQUESTED'));assert.ok(q.counts.OPTED_OUT>0);assert.equal(q.aiMaySend,false);assert.equal(JSON.stringify(q).includes('Synthetic transcript'),false);});
 await t.test('care queue paginates all matching threads exactly once',async()=>{for(let i=0;i<55;i++)await receive(String(seq++));let q=await queue(),ids=q.items.map(x=>x.id),rounds=0;while(q.nextCursor){assert.ok(++rounds<10);q=await queue('WAITING',q.nextCursor);ids.push(...q.items.map(x=>x.id));}assert.equal(new Set(ids).size,ids.length);assert.equal(ids.length,q.counts.WAITING);});
 await t.test('care queue refuses stale/wrong-mode/foreign cursors and invalid filters',async()=>{const q=await queue(),cursor={...q.nextCursor,id:q.items[0].id,version:q.items[0].version};await db.query('UPDATE crm_care_threads SET revision=revision+1 WHERE id=$1',[cursor.id]);await assert.rejects(queue('WAITING',cursor),e=>e.code==='40001');await assert.rejects(queue('OPTED_OUT',cursor),e=>e.code==='40001');await assert.rejects(queue('WAITING',cursor,other),e=>e.code==='42501');await assert.rejects(queue('MISSING'),e=>e.code==='22023');await assert.rejects(query('crm_care_queue',[admin,company,'WAITING',cursor.id,null]),e=>e.code==='22023');});
 await t.test('care queue invalidates paging when a different row changes priority or state',async()=>{let q=await queue();assert.ok(q.nextCursor);const otherId=q.items.find(x=>x.id!==q.nextCursor.id).id;await db.query("UPDATE crm_care_threads SET mode='HUMAN_REQUESTED',human_deadline=clock_timestamp() WHERE id=$1",[otherId]);await assert.rejects(queue('WAITING',q.nextCursor),e=>e.code==='40001');q=await queue();await receive(String(seq++));await assert.rejects(queue('WAITING',q.nextCursor),e=>e.code==='40001');});
 const transcript=await receive(String(seq++),125);
 await t.test('care history returns all125 messages without gaps or duplicates',async()=>{const first=await read(transcript);assert.equal(first.messages.length,50);assert.equal(first.messageCount,125);let rows=first.messages,before=rows[0].id,rounds=0;while(before){assert.ok(++rounds<10);const older=await history(transcript,before,first.version);assert.equal(older.version,first.version);rows=[...older.messages,...rows];before=older.nextBefore;}const expected=(await db.query('SELECT id FROM crm_care_messages WHERE thread_id=$1 ORDER BY sent_at,id',[transcript])).rows.map(x=>x.id);assert.deepEqual(rows.map(x=>x.id),expected);assert.equal(new Set(rows.map(x=>x.id)).size,125);});
 await t.test('care history denies another thread cursor and changes during paging',async()=>{const v=await read(transcript),another=await receive(String(seq++)),foreign=(await read(another)).messages[0].id;await assert.rejects(history(transcript,foreign,v.version),e=>e.code==='22023');const psid=(await db.query('SELECT psid FROM crm_care_threads WHERE id=$1',[transcript])).rows[0].psid;await receive(psid);await assert.rejects(history(transcript,v.messages[0].id,v.version),e=>e.code==='40001');});
 await t.test('care history rechecks current Page/company and queue flags inaccessible scope',async()=>{const v=await read(transcript);await db.query("UPDATE facebook_pages SET default_company_id=$1 WHERE page_id='123'",[other]);try{await assert.rejects(history(transcript,v.messages[0].id,v.version),e=>e.code==='42501');const q=await queue();assert.ok(q.unavailableCount>0);assert.ok(q.items.every(x=>x.scope_available===false));}finally{await db.query("UPDATE facebook_pages SET default_company_id=$1 WHERE page_id='123'",[company]);}});
 await t.test('care history rechecks actor even with valid cursor/version',async()=>{const v=await read(transcript);await db.query('UPDATE users SET is_active=false WHERE id=$1',[admin]);try{await assert.rejects(history(transcript,v.messages[0].id,v.version),e=>e.code==='42501');await assert.rejects(queue(),e=>e.code==='42501');}finally{await db.query('UPDATE users SET is_active=true WHERE id=$1',[admin]);}});
};
