'use strict';
const assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {createLeadCensus,readCensusPage}=require('../src/modules/marketingAutomation/facebookLeadCensus');
const {createLeadIntake}=require('../src/modules/marketingAutomation/facebookLeadIntake');
module.exports=async(t,{db,peers,company,other,tenant,admin,sales,bind,query})=>{
 await bind();const date=n=>new Date(Date.now()+7*3600000+n*86400000).toISOString().slice(0,10),trial=randomUUID();
 await query('marketing_lead_trial_set',[admin,company,trial,randomUUID(),{name:'Census synthetic test',since:date(-1),until:date(28),expectedRevision:0}]);
 const start=(key=randomUUID(),who=admin,cid=company,c=peers[0],pages=['123'])=>query('marketing_fb_census_start',[who,cid,trial,key,pages],c);
 const stop=()=>db.query("UPDATE marketing_fb_census_runs SET state='FAILED' WHERE state='RUNNING'");
 const status=()=>query('marketing_fb_census_status',[admin,company,trial]);
 const claim=async(c=peers[0])=>{const token=randomUUID();const q=(await c.query('SELECT * FROM marketing_fb_census_claim($1,$2)',[['123'],token])).rows[0];return{q,token}};
 const finish=(item,rows=[],next=null,c=peers[0])=>query('marketing_fb_census_commit',[item.q.id,item.token,{rows,next,graphVersion:'v24.0'}],c);
 const getContext=item=>query('marketing_fb_census_context',[item.q.id,item.token]);
 const rpc={rpc:async(name,args)=>{
  try{const data=name.endsWith('_claim')?(await peers[0].query(`SELECT * FROM ${name}(${Object.keys(args).map((_,i)=>'$'+(i+1)).join(',')})`,Object.values(args))).rows:await query(name,Object.values(args));return{data};}
  catch(e){return{error:{code:e.code}};}
 }};
 await t.test('private census tables/context deny browser roles and foreign operators',async()=>{for(const role of ['anon','authenticated','service_role']){await db.query('SET ROLE '+role);await assert.rejects(db.query('SELECT * FROM marketing_fb_census_runs'),e=>e.code==='42501');await assert.rejects(db.query('SELECT marketing_fb_census_scope($1,$2)',[company,trial]),e=>e.code==='42501');if(role!=='service_role')await assert.rejects(query('marketing_fb_census_status',[admin,company,trial],db),e=>e.code==='42501');await db.query('RESET ROLE');}await assert.rejects(start(randomUUID(),sales),e=>e.code==='42501');await assert.rejects(start(randomUUID(),admin,other),e=>e.code==='42501');await assert.rejects(start(randomUUID(),admin,company,peers[0],[null]),e=>e.code==='22023');});
 await t.test('start is idempotent, concurrent duplicates create one run, active run blocks another key',async()=>{const key=randomUUID(),r=await Promise.all([start(key,admin,company,peers[0]),start(key,admin,company,peers[1])]);assert.equal(r[0].id,r[1].id);assert.equal(r.filter(x=>x.replayed).length,1);await assert.rejects(start(),e=>e.code==='40001');assert.equal((await db.query('SELECT count(*)::int n FROM marketing_fb_census_tasks WHERE run_id=$1',[r[0].id])).rows[0].n,2);await stop();});
 await t.test('provider scan recovers missed notifications into verified CRM intake with no duplicate on webhook replay',async()=>{
  const r=await start(),acquired=new Date(Date.parse(date(0)+'T00:00:00+07:00')-3600000).toISOString(),recoveryUntil=new Date(Date.parse((await status()).run.until)+1).toISOString();
  await db.query('SELECT pg_sleep(0.01)');
  const fetchImpl=async url=>{const p=new URL(url).pathname;return{ok:true,json:async()=>p.endsWith('/leadgen_forms')?{data:[{id:'456',page_id:'123',status:'ARCHIVED',expired_leads_count:0}]}:p.endsWith('/leads')?{data:[{id:'8101',form_id:'456',created_time:acquired},{id:'8102',form_id:'456',created_time:acquired},{id:'8103',form_id:'456',created_time:'2020-01-01T00:00:00Z'},{id:'8104',form_id:'456',created_time:recoveryUntil}]}:{id:'456',page_id:'123'}}};
  await createLeadCensus({db:rpc,isPrimary:()=>true,pages:new Set(['123']),env:{VPT_FB_LEAD_CENSUS:'1',VPT_META_GRAPH_VERSION:'v24.0'},readSource:x=>readCensusPage({...x,fetchImpl})}).drain();
  let s=await status();assert.equal(s.run.id,r.id);assert.equal(s.run.state,'SCANNED');assert.equal(s.run.enumerated,2);assert.equal(s.run.awaitingIntake,2);assert.equal(s.run.cpqlReady,false);assert.equal(s.run.scopeCurrent,true);
  const intake=createLeadIntake({db:rpc,isPrimary:()=>true,pages:new Set(['123']),isPaused:()=>false,readSource:async({receipt,context})=>({proof:{provider:'META_LEAD_ADS_V1',pageId:receipt.page_id,formId:receipt.form_id,leadgenId:receipt.leadgen_id,source:'PAID',accountId:context.accountId,adId:'888',adsetId:'999',campaignId:'111',graphVersion:'v24.0',acquiredAt:acquired,fetchedAt:new Date().toISOString()},contact:{name:'Synthetic recovered',phone:'090123'+receipt.leadgen_id,email:'',request:'Tủ bếp'}})});
  await intake.drain();s=await status();assert.equal(s.run.awaitingIntake,0);assert.equal((await db.query('SELECT count(*)::int n FROM crm_leads')).rows[0].n,2);
  await query('marketing_fb_lead_enqueue',[JSON.stringify([{pageId:'123',formId:'456',leadgenId:'8101'}]),'a'.repeat(64)]);await intake.drain();assert.equal((await db.query('SELECT count(*)::int n FROM crm_leads')).rows[0].n,2);assert.ok(!JSON.stringify(s).includes('page-test-token'));assert.ok(!JSON.stringify(s).includes('090123'));
 });
 await t.test('parallel claims and duplicate chunk commit cannot advance the same task twice',async()=>{await start();const a=await Promise.all([claim(peers[0]),claim(peers[1])]);assert.notEqual(a[0].q.id,a[1].q.id);const q=a.find(x=>x.q.kind==='FORMS');const rs=await Promise.allSettled([finish(q,[],null,peers[0]),finish(q,[],null,peers[1])]);assert.equal(rs.filter(x=>x.status==='fulfilled').length,1);assert.equal(rs.find(x=>x.status==='rejected').reason.code,'40001');await stop();});
 await t.test('saved cursor survives worker restart, old token fails and repeated cursor rolls back',async()=>{await start();let a=await claim();assert.equal(a.q.kind,'FORMS');await finish(a,[], 'opaque-A');a=await claim();assert.equal((await getContext(a)).after,'opaque-A');await db.query("UPDATE marketing_fb_census_tasks SET lease_until=clock_timestamp()-interval '1 second' WHERE id=$1",[a.q.id]);const b=await claim(peers[1]);assert.equal(b.q.id,a.q.id);assert.notEqual(b.token,a.token);await assert.rejects(finish(a),e=>e.code==='40001');await assert.rejects(finish(b,[],'opaque-A'),e=>e.code==='22023');const row=(await db.query('SELECT * FROM marketing_fb_census_tasks WHERE id=$1',[b.q.id])).rows[0];assert.equal(row.cursor_after,'opaque-A');assert.equal(row.chunks,1);await finish(b);await stop();});
 await t.test('failed latest scan remains visible, restart uses a new run, not old success',async()=>{await start();const a=await claim();await query('marketing_fb_census_fail',[a.q.id,a.token,'CENSUS_PROVIDER_UNAVAILABLE']);let s=await status();assert.equal(s.run.state,'FAILED');assert.equal(s.run.failureCode,'CENSUS_PROVIDER_UNAVAILABLE');assert.equal(s.run.cpqlReady,false);const r=await start();s=await status();assert.equal(s.run.id,r.id);assert.equal(s.run.state,'RUNNING');await stop();});
 await t.test('scope drift, new unselected Page, revoked actor and token rotation invalidate scans',async()=>{await db.query("INSERT INTO facebook_pages VALUES('999',$1,true,'synthetic')",[company]);await assert.rejects(start(),e=>e.code==='42501');await db.query("DELETE FROM facebook_pages WHERE page_id='999'");await start();const a=await claim();await db.query("UPDATE facebook_pages SET access_token='rotated' WHERE page_id='123'");await assert.rejects(getContext(a),e=>e.code==='40001');assert.equal((await status()).run.scopeCurrent,false);await db.query("UPDATE facebook_pages SET access_token='page-test-token' WHERE page_id='123'");await db.query('UPDATE users SET is_active=false WHERE id=$1',[admin]);await assert.rejects(getContext(a),e=>e.code==='42501');await db.query('UPDATE users SET is_active=true WHERE id=$1',[admin]);await stop();});
 const blocked=async()=>{for(let i=0;i<100;i++){const n=(await db.query("SELECT count(*)::int n FROM pg_stat_activity WHERE wait_event_type='Lock' AND query LIKE 'SELECT marketing_fb_census_%'")).rows[0].n;if(n)return;await new Promise(r=>setTimeout(r,5));}assert.fail('expected blocked census query');};
 await t.test('lease expiry while waiting for Page locks rejects context after the wait',async()=>{await start();const a=await claim();await db.query("UPDATE marketing_fb_census_tasks SET lease_until=clock_timestamp()+interval '500 milliseconds' WHERE id=$1",[a.q.id]);await db.query('BEGIN');await db.query("SELECT * FROM facebook_pages WHERE page_id='123' FOR UPDATE");const p=getContext(a).then(v=>({v}),e=>({e}));try{await blocked();await db.query('SELECT pg_sleep(0.6)');}finally{await db.query('COMMIT');}assert.equal((await p).e?.code,'40001');assert.equal((await db.query('SELECT chunks FROM marketing_fb_census_tasks WHERE id=$1',[a.q.id])).rows[0].chunks,0);await stop();});
 await t.test('lease expiry after enqueue waits rolls back items and cursor atomically',async()=>{await start();let a=await claim();await finish(a);a=await claim();assert.equal(a.q.kind,'LEADS');await query('marketing_fb_lead_enqueue',[JSON.stringify([{pageId:'123',formId:'456',leadgenId:'8999'}]),'b'.repeat(64)]);await db.query("UPDATE marketing_fb_census_tasks SET lease_until=clock_timestamp()+interval '500 milliseconds' WHERE id=$1",[a.q.id]);await db.query('BEGIN');await db.query("SELECT * FROM marketing_fb_lead_receipts WHERE leadgen_id='8999' FOR UPDATE");const p=finish(a,[{id:'8999',acquiredAt:new Date(Date.parse(date(0)+'T00:00:00+07:00')-3600000).toISOString()}],'later').then(v=>({v}),e=>({e}));try{await blocked();await db.query('SELECT pg_sleep(0.6)');}finally{await db.query('COMMIT');}assert.equal((await p).e?.code,'40001');assert.equal((await db.query('SELECT count(*)::int n FROM marketing_fb_census_items WHERE run_id=$1',[a.q.run_id])).rows[0].n,0);assert.equal((await db.query('SELECT count(*)::int n FROM marketing_measurement.census_observations WHERE run_id=$1',[a.q.run_id])).rows[0].n,0);const row=(await db.query('SELECT * FROM marketing_fb_census_tasks WHERE id=$1',[a.q.id])).rows[0];assert.equal(row.chunks,0);assert.equal(row.cursor_after,null);await stop();});
 await t.test('Page inserted between start validation and scope snapshot is rejected',async()=>{
  const original=(await db.query("SELECT pg_get_functiondef('marketing_fb_census_start(uuid,uuid,uuid,uuid,text[])'::regprocedure) d")).rows[0].d;
  // Wait BEFORE the next SQL statement takes its snapshot. Waiting inside the
  // STABLE scope helper would correctly retain the earlier statement snapshot.
  const marker='s:=public.marketing_fb_census_scope';assert.ok(original.includes(marker));
  const altered=original.replace(marker,'PERFORM pg_advisory_lock(813714); PERFORM pg_advisory_unlock(813714); '+marker);
  await db.query(altered);await db.query('SELECT pg_advisory_lock(813714)');const p=start().then(v=>({v}),e=>({e}));
  try{await blocked();await db.query("INSERT INTO facebook_pages VALUES('999',$1,true,'synthetic')",[company]);}finally{await db.query('SELECT pg_advisory_unlock(813714)');}
  try{assert.equal((await p).e?.code,'42501');}finally{await db.query(original);await db.query("DELETE FROM facebook_pages WHERE page_id='999'");}
 });
 await require('./facebookLeadCensus.period.cases')(t,{db,peers,company,other,admin,query,trial,start,stop,claim,finish,getContext,date});
 await require('./facebookLeadCensus.reconciliation.cases')(t,{db,peers,company,other,admin,query,trial});
 await require('./facebookLeadCensus.observedCpql.cases')(t,{db,peers,query,tenant});
 await require('./facebookLeadCensus.sourceRegistry.cases')(t,{db,peers,query,tenant});
};
