'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('crypto'),{pathToFileURL}=require('url'),path=require('path');
const model=import(pathToFileURL(path.resolve(__dirname,'../../frontend/src/components/facebook/careConsoleState.mjs')).href);
const {createCustomerCare}=require('../src/modules/marketingAutomation/facebookCustomerCare');
const companyId=randomUUID(),actorId=randomUUID(),threadId=randomUUID(),version='a'.repeat(32),now=new Date().toISOString();
const message=()=>({id:randomUUID(),direction:'inbound',content:'<script>untrusted text</script>',attachments:[],sent_at:now});
const snapshot=()=>({companyId,threadId,version,mode:'WAITING',aiMaySend:false,messages:[message()],messageCount:1,historyTruncated:false,target:{routingReady:false},humanDeadline:null});
const pending=()=>({companyId,actorId,requestId:randomUUID(),command:{threadId,expectedVersion:version,action:'TAKEOVER',reason:'Tiếp nhận yêu cầu và xử lý khách giả'}});
const memory=()=>{const values=new Map();return{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)}};
test('care view refuses wrong company/thread, unknown mode and AI-enabled response',async()=>{const m=await model;for(const patch of [{companyId:randomUUID()},{threadId:randomUUID()},{mode:'AI_ACTIVE'},{aiMaySend:true},{messageCount:0},{historyTruncated:true}])assert.throws(()=>m.threadView({...snapshot(),...patch},companyId,threadId));assert.equal(m.threadView(snapshot(),companyId,threadId).messages[0].content,'<script>untrusted text</script>');});
test('care queue requires verified counters, scope flags and matching pagination cursor',async()=>{const m=await model,x={id:threadId,mode:'WAITING',version,scope_available:true,created_at:now,human_deadline:null},q={companyId,mode:'WAITING',aiMaySend:false,observedAt:now,unavailableCount:0,counts:{WAITING:1},items:[x],nextCursor:null};assert.equal(m.queueView(q,companyId,'WAITING').counts.OPTED_OUT,0);for(const patch of [{counts:null},{counts:{WAITING:-1}},{companyId:randomUUID()},{nextCursor:{id:randomUUID(),version}},{items:[x,x]}])assert.throws(()=>m.queueView({...q,...patch},companyId,'WAITING'));});
test('care history rejects wrong scope, version and repeated message IDs',async()=>{const m=await model,msg=message(),x={companyId,threadId,version,aiMaySend:false,messages:[msg],messageCount:2,nextBefore:null};assert.equal(m.historyView(x,companyId,threadId,version,new Set()).messages.length,1);assert.throws(()=>m.historyView(x,companyId,threadId,'b'.repeat(32),new Set()));assert.throws(()=>m.historyView(x,companyId,threadId,version,new Set([msg.id])));assert.throws(()=>m.historyView({...x,companyId:randomUUID()},companyId,threadId,version,new Set()));});
test('lost-response command survives session reload and remains identical for retry',async()=>{const m=await model,s=memory(),p=pending();m.savePending(s,p);const restored=m.readPending(s,actorId,companyId);assert.deepEqual(m.controlPayload(restored),{companyId,requestId:p.requestId,command:p.command});assert.deepEqual(m.savePending(s,restored),p);assert.throws(()=>m.savePending(s,pending()));});
test('pending command is isolated by actor and company',async()=>{const m=await model,s=memory();m.savePending(s,pending());assert.equal(m.readPending(s,actorId,randomUUID()),null);assert.equal(m.readPending(s,randomUUID(),companyId),null);});
test('corrupt/browser-blocked pending storage prevents preparing a new command',async()=>{const m=await model,s=memory();s.setItem(m.pendingKey(actorId,companyId),'{bad');assert.throws(()=>m.readPending(s,actorId,companyId));assert.throws(()=>m.savePending({getItem:()=>null,setItem(){throw Error('blocked')}},pending()));assert.throws(()=>m.savePending({getItem:()=>null,setItem(){}},pending()));});
test('ack must match exact scope/target/action before clearing saved intent',async()=>{const m=await model,p=pending(),good={accepted:true,companyId,threadId,mode:'HUMAN_ACTIVE'};assert.equal(m.controlAck(good,p).accepted,true);for(const patch of [{companyId:randomUUID()},{threadId:randomUUID()},{accepted:false},{mode:'OPTED_OUT'}])assert.throws(()=>m.controlAck({...good,...patch},p));const s=memory();m.savePending(s,p);m.clearPending(s,actorId,companyId);assert.equal(m.readPending(s,actorId,companyId),null);});
function response(){return{code:200,set(){return this},status(n){this.code=n;return this},json(x){this.data=x;return this}};}
test('care history and queue HTTP pass validated cursors with server actor identity',async()=>{const calls=[],db={rpc:async(name,args)=>{calls.push({name,args});return{data:name==='crm_care_queue'?{companyId,mode:'WAITING'}:{companyId,threadId}}}},handle=createCustomerCare({db,isPrimary:()=>true,env:{VPT_FB_CARE_ADMIN:'1'}}).handle;for(const [op,query]of [['queue',{companyId,mode:'WAITING',after:threadId,afterVersion:version,queueVersion:version}],['history',{companyId,threadId,before:randomUUID(),version}]]){const res=response();await handle({user:{userId:actorId},query},res,op);assert.equal(res.code,200);}assert.equal(calls[0].args.p_actor,actorId);assert.equal(calls[0].args.p_after_version,version);assert.equal(calls[1].name,'crm_care_history');});
test('care HTTP rejects unpaired cursors, wrong-state filters, spoofed actors and invalid history before DB',async()=>{let calls=0;const handle=createCustomerCare({db:{rpc:async()=>{calls++;return{data:{}}}},isPrimary:()=>true,env:{VPT_FB_CARE_ADMIN:'1'}}).handle;for(const [op,query]of [['queue',{companyId,mode:'WAITING',after:threadId}],['queue',{companyId,mode:'WRONG'}],['queue',{companyId,mode:'WAITING',actorId}],['history',{companyId,threadId,before:threadId,version:'bad'}]]){const res=response();await handle({user:{id:actorId},query},res,op);assert.equal(res.code,400);}assert.equal(calls,0);});
