'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
const modulePromise=import(pathToFileURL(path.resolve(__dirname,'../../frontend/src/components/facebook/duplicateReviewState.mjs')).href);
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),company=id(1),lead=id(2);
const data=()=>({companyId:company,policy:'CRM_EXACT_CONTACT_REVIEW_V1',readOnly:true,merged:0,comparisonCoverage:'COMPLETE',allowBudgetExecution:false,qualifiedUniquePaidLead:false,asOf:'2026-10-04T00:00:00Z',scannedLeadCount:1,availableLeadCount:1,reviewGroupCount:1,unresolvedPairCount:0,candidates:[],groups:[{groupId:lead,members:[{leadId:lead,available:true,title:'Synthetic'}],reasons:['CONTACT_UNMATCHABLE'],deduplicationComplete:false}]});
test('actual UI reader accepts current complete company snapshot',async()=>{const {createDuplicateReviewReader}=await modulePromise,states=[];const r=createDuplicateReviewReader({companyId:company,read:async()=>({ok:true,data:data()}),update:x=>states.push(x)});await r.load();assert.equal(states.at(-1).data.reviewGroupCount,1);});
for(const [label,change]of [['foreign',d=>{d.companyId=id(7);}],['partial',d=>{d.comparisonCoverage='PARTIAL';}],['incorrect count',d=>{d.reviewGroupCount=0;}],['unavailable title',d=>{d.groups[0].members[0].available=false;}],['orphan pair',d=>{d.candidates=[{leftGroupId:lead,rightGroupId:id(8),resolved:false,matchingFields:['PHONE']}];}],['destructive',d=>{d.merged=1;}],['revenue claim',d=>{d.allowBudgetExecution=true;}]])test('UI rejects '+label,async()=>{const {acceptDuplicateReview}=await modulePromise,d=data();change(d);assert.throws(()=>acceptDuplicateReview(d,company));});
test('newer request wins and a response from disposed company is discarded',async()=>{const {createDuplicateReviewReader}=await modulePromise,states=[],pending=[];const r=createDuplicateReviewReader({companyId:company,read:()=>new Promise(resolve=>pending.push(resolve)),update:x=>states.push(x)});const a=r.load(),b=r.load();pending[1]({ok:true,data:data()});await b;const n=states.length;pending[0]({ok:false,data:{error:'OLD'}});await a;assert.equal(states.length,n);const c=r.load();r.dispose();const before=states.length;pending[2]({ok:true,data:data()});await c;assert.equal(states.length,before);});
test('fresh failed read clears prior numbers instead of showing zero',async()=>{const {createDuplicateReviewReader}=await modulePromise,states=[];let ok=true;const r=createDuplicateReviewReader({companyId:company,read:async()=>({ok,data:ok?data():{error:'Rights revoked'}}),update:x=>states.push(x)});await r.load();ok=false;await r.load();assert.equal(states.at(-1).data,null);assert.equal(states.at(-1).error,'Rights revoked');});
