'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const express=require('express'),{createSourceExport}=require('../src/modules/marketingAutomation/sourceExport');
test('real Express 2mb JSON parser accepts full 1MiB CSV and service rejects one extra byte',async()=>{
 const actor='00000000-0000-4000-8000-000000000001',company='00000000-0000-4000-8000-000000000002',trial='00000000-0000-4000-8000-000000000003';let calls=0;
 const service=createSourceExport({env:{VPT_MARKETING_SOURCE_EXPORT:'1',VPT_MARKETING_TRIAL_REPORT:'1'},isPrimary:()=>true,db:{rpc:async(_name,args)=>{calls++;const c=args.p_command;return{data:{policy:'SOURCE_EXPORT_COMPARISON_V1',actorId:actor,companyId:company,trialId:trial,requestId:args.p_request,contextVersion:c.contextVersion,fileSha256:c.fileSha256,fileBytes:c.fileBytes,pageId:c.pageId,formId:c.formId,replayed:false,recordedAt:'2026-10-02T00:00:00Z',sinceAt:'2026-09-30T17:00:00Z',untilExclusive:'2026-10-01T17:00:00Z',exportedAt:c.exportedAt,sourceReference:c.sourceReference,sourceNote:c.sourceNote,censusRunId:actor,registryDigest:'b'.repeat(64),pagesDigest:'c'.repeat(64),normalizedRowsDigest:'d'.repeat(64),providerCoverage:'UNVERIFIED',allowBudgetExecution:false,status:'MATCHED_EXPORTED_IDS',comparison:{rows:1,inPeriodRows:1,outsidePeriodRows:0,uniqueExportIds:1,duplicateRows:0,observedIds:1,matched:1,notInExport:0,notObserved:0,conflicts:0,differences:[]}}};}}});
 const app=express();app.use(express.json({limit:'2mb'}));app.post('/api/crm/marketing-trials/:trialId/source-exports',(req,res)=>{req.user={userId:actor};return service(req,res,true);});
 const server=http.createServer(app);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const request=async size=>{const prefix='id,created_time,unused\n9,2026-10-01T00:00:00Z,',csv=prefix+'x'.repeat(size-Buffer.byteLength(prefix));const payload=JSON.stringify({requestId:actor,contextVersion:'a'.repeat(64),pageId:'123',formId:'456',fileBase64:Buffer.from(csv).toString('base64'),delimiter:',',columns:{id:'id',createdAt:'created_time',formId:null},exportedAt:'2026-10-02T00:00:00Z',sourceReference:'Synthetic maximum file',sourceNote:'No contact data, only synthetic padding.'});return new Promise((resolve,reject)=>{const r=http.request({hostname:'127.0.0.1',port:server.address().port,path:`/api/crm/marketing-trials/${trial}/source-exports?company_id=${company}`,method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload)}},res=>{let b='';res.on('data',d=>b+=d);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(b)}));});r.on('error',reject);r.end(payload);});};
 try{const good=await request(1048576);assert.equal(good.status,200);assert.equal(good.body.fileBytes,1048576);assert.equal(calls,1);const bad=await request(1048577);assert.equal(bad.status,400);assert.equal(calls,1);}finally{await new Promise(resolve=>server.close(resolve));}
});
