'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {context,receipt,id}=require('./marketingAutomation.measurementSnapshot.fixture');
const {calculateSnapshot,projectReport,createMeasurementSnapshot}=require('../src/modules/marketingAutomation/measurementSnapshot');
const env={VPT_MARKETING_MEASUREMENT_SNAPSHOT:'1',VPT_MARKETING_TRIAL_REPORT:'1'};
function request(c,b){return{user:{userId:c.actorId},query:{company_id:c.companyId},params:{trialId:c.trialId},body:b};}
async function run(c,body,db,options={}){const res={statusCode:200,set(){},status(n){this.statusCode=n;return this;},json(x){this.body=x;return this;}};await createMeasurementSnapshot({db,isPrimary:()=>true,env,...options})(request(c,body),res,!!body);return res;}
test('observed snapshot preserves 1m/4=250k and zero-lead account spend without claiming complete',()=>{
 const c=context(),r=calculateSnapshot(c);assert.equal(r.spend.spendVnd,1000000);assert.equal(r.observedMeasurement.costPerQualifiedLeadVnd,250000);assert.equal(r.counts.qualified,4);assert.equal(r.spend.sources.length,2);assert.equal(r.status,'SAVED_OBSERVED_INCOMPLETE');assert.equal(r.targetStatus,'NOT_EVALUATED');assert.equal(r.allowBudgetExecution,false);assert.equal(r.obligations.filter(x=>x.code==='ACCOUNT_DESTINATIONS_UNVERIFIED').length,2);
 for(const field of ['contacts','leadPhone','phone','leadId','groupId','title','proof','fileBase64'])assert.ok(!JSON.stringify(r).includes('"'+field+'"'));
});
test('zero qualified and unknown spend stay distinct',()=>{const c=context();c.facts.qualities.forEach(q=>q.evidence=null);let r=calculateSnapshot(c);assert.equal(r.observedMeasurement.status,'NO_QUALIFIED_LEADS');assert.equal(r.observedMeasurement.costPerQualifiedLeadVnd,null);c.facts.runs.pop();r=calculateSnapshot(c);assert.equal(r.spend.spendVnd,null);assert.equal(r.observedMeasurement.status,'UNAVAILABLE');assert.ok(r.obligations.some(x=>x.code==='SPEND_UNAVAILABLE'&&x.accountId==='act_2'));});
test('public historical projection strips injected private keys',()=>{const c=context(),r=calculateSnapshot(c);r.contacts=['secret'];r.spend.sources[0].token='private';r.counts.phone=123;const s=JSON.stringify(projectReport(r,c.companyId,c.trialId));assert.ok(!s.includes('secret'));assert.ok(!s.includes('private'));assert.ok(!s.includes('"phone"'));});
test('historical projection rejects arithmetic, completion, period and scope forgeries',()=>{const c=context();for(const change of [r=>r.targetStatus='MET',r=>r.allowBudgetExecution=true,r=>r.companyId=id(999),r=>r.observedMeasurement.costPerQualifiedLeadVnd=1,r=>r.period.qualificationAsOf='2020-01-01T00:00:00Z',r=>r.dependencies.identity='wrong']){const r=calculateSnapshot(c);change(r);assert.throws(()=>projectReport(r,c.companyId,c.trialId));}});
test('GET works with standard UUID and never forwards raw facts',async()=>{const c=context(),r=await run(c,null,{rpc:async()=>({data:c})});assert.equal(r.statusCode,200);assert.equal(r.body.preview.counts.qualified,4);assert.equal(r.body.actorId,c.actorId);assert.ok(!JSON.stringify(r.body).includes('090123'));assert.equal(r.body.facts,undefined);});
test('POST computes server report; only request and version are accepted from browser',async()=>{const c=context(),b={requestId:id(900),contextVersion:c.contextVersion},calls=[];const db={rpc:async(n,a)=>{calls.push({n,a});return{data:n==='marketing_measurement_prepare'?c:receipt(c,a.p_report,b.requestId)};}};let r=await run(c,b,db);assert.equal(r.statusCode,200);assert.equal(calls.length,2);assert.equal(calls[1].a.p_report.observedMeasurement.costPerQualifiedLeadVnd,250000);r=await run(c,{...b,report:{cost:1}},db);assert.equal(r.statusCode,400);assert.equal(calls.length,2);});
test('lost response retry uses historical receipt before recomputing changed or unavailable facts',async()=>{const c=context(),report=calculateSnapshot(c),old={...receipt(c,report),replayed:true};let n=0;const r=await run(c,{requestId:old.requestId,contextVersion:old.contextVersion},{rpc:async()=>{n++;return{data:{receipt:old,facts:null}};}});assert.equal(r.statusCode,200);assert.equal(n,1);assert.equal(r.body.report.asOf,report.asOf);assert.equal(r.body.replayed,true);});
test('actor/context mismatch in replay is rejected',async()=>{const c=context(),old={...receipt(c,calculateSnapshot(c)),replayed:true,actorId:id(999)};const r=await run(c,{requestId:old.requestId,contextVersion:c.contextVersion},{rpc:async()=>({data:{receipt:old}})});assert.equal(r.statusCode,503);});
test('default-off, secondary, revoked and stale boundaries stop before publication',async()=>{const c=context();let n=0;const db={rpc:async()=>{n++;return{data:c};}};assert.equal((await run(c,null,db,{env:{}})).statusCode,503);assert.equal((await run(c,null,db,{isPrimary:()=>false})).statusCode,503);assert.equal(n,0);for(const [code,status]of [['42501',403],['40001',409],['23505',409],['22023',400]])assert.equal((await run(c,{requestId:id(900),contextVersion:c.contextVersion},{rpc:async()=>({error:{code}})})).statusCode,status);});
test('primary loss after prepare blocks the write RPC',async()=>{const c=context();let primary=true,n=0;const r=await run(c,{requestId:id(900),contextVersion:c.contextVersion},{rpc:async()=>{n++;primary=false;return{data:c};}},{isPrimary:()=>primary});assert.equal(r.statusCode,503);assert.equal(n,1);});
test('UI scope, old reply and misleading arithmetic are rejected',async()=>{const u=await import('../../frontend/src/components/marketing/measurementSnapshotState.mjs'),c=context(),old=receipt(c,calculateSnapshot(c)),b={requestId:old.requestId,contextVersion:c.contextVersion};assert.equal(u.snapshotReceipt(old,c.companyId,c.trialId,b,c.actorId),old);assert.throws(()=>u.snapshotReceipt(old,id(999),c.trialId,b,c.actorId));assert.throws(()=>u.snapshotReceipt(old,c.companyId,c.trialId,{...b,requestId:id(991)},c.actorId));const altered=structuredClone(old);altered.report.observedMeasurement.costPerQualifiedLeadVnd=1;assert.throws(()=>u.snapshotReceipt(altered,c.companyId,c.trialId));});
test('pending request survives reload, remains actor/company scoped, and quota failure blocks sending',async()=>{const u=await import('../../frontend/src/components/marketing/measurementSnapshotState.mjs'),c=context(),b={requestId:id(900),contextVersion:c.contextVersion},m=new Map(),storage={getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};u.savePending(storage,c.actorId,c.companyId,c.trialId,b);assert.deepEqual(u.readPending(storage,c.actorId,c.companyId,c.trialId),b);assert.equal(u.readPending(storage,id(999),c.companyId,c.trialId),null);assert.equal(u.readPending(storage,c.actorId,id(999),c.trialId),null);assert.throws(()=>u.savePending(storage,c.actorId,c.companyId,c.trialId,{...b,report:{}}));assert.throws(()=>u.savePending({...storage,setItem(){throw Error('quota');}},c.actorId,c.companyId,c.trialId,b));u.clearPending(storage,c.actorId,c.companyId,c.trialId);assert.equal(m.size,0);});

