'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture,id}=require('./marketingAutomation.trial.fixture');
const {reportTrial}=require('../src/modules/marketingAutomation/trialReport');
function scanned(){
 const f=fixture();f.providerReconciliation={version:1,companyId:f.companyId,trialId:f.trial.id,status:'AVAILABLE',complete:true,
  run:{id:id(801),state:'SCANNED',trialRevision:1,scopeCurrent:true,tasksPending:0,since:'2026-10-01T00:00:00+07:00',until:'2026-10-01T11:00:00Z',startedAt:'2026-10-01T11:00:00Z',finishedAt:'2026-10-01T12:00:00Z'},
  forms:[{pageId:'123',formId:'456',discovered:true,expiredLeads:0}],items:f.sources.map(s=>({receiptId:s.receiptId,pageId:s.proof.pageId,formId:s.proof.formId,leadgenId:s.proof.leadgenId,acquiredAt:s.acquiredAt}))};return f;
}
test('all enumerated IDs match CRM but an API subset is not complete paid coverage',()=>{const f=scanned(),r=reportTrial(f);assert.equal(r.reconciliation.matchStatus,'MATCHED_ENUMERATED');assert.equal(r.reconciliation.counts.receivedCrm,6);assert.equal(r.observed.qualified,4);assert.equal(r.spend.spendVnd,1000000);assert.equal(r.costPerQualifiedLeadVnd,null);assert.equal(r.targetMetToDate,false);assert.equal(r.coverage.provider,'PARTIAL');assert.equal(r.reconciliation.cpqlReady,false);assert.ok(!r.reasons.includes('PROVIDER_CENSUS_NOT_CONNECTED'));});
test('pending and review receipts remain distinct from successfully reconciled CRM',()=>{const f=scanned();f.receipts[0].state='PENDING';f.receipts[1].state='REVIEW';const c=reportTrial(f).reconciliation.counts;assert.equal(c.awaitingIntake,1);assert.equal(c.reviewRequired,1);assert.equal(c.receivedCrm,4);});
test('provider metadata disagreement does not count as matched',()=>{const f=scanned();f.sources[0].proof.formId='789';const c=reportTrial(f).reconciliation.counts;assert.equal(c.proofConflict,1);assert.equal(c.receivedCrm,5);});
test('receipt envelope conflict is visible',()=>{const f=scanned();f.receipts[0].leadgenId='555';assert.equal(reportTrial(f).reconciliation.counts.proofConflict,1);});
test('missing receipt and deleted CRM member are retained',()=>{const f=scanned();f.receipts.shift();f.identity.members[1].available=false;f.identity.members[1].contextVersion=null;const c=reportTrial(f).reconciliation.counts;assert.equal(c.missingReceipt,1);assert.equal(c.missingCrm,1);assert.equal(c.unlinkedProofs,1);});
test('reverse comparison finds known ID omitted by the provider enumeration',()=>{const f=scanned();f.providerReconciliation.items.pop();const r=reportTrial(f).reconciliation;assert.equal(r.counts.notEnumerated,1);assert.equal(r.matchStatus,'DISCREPANCIES');});
test('receipt outside scan upper bound waits for a later scan, not a false missing-ID alert',()=>{const f=scanned();f.providerReconciliation.items.pop();const s=f.sources.at(-1);s.acquiredAt=s.proof.acquiredAt='2026-10-01T13:00:00Z';f.qualities.at(-1).firstKnownAt=s.acquiredAt;assert.equal(reportTrial(f).reconciliation.counts.notEnumerated,0);});
test('unknown acquisition cannot be excluded by webhook delivery time',()=>{const f=scanned();f.receipts.push({id:id(803),state:'REVIEW',receivedAt:'2020-01-01T00:00:00Z'});assert.equal(reportTrial(f).reconciliation.counts.unknownAcquiredTime,1);});
test('latest failed scan never inherits an old successful status',()=>{const f=scanned();f.providerReconciliation.run.state='FAILED';f.providerReconciliation.run.tasksPending=1;const r=reportTrial(f).reconciliation;assert.equal(r.status,'FAILED');assert.equal(r.matchStatus,'NOT_CHECKED');});
test('running partial scan remains explicitly not checked',()=>{const f=scanned();f.providerReconciliation.run.state='RUNNING';f.providerReconciliation.run.finishedAt=null;f.providerReconciliation.run.tasksPending=1;const r=reportTrial(f).reconciliation;assert.equal(r.status,'RUNNING');assert.equal(r.matchStatus,'NOT_CHECKED');});
for(const change of [f=>f.providerReconciliation.run.scopeCurrent=false,f=>f.trial.revision++,f=>{f.trial.since='2026-09-01';f.trial.until='2026-09-30';}])test('changed configuration retains stale evidence, not current match '+change,()=>{const f=scanned();change(f);assert.equal(reportTrial(f).reconciliation.status,'STALE');});
for(const change of [f=>f.providerReconciliation.forms[0].discovered=false,f=>f.providerReconciliation.forms[0].expiredLeads=1,f=>f.providerReconciliation.forms[0].expiredLeads=null])test('form coverage issues prevent matched status '+change,()=>{const f=scanned();change(f);assert.equal(reportTrial(f).reconciliation.matchStatus,'DISCREPANCIES');});
for(const change of [f=>f.providerReconciliation.companyId=id(900),f=>f.providerReconciliation.trialId=id(900),f=>f.providerReconciliation.complete=false,f=>f.providerReconciliation.items.push(f.providerReconciliation.items[0]),f=>f.providerReconciliation.items[0].acquiredAt='2020-01-01T00:00:00Z',f=>f.providerReconciliation.run.tasksPending=1,f=>f.providerReconciliation.forms=[]])test('reject wrong scope or malformed snapshot '+change,()=>{const f=scanned();change(f);assert.throws(()=>reportTrial(f),/TRIAL_RECONCILIATION_UNAVAILABLE/);});
test('public projection omits raw provider IDs, contacts, proofs and tokens',()=>{const f=scanned(),s=JSON.stringify(reportTrial(f).reconciliation);for(const key of ['leadgenId','pageId','proof','phone','access_token','scopeCurrent'])assert.ok(!s.includes('"'+key+'":'));assert.ok(!s.includes('090123456'));});
test('client-like completeness decorations cannot enable CPQL',()=>{const f=scanned();Object.assign(f.providerReconciliation,{cpqlReady:true,providerComplete:true,coverage:'COMPLETE'});assert.equal(reportTrial(f).costPerQualifiedLeadVnd,null);});
module.exports={scanned};
