'use strict';
const test = require('node:test'), assert = require('node:assert/strict');
const { measureLeadTrial } = require('../src/modules/marketingAutomation/leadMeasurement');
const { APPROVED_PLAN } = require('../src/modules/marketingAutomation/policy');
function fixture() { return { companyId:'vpt', trialId:'trial', start:'2026-10-01T00:00:00Z', end:'2026-10-31T00:00:00Z', asOf:'2026-11-10T00:00:00Z', currency:'VND', sourceVerified:true, spendFresh:true, qualificationFresh:true, coverage:{spend:'COMPLETE',leads:'COMPLETE',qualification:'COMPLETE',attribution:'COMPLETE'}, accountIds:['fb','google'],
  spend:[{companyId:'vpt',trialId:'trial',accountId:'fb',eventId:'spend1',spentAt:'2026-10-02T00:00:00Z',amountVnd:250000,currency:'VND'}],
  paidLeads:[{companyId:'vpt',trialId:'trial',canonicalLeadId:'lead1',accountId:'fb',sourceEvidenceId:'receipt1',attributionPolicy:'FIRST_VERIFIED_PAID_LEAD_V1',createdAt:'2026-10-02T00:00:00Z',qualification:'QUALIFIED',qualificationEvidenceId:'check1',qualifiedBy:'approved-rule-v1',qualifiedAt:'2026-10-03T00:00:00Z',contactVerified:true,demandMatches:true,serviceAreaVerified:true}] }; }
test('Founder interim target is 250k per verified paid Lead; 300 implies 75m, not a new cap',()=>{assert.equal(APPROVED_PLAN.primaryMetric,'COST_PER_QUALIFIED_PAID_LEAD');assert.equal(APPROVED_PLAN.targetQualifiedLeadCostVnd*300,75000000);assert.equal(APPROVED_PLAN.trialCapVnd,100000000);});
test('250k exact qualifies to date with no accounting dependency or spending grant',()=>{const r=measureLeadTrial(fixture());assert.equal(r.costPerQualifiedLeadVnd,250000);assert.equal(r.targetMetToDate,true);assert.equal(r.revenueTargetEvaluated,false);assert.equal(r.allowBudgetExecution,false);});
test('one VND above target is not rounded down to pass',()=>{const s=fixture();s.spend[0].amountVnd++;assert.equal(measureLeadTrial(s).targetMetToDate,false);});
test('all spend including a different platform with zero Leads is counted',()=>{const s=fixture();s.spend.push({...s.spend[0],accountId:'google',amountVnd:100000});assert.equal(measureLeadTrial(s).costPerQualifiedLeadVnd,350000);});
test('duplicate spend receipts and canonical Leads count once',()=>{const s=fixture();s.spend.push({...s.spend[0]});s.paidLeads.push({...s.paidLeads[0]});assert.equal(measureLeadTrial(s).qualifiedLeads,1);assert.equal(measureLeadTrial(s).costPerQualifiedLeadVnd,250000);});
test('conflicting platform attribution cannot count the same customer twice',()=>{const s=fixture();s.paidLeads.push({...s.paidLeads[0],accountId:'google'});assert.equal(measureLeadTrial(s).reason,'CONFLICTING_LEAD');});
test('pending and rejected customers are separate and not in the denominator',()=>{const s=fixture();s.paidLeads.push({...s.paidLeads[0],canonicalLeadId:'pending',qualification:'PENDING'},{...s.paidLeads[0],canonicalLeadId:'rejected',qualification:'REJECTED'});const r=measureLeadTrial(s);assert.equal(r.receivedPaidLeads,3);assert.equal(r.qualifiedLeads,1);assert.equal(r.pendingLeads,1);assert.equal(r.rejectedLeads,1);assert.equal(r.costPerQualifiedLeadVnd,250000);});
test('zero qualified Leads has null cost and never achieves target',()=>{const s=fixture();s.paidLeads=[];const r=measureLeadTrial(s);assert.equal(r.status,'NO_QUALIFIED_LEADS');assert.equal(r.costPerQualifiedLeadVnd,null);assert.equal(r.targetMetToDate,false);});
for(const k of ['spend','leads','qualification','attribution'])test('incomplete '+k+' is unknown, not a cheap Lead',()=>{const s=fixture();s.coverage[k]='PARTIAL';assert.equal(measureLeadTrial(s).status,'UNKNOWN');});
for(const k of ['sourceVerified','spendFresh','qualificationFresh'])test('unverified source '+k+' cannot be used',()=>{const s=fixture();s[k]=false;assert.equal(measureLeadTrial(s).reason,'UNVERIFIED_SOURCE');});
for(const k of ['contactVerified','demandMatches','serviceAreaVerified','qualificationEvidenceId','qualifiedBy'])test('qualification requires '+k,()=>{const s=fixture();delete s.paidLeads[0][k];assert.equal(measureLeadTrial(s).reason,'UNVERIFIED_QUALIFICATION');});
test('AI warm/hot label is not a verified Lead',()=>{const s=fixture();s.paidLeads[0].qualification='nong';assert.equal(measureLeadTrial(s).reason,'INVALID_LEAD');});
test('source from an old acquisition cohort is rejected',()=>{const s=fixture();s.paidLeads[0].createdAt='2026-09-30T00:00:00Z';assert.equal(measureLeadTrial(s).reason,'INVALID_LEAD');});
test('qualification may arrive after spending ends, but not after the snapshot',()=>{const s=fixture();s.paidLeads[0].qualifiedAt='2026-11-02T00:00:00Z';assert.equal(measureLeadTrial(s).targetMetToDate,true);s.paidLeads[0].qualifiedAt='2026-12-02T00:00:00Z';assert.equal(measureLeadTrial(s).reason,'UNVERIFIED_QUALIFICATION');});
test('wrong company and account block measurement',()=>{for(const patch of [{companyId:'other'},{accountId:'other'}]){const s=fixture();Object.assign(s.paidLeads[0],patch);assert.equal(measureLeadTrial(s).status,'UNKNOWN');}});
test('conflicting spend event must be reconciled',()=>{const s=fixture();s.spend.push({...s.spend[0],amountVnd:1});assert.equal(measureLeadTrial(s).reason,'CONFLICTING_SPEND');});
