'use strict';
const assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const{reportTrial}=require('../src/modules/marketingAutomation/trialReport');
module.exports=async(t,{db,peers,company,other,tenant,admin,sales,region,bind,setup,proof,commit,query})=>{
 await bind();
 const date=offset=>new Date(Date.now()+7*3600000+offset*86400000).toISOString().slice(0,10),since=date(-1),until=date(28),trial=randomUUID();
 const config={name:'Synthetic whole-account trial',since,until,expectedRevision:0};
 const set=(id=trial,cmd=config,who=admin,cid=company,key=randomUUID(),c=peers[0])=>query('marketing_lead_trial_set',[who,cid,id,key,cmd],c);
 const snapshot=(c=peers[0])=>query('marketing_lead_trial_snapshot',[admin,company,trial],c);
 let seq=200;const fresh=async()=>{const item=await setup(),p={...proof(item),acquiredAt:since+'T12:00:00+07:00'},contact={name:'Trial synthetic',phone:'090111'+String(seq++).padStart(4,'0'),email:'',request:'Tủ bếp'};const r=await commit(item,p,peers[0],contact);const customerId=(await db.query('SELECT customer_id FROM crm_leads WHERE id=$1',[r.leadId])).rows[0].customer_id;return{...r,customerId,item,p};};
 const qualify=async(id,status='QUALIFIED')=>{const q=await query('crm_lead_quality_read',[admin,company,id]);return query('crm_lead_quality_record',[admin,company,id,randomUUID(),q.revision,q.contextVersion,{status,contactVerified:status==='QUALIFIED',demandMatches:status==='QUALIFIED',serviceAreaVerified:status==='QUALIFIED',evidence:'Verified synthetic customer facts in isolated PostgreSQL.'}]);};
 await t.test('private trial tables and pure helpers deny public/direct access',async()=>{for(const role of ['anon','authenticated','service_role']){await db.query('SET ROLE '+role);await assert.rejects(db.query('SELECT * FROM marketing_lead_trials'),e=>e.code==='42501');await assert.rejects(db.query('SELECT marketing_trial_identity_inventory($1)',[company]),e=>e.code==='42501');if(role!=='service_role')await assert.rejects(query('marketing_lead_trial_list',[admin,company],db),e=>e.code==='42501');await db.query('RESET ROLE');}await assert.rejects(query('marketing_lead_trial_list',[sales,company]),e=>e.code==='42501');});
 await t.test('registration records every account, idempotent request and thirty local days',async()=>{await db.query("INSERT INTO fb_ad_accounts VALUES('act_88',$1,true,NULL,'synthetic')",[company]);const key=randomUUID(),a=await set(trial,config,admin,company,key),b=await set(trial,config,admin,company,key);assert.deepEqual(a.account_ids,['act_77','act_88']);assert.equal(b.replayed,true);await assert.rejects(set(trial,{...config,name:'Changed with stale version'}),e=>e.code==='40001');await assert.rejects(set(randomUUID(),{...config,until:since}),e=>e.code==='22023');});
 await t.test('cross-company concurrent same UUID cannot overwrite the winner',async()=>{const who=randomUUID(),id=randomUUID();await db.query("INSERT INTO users VALUES($1,$2,$3,'admin',true)",[who,other,tenant]);await db.query("INSERT INTO fb_ad_accounts VALUES('act_99',$1,true,NULL,'synthetic')",[other]);const rs=await Promise.allSettled([set(id,config,admin,company,randomUUID(),peers[0]),set(id,{...config,name:'Other company'},who,other,randomUUID(),peers[1])]);assert.equal(rs.filter(x=>x.status==='fulfilled').length,1);assert.equal(rs.find(x=>x.status==='rejected').reason.code,'42501');const winner=rs.find(x=>x.status==='fulfilled').value;const row=(await db.query('SELECT * FROM marketing_lead_trials WHERE id=$1',[id])).rows[0];assert.equal(row.company_id,winner.company_id);assert.equal(row.name,winner.name);assert.equal((await db.query('SELECT count(*)::int n FROM marketing_lead_trial_events WHERE trial_id=$1',[id])).rows[0].n,1);});
 let qualified;
 await t.test('real receipt, quality, identity and all-account spend reach one observed report',async()=>{qualified=await fresh();await qualify(qualified.leadId);for(const account of ['act_77','act_88']){const run=await query('marketing_spend_begin',[account,company,since,date(0)]);await query('marketing_spend_finish',[run.id,company,{accountId:account,currency:'VND',timezone:'Asia/Ho_Chi_Minh',source:'META_ACCOUNT_INSIGHTS_V1',since,until:date(0),totalVnd:500000,days:[{date:since,amountVnd:250000},{date:date(0),amountVnd:250000}]},null]);}const r=reportTrial(await snapshot());assert.equal(r.spend.spendVnd,500000);assert.equal(r.observed.qualified,1);assert.equal(r.costPerQualifiedLeadVnd,null);assert.equal(r.coverage.provider,'MISSING');assert.equal(r.items[0].acquisitionLeadId,qualified.leadId);});
 await t.test('read context and inventory match650/654 while unqualified reads enroll nothing',async()=>{const pending=await fresh(),before=(await db.query('SELECT count(*)::int n FROM crm_lead_quality_source_versions')).rows[0].n;const s=await snapshot();assert.equal((await db.query('SELECT count(*)::int n FROM crm_lead_quality_source_versions')).rows[0].n,before);const q=await query('crm_lead_quality_read',[admin,company,qualified.leadId]);assert.equal(s.qualities.find(x=>x.leadId===qualified.leadId).contextVersion,q.contextVersion);const inventory=await query('crm_identity_review_snapshot',[admin,company]);assert.equal(s.identity.snapshotToken,inventory.snapshotToken);assert.equal(s.qualities.find(x=>x.leadId===pending.leadId).evidence,null);});
 await t.test('fresh rejected decision stays rejected with routing not ready',async()=>{const a=await fresh();await db.query('UPDATE crm_leads SET assigned_to=NULL WHERE id=$1',[a.leadId]);const q=await qualify(a.leadId,'REJECTED');assert.equal(q.status,'REJECTED');const r=reportTrial(await snapshot()).items.find(x=>x.acquisitionLeadId===a.leadId);assert.equal(r.status,'REJECTED');});
 await t.test('old Lead or Customer cannot be renewed by a current first touch',async()=>{const a=await fresh(),b=await fresh();await qualify(a.leadId);await qualify(b.leadId);await db.query("UPDATE crm_leads SET created_at=now()-interval '60 days' WHERE id=$1",[a.leadId]);await db.query("UPDATE customers SET created_at=now()-interval '60 days' WHERE id=$1",[b.item.r.customer_id||b.customerId]);const r=reportTrial(await snapshot());assert.equal(r.items.find(x=>x.acquisitionLeadId===a.leadId).status,'EXISTING');assert.equal(r.items.find(x=>x.acquisitionLeadId===b.leadId).status,'EXISTING');});
 await t.test('quality A-B-A stays stale and matches canonical650 context',async()=>{const a=await fresh();await qualify(a.leadId);await db.query("UPDATE crm_leads SET description='Changed' WHERE id=$1",[a.leadId]);await db.query("UPDATE crm_leads SET description='Tủ bếp' WHERE id=$1",[a.leadId]);const q=await query('crm_lead_quality_read',[admin,company,a.leadId]),s=await snapshot();assert.equal(q.needsRecheck,true);assert.equal(s.qualities.find(x=>x.leadId===a.leadId).contextVersion,q.contextVersion);assert.equal(reportTrial(s).items.find(x=>x.acquisitionLeadId===a.leadId).status,'PENDING');});
 await t.test('repeatable one-statement read does not mix a concurrently revoked qualification',async()=>{
  const a=await fresh();await qualify(a.leadId);
  const original=(await db.query("SELECT pg_get_functiondef('marketing_trial_quality_context(jsonb,jsonb,jsonb,jsonb,jsonb,boolean,jsonb)'::regprocedure) d")).rows[0].d;
  await db.query(original.replace(/BEGIN\r?\n/,'BEGIN\n PERFORM pg_sleep(0.08);\n'));
  try{
   const read=snapshot(peers[1]);let observed=false;
   for(let i=0;i<60;i++){const r=await db.query("SELECT count(*)::int n FROM pg_stat_activity WHERE wait_event='PgSleep' AND query LIKE 'SELECT marketing_lead_trial_snapshot%'");if(r.rows[0].n){observed=true;break;}await new Promise(r=>setTimeout(r,10));}
   assert.equal(observed,true);await qualify(a.leadId,'REJECTED');
   const before=reportTrial(await read).items.find(x=>x.acquisitionLeadId===a.leadId);assert.equal(before.status,'QUALIFIED');
  }finally{await db.query(original);}
  assert.equal(reportTrial(await snapshot()).items.find(x=>x.acquisitionLeadId===a.leadId).status,'REJECTED');
 });
 await t.test('disabled account and latest failed sync block spend, not zero-fill',async()=>{await db.query("UPDATE fb_ad_accounts SET bat=false WHERE ad_account_id='act_88'");assert.equal(reportTrial(await snapshot()).spend.spendVnd,null);await db.query("UPDATE fb_ad_accounts SET bat=true WHERE ad_account_id='act_88'");const run=await query('marketing_spend_begin',['act_88',company,since,date(0)]);await query('marketing_spend_finish',[run.id,company,null,'PROVIDER_UNAVAILABLE']);assert.equal(reportTrial(await snapshot()).spend.spendVnd,null);});
 await t.test('deleted Lead retains source/receipt and blocks its group',async()=>{const a=await fresh();await db.query('DELETE FROM crm_leads WHERE id=$1',[a.leadId]);const r=reportTrial(await snapshot());assert.ok(r.observed.unlinkedProofs>0||r.observed.unresolved>0);});
 await t.test('current tenant/actor revocation denies read and replay',async()=>{await db.query('UPDATE tenants SET is_active=false WHERE id=$1',[tenant]);await assert.rejects(snapshot(),e=>e.code==='42501');await db.query('UPDATE tenants SET is_active=true WHERE id=$1',[tenant]);await db.query('UPDATE users SET is_active=false WHERE id=$1',[admin]);await assert.rejects(set(),e=>e.code==='42501');await db.query('UPDATE users SET is_active=true WHERE id=$1',[admin]);});
};
