'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const {parseExport,csvRows,stamp,createSourceExport}=require('../src/modules/marketingAutomation/sourceExport');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const body=(csv='id,created_time,form_id,name\r\n90071992547409931234,2026-10-01T07:00:00+0700,456,"Private, name"\r\n')=>({requestId:id(4),contextVersion:'a'.repeat(64),pageId:'123',formId:'456',fileBase64:Buffer.from(csv).toString('base64'),delimiter:',',columns:{id:'id',createdAt:'created_time',formId:'form_id'},exportedAt:'2026-10-02T00:00:00Z',sourceReference:'Synthetic export file',sourceNote:'Synthetic filtered form export for isolated tests only.'});
test('server hashes exact bytes, preserves long IDs and strips all unused personal fields',()=>{const b=body(),x=parseExport(b);assert.equal(x.command.rows[0].leadgenId,'90071992547409931234');assert.equal(x.command.rows[0].acquiredAt,'2026-10-01T00:00:00.000Z');assert.equal(x.command.fileSha256,createHash('sha256').update(Buffer.from(b.fileBase64,'base64')).digest('hex'));assert.ok(!JSON.stringify(x).includes('Private'));assert.ok(!JSON.stringify(x).includes('fileBase64'));});
test('UTF16LE BOM, tabs, quoted newlines and doubled quotes parse without treating names as data',()=>{const b=body();b.delimiter='\t';const text='id\tcreated_time\tform_id\tname\r\n123\t2026-10-01T00:00:00Z\t456\t"A\nB ""C"""\r\n';b.fileBase64=Buffer.concat([Buffer.from([255,254]),Buffer.from(text,'utf16le')]).toString('base64');assert.equal(parseExport(b).command.encoding,'UTF-16LE');assert.equal(parseExport(b).command.rows.length,1);});
test('header-only file remains an explicit empty export; absent header is invalid',()=>{assert.equal(parseExport(body('id,created_time,form_id,name\n')).command.rows.length,0);assert.throws(()=>parseExport(body('')),e=>e.status===400);});
test('duplicates and out-of-order rows are retained for database comparison',()=>{const x=parseExport(body('id,created_time,form_id,name\n7,2026-10-01T00:00:00Z,456,A\n7,2026-10-01T00:00:00Z,456,B\n'));assert.equal(x.command.rows.length,2);});
test('optional absent form column uses declared form, never guesses another column',()=>{const b=body('id,created_time\n3,2026-10-01T00:00:00Z');b.columns.formId=null;assert.equal(parseExport(b).command.rows[0].formId,'456');});
for(const [label,value]of Object.entries({locale:'01/10/2026 08:00',offsetless:'2026-10-01T08:00:00',invalidDay:'2026-02-30T00:00:00Z',largeHour:'2026-10-01T24:00:00Z',seconds:'2026-10-01T00:00:60Z',offset:'2026-10-01T00:00:00+14:01',infinite:'infinity'}))test('reject ambiguous timestamp '+label,()=>assert.throws(()=>stamp(value),e=>e.status===400));
for(const [label,text]of Object.entries({duplicateHeader:'id,id,created_time\n1,1,2026-10-01T00:00:00Z',badWidth:'id,created_time,form_id,name\n1,2026-10-01T00:00:00Z,456',badQuote:'id,created_time,form_id,name\n1,2026-10-01T00:00:00Z,456,"unclosed',precisionLost:'id,created_time,form_id,name\n9.007E18,2026-10-01T00:00:00Z,456,A',formula:'id,created_time,form_id,name\n=1+2,2026-10-01T00:00:00Z,456,A',nul:'id,created_time,form_id,name\n1,2026-10-01T00:00:00Z,456,A\0'}))test('reject malformed file '+label,()=>assert.throws(()=>parseExport(body(text)),e=>e.status===400));
test('invalid encodings, base64, client supplied trust fields and oversized inputs rejected',()=>{for(const patch of [{fileBase64:'%%%='},{fileBase64:Buffer.from([255,255,255]).toString('base64')},{fileSha256:'b'.repeat(64)},{providerCoverage:'COMPLETE'},{fileBase64:Buffer.alloc(1048577).toString('base64')},{columns:{id:'id',createdAt:'id',formId:null}}])assert.throws(()=>parseExport({...body(),...patch}),e=>e.status===400);assert.throws(()=>csvRows('id\n'+'7\n'.repeat(5001),','),e=>e.status===400);});
function harness(options={}){let calls=[];const env={VPT_MARKETING_SOURCE_EXPORT:'1',VPT_MARKETING_TRIAL_REPORT:'1',...options.env};const service=createSourceExport({env,isPrimary:()=>options.primary!==false,db:{rpc:async(name,args)=>{calls.push({name,args});if(options.error)return{error:{code:options.error}};return{data:options.data||{policy:'SOURCE_EXPORT_COMPARISON_V1',actorId:id(1),companyId:id(2),trialId:id(3),providerCoverage:'UNVERIFIED',allowBudgetExecution:false,requestId:args.p_request,fileSha256:args.p_command?.fileSha256,replayed:false,contextVersion:'a'.repeat(64),pageId:'123',formId:'456',recordedAt:'2026-10-02T00:00:00Z',censusRunId:id(8),registryDigest:'b'.repeat(64),pagesDigest:'c'.repeat(64),sinceAt:'2026-09-30T17:00:00Z',untilExclusive:'2026-10-01T17:00:00Z',fileBytes:args.p_command?.fileBytes,normalizedRowsDigest:'d'.repeat(64),exportedAt:'2026-10-02T00:00:00Z',sourceReference:'Synthetic file',sourceNote:'Synthetic evidence only.',status:'MATCHED_EXPORTED_IDS',comparison:{rows:1,inPeriodRows:1,outsidePeriodRows:0,uniqueExportIds:1,duplicateRows:0,observedIds:1,matched:1,notInExport:0,notObserved:0,conflicts:0,differences:[]}}};}}});const req={user:{userId:id(1)},query:{company_id:id(2)},params:{trialId:id(3)},body:body()},res={code:200,set(){},status(n){this.code=n;return this;},json(x){this.value=x;return this;}};return{calls,service,req,res};}
test('service is primary/default-off and takes current actor from session; strips unused fields before RPC',async()=>{for(const options of [{primary:false},{env:{VPT_MARKETING_SOURCE_EXPORT:'0'}}]){const h=harness(options);await h.service(h.req,h.res,true);assert.equal(h.res.code,503);assert.equal(h.calls.length,0);}const h=harness();await h.service(h.req,h.res,true);assert.equal(h.res.code,200);assert.equal(h.calls[0].args.p_actor,id(1));assert.ok(!JSON.stringify(h.calls).includes('Private'));});
test('invalid scope/filter and SQL failures never return an empty successful comparison',async()=>{for(const [code,status]of [['42501',403],['40001',409],['23505',409],['22023',400],['XX000',503]]){const h=harness({error:code});await h.service(h.req,h.res);assert.equal(h.res.code,status);}const h=harness();h.req.query.page_id='999';await h.service(h.req,h.res);assert.equal(h.res.code,400);assert.equal(h.calls.length,0);});
test('response with wrong actor or invented provider completeness is rejected',async()=>{for(const delta of [{actorId:id(90)},{providerCoverage:'COMPLETE'},{allowBudgetExecution:true}]){const h=harness({data:{policy:'SOURCE_EXPORT_COMPARISON_V1',actorId:id(1),companyId:id(2),trialId:id(3),providerCoverage:'UNVERIFIED',allowBudgetExecution:false,...delta}});await h.service(h.req,h.res);assert.equal(h.res.code,503);}});
module.exports={body};

test('export read deduplicates form inventory, keeps stale evidence historical and strips unused fields',async()=>{
 const recorded=harness();await recorded.service(recorded.req,recorded.res,true);const saved=recorded.res.value;
 const data={policy:'SOURCE_EXPORT_COMPARISON_V1',actorId:id(1),companyId:id(2),trialId:id(3),providerCoverage:'UNVERIFIED',allowBudgetExecution:false,
  contextVersion:'a'.repeat(64),asOf:'2026-10-03T00:00:00Z',registry:{status:'CURRENT',declaration:{entries:[{kind:'META_LEAD_ADS',pageId:'123',formId:'456'},{kind:'META_LEAD_ADS',pageId:'123',formId:'456'},{kind:'WEBSITE',pageId:null,formId:null}]}},
  census:{run:{id:id(8),state:'SCANNED',since:'2026-09-30T17:00:00Z',until:'2026-10-01T17:00:00Z',scopeCurrent:true,witness:{status:'TRAVERSED',pagesDigest:'c'.repeat(64)}},measuredEvidence:{count:1,digest:'d'.repeat(64)}},exports:[{currentStatus:'STALE_AUTHORITY',receipt:saved}],privateToken:'synthetic-secret'};
 const h=harness({data});await h.service(h.req,h.res);
 assert.equal(h.res.code,200);assert.deepEqual(h.res.value.forms,[{pageId:'123',formId:'456'}]);assert.equal(h.res.value.census.measuredCount,1);
 assert.equal(h.res.value.exports[0].currentStatus,'STALE_AUTHORITY');assert.equal(h.res.value.providerCoverage,'UNVERIFIED');assert.ok(!JSON.stringify(h.res.value).includes('synthetic-secret'));
 for(const change of [x=>x.registry.declaration.entries[0].formId='invalid',x=>x.census.run.witness.pagesDigest='bad',x=>x.exports[0].currentStatus='CURRENT_BUT_UNCHECKED',x=>x.exports[0].receipt.companyId=id(99)]){
  const bad=structuredClone(data);change(bad);const invalid=harness({data:bad});await invalid.service(invalid.req,invalid.res);assert.equal(invalid.res.code,503);
 }
});

test('export difference rows preserve the reason without exposing contact data',async()=>{
 const recorded=harness();await recorded.service(recorded.req,recorded.res,true);const data=recorded.res.value;
 data.status='DISCREPANCIES';data.comparison.notObserved=1;data.comparison.matched=0;
 data.comparison.differences=[{id:'99',reason:'NOT_OBSERVED',exportedForm:'456',observedForm:null,exportedEpoch:1790812800,observedEpoch:null,phone:'synthetic-private'}];
 const h=harness({data});await h.service(h.req,h.res);assert.equal(h.res.code,200);
 assert.equal(h.res.value.comparison.differences[0].reason,'NOT_OBSERVED');assert.ok(!JSON.stringify(h.res.value).includes('synthetic-private'));
});
test('UI pending survives reload in the same scope without storing file bytes, and fails before POST if storage fails',async()=>{const ui=await import('../../frontend/src/components/marketing/sourceExportState.mjs');const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};const b=body(),{fileBase64,...request}=b,p={fileHash:'b'.repeat(64),request};ui.storePending(storage,id(1),id(2),id(3),p);assert.deepEqual(ui.readPending(storage,id(1),id(2),id(3)),p);assert.equal(ui.readPending(storage,id(90),id(2),id(3)),null);assert.ok(![...map.values()].join('').includes('fileBase64'));assert.throws(()=>ui.storePending(storage,id(1),id(2),id(3),{...p,request:{...request,fileBase64}}));assert.throws(()=>ui.storePending({...storage,setItem(){throw Error('quota');}},id(1),id(2),id(3),p));ui.clearPending(storage,id(1),id(2),id(3));assert.equal(ui.readPending(storage,id(1),id(2),id(3)),null);});
test('UI rejects receipt from another request, file, actor or evidence context',async()=>{const ui=await import('../../frontend/src/components/marketing/sourceExportState.mjs'),b=body(),p={fileHash:'b'.repeat(64),request:b};const x={policy:'SOURCE_EXPORT_COMPARISON_V1',actorId:id(1),companyId:id(2),trialId:id(3),contextVersion:b.contextVersion,providerCoverage:'UNVERIFIED',allowBudgetExecution:false,requestId:b.requestId,fileSha256:p.fileHash,replayed:true,status:'MATCHED_EXPORTED_IDS',comparison:{differences:[]}};assert.equal(ui.exportReceipt(x,p,id(1),id(2),id(3)),x);for(const patch of [{actorId:id(9)},{requestId:id(8)},{fileSha256:'c'.repeat(64)},{contextVersion:'d'.repeat(64)},{providerCoverage:'COMPLETE'},{allowBudgetExecution:true}])assert.throws(()=>ui.exportReceipt({...x,...patch},p,id(1),id(2),id(3)));});
