'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{randomUUID,createHash}=require('node:crypto');
module.exports=async(t,{db,peers,query,admin,sales,company,other,region})=>{
 await db.query('CREATE TABLE IF NOT EXISTS projects(id uuid PRIMARY KEY)');
 for(const file of ['22_events.sql'])await db.query(fs.readFileSync(path.resolve(__dirname,'../../database',file),'utf8'));
 await db.query('ALTER TABLE crm_events ADD COLUMN company_id uuid');
 for(const file of ['245_crm_events_module.sql','506_crm_events_occurrence_dates.sql','508_crm_events_module_custom.sql','663_crm_survey_availability.sql']){const sql=fs.readFileSync(path.resolve(__dirname,'../../database',file),'utf8');await db.query(sql);await db.query(sql);}
 const lead=randomUUID(),psid='9741001';await db.query("INSERT INTO crm_leads(id,title,company_id,region_id,assigned_to) VALUES($1,'Synthetic survey Lead',$2,$3,$4)",[lead,company,region,sales]);await db.query("INSERT INTO facebook_contacts(page_id,psid,lead_id) VALUES('123',$1,$2)",[psid,lead]);
 const msg={pageId:'123',psid,mid:'survey-start',direction:'inbound',intent:'MESSAGE',content:'Synthetic request only',attachments:[],sentAt:new Date().toISOString()};await query('crm_care_receive',[JSON.stringify([{...msg,payloadHash:createHash('sha256').update(JSON.stringify(msg)).digest('hex')}])]);
 const thread=(await db.query("SELECT id FROM crm_care_threads WHERE psid=$1",[psid])).rows[0].id;
 const start=Math.floor((Date.now()+3*86400000)/86400000)*86400000+2*3600000,iso=n=>new Date(n).toISOString(),from=iso(start-3600000),to=iso(start+86400000);
 const doc={calendarSource:'CRM_COMPLETE',externalCalendarCoverage:'ALL_BUSY_IN_CRM',sourceReference:'Synthetic complete staff calendar coverage; not production',validUntil:iso(start+2*86400000),bufferMinutes:0,slots:[{startsAt:iso(start),endsAt:iso(start+3600000)}]};
 const roster=(who=sales)=>query('crm_survey_roster_read',[admin,company,who,region]);
 const command=async(d=doc,who=sales)=>({action:'SAVE',staffId:who,regionId:region,expectedRevision:(await roster(who)).revision,reason:'Synthetic calendar source verification',document:d});
 const save=async(d=doc,who=sales)=>query('crm_survey_roster_change',[admin,company,randomUUID(),await command(d,who)]);
 const available=(who=admin,cid=company)=>query('crm_survey_availability',[who,cid,thread,from,to]);
 const event=async({role='assignee',eventCompany=company,status='planned',a=start,b=start+3600000,allDay=false,days=null}={})=>{
  const id=randomUUID();await db.query("INSERT INTO crm_events(id,title,company_id,start_time,end_time,all_day,status,assignee_id,created_by,module,occurrence_dates) VALUES($1,'PRIVATE other customer location',$2,$3,$4,$5,$6,$7,$8,'custom-work',$9)",[id,eventCompany,iso(a),b===null?null:iso(b),allDay,status,role==='assignee'?sales:null,role==='creator'?sales:null,days]);
  if(role==='participant')await db.query("INSERT INTO crm_event_participants(event_id,user_id,status) VALUES($1,$2,'pending')",[id,sales]);return id;
 };
 const remove=id=>db.query('DELETE FROM crm_events WHERE id=$1',[id]);
 await t.test('survey sources are empty by default and private for every application role',async()=>{assert.equal((await available()).status,'NO_CONFIRMED_OPTION');for(const role of ['anon','authenticated','service_role']){await db.query('SET ROLE '+role);try{await assert.rejects(db.query('SELECT * FROM crm_survey_rosters'),e=>e.code==='42501');await assert.rejects(db.query('DELETE FROM crm_survey_roster_events'),e=>e.code==='42501');if(role!=='service_role')await assert.rejects(query('crm_survey_availability',[admin,company,thread,from,to],db),e=>e.code==='42501')}finally{await db.query('RESET ROLE')}}await assert.rejects(available(sales),e=>e.code==='42501');await assert.rejects(available(admin,other),e=>e.code==='42501')});
 await t.test('survey roster publication is atomic, versioned and idempotent under concurrency',async()=>{const cmd=await command(),key=randomUUID();const rs=await Promise.all([query('crm_survey_roster_change',[admin,company,key,cmd],peers[0]),query('crm_survey_roster_change',[admin,company,key,cmd],peers[1])]);assert.equal(rs.filter(x=>x.replayed).length,1);assert.equal((await roster()).revision,1);await assert.rejects(query('crm_survey_roster_change',[admin,company,randomUUID(),cmd]),e=>e.code==='40001');await assert.rejects(query('crm_survey_roster_change',[admin,company,key,{...cmd,reason:'Another different synthetic reason'}]),e=>e.code==='23505');await peers[0].query('BEGIN');await query('crm_survey_roster_change',[admin,company,randomUUID(),await command()],peers[0]);await peers[0].query('ROLLBACK');assert.equal((await roster()).revision,1);const x=await available();assert.equal(x.status,'AVAILABLE_SNAPSHOT');assert.equal(x.items.length,1);assert.equal(x.reservationMade,false);assert.equal(x.customerConfirmationRequired,true);assert.ok(x.items[0].snapshotExpiresAt)});
 await t.test('survey source rejects missing external coverage, overlapping slots, bad expiry and foreign staff',async()=>{for(const d of[{...doc,externalCalendarCoverage:'UNKNOWN'},{...doc,slots:[...doc.slots,...doc.slots]},{...doc,validUntil:iso(Date.now()-1000)},{...doc,slots:[{startsAt:iso(start),endsAt:iso(start+60000)}]}])await assert.rejects(save(d),e=>e.code==='22023');const u=randomUUID();await db.query("INSERT INTO users(id,company_id,tenant_id,role,is_active) SELECT $1,$2,tenant_id,'sales',true FROM companies WHERE id=$2",[u,other]);await assert.rejects(save(doc,u),e=>e.code==='42501')});
 await t.test('survey busy scan covers all three person links across companies and custom modules without leaking event details',async()=>{for(const role of ['assignee','creator','participant']){const id=await event({role,eventCompany:other,status:null});let a=await available();assert.equal(a.items.length,0);assert.equal(a.busyExcluded,1);assert.equal(JSON.stringify(a).includes('PRIVATE'),false);await db.query("UPDATE crm_events SET status='unknown-state' WHERE id=$1",[id]);assert.equal((await available()).items.length,0);await db.query("UPDATE crm_events SET status='cancelled' WHERE id=$1",[id]);assert.equal((await available()).items.length,1);await remove(id)}});
 await t.test('survey declines only remove participant occupancy and exact interval boundaries respect travel buffer',async()=>{const p=await event({role:'participant'});await db.query("UPDATE crm_event_participants SET status='declined' WHERE event_id=$1",[p]);assert.equal((await available()).items.length,1);await db.query('UPDATE crm_event_participants SET status=NULL WHERE event_id=$1',[p]);assert.equal((await available()).items.length,0);await remove(p);const id=await event({a:start-3600000,b:start});assert.equal((await available()).items.length,1);await save({...doc,bufferMinutes:30});assert.equal((await available()).items.length,0);await remove(id);await save()});
 await t.test('survey blocks whole VN days, discrete dates, overnight, unknown end and null all-day semantics',async()=>{for(const spec of[{allDay:true,a:start+3*3600000,b:start+4*3600000},{days:[iso(start+7*3600000).slice(0,10)],a:start+3*86400000,b:start+4*86400000},{a:start-12*3600000,b:start+3600000},{a:start-5*86400000,b:null},{a:start+3*86400000,b:start+4*86400000,allDay:null}]){const id=await event(spec);assert.equal((await available()).items.length,0);await remove(id)}const id=await event({days:[iso(start+7*3600000+2*86400000).slice(0,10)]});assert.equal((await available()).items.length,1);await remove(id)});
 await t.test('survey never truncates old participant calendars at500 or1000 rows and refreshes versions after calendar edits',async()=>{const v=(await available()).items[0].version;await db.query("INSERT INTO crm_events(id,title,company_id,start_time,end_time,all_day,status) SELECT gen_random_uuid(),'synthetic bulk',$1,$2::timestamptz-interval '2 hours',$2::timestamptz-interval '1 hour',false,'planned' FROM generate_series(1,1100)",[other,iso(start)]);await db.query("INSERT INTO crm_event_participants(event_id,user_id,status) SELECT id,$1,'confirmed' FROM crm_events WHERE title='synthetic bulk'",[sales]);assert.notEqual((await available()).items[0].version,v);const id=await event({role:'participant',eventCompany:other});assert.equal((await available()).items.length,0);await remove(id);await db.query("DELETE FROM crm_events WHERE title='synthetic bulk'")});
 await t.test('survey rechecks current source expiry, staff membership and source confirmer rights',async()=>{await db.query("UPDATE crm_survey_rosters SET document=jsonb_set(document,'{validUntil}',to_jsonb((clock_timestamp()-interval '1 minute')::text))");assert.equal((await available()).items.length,0);await save();await db.query('DELETE FROM user_company_regions WHERE user_id=$1 AND region_id=$2',[sales,region]);assert.equal((await available()).status,'CARE_OR_ROUTING_UNAVAILABLE');await db.query('INSERT INTO user_company_regions VALUES($1,$2)',[sales,region]);const second=randomUUID();await db.query("INSERT INTO users(id,company_id,tenant_id,role,is_active) SELECT $1,id,tenant_id,'admin',true FROM companies WHERE id=$2",[second,company]);await db.query('UPDATE users SET is_active=false WHERE id=$1',[admin]);try{const r=await available(second);assert.equal(r.items.length,0);assert.equal(r.issues[0].reason,'STAFF_OR_SOURCE_AUTHORITY_UNAVAILABLE')}finally{await db.query('UPDATE users SET is_active=true WHERE id=$1',[admin])}});
 await t.test('survey stop and takeover never produce a bookable candidate',async()=>{for(const mode of ['HUMAN_ACTIVE','HUMAN_REQUESTED','OPTED_OUT']){await db.query('UPDATE crm_care_threads SET mode=$2 WHERE id=$1',[thread,mode]);const r=await available();assert.equal(r.status,'CARE_OR_ROUTING_UNAVAILABLE');assert.deepEqual(r.items,[])}await db.query("UPDATE crm_care_threads SET mode='WAITING' WHERE id=$1",[thread])});
 await t.test('survey invalid infinite occurrence dates cannot become free time',async()=>{for(const days of [['infinity'],['-infinity'],[null]]){const id=await event({days});assert.equal((await available()).items.length,0);await remove(id)}});
 const extraStaff=async()=>{const id=randomUUID();await db.query("INSERT INTO users(id,company_id,tenant_id,role,is_active) SELECT $1,id,tenant_id,'sales',true FROM companies WHERE id=$2",[id,company]);await db.query('INSERT INTO user_company_regions VALUES($1,$2)',[id,region]);await save(doc,id);return id;};
 const waitBlocked=async pid=>{const owner=(await db.query('SELECT pg_backend_pid() p')).rows[0].p;for(let n=0;n<100;n++){if((await db.query('SELECT $1::int=ANY(pg_blocking_pids($2)) b',[owner,pid])).rows[0].b)return;await db.query('SELECT pg_sleep(0.02)')}throw Error('availability did not reach the held staff lock')};
 await t.test('survey uses one calendar inventory when an event is reassigned during the read',async()=>{const staffA=await extraStaff(),staffB=await extraStaff(),first=[staffA,staffB].sort()[0],second=[staffA,staffB].sort()[1],id=await event();await db.query('UPDATE crm_events SET assignee_id=$2 WHERE id=$1',[id,second]);const pid=(await peers[1].query('SELECT pg_backend_pid() p')).rows[0].p;await db.query('BEGIN');await db.query('UPDATE users SET role=role WHERE id=$1',[first]);const pending=query('crm_survey_availability',[admin,company,thread,from,to],peers[1]);try{await waitBlocked(pid);await peers[2].query('SELECT 1');await db.query('UPDATE crm_events SET assignee_id=$2 WHERE id=$1',[id,first]);}finally{await db.query('COMMIT')}const r=await pending;assert.ok(r.items.some(x=>x.staffId===first));assert.equal(r.items.some(x=>x.staffId===second),false);await remove(id);await db.query('DELETE FROM crm_survey_rosters WHERE staff_id=ANY($1)',[[staffA,staffB]])});
 await t.test('survey drops all options when a staff lock outlives the30second snapshot',async()=>{const staffId=await extraStaff(),pid=(await peers[1].query('SELECT pg_backend_pid() p')).rows[0].p;await db.query('BEGIN');await db.query('UPDATE users SET role=role WHERE id=$1',[staffId]);const pending=query('crm_survey_availability',[admin,company,thread,from,to],peers[1]);try{await waitBlocked(pid);await db.query('SELECT pg_sleep(30.2)')}finally{await db.query('COMMIT')}const r=await pending;assert.equal(r.status,'NO_CONFIRMED_OPTION');assert.deepEqual(r.items,[]);assert.ok(r.issues.some(x=>x.reason==='SOURCE_OR_SNAPSHOT_EXPIRED'));await db.query('DELETE FROM crm_survey_rosters WHERE staff_id=$1',[staffId])});
 await t.test('survey bounded query returns no partial option list and database read errors never become free time',async()=>{await assert.rejects(query('crm_survey_availability',[admin,company,thread,from,iso(start+16*86400000)]),e=>e.code==='22023');const extras=[];for(let k=0;k<4;k++){const u=randomUUID();extras.push(u);await db.query("INSERT INTO users(id,company_id,tenant_id,role,is_active) SELECT $1,id,tenant_id,'sales',true FROM companies WHERE id=$2",[u,company]);await db.query('INSERT INTO user_company_regions VALUES($1,$2)',[u,region]);await save({...doc,slots:Array.from({length:64},(_,i)=>({startsAt:iso(start+i*900000),endsAt:iso(start+(i+1)*900000)}))},u)}const r=await available();assert.equal(r.status,'NARROW_RANGE_REQUIRED');assert.deepEqual(r.items,[]);await db.query('DELETE FROM crm_survey_rosters WHERE staff_id=ANY($1)',[extras]);await db.query('BEGIN');await db.query('ALTER TABLE crm_events RENAME TO temporary_missing_calendar');try{await assert.rejects(query('crm_survey_availability',[admin,company,thread,from,to],db),e=>e.code==='42P01')}finally{await db.query('ROLLBACK')}});
};
