'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {createSurveyHandoffs}=require('../src/modules/marketingAutomation/surveyHandoffs');
const company=randomUUID(),actor=randomUUID(),proposal=randomUUID(),request=randomUUID(),version='a'.repeat(32),at='2027-01-01T02:00:00Z';
const result={proposalId:proposal,companyId:company,requestId:request,actorId:actor,state:'ACKNOWLEDGED',receivedVersion:version,messageCount:5,receivedAt:at,replayed:false,aiMaySend:false};
const body={companyId:company,requestId:request,command:{proposalId:proposal,expectedVersion:version}};
async function run({op='ack',input=body,data=result,error,user={id:actor},env={VPT_SURVEY_HANDOFFS:'1'},isPrimary=()=>true,afterRpc=()=>{}}={}){
 const calls=[],res={code:200,headers:{},set(k,v){this.headers[k]=v;return this},status(n){this.code=n;return this},json(x){this.body=x;return this}};
 await createSurveyHandoffs({env,isPrimary,db:{rpc:async(...args)=>{calls.push(args);afterRpc();return{data,error}}}}).handle({user,body:input,query:input},res,op);return{...res,calls};
}
test('handoff is default-off and primary-only',async()=>{for(const options of [{env:{}},{isPrimary:()=>false}]){const r=await run(options);assert.equal(r.code,503);assert.equal(r.calls.length,0)}});
test('handoff actor is server-established and receipt has exact request, scope, recipient and version',async()=>{const r=await run();assert.equal(r.code,200);assert.equal(r.headers['Cache-Control'],'no-store');assert.deepEqual(r.calls[0],['crm_survey_handoff_ack',{p_actor:actor,p_company:company,p_request:request,p_command:body.command}]);assert.equal((await run({user:{id:actor,userId:randomUUID()}})).code,403)});
test('handoff rejects actor, send, booking, takeover, proxy or unpaired cursor inputs before storage',async()=>{for(const options of [{input:{...body,actorId:actor}},{input:{...body,command:{...body.command,recipientId:actor}}},{op:'send'},{op:'book'},{op:'queue',input:{companyId:company,state:'PENDING',after:proposal}},{op:'read',input:{companyId:company,proposalId:proposal,version}}]){const r=await run(options);assert.equal(r.code,400);assert.equal(r.calls.length,0)}});
test('handoff never passes secret fields or wrong/stale receipts through',async()=>{for(const patch of [{companyId:randomUUID()},{actorId:randomUUID()},{requestId:randomUUID()},{proposalId:randomUUID()},{receivedVersion:'b'.repeat(32)},{confirmationToken:'private'},{aiMaySend:true}])assert.equal((await run({data:{...result,...patch}})).code,503)});
test('handoff errors preserve permission, stale and unknown distinctions without source details',async()=>{for(const [code,status] of [['42501',403],['40001',409],['23505',409],['22023',400],['XX000',503]]){const r=await run({error:{code,message:'SECRET'}});assert.equal(r.code,status);assert.equal(JSON.stringify(r.body).includes('SECRET'),false)}});
test('primary change after database commit is uncertain and exact persisted request remains retryable',async()=>{let primary=true;assert.equal((await run({isPrimary:()=>primary,afterRpc:()=>{primary=false}})).code,503);assert.equal((await run({data:{...result,replayed:true}})).code,200)});
test('queue scope, counts and opaque unavailable rows are validated',async()=>{const q={companyId:company,state:'PENDING',items:[{proposalId:proposal,state:'PENDING',createdAt:at,scopeReady:false,appointment:null,title:null,careMode:null}],counts:{PENDING:1,ACKNOWLEDGED:0},unavailableCount:1,version,nextAfter:null,observedAt:at,aiMaySend:false};const options={op:'queue',input:{companyId:company,state:'PENDING'},data:q};assert.equal((await run(options)).code,200);for(const patch of [{companyId:randomUUID()},{counts:null},{items:[{...q.items[0],title:'foreign data'}]}])assert.equal((await run({...options,data:{...q,...patch}})).code,503)});
