'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {proposalConsoleView,createProposalConsole}=require('../src/modules/marketingAutomation/surveyProposalConsole');
const {id}=require('./marketingAutomation.trial.fixture');
function fixture(){return{policy:'SURVEY_PROPOSAL_CONSOLE_V1',companyId:id(1),actorId:id(2),threadId:id(3),asOf:'2026-10-03T00:00:00Z',careMode:'WAITING',deliveryBusy:false,total:1,canConfirmCustomer:false,canResend:false,aiMaySend:false,
 items:[{proposalId:id(4),createdAt:'2026-10-03T00:00:00Z',scopeReady:true,state:'OPEN',expiresAt:'2026-10-03T00:15:00Z',appointment:{startsAt:'2027-01-01T01:00:00Z',endsAt:'2027-01-01T02:00:00Z',staffName:'Synthetic staff',location:'Synthetic location',timeZone:'Asia/Ho_Chi_Minh'},delivery:{state:'QUEUED',conflict:false,hasProblem:false,blockedReason:null},booking:null,outcomes:[]}]};}
test('console separates proposal, transport acceptance, booking and customer outcome',()=>{for(const state of ['QUEUED','SENDING','SENT','UNCERTAIN']){const x=fixture();x.items[0].delivery.state=state;const r=proposalConsoleView(x);assert.equal(r.items[0].state,'OPEN');assert.equal(r.items[0].booking,null);assert.equal(r.canResend,false);}const x=fixture();x.items[0].state='BOOKED';x.items[0].booking={eventId:id(5),status:'BOOKED_HANDOFF_PENDING'};x.items[0].outcomes=[{kind:'BOOKED',state:'UNCERTAIN',conflict:false}];assert.equal(proposalConsoleView(x).items[0].outcomes[0].state,'UNCERTAIN');});
test('projection never returns private transport bytes or arbitrary source error details',()=>{const x=fixture();x.token='PRIVATE';x.items[0].confirmationToken='PRIVATE';x.items[0].appointment.psid='PRIVATE';x.items[0].delivery.blockedReason='PRIVATE SOURCE ERROR';x.items[0].delivery.payload={token:'PRIVATE'};const r=proposalConsoleView(x);assert.equal(r.items[0].delivery.blockedReason,'OTHER');assert.ok(!JSON.stringify(r).includes('PRIVATE'));});
test('out-of-scope history is opaque and cannot carry stale address or state',()=>{const x=fixture();x.items[0]={proposalId:id(4),createdAt:x.asOf,scopeReady:false,state:null,expiresAt:null,appointment:null,delivery:null,booking:null,outcomes:null};assert.equal(proposalConsoleView(x).items[0].appointment,null);x.items[0].appointment={location:'PRIVATE'};assert.throws(()=>proposalConsoleView(x));});
for(const [name,change]of[['partial page',x=>x.total=2],['invalid actor',x=>x.actorId='bad'],['confirmed without booking',x=>x.items[0].state='BOOKED'],['malformed dates',x=>x.items[0].appointment.endsAt='bad'],['duplicate outcome',x=>x.items[0].outcomes=Array(2).fill({kind:'BOOKED',state:'QUEUED',conflict:false})],['confirm capability',x=>x.canConfirmCustomer=true]])test('reject '+name,()=>{const x=fixture();change(x);assert.throws(()=>proposalConsoleView(x));});
const request=()=>({user:{userId:id(2)},query:{companyId:id(1),threadId:id(3)}}),response=()=>({code:200,set(){return this;},status(s){this.code=s;return this;},json(x){this.body=x;return this;}});
test('console derives authenticated scope and stays default off/primary only',async()=>{
 for(const cfg of [{env:{}},{env:{VPT_SURVEY_PROPOSAL_CONSOLE:'1'},isPrimary:()=>false}]){const r=response();await createProposalConsole({db:{rpc:()=>assert.fail()},isPrimary:()=>true,...cfg})(request(),r);assert.equal(r.code,503);}
 let called;const r=response();await createProposalConsole({db:{rpc:async(n,a)=>{called={n,a};return{data:fixture()};}},isPrimary:()=>true,env:{VPT_SURVEY_PROPOSAL_CONSOLE:'1'}})(request(),r);assert.equal(r.code,200);assert.deepEqual(called.a,{p_actor:id(2),p_company:id(1),p_thread:id(3)});
});
test('wrong response scope and permission/source failures cannot show stale history',async()=>{
 for(const result of [{data:{...fixture(),threadId:id(6)}},{error:{code:'42501'}},{error:{code:'XX000'}}]){const r=response();await createProposalConsole({db:{rpc:async()=>result},isPrimary:()=>true,env:{VPT_SURVEY_PROPOSAL_CONSOLE:'1'}})(request(),r);assert.ok([403,503].includes(r.code));assert.equal(r.body.items,undefined);}
});
test('frontend validates scope, Vietnam clock and impossible dates',async()=>{const s=await import('../../frontend/src/components/facebook/surveyProposalState.mjs');const x=proposalConsoleView(fixture());assert.equal(s.proposalList(x,id(1),id(2),id(3)),x);assert.throws(()=>s.proposalList(x,id(1),id(2),id(8)));assert.equal(s.vietnamInstant('2027-01-01T08:00'),'2027-01-01T01:00:00.000Z');assert.throws(()=>s.vietnamInstant('2027-02-30T08:00'));});
test('durable retry keeps the exact request and scope across reload; receipt mismatch never clears it',async()=>{
 const s=await import('../../frontend/src/components/facebook/surveyProposalState.mjs'),map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};
 const p={actorId:id(2),companyId:id(1),threadId:id(3),requestId:id(6),command:{threadId:id(3),optionId:'a'.repeat(32),startsAt:'2027-01-01T01:00:00Z',endsAt:'2027-01-01T02:00:00Z',location:'Synthetic location'}};
 s.savePendingProposal(storage,p);assert.deepEqual(s.readPendingProposal(storage,id(2),id(1),id(3)),p);assert.equal(s.readPendingProposal(storage,id(7),id(1),id(3)),null);
 const r={companyId:id(1),threadId:id(3),proposalId:id(4),requestId:id(6),replayed:true,state:'OPEN',reservationMade:false,customerConfirmationRequired:true,business:{companyId:id(1),startsAt:p.command.startsAt,endsAt:p.command.endsAt,location:p.command.location}};
 assert.equal(s.proposalReceipt(r,p),r);assert.throws(()=>s.proposalReceipt({...r,requestId:id(7)},p));assert.equal(map.size,1);s.clearPendingProposal(storage,p);assert.equal(map.size,0);
});
test('malformed session and expired availability fail closed',async()=>{const s=await import('../../frontend/src/components/facebook/surveyProposalState.mjs');assert.throws(()=>s.readPendingProposal({getItem:()=>'{bad'},id(2),id(1),id(3)));assert.throws(()=>s.availableOptions({companyId:id(1),threadId:id(3),reservationMade:false,customerConfirmationRequired:true,status:'AVAILABLE_SNAPSHOT',items:[{staffId:id(9),regionId:id(8),optionId:'a'.repeat(32),startsAt:'2027-01-01T00:00:00Z',endsAt:'2027-01-01T01:00:00Z',snapshotExpiresAt:'2026-01-01T00:00:00Z',sourceValidUntil:'2027-01-01T00:00:00Z'}]},id(1),id(3),Date.parse('2026-10-03T00:00:00Z')));});
module.exports={fixture};
