'use strict';
const test = require('node:test'), assert = require('node:assert/strict'), { randomUUID } = require('node:crypto');
const { createSurveyProposals, validCommand } = require('../src/modules/marketingAutomation/surveyProposals');
const company = randomUUID(), actor = randomUUID(), thread = randomUUID(), proposal = randomUUID(), request = randomUUID();
const command = { threadId: thread, optionId: 'a'.repeat(32), startsAt: '2027-01-01T01:00:00Z', endsAt: '2027-01-01T02:00:00Z', location: 'Synthetic isolated location' };
const view = { proposalId: proposal, companyId: company, threadId: thread, state: 'OPEN', business: { companyId: company }, expiresAt: '2027-01-01T00:15:00Z', reservationMade: false, booking: null, deliveryState: 'QUEUED', customerConfirmationRequired: true, requestId: request, replayed: false };
const run = async ({ env = { VPT_SURVEY_PROPOSALS: '1' }, isPrimary = () => true, result = { data: view }, op = 'propose', body = { companyId: company, requestId: request, command }, user = { id: actor } } = {}) => {
  const calls = [], res = { code: 200, headers: {}, set(k, v) { this.headers[k] = v; return this; }, status(v) { this.code = v; return this; }, json(v) { this.body = v; return this; } };
  const service = createSurveyProposals({ env, isPrimary, db: { async rpc(...args) { calls.push(args); return typeof result === 'function' ? result() : result; } } });
  await service.handle({ user, body, query: body }, res, op); return { ...res, calls };
};
test('proposal API is disabled by default and on backup', async () => { for (const options of [{ env: {} }, { isPrimary: () => false }]) { const r = await run(options); assert.equal(r.code, 503); assert.equal(r.calls.length, 0); } });
test('proposal validates shape and excludes customer-confirmation/actor injection', async () => { assert.equal(validCommand(command), true); for (const x of [{ ...command, customerConfirmed: true }, { ...command, location: '' }, { ...command, endsAt: command.startsAt }]) { const r = await run({ body: { companyId: company, requestId: request, command: x } }); assert.equal(r.code, 400); assert.equal(r.calls.length, 0); } });
test('actor and company come from authenticated request and exact receipt is checked', async () => { const r = await run(); assert.equal(r.code, 200); assert.equal(r.calls[0][0], 'crm_survey_propose'); assert.equal(r.calls[0][1].p_actor, actor); assert.equal(r.headers['Cache-Control'], 'no-store'); assert.equal((await run({ user: { id: actor, userId: randomUUID() } })).code, 403); });
test('wrong company, thread, receipt or private token in response is rejected', async () => { for (const patch of [{ companyId: randomUUID() }, { threadId: randomUUID() }, { requestId: randomUUID() }, { confirmation_token: randomUUID() }]) assert.equal((await run({ result: { data: { ...view, ...patch } } })).code, 503); });
test('proposal read verifies exact identity and cannot invoke book or confirm', async () => { assert.equal((await run({ op: 'read', body: { companyId: company, proposalId: proposal } })).code, 200); assert.equal((await run({ op: 'read', body: { companyId: company, proposalId: randomUUID() } })).code, 503); for (const op of ['book', 'confirm', 'send']) { const r = await run({ op }); assert.equal(r.code, 400); assert.equal(r.calls.length, 0); } });
test('permission, stale data, invalid input and storage errors use bounded errors', async () => { for (const [code, status] of [['42501', 403], ['40001', 409], ['23505', 409], ['22023', 400], ['XX000', 503]]) { const r = await run({ result: { error: { code, message: 'SECRET SOURCE' } } }); assert.equal(r.code, status); assert.equal(JSON.stringify(r.body).includes('SECRET'), false); } });
test('primary switch before response never returns an acknowledged proposal', async () => { let primary = true; const r = await run({ isPrimary: () => primary, result: () => { primary = false; return { data: view }; } }); assert.equal(r.code, 503); });
