import {
  BarChart3,
  Bot,
  BriefcaseBusiness,
  Building2,
  Factory,
  FileText,
  HandCoins,
  LayoutDashboard,
  Library,
  PackageSearch,
  Settings2,
  ShoppingCart,
  Users,
} from 'lucide-react';

export const OS_NAVIGATION = [
  { key: 'home', to: '/business-os', label: 'Trung tâm điều hành', icon: LayoutDashboard },
  { key: 'work', to: '/business-os/work', label: 'Công việc', icon: BriefcaseBusiness },
  { key: 'sales', to: '/business-os/sales', label: 'Kinh doanh', icon: HandCoins },
  { key: 'operations', to: '/business-os/operations', label: 'Vận hành', icon: Factory },
  { key: 'purchasing', to: '/business-os/purchasing', label: 'Mua hàng', icon: ShoppingCart },
  { key: 'finance', to: '/business-os/finance', label: 'Tài chính', icon: FileText },
  { key: 'customers', to: '/business-os/customers', label: 'Khách hàng', icon: Users },
  { key: 'reports', to: '/business-os/reports', label: 'Báo cáo', icon: BarChart3 },
];

export const OS_SECONDARY_NAVIGATION = [
  { key: 'knowledge', to: '/business-os/knowledge', label: 'Kiến thức', icon: Library },
  { key: 'ai', to: '/business-os/ai', label: 'AI Agent Center', icon: Bot, badge: 'AI' },
  { key: 'admin', to: '/business-os/admin', label: 'Thiết kế hệ thống', icon: Settings2 },
];

export const WORKSPACE_BLUEPRINTS = {
  work: {
    eyebrow: 'Work Management',
    title: 'Không gian công việc',
    description: 'Một hàng đợi duy nhất cho việc cá nhân, đội nhóm, phê duyệt và các nhiệm vụ phát sinh từ quy trình.',
    accent: 'blue',
    icon: BriefcaseBusiness,
    legacyRoute: '/work/tasks-unified',
    primaryAction: 'Mở danh sách công việc',
    metrics: [
      ['Việc cần làm hôm nay', '0', 'Theo người đăng nhập'],
      ['Đang bị chặn', '0', 'Cần hỗ trợ hoặc đầu vào'],
      ['Chờ phê duyệt', '0', 'Theo đúng thẩm quyền'],
      ['Hoàn thành đúng hạn', '—', 'Đo từ sự kiện thực tế'],
    ],
    lanes: [
      ['Việc của tôi', 'Theo ưu tiên, deadline và ngữ cảnh hồ sơ'],
      ['Việc của đội', 'Capacity, phân công và điểm nghẽn'],
      ['Phê duyệt', 'Yêu cầu có bằng chứng và lịch sử quyết định'],
      ['Lịch & kế hoạch', 'Planner hợp nhất từ các quy trình'],
    ],
  },
  operations: {
    eyebrow: 'Operations',
    title: 'Điều hành dự án & sản xuất',
    description: 'Theo dõi một vòng đời thống nhất từ bàn giao đơn hàng đến sản xuất, giao hàng, lắp đặt và nghiệm thu.',
    accent: 'orange',
    icon: Factory,
    legacyRoute: '/work/unified',
    primaryAction: 'Mở vận hành hiện tại',
    metrics: [
      ['Dự án đang chạy', '—', 'Theo macro lifecycle'],
      ['Cảnh báo tiến độ', '—', 'Aging, blocker và SLA'],
      ['Chờ bàn giao', '—', 'Acceptance contract'],
      ['Chất lượng lần đầu', '—', 'First-pass quality'],
    ],
    lanes: [
      ['Danh mục dự án', 'Sức khỏe, deadline, ngân sách và người phụ trách'],
      ['Kiểm soát sản xuất', 'WIP, capacity, vật tư và QC theo công đoạn'],
      ['Vận chuyển', 'Readiness, lịch xe và bằng chứng giao hàng'],
      ['Lắp đặt & nghiệm thu', 'Lịch đội, checklist, punch list và ký nhận'],
    ],
  },
  purchasing: {
    eyebrow: 'Procurement',
    title: 'Mua hàng & nhà cung cấp',
    description: 'Kiểm soát nhu cầu vật tư, phê duyệt mua, đơn mua và nhập kho theo đúng nhu cầu của dự án.',
    accent: 'amber',
    icon: ShoppingCart,
    legacyRoute: '/products',
    primaryAction: 'Mở danh mục hiện tại',
    metrics: [
      ['Yêu cầu mua mới', '—', 'Sinh từ nhu cầu dự án'],
      ['Chờ duyệt', '—', 'Theo hạn mức và vai trò'],
      ['Đơn mua đang mở', '—', 'Theo dõi ngày giao'],
      ['Rủi ro thiếu vật tư', '—', 'Tác động trực tiếp tiến độ'],
    ],
    lanes: [
      ['Nhu cầu vật tư', 'Gom theo dự án, deadline và mức độ ưu tiên'],
      ['Đơn mua hàng', 'Phiên bản, phê duyệt và cam kết giao'],
      ['Nhà cung cấp', 'Năng lực, chất lượng và lịch sử giao hàng'],
      ['Nhận hàng', 'Số lượng, chất lượng và liên kết công nợ'],
    ],
  },
  finance: {
    eyebrow: 'Finance',
    title: 'Tài chính vận hành',
    description: 'Liên kết báo giá, đơn hàng, mốc thanh toán, công nợ và lợi nhuận với từng hồ sơ kinh doanh và dự án.',
    accent: 'emerald',
    icon: FileText,
    legacyRoute: '/ketoan/dashboard',
    primaryAction: 'Mở tài chính hiện tại',
    metrics: [
      ['Doanh thu ghi nhận', '—', 'Theo kỳ và công ty'],
      ['Công nợ đến hạn', '—', 'Có owner và escalation'],
      ['Dòng tiền dự kiến', '—', 'Từ milestone hợp đồng'],
      ['Biên lợi nhuận', '—', 'Drill-down tới dự án'],
    ],
    lanes: [
      ['Hóa đơn & thanh toán', 'Đối chiếu trạng thái và chứng từ'],
      ['Công nợ phải thu', 'Aging, cam kết và nhắc hạn'],
      ['Dòng tiền', 'Thực tế so với dự kiến'],
      ['Hiệu quả dự án', 'Doanh thu, chi phí và biên lợi nhuận'],
    ],
  },
  customers: {
    eyebrow: 'Customer 360',
    title: 'Trung tâm khách hàng',
    description: 'Một hồ sơ quan hệ duy nhất cho liên hệ, cơ hội, đơn hàng, dự án, chăm sóc và bảo hành.',
    accent: 'violet',
    icon: Users,
    legacyRoute: '/customers',
    primaryAction: 'Mở danh sách khách hàng',
    metrics: [
      ['Khách hàng hoạt động', '—', 'Có giao dịch hoặc dự án'],
      ['Lịch chăm sóc', '—', 'Theo hành trình sau bán'],
      ['Yêu cầu bảo hành', '—', 'SLA theo mức độ'],
      ['Mức độ hài lòng', '—', 'CSAT/NPS có nguồn'],
    ],
    lanes: [
      ['Customer 360', 'Thông tin, giá trị và toàn bộ lịch sử quan hệ'],
      ['Chăm sóc sau bán', 'Lịch 7/30 ngày và playbook theo phân khúc'],
      ['Bảo hành & dịch vụ', 'Case, SLA, bằng chứng và kết quả'],
      ['Phản hồi khách hàng', 'CSAT/NPS gắn với giao dịch thực tế'],
    ],
  },
  reports: {
    eyebrow: 'Decision Intelligence',
    title: 'Báo cáo & chỉ số',
    description: 'Mỗi chỉ số đều có định nghĩa, nguồn dữ liệu và khả năng đi ngược tới hồ sơ hoặc sự kiện tạo ra nó.',
    accent: 'cyan',
    icon: BarChart3,
    legacyRoute: '/management',
    primaryAction: 'Mở báo cáo hiện tại',
    metrics: [
      ['Sức khỏe doanh nghiệp', '—', 'Chỉ số tổng hợp theo vai trò'],
      ['SLA đạt chuẩn', '—', 'Theo process và phòng ban'],
      ['Nút thắt lớn nhất', '—', 'Aging và capacity'],
      ['Dự báo kỳ này', '—', 'Có giải thích và độ tin cậy'],
    ],
    lanes: [
      ['Điều hành', 'Kết quả, rủi ro và ngoại lệ cần quyết định'],
      ['Kinh doanh', 'Funnel, conversion, forecast và sales cycle'],
      ['Vận hành', 'WIP, SLA, chất lượng và đúng hạn'],
      ['Tài chính', 'Doanh thu, công nợ, dòng tiền và lợi nhuận'],
    ],
  },
  knowledge: {
    eyebrow: 'Knowledge & SOP',
    title: 'Kiến thức doanh nghiệp',
    description: 'Biến quy trình thành hướng dẫn có thể học, áp dụng và kiểm chứng ngay trong công việc thực tế.',
    accent: 'indigo',
    icon: Library,
    legacyRoute: '/knowledge',
    primaryAction: 'Mở kho kiến thức',
    metrics: [
      ['SOP đang áp dụng', '—', 'Gắn trực tiếp với stage'],
      ['Nội dung cần cập nhật', '—', 'Theo version quy trình'],
      ['Nhân sự đang học', '—', 'Theo vai trò và năng lực'],
      ['Chứng nhận còn hiệu lực', '—', 'Theo kỹ năng bắt buộc'],
    ],
    lanes: [
      ['Quy trình chuẩn', 'SOP theo process, stage và vai trò'],
      ['Đào tạo', 'Lộ trình học theo vị trí công việc'],
      ['Mẫu biểu', 'Checklist, biên bản và tài liệu chuẩn'],
      ['Năng lực', 'Kỹ năng, chứng nhận và khoảng trống đào tạo'],
    ],
  },
};

export const SALES_LIFECYCLE = [
  ['lead', 'Lead'],
  ['qualification', 'Qualification'],
  ['deal', 'Deal'],
  ['survey', 'Khảo sát (nếu cần)'],
  ['design', 'Thiết kế / kiểm tra'],
  ['quotation', 'Báo giá'],
  ['negotiation', 'Đàm phán'],
  ['order', 'Đơn hàng'],
  ['project', 'Dự án'],
  ['production', 'Sản xuất'],
  ['delivery_ready', 'Sẵn sàng giao'],
  ['installation', 'VC / Lắp đặt'],
  ['completed', 'Đã bàn giao'],
];

export const COMPANY_LIFECYCLE = [
  ['sales', 'Kinh doanh', 'Lead → Đơn hàng'],
  ['project', 'Dự án', 'Khởi tạo → Bàn giao'],
  ['production', 'Sản xuất', 'Kế hoạch → QC'],
  ['delivery', 'Giao hàng', 'Đóng gói → Giao'],
  ['installation', 'Lắp đặt', 'Sẵn sàng → Nghiệm thu'],
  ['customer', 'Khách hàng', 'Chăm sóc → Bảo hành'],
];

export const COMMANDS = [
  ...OS_NAVIGATION.map((item) => ({ ...item, group: 'Không gian' })),
  ...OS_SECONDARY_NAVIGATION.map((item) => ({ ...item, group: 'Hệ thống' })),
  { key: 'legacy-crm', to: '/crm/dashboard', label: 'Mở CRM hiện tại', icon: PackageSearch, group: 'Hệ thống hiện tại' },
  { key: 'legacy-company', to: '/management', label: 'Mở điều hành hiện tại', icon: Building2, group: 'Hệ thống hiện tại' },
];
