const uuid=x=>typeof x==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x);
const hash=x=>typeof x==='string'&&/^[a-f0-9]{32}$/.test(x);
const object=x=>!!x&&typeof x==='object'&&!Array.isArray(x);
const date=x=>typeof x==='string'&&Number.isFinite(Date.parse(x));
const requireValue=ok=>{if(!ok)throw Error('CARE_LIBRARY_INVALID');};
export const channelLabels={facebook:'Facebook',website:'Website',google:'Google',tiktok:'TikTok',zalo:'Zalo',chatgpt:'ChatGPT'};
export const purposeLabels={ADVICE:'Tư vấn sản phẩm',QUALIFY:'Hỏi nhu cầu',HANDOFF:'Bàn giao cho nhân viên'};
export const stateLabels={DRAFT:'Bản nháp',APPROVED:'Đã duyệt',REVOKED:'Đã thu hồi'};
export const readinessLabels={NOT_APPROVED:'Chưa được duyệt',SOURCE_UNAVAILABLE:'Nguồn không còn khả dụng',SOURCE_CHANGED:'Thông tin nguồn đã thay đổi',APPROVER_UNAVAILABLE:'Quyền duyệt không còn hiệu lực',EXPIRED:'Nội dung hết hạn'};
export function documentValid(d){return object(d)&&Object.keys(d).length===9&&typeof d.title==='string'&&d.title.trim().length>0&&d.title.length<=200&&typeof d.question==='string'&&d.question.trim().length>0&&d.question.length<=1000&&typeof d.answer==='string'&&d.answer.trim().length>0&&d.answer.length<=4000&&!/\{\{|\}\}/.test(d.answer)&&typeof d.sourceReference==='string'&&d.sourceReference.trim().length>0&&d.sourceReference.length>=20&&d.sourceReference.length<=2000&&(d.productId===null||uuid(d.productId))&&Object.hasOwn(purposeLabels,d.purpose)&&Array.isArray(d.regionIds)&&d.regionIds.length>0&&d.regionIds.length<=20&&d.regionIds.every(uuid)&&new Set(d.regionIds).size===d.regionIds.length&&Array.isArray(d.channels)&&d.channels.length>0&&d.channels.length<=6&&d.channels.every(c=>Object.hasOwn(channelLabels,c))&&new Set(d.channels).size===d.channels.length&&date(d.validUntil);}
const rowValid=x=>object(x)&&uuid(x.entryId)&&hash(x.version)&&Number.isSafeInteger(x.revision)&&x.revision>0&&Object.hasOwn(stateLabels,x.state)&&typeof x.approvedReady==='boolean'&&typeof x.sourceReady==='boolean'&&typeof x.canApprove==='boolean';
export function entryView(data,companyId,entryId){requireValue(data?.companyId===companyId&&data.entryId===entryId&&rowValid(data)&&documentValid(data.document));return data;}
export function listView(data,companyId){requireValue(data?.companyId===companyId&&typeof data.canApprove==='boolean'&&Array.isArray(data.items)&&data.items.length<=50&&data.items.every(x=>x.companyId===companyId&&rowValid(x)&&typeof x.title==='string')&&new Set(data.items.map(x=>x.entryId)).size===data.items.length&&(data.nextAfter===null||(uuid(data.nextAfter)&&data.items.at(-1)?.entryId===data.nextAfter)));return data;}
export function choicesView(data,companyId,kind,search){requireValue(data?.companyId===companyId&&data.kind===kind&&data.search===search&&Array.isArray(data.items)&&data.items.length<=50&&data.items.every(x=>uuid(x?.id)&&typeof x.name==='string'&&typeof x.code==='string')&&new Set(data.items.map(x=>x.id)).size===data.items.length&&(data.nextAfter===null||(uuid(data.nextAfter)&&data.items.at(-1)?.id===data.nextAfter)));return data;}
export function historyView(data,companyId,entryId,version,known=new Set()){
 requireValue(data?.companyId===companyId&&data.entryId===entryId&&data.version===version&&data.historical===true&&Array.isArray(data.items)&&data.items.length<=50);
 requireValue(data.items.every(x=>uuid(x?.requestId)&&!known.has(x.requestId)&&['SAVE','APPROVE','REVOKE'].includes(x.action)&&date(x.recordedAt)&&typeof x.actorName==='string'&&typeof x.reason==='string'&&Number.isSafeInteger(x.revision)&&x.revision>0&&Object.hasOwn(stateLabels,x.state)&&documentValid(x.document))&&new Set(data.items.map(x=>x.requestId)).size===data.items.length&&(data.nextBefore===null||(uuid(data.nextBefore)&&data.items.at(-1)?.requestId===data.nextBefore)));return data;
}
export function previewView(data,entry){requireValue(data?.companyId===entry.companyId&&data.entryId===entry.entryId&&data.version===entry.version&&data.send===false&&data.text===entry.document.answer&&data.sourceReference===entry.document.sourceReference&&data.validUntil===entry.document.validUntil);return data;}
export function pendingKey(actorId,companyId){requireValue(uuid(actorId)&&uuid(companyId));return `vpt-care-library-pending-v1:${actorId}:${companyId}`;}
function pendingValid(x,actorId,companyId){const c=x?.command;return object(x)&&x.actorId===actorId&&x.companyId===companyId&&uuid(x.requestId)&&object(c)&&uuid(c.entryId)&&['SAVE','APPROVE','REVOKE'].includes(c.action)&&(hash(c.expectedVersion)||(c.action==='SAVE'&&c.expectedVersion===null))&&typeof c.reason==='string'&&c.reason.trim().length>=20&&c.reason.length<=2000&&Object.keys(c).every(k=>['entryId','action','expectedVersion','reason','document'].includes(k))&&(c.action==='SAVE'?documentValid(c.document):!Object.hasOwn(c,'document'));}
export function readPending(storage,actorId,companyId){const raw=storage.getItem(pendingKey(actorId,companyId));if(raw===null)return null;const x=JSON.parse(raw);requireValue(pendingValid(x,actorId,companyId));return x;}
export function savePending(storage,x){requireValue(pendingValid(x,x.actorId,x.companyId));const key=pendingKey(x.actorId,x.companyId),raw=JSON.stringify(x),old=storage.getItem(key);requireValue(old===null||old===raw);storage.setItem(key,raw);requireValue(storage.getItem(key)===raw);return x;}
export function clearPending(storage,actorId,companyId){const key=pendingKey(actorId,companyId);storage.removeItem(key);requireValue(storage.getItem(key)===null);}
export const changePayload=({companyId,requestId,command})=>({companyId,requestId,command});
export function changeAck(data,pending){requireValue(data?.companyId===pending.companyId&&data.entryId===pending.command.entryId&&data.requestId===pending.requestId&&data.action===pending.command.action&&typeof data.replayed==='boolean');entryView(data.entry,pending.companyId,pending.command.entryId);requireValue(data.entry.state===({SAVE:'DRAFT',APPROVE:'APPROVED',REVOKE:'REVOKED'}[pending.command.action]));return data;}
export const vietnamInput=iso=>date(iso)?new Date(Date.parse(iso)+7*3600000).toISOString().slice(0,16):'';
export function vietnamISO(input){if(typeof input!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(input))return '';const d=new Date(input+':00+07:00');if(!Number.isFinite(d.getTime())||vietnamInput(d.toISOString())!==input)return '';return d.toISOString();}
