'use strict';
const {Router}=require('express');
const {supabase}=require('../config/supabase');
const state=require('../config/supabaseRouter');
const {createCustomerCare}=require('../modules/marketingAutomation/facebookCustomerCare');
const {createCareConnections}=require('../modules/marketingAutomation/careConnections');
const {createCareLibrary}=require('../modules/marketingAutomation/customerCareLibrary');
const {createCareAdvisor}=require('../modules/marketingAutomation/careAdvisor');
const {createSurveyAvailability}=require('../modules/marketingAutomation/surveyAvailability');
const {createSurveyProposals}=require('../modules/marketingAutomation/surveyProposals');
const {createProposalConsole}=require('../modules/marketingAutomation/surveyProposalConsole');
const {createSurveyHandoffs}=require('../modules/marketingAutomation/surveyHandoffs');
// Parent mount authenticates; each RPC checks the current actor and company.
const r=Router(),care=createCustomerCare({db:supabase,isPrimary:()=>!state.isFailoverEnabled()&&state.getActiveTarget()==='primary'});
require('../helpers/trackedRouter').trackRouterHandlers(r,require('../helpers/facebookProcessWork'));
r.get('/threads',(req,res)=>care.handle(req,res,'list'));
r.get('/queue',(req,res)=>care.handle(req,res,'queue'));
r.get('/thread',(req,res)=>care.handle(req,res,'read'));
r.get('/history',(req,res)=>care.handle(req,res,'history'));
r.post('/control',(req,res)=>care.handle(req,res,'control'));
const connections=createCareConnections({db:supabase,isPrimary:()=>!state.isFailoverEnabled()&&state.getActiveTarget()==='primary'});
r.get('/connection',(req,res)=>connections.handle(req,res,'read'));
r.get('/connection/choices',(req,res)=>connections.handle(req,res,'choices'));
r.post('/connection/link',(req,res)=>connections.handle(req,res,'link'));
r.post('/connection/close',(req,res)=>connections.handle(req,res,'close'));
const library=createCareLibrary({db:supabase,isPrimary:()=>!state.isFailoverEnabled()&&state.getActiveTarget()==='primary'});
r.get('/library',(req,res)=>library.handle(req,res,'list'));
r.get('/library/entry',(req,res)=>library.handle(req,res,'read'));
r.get('/library/choices',(req,res)=>library.handle(req,res,'choices'));
r.get('/library/history',(req,res)=>library.handle(req,res,'history'));
r.post('/library/change',(req,res)=>library.handle(req,res,'change'));
r.post('/library/preview',(req,res)=>library.handle(req,res,'preview'));
// No live inference port is configured here. Provider/model/cost authorization
// remains a separate release gate; read/close support durable draft reconciliation.
const advisor=createCareAdvisor({db:supabase,isPrimary:()=>!state.isFailoverEnabled()&&state.getActiveTarget()==='primary'});
r.get('/advisor/draft',(req,res)=>advisor.handle(req,res,'read'));
r.post('/advisor/draft',(req,res)=>advisor.handle(req,res,'generate'));
r.post('/advisor/draft/close',(req,res)=>advisor.handle(req,res,'close'));
r.post('/advisor/draft/retry',(req,res)=>advisor.handle(req,res,'retry'));
const survey=createSurveyAvailability({db:supabase,isPrimary:()=>!state.isFailoverEnabled()&&state.getActiveTarget()==='primary'});
r.get('/survey/roster',(req,res)=>survey.handle(req,res,'read'));
r.post('/survey/roster/change',(req,res)=>survey.handle(req,res,'change'));
r.get('/survey/availability',(req,res)=>survey.handle(req,res,'availability'));
const proposals=createSurveyProposals({db:supabase,isPrimary:()=>!state.isFailoverEnabled()&&state.getActiveTarget()==='primary'});
const proposalConsole=createProposalConsole({db:supabase,isPrimary:()=>!state.isFailoverEnabled()&&state.getActiveTarget()==='primary'});
r.get('/survey/proposals',(req,res)=>proposalConsole(req,res));
r.get('/survey/proposal',(req,res)=>proposals.handle(req,res,'read'));
r.post('/survey/proposal',(req,res)=>proposals.handle(req,res,'propose'));
const handoffs=createSurveyHandoffs({db:supabase,isPrimary:()=>!state.isFailoverEnabled()&&state.getActiveTarget()==='primary'});
r.get('/survey/handoffs',(req,res)=>handoffs.handle(req,res,'queue'));
r.get('/survey/handoff',(req,res)=>handoffs.handle(req,res,'read'));
r.post('/survey/handoff/ack',(req,res)=>handoffs.handle(req,res,'ack'));
module.exports=r;
