const { AGENT_TYPES, RUN_STATES } = require('./constants');
const { factoryError } = require('./errors');

const STANDARD_TRANSITIONS = Object.freeze({
  [RUN_STATES.REQUESTED]: [RUN_STATES.ANALYZED],
  [RUN_STATES.ANALYZED]: [RUN_STATES.ARCHITECTURE_APPROVED],
  [RUN_STATES.ARCHITECTURE_APPROVED]: [RUN_STATES.READY_TO_BUILD],
  [RUN_STATES.READY_TO_BUILD]: [RUN_STATES.BUILDING],
  [RUN_STATES.BUILDING]: [RUN_STATES.BUILT],
  [RUN_STATES.BUILT]: [RUN_STATES.IN_REVIEW],
  [RUN_STATES.IN_REVIEW]: [RUN_STATES.REVIEW_PASSED, RUN_STATES.BLOCKED, RUN_STATES.CHANGES_REQUESTED],
  [RUN_STATES.REVIEW_PASSED]: [RUN_STATES.TESTING],
  [RUN_STATES.TESTING]: [RUN_STATES.TEST_PASSED, RUN_STATES.FAILED],
  [RUN_STATES.TEST_PASSED]: [RUN_STATES.UAT_READY],
  [RUN_STATES.UAT_READY]: [RUN_STATES.UAT_PASSED],
  [RUN_STATES.UAT_PASSED]: [RUN_STATES.RELEASE_CANDIDATE],
  [RUN_STATES.RELEASE_CANDIDATE]: [RUN_STATES.AWAITING_FOUNDER_APPROVAL],
  [RUN_STATES.AWAITING_FOUNDER_APPROVAL]: [RUN_STATES.BASELINED],
  [RUN_STATES.BASELINED]: [RUN_STATES.ROLLED_BACK],
  [RUN_STATES.BLOCKED]: [],
  [RUN_STATES.FAILED]: [RUN_STATES.READY_TO_BUILD],
  [RUN_STATES.CHANGES_REQUESTED]: [RUN_STATES.READY_TO_BUILD],
  [RUN_STATES.ROLLED_BACK]: [],
});

const ALLOWED_ACTOR_TYPES = Object.freeze({
  [RUN_STATES.ANALYZED]: [AGENT_TYPES.PRODUCT_OWNER],
  [RUN_STATES.ARCHITECTURE_APPROVED]: [AGENT_TYPES.SOLUTION_ARCHITECT],
  [RUN_STATES.READY_TO_BUILD]: [AGENT_TYPES.ORCHESTRATOR],
  [RUN_STATES.BUILDING]: [AGENT_TYPES.BACKEND_DOMAIN, AGENT_TYPES.FRONTEND, AGENT_TYPES.DATABASE_MIGRATION],
  [RUN_STATES.BUILT]: [AGENT_TYPES.BACKEND_DOMAIN, AGENT_TYPES.FRONTEND, AGENT_TYPES.DATABASE_MIGRATION],
  [RUN_STATES.IN_REVIEW]: [AGENT_TYPES.ORCHESTRATOR],
  [RUN_STATES.REVIEW_PASSED]: [AGENT_TYPES.SECURITY_ARCHITECTURE_REVIEWER],
  [RUN_STATES.BLOCKED]: [AGENT_TYPES.SECURITY_ARCHITECTURE_REVIEWER],
  [RUN_STATES.CHANGES_REQUESTED]: [AGENT_TYPES.SECURITY_ARCHITECTURE_REVIEWER],
  [RUN_STATES.TESTING]: [AGENT_TYPES.QA_UAT],
  [RUN_STATES.TEST_PASSED]: [AGENT_TYPES.QA_UAT],
  [RUN_STATES.FAILED]: [AGENT_TYPES.QA_UAT],
  [RUN_STATES.UAT_READY]: [AGENT_TYPES.QA_UAT],
  [RUN_STATES.UAT_PASSED]: [AGENT_TYPES.QA_UAT],
  [RUN_STATES.RELEASE_CANDIDATE]: [AGENT_TYPES.RELEASE_BASELINE],
  [RUN_STATES.AWAITING_FOUNDER_APPROVAL]: [AGENT_TYPES.RELEASE_BASELINE],
  [RUN_STATES.BASELINED]: [AGENT_TYPES.RELEASE_BASELINE],
  [RUN_STATES.ROLLED_BACK]: [AGENT_TYPES.RELEASE_BASELINE],
});

function assertTransitionAllowed(fromState, toState) {
  const allowed = STANDARD_TRANSITIONS[fromState] || [];
  if (!allowed.includes(toState)) {
    throw factoryError('INVALID_GATE_TRANSITION', `Không thể chuyển ${fromState} → ${toState}.`, { from: fromState, to: toState });
  }
}

function assertActorTypeAllowed(agent, toState) {
  const allowed = ALLOWED_ACTOR_TYPES[toState] || [];
  if (!allowed.includes(agent.agent_type)) {
    throw factoryError('GATE_ACTOR_DENIED', `${agent.agent_type} không được chuyển gate sang ${toState}.`, { to: toState });
  }
}

module.exports = {
  ALLOWED_ACTOR_TYPES,
  STANDARD_TRANSITIONS,
  assertActorTypeAllowed,
  assertTransitionAllowed,
};
