/**
 * Product tours — bước gắn [data-tour="…"].
 * advanceOn: 'target-click' | 'next'
 * ensureOpen / ensureClose: xem ProductTourProvider.runStepChrome
 * waitForPath: string | string[]
 */

/**
 * @typedef {{
 *   target: string;
 *   title: string;
 *   body: string;
 *   advanceOn?: 'target-click' | 'next';
 *   ensureOpen?: string;
 *   ensureClose?: string;
 *   waitForPath?: string | string[];
 *   missingHint?: string;
 *   scroll?: boolean;
 *   optional?: boolean;
 *   placement?: 'left' | 'right' | 'top' | 'bottom';
 * }} TourStep
 */
/** @typedef {{ id: string; title: string; steps: TourStep[] }} TourDef */

const CRM = '/crm';
const LEAD = '/crm/leads';
const ASSIGN = ['/crm/assignments', '/sx/assignments', '/vc/assignments'];

/** @type {Record<string, TourDef>} */
export const TOURS = {
  'crm-familiar': {
    id: 'crm-familiar',
    title: 'Làm quen CRM',
    steps: [
      {
        target: 'app-switcher',
        title: 'Nút lưới module',
        body: 'Góc trên sidebar — bấm nút lưới để mở danh sách Tất cả ứng dụng.',
        advanceOn: 'target-click',
      },
      {
        target: 'app-switcher-crm',
        title: 'Thẻ CRM trong danh sách',
        body: 'Trong panel ứng dụng, tìm thẻ CRM (ưa thích hoặc danh sách module).',
        advanceOn: 'next',
        ensureOpen: 'app-switcher',
      },
      {
        target: 'app-switcher-crm',
        title: 'Bấm vào CRM',
        body: 'Bấm thẻ CRM để vào module bán hàng.',
        advanceOn: 'target-click',
        ensureOpen: 'app-switcher',
      },
      {
        target: 'nav-crm-dashboard',
        title: 'Menu Dashboard CRM',
        body: 'Panel chọn module đã đóng. Trên sidebar, tìm mục Dashboard CRM.',
        advanceOn: 'next',
        ensureClose: 'app-switcher',
        ensureOpen: 'crm-overview-menu',
        waitForPath: CRM,
      },
      {
        target: 'nav-crm-dashboard',
        title: 'Vào Bảng Lead',
        body: 'Bấm Dashboard CRM — đây là Bảng Lead/Deal (Kanban).',
        advanceOn: 'target-click',
        ensureOpen: 'crm-overview-menu',
        waitForPath: CRM,
      },
      {
        target: 'pipeline-tab-lead',
        title: 'Tab Leads',
        body: 'Tab màu xanh — danh sách khách tiềm năng theo cột giai đoạn.',
        advanceOn: 'next',
        ensureOpen: 'crm-lead-tab',
        waitForPath: CRM,
      },
      {
        target: 'pipeline-tab-deal',
        title: 'Tab Deals',
        body: 'Tab Deals — cơ hội đã chuyển từ Lead hoặc tạo trực tiếp.',
        advanceOn: 'next',
        waitForPath: CRM,
      },
      {
        target: 'pipeline-tab-lead',
        title: 'Quay lại tab Leads',
        body: 'Bấm tab Leads để tiếp tục làm quen với bảng khách mới.',
        advanceOn: 'target-click',
        waitForPath: CRM,
      },
      {
        target: 'add-lead',
        title: 'Nút + Thêm Lead',
        body: 'Góc phải thanh công cụ — tạo Lead mới từ đây.',
        advanceOn: 'next',
        ensureOpen: 'crm-lead-tab',
        waitForPath: CRM,
      },
      {
        target: 'crm-toolbar',
        title: 'Thanh công cụ Dashboard',
        body: 'Hàng này gồm tìm kiếm, bộ lọc, chế độ xem Kanban/Thêm, Giao việc và Tùy chỉnh.',
        advanceOn: 'next',
        ensureOpen: 'crm-lead-tab',
        waitForPath: CRM,
      },
      {
        target: 'crm-search',
        title: 'Ô tìm kiếm',
        body: 'Gõ tên, SĐT hoặc mã Lead/Deal. Chip lọc nhanh cũng hiện cạnh ô tìm khi đang dùng bộ lọc.',
        advanceOn: 'next',
        waitForPath: CRM,
      },
      {
        target: 'crm-filter',
        title: 'Nút bộ lọc',
        body: 'Biểu tượng phễu cạnh ô tìm — bấm để mở panel Bộ lọc nâng cao.',
        advanceOn: 'next',
        waitForPath: CRM,
        placement: 'bottom',
      },
      {
        target: 'crm-filter-panel',
        title: 'Panel Bộ lọc',
        body: 'Panel nổi: lọc nhân viên, công ty, nguồn, giai đoạn, vùng, SĐT, thời gian… Có thể kéo thanh tiêu đề để đổi vị trí.',
        advanceOn: 'next',
        ensureOpen: 'crm-filter-panel',
        waitForPath: CRM,
        placement: 'left',
      },
      {
        target: 'crm-filter-tabs',
        title: 'Tab trong Bộ lọc',
        body: 'Chuyển tab (Nhân viên / Khách / Thời gian…) để chỉnh từng nhóm điều kiện. Chip lọc hiện cạnh ô tìm khi đang áp dụng.',
        advanceOn: 'next',
        ensureOpen: 'crm-filter-panel',
        waitForPath: CRM,
        placement: 'left',
      },
      {
        target: 'crm-view-mode',
        title: 'Chế độ xem',
        body: 'Kanban là mặc định (cột giai đoạn). Cạnh đó nút Thêm để chọn kiểu giao diện khác.',
        advanceOn: 'next',
        waitForPath: CRM,
        placement: 'bottom',
      },
      {
        target: 'crm-view-mode-more',
        title: 'Chọn loại giao diện',
        body: 'Bấm Thêm để mở danh sách: Danh sách, Deadline, và các chế độ xem khác (tùy cấu hình).',
        advanceOn: 'next',
        waitForPath: CRM,
        placement: 'bottom',
      },
      {
        target: 'crm-view-mode-menu',
        title: 'Menu chế độ xem',
        body: 'Chọn một dòng để đổi giao diện bảng. Tour này giữ Kanban — bạn chỉ cần xem các lựa chọn rồi Tiếp.',
        advanceOn: 'next',
        ensureOpen: 'crm-view-mode-menu',
        waitForPath: CRM,
        placement: 'left',
      },
      {
        target: 'crm-assign-tasks',
        title: 'Giao việc',
        body: 'Mở danh sách việc được giao cho bạn (có badge nếu còn việc chưa xử lý).',
        advanceOn: 'next',
        waitForPath: CRM,
        placement: 'bottom',
      },
      {
        target: 'crm-kanban-settings',
        title: 'Nút Tùy chỉnh',
        body: 'Bánh răng «Tùy chỉnh» — chỉnh cách cuộn cột và giới hạn số thẻ tải trên Kanban.',
        advanceOn: 'next',
        waitForPath: CRM,
        placement: 'left',
      },
      {
        target: 'crm-kanban-settings-menu',
        title: 'Menu Tùy chỉnh',
        body: 'Cuộn chung / cuộn riêng từng cột, và trần số thẻ tự tải khi cuộn. Đổi xong click ra ngoài hoặc Tiếp.',
        advanceOn: 'next',
        ensureOpen: 'crm-kanban-settings-menu',
        waitForPath: CRM,
        placement: 'left',
      },
      {
        target: 'crm-kpis',
        title: 'Thẻ KPI',
        body: 'Tổng Lead, đang xử lý, tỷ lệ chuyển đổi, điểm KPI tháng… Bấm tiêu đề khu vực để thu/gọn.',
        advanceOn: 'next',
        waitForPath: CRM,
      },
      {
        target: 'kanban-pipeline',
        title: 'Các cột Kanban',
        body: 'Mỗi cột = một giai đoạn (Mới, Liên hệ…). Thẻ nằm trong cột hiện tại của khách.',
        advanceOn: 'next',
        waitForPath: CRM,
      },
      {
        target: 'kanban-column-select-all',
        title: 'Chọn cả cột',
        body: 'Icon ✓ trên đầu cột — chọn hoặc bỏ chọn mọi thẻ trong cột đó (để gộp / chuyển hàng loạt).',
        advanceOn: 'next',
        waitForPath: CRM,
        missingHint: 'Cột trống hoặc chưa tải thẻ — tạo Lead rồi học lại bước này.',
      },
      {
        target: 'kanban-card',
        title: 'Một thẻ Lead',
        body: 'Thẻ hiện tên, khách, giá trị… Bấm thẻ để mở chi tiết (học ở nhiệm vụ Chi tiết).',
        advanceOn: 'next',
        waitForPath: CRM,
        missingHint: 'Chưa có thẻ — tạo Lead ở nhiệm vụ «Tạo Lead và Deal» rồi học lại.',
      },
      {
        target: 'kanban-card-select',
        title: 'Ô chọn trên thẻ',
        body: 'Góc trên thẻ (hiện khi rê chuột) — chọn thẻ để gộp, xóa hoặc chuyển giai đoạn hàng loạt.',
        advanceOn: 'next',
        waitForPath: CRM,
        missingHint: 'Chưa có thẻ để chọn — tạo Lead rồi học lại.',
      },
      {
        target: 'crm-bulk-bar',
        title: 'Thanh thao tác hàng loạt',
        body: 'Khi đã chọn ≥1 thẻ, thanh vàng hiện phía trên bảng: gộp, gán, xóa, chuyển giai đoạn.',
        advanceOn: 'next',
        ensureOpen: 'crm-select-cards-1',
        waitForPath: CRM,
        missingHint: 'Chưa chọn được thẻ — cần ít nhất 1 Lead trên bảng.',
      },
      {
        target: 'crm-bulk-assign',
        title: 'Gán phụ trách',
        body: 'Gán (hoặc đổi) người phụ trách cho các thẻ đã chọn — thường dành cho admin.',
        advanceOn: 'next',
        ensureOpen: 'crm-select-cards-1',
        waitForPath: CRM,
        optional: true,
        missingHint: 'Nút chỉ hiện với quyền admin — bỏ qua nếu bạn không thấy.',
      },
      {
        target: 'crm-bulk-merge',
        title: 'Gộp đã chọn',
        body: 'Cần ≥2 thẻ đã chọn. Gộp trùng Lead/Deal thành một bản ghi.',
        advanceOn: 'next',
        ensureOpen: 'crm-select-cards-2',
        waitForPath: CRM,
        optional: true,
        missingHint: 'Cần ít nhất 2 thẻ trên bảng để học bước Gộp.',
      },
      {
        target: 'crm-bulk-stage',
        title: 'Chọn cột đích',
        body: 'Chọn giai đoạn rồi bấm Chuyển — đưa hàng loạt thẻ đã chọn sang cột đó.',
        advanceOn: 'next',
        ensureOpen: 'crm-select-cards-1',
        waitForPath: CRM,
        missingHint: 'Thanh hàng loạt chưa mở — chọn lại thẻ rồi học lại.',
      },
      {
        target: 'kanban-card',
        title: 'Quay lại một thẻ',
        body: 'Sau thao tác hàng loạt — nhìn lại thẻ trên bảng. Cụm nút nằm ở cuối thẻ.',
        advanceOn: 'next',
        ensureClose: 'crm-bulk-selection',
        waitForPath: CRM,
        missingHint: 'Chưa có thẻ — tạo Lead rồi học lại.',
      },
      {
        target: 'kanban-card-actions',
        title: 'Cụm nút trên thẻ',
        body: 'Cuối thẻ (viền tím nhạt): chuyển cột nhanh, bình luận nhanh, menu thêm (ghim, hạn…).',
        advanceOn: 'next',
        ensureClose: 'crm-bulk-selection',
        waitForPath: CRM,
        missingHint: 'Chưa có thẻ — tạo Lead rồi học lại.',
      },
      {
        target: 'kanban-quick-move',
        title: 'Chuyển cột nhanh',
        body: 'Icon mũi tên hai chiều trong cụm nút — bấm để chọn giai đoạn đích, không cần kéo thẻ.',
        advanceOn: 'next',
        waitForPath: CRM,
        missingHint: 'Chưa có thẻ hoặc pipeline chỉ một cột.',
      },
    ],
  },

  'crm-create-lead-deal': {
    id: 'crm-create-lead-deal',
    title: 'Tạo Lead và Deal',
    steps: [
      {
        target: 'pipeline-tab-lead',
        title: 'Chọn tab Leads',
        body: 'Trước khi tạo khách mới — chắc chắn đang ở tab Leads.',
        advanceOn: 'next',
        ensureOpen: 'crm-lead-tab',
        waitForPath: CRM,
      },
      {
        target: 'add-lead',
        title: 'Bấm + Thêm Lead',
        body: 'Bấm nút xanh + Thêm Lead để mở form tạo nhanh.',
        advanceOn: 'target-click',
        waitForPath: CRM,
      },
      {
        target: 'new-lead-modal',
        title: 'Cửa sổ form Lead',
        body: 'Form bên trái nhập liệu; bên phải xem trước thẻ Kanban.',
        advanceOn: 'next',
        ensureOpen: 'new-lead-modal',
        waitForPath: CRM,
      },
      {
        target: 'new-lead-title',
        title: 'Ô tên lead',
        body: 'Bắt buộc — đặt tên gợi nhớ (VD: Tủ bếp chữ L - Anh Minh).',
        advanceOn: 'next',
        waitForPath: CRM,
      },
      {
        target: 'new-lead-company',
        title: 'Công ty / khu vực',
        body: 'Chọn công ty (và khu vực nếu có). Admin chọn từ danh sách; nhân viên thường đã gán sẵn.',
        advanceOn: 'next',
        waitForPath: CRM,
        missingHint: 'Ô công ty có thể khác giao diện theo quyền — bấm Tiếp.',
      },
      {
        target: 'new-lead-customer',
        title: 'Khối khách hàng',
        body: 'Điền tên khách (bắt buộc), SĐT, công ty KH nếu có.',
        advanceOn: 'next',
        waitForPath: CRM,
      },
      {
        target: 'new-lead-phone',
        title: 'Số điện thoại',
        body: 'Nên nhập SĐT để quét trùng và gọi lại khách sau này.',
        advanceOn: 'next',
        waitForPath: CRM,
      },
      {
        target: 'new-lead-source',
        title: 'Nguồn & loại Lead',
        body: 'Chọn nguồn (Zalo, Facebook…) và loại Lead nếu công ty có cấu hình.',
        advanceOn: 'next',
        waitForPath: CRM,
        missingHint: 'Không thấy ô nguồn — bấm Tiếp.',
      },
      {
        target: 'new-lead-save',
        title: 'Nút Tạo Lead',
        body: 'Khi đủ thông tin bấm Tạo Lead. Bài này không bắt buộc lưu — có thể Hủy / Tiếp.',
        advanceOn: 'next',
        waitForPath: CRM,
      },
      {
        target: 'new-lead-modal-close',
        title: 'Đóng form Lead',
        body: 'Bấm X (hoặc Hủy) để đóng form trước khi sang tạo Deal.',
        advanceOn: 'target-click',
        waitForPath: CRM,
        missingHint: 'Form đã đóng — bấm Tiếp.',
      },
      {
        target: 'pipeline-tab-deal',
        title: 'Chuyển sang tab Deals',
        body: 'Bấm tab Deals để tạo cơ hội bán hàng trực tiếp.',
        advanceOn: 'target-click',
        ensureClose: 'new-lead-modal',
        waitForPath: CRM,
      },
      {
        target: 'add-lead',
        title: 'Nút + Thêm Deal',
        body: 'Trên tab Deals nút đổi thành + Thêm Deal — bấm để mở form Deal.',
        advanceOn: 'target-click',
        ensureOpen: 'crm-deal-tab',
        waitForPath: CRM,
      },
      {
        target: 'new-deal-modal',
        title: 'Form tạo Deal',
        body: 'Tương tự Lead: tên deal, khách, giá trị… Có thể tạo Deal không qua Lead.',
        advanceOn: 'next',
        ensureOpen: 'new-deal-modal',
        waitForPath: CRM,
      },
      {
        target: 'new-deal-title',
        title: 'Ô tên Deal',
        body: 'Nhập tên Deal (bắt buộc) — thường gắn với công trình / khách.',
        advanceOn: 'next',
        waitForPath: CRM,
      },
      {
        target: 'new-deal-save',
        title: 'Nút Tạo Deal',
        body: 'Bấm Tạo Deal khi đủ thông tin — hoặc đóng form. Xong nhiệm vụ này.',
        advanceOn: 'next',
        waitForPath: CRM,
      },
    ],
  },

  'crm-lead-deal-detail': {
    id: 'crm-lead-deal-detail',
    title: 'Chi tiết Lead / Deal',
    steps: [
      {
        target: 'pipeline-tab-lead',
        title: 'Mở từ tab Leads',
        body: 'Lead và Deal dùng chung trang chi tiết (/crm/leads/…). Bắt đầu từ tab Leads trên Dashboard.',
        advanceOn: 'next',
        ensureOpen: 'crm-lead-tab',
        waitForPath: CRM,
      },
      {
        target: 'pipeline-tab-deal',
        title: 'Hoặc từ tab Deals',
        body: 'Deal cũng mở cùng kiểu trang chi tiết. Học xong có thể thử lại với thẻ Deal.',
        advanceOn: 'next',
        waitForPath: CRM,
      },
      {
        target: 'pipeline-tab-lead',
        title: 'Quay tab Leads',
        body: 'Bấm tab Leads — chọn một thẻ để vào hồ sơ.',
        advanceOn: 'target-click',
        waitForPath: CRM,
      },
      {
        target: 'kanban-card',
        title: 'Mở một thẻ',
        body: 'Bấm vào thẻ được khoanh — hoặc bấm Tiếp — để mở trang chi tiết Lead/Deal.',
        advanceOn: 'target-click',
        ensureOpen: 'crm-lead-tab',
        waitForPath: CRM,
        missingHint: 'Chưa có thẻ — tạo ở nhiệm vụ «Tạo Lead và Deal» rồi học lại.',
      },
      {
        target: 'lead-detail-header',
        title: 'Thanh tiêu đề hồ sơ',
        body: 'Badge LEAD hoặc DEAL, mã, tên. Bấm tên để sửa (nếu có quyền). Lead và Deal khác nhau chủ yếu ở nút hành động bên phải.',
        advanceOn: 'next',
        waitForPath: LEAD,
        missingHint: 'Không thấy header hồ sơ — tải lại trang rồi bấm «Hướng dẫn chi tiết».',
      },
      {
        target: 'lead-detail-back',
        title: 'Quay lại Kanban',
        body: 'Mũi tên trái — về Dashboard, giữ bộ lọc và tab (Lead/Deal) đã chọn.',
        advanceOn: 'next',
        waitForPath: LEAD,
      },
      {
        target: 'lead-detail-pin',
        title: 'Ghim lên đầu cột',
        body: 'Ghim để thẻ nổi đầu cột Kanban — theo dõi khách ưu tiên.',
        advanceOn: 'next',
        waitForPath: LEAD,
      },
      {
        target: 'lead-detail-interact',
        title: 'Đã tương tác',
        body: 'Đánh dấu đã liên hệ khách (gọi/Zalo/gặp). Giúp lọc và nhận biết thẻ đã chăm sóc.',
        advanceOn: 'next',
        waitForPath: LEAD,
      },
      {
        target: 'lead-detail-actions',
        title: 'Cụm nút hành động',
        body: 'Bên phải header: Chuyển Deal / Trả về Lead, đổi phụ trách, tạo sự kiện, Import Excel — hiện tùy loại Lead/Deal và quyền.',
        advanceOn: 'next',
        waitForPath: LEAD,
      },
      {
        target: 'lead-convert-deal',
        title: 'Chuyển Deal (Lead)',
        body: 'Chỉ trên Lead đủ điều kiện. Khi khách sẵn sàng báo giá/chốt — bấm để tạo Deal gắn pipeline.',
        advanceOn: 'next',
        waitForPath: LEAD,
        optional: true,
        placement: 'left',
        missingHint: 'Không thấy nút: đang mở Deal, thiếu SĐT/KH, hoặc thiếu quyền — Tiếp.',
      },
      {
        target: 'lead-revert-lead',
        title: 'Trả về Lead (Deal)',
        body: 'Chỉ trên Deal — trả lại Lead và chọn lại phụ trách khi cần làm ấm lại khách.',
        advanceOn: 'next',
        waitForPath: LEAD,
        optional: true,
        placement: 'left',
        missingHint: 'Nút chỉ hiện với Deal (và đủ quyền) — đang mở Lead thì Tiếp.',
      },
      {
        target: 'lead-transfer-assignee',
        title: 'Chuyển người phụ trách',
        body: 'Đổi công ty/khu vực và người phụ trách hồ sơ — thường dùng khi bàn giao nội bộ.',
        advanceOn: 'next',
        waitForPath: LEAD,
        optional: true,
        placement: 'left',
        missingHint: 'Không thấy nút theo quyền — Tiếp.',
      },
      {
        target: 'lead-create-event',
        title: 'Nút Tạo sự kiện',
        body: 'Trên hồ sơ Lead/Deal — bấm «Tạo sự kiện» để lên lịch hẹn gắn sẵn khách + deal này (khảo sát, ký HĐ, lắp đặt…). Sự kiện sẽ hiện trên trang Sự kiện CRM.',
        advanceOn: 'next',
        waitForPath: LEAD,
        placement: 'left',
      },
      {
        target: 'event-create-modal',
        title: 'Form tạo sự kiện từ hồ sơ',
        body: 'Tour tự mở form. Lead/Deal và khách thường đã gắn sẵn (không cần chọn lại). Điền loại, tiêu đề, ngày giờ rồi lưu — cả team thấy trên lịch.',
        advanceOn: 'next',
        ensureOpen: 'lead-event-modal',
        waitForPath: LEAD,
      },
      {
        target: 'event-create-type',
        title: 'Chọn loại sự kiện',
        body: 'Chọn loại (Khảo sát, Ký HĐ…). Tiêu đề thường tự thêm tiền tố theo loại — sửa tiếp tên khách/địa điểm cho dễ nhận.',
        advanceOn: 'next',
        ensureOpen: 'lead-event-modal',
        waitForPath: LEAD,
      },
      {
        target: 'event-create-title',
        title: 'Tiêu đề sự kiện',
        body: 'Bắt buộc. Nên ghi rõ việc + khách (VD: Khảo sát - Anh Minh Q7).',
        advanceOn: 'next',
        ensureOpen: 'lead-event-modal',
        waitForPath: LEAD,
      },
      {
        target: 'event-create-datetime',
        title: 'Ngày & giờ',
        body: 'Chọn ngày bắt đầu (bắt buộc) và giờ theo đồng hồ 24h. Có thể thêm giờ kết thúc. Sự kiện hết hạn/đến hạn hiện trên lịch & thông báo.',
        advanceOn: 'next',
        ensureOpen: 'lead-event-modal',
        waitForPath: LEAD,
      },
      {
        target: 'event-create-location',
        title: 'Địa điểm',
        body: 'Địa chỉ gặp khách / công trình — thường lấy sẵn từ hồ sơ, chỉnh nếu cần.',
        advanceOn: 'next',
        ensureOpen: 'lead-event-modal',
        waitForPath: LEAD,
      },
      {
        target: 'event-create-links',
        title: 'Liên kết Lead/Deal & khách',
        body: 'Khi tạo từ hồ sơ, ô Lead/Deal đã khóa sẵn. Từ trang Sự kiện bạn có thể chọn lead/deal khác.',
        advanceOn: 'next',
        ensureOpen: 'lead-event-modal',
        waitForPath: LEAD,
      },
      {
        target: 'event-create-assignee',
        title: 'Người phụ trách sự kiện',
        body: 'Ai chịu trách nhiệm buổi hẹn — mặc định thường là người phụ trách hồ sơ. Đổi nếu nhờ đồng nghiệp đi thay.',
        advanceOn: 'next',
        ensureOpen: 'lead-event-modal',
        waitForPath: LEAD,
      },
      {
        target: 'event-create-participants',
        title: 'Người tham gia',
        body: 'Thêm sale, kỹ thuật, xưởng… Họ nhận sự kiện trên lịch và có thể được nhắc.',
        advanceOn: 'next',
        ensureOpen: 'lead-event-modal',
        waitForPath: LEAD,
      },
      {
        target: 'event-create-save',
        title: 'Lưu sự kiện',
        body: 'Bấm «Tạo sự kiện» khi đủ thông tin. Bài hướng dẫn không bắt buộc lưu — có thể Hủy / đóng form rồi Tiếp.',
        advanceOn: 'next',
        ensureOpen: 'lead-event-modal',
        waitForPath: LEAD,
      },
      {
        target: 'event-create-modal-close',
        title: 'Đóng form sự kiện',
        body: 'Đóng form để tiếp tục xem các phần khác của hồ sơ. Xem / sửa sự kiện sau tại menu CRM → Sự kiện.',
        advanceOn: 'target-click',
        ensureOpen: 'lead-event-modal',
        waitForPath: LEAD,
        missingHint: 'Form đã đóng — bấm Tiếp.',
      },
      {
        target: 'lead-pipeline-stepper',
        title: 'Thanh giai đoạn & sự kiện tự tạo',
        body: 'Đổi giai đoạn tại đây (hoặc kéo thẻ Kanban). Một số cột bật «tạo sự kiện khi vào» — hệ thống hỏi lịch hẹn khi chuyển cột (vd. khảo sát).',
        advanceOn: 'next',
        ensureClose: 'event-create-modal',
        waitForPath: LEAD,
      },
      {
        target: 'lead-detail-tabs',
        title: 'Thanh tab hồ sơ',
        body: 'Cột phải là nơi làm việc chính. Quan trọng nhất: tab Bình luận — trao đổi nội bộ trên từng Lead/Deal. Các tab khác hỗ trợ task, file, đặt hàng…',
        advanceOn: 'next',
        scroll: false,
        waitForPath: LEAD,
      },
      {
        target: 'lead-info-customer',
        title: 'Khối Khách hàng',
        body: 'Cột trái — tên, SĐT, email khách. Bấm từng dòng để sửa nhanh.',
        advanceOn: 'next',
        waitForPath: LEAD,
      },
      {
        target: 'lead-info-panel',
        title: 'Khối Thông tin',
        body: 'Giá trị ước tính, tiền cọc, nguồn, loại, phụ trách, công ty… — chỉnh tại chỗ trên hồ sơ.',
        advanceOn: 'next',
        waitForPath: LEAD,
        missingHint: 'Cuộn cột trái nếu chưa thấy khối Thông tin — hoặc Tiếp.',
      },
      {
        target: 'lead-tab-comments',
        title: '💬 Bình luận — quan trọng nhất',
        body: 'Nơi trao đổi chính về hồ sơ này: hỏi đồng nghiệp, @mention, đính kèm, cập nhật tiến độ. Ưu tiên viết ở đây thay vì chat riêng ngoài app.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-comments',
        scroll: false,
        waitForPath: LEAD,
      },
      {
        target: 'lead-comments-panel',
        title: 'Khung trao đổi Bình luận',
        body: 'Gõ tin → gửi; dùng @ để gọi người phụ trách/thành viên. Mọi người mở cùng Lead/Deal đều thấy lịch sử — bàn giao và làm việc nhóm rõ ràng.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-comments',
        scroll: false,
        waitForPath: LEAD,
        missingHint: 'Đang mở tab Bình luận… nếu chưa thấy khung chat — Tiếp.',
      },
      {
        target: 'lead-tab-tasks',
        title: 'Tab Công việc',
        body: 'Tour tự mở tab ✅ Công việc — danh sách nhiệm vụ theo giai đoạn (gọi khách, khảo sát, báo giá…). Thường phải hoàn thành task trước khi kéo thẻ sang cột mới.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-tasks',
        scroll: false,
        waitForPath: LEAD,
      },
      {
        target: 'crm-task-row',
        title: 'Một dòng nhiệm vụ',
        body: 'Mỗi dòng = 1 việc phải làm. Bấm tên để mở chi tiết (ghi chú/file). Hàng nút bên phải là thao tác nhanh.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-tasks',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Chưa có nhiệm vụ trên hồ sơ — Tiếp.',
      },
      {
        target: 'crm-task-complete',
        title: 'Hoàn thành nhiệm vụ',
        body: 'Vòng tròn bên trái — bấm để đánh dấu xong / chưa xong. Nhiều cột bắt buộc hoàn thành task trước khi kéo giai đoạn.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-tasks',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Chưa có task — Tiếp.',
      },
      {
        target: 'crm-task-deadline',
        title: 'Ngày hẹn',
        body: '«+ Ngày hẹn» — đặt deadline gọi/gặp khách. Đổi bằng cách bấm lại ngày đã chọn.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-tasks',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Chưa có task — Tiếp.',
      },
      {
        target: 'crm-task-actions',
        title: 'Cụm nút thao tác task',
        body: 'Bên phải dòng: ghi chú & file, gán người, Đủ/Chưa, ghi nhận file, sửa, xóa. Dùng hàng ngày khi xử lý từng việc.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-tasks',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        placement: 'left',
        missingHint: 'Chưa có task — Tiếp.',
      },
      {
        target: 'crm-task-notes-files',
        title: 'Ghi chú & file (kẹp giấy)',
        body: 'Icon kẹp giấy bên phải dòng task. Tour sẽ tự mở khu vực bên dưới: xem mô tả mẫu, checklist, thêm ghi chú nội bộ, tải ảnh/PDF minh chứng. Nhiều giai đoạn bắt buộc có ghi chú hoặc file trước khi đánh dấu xong / kéo cột.',
        advanceOn: 'next',
        ensureOpen: 'crm-task-expand-notes',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Chưa có task — Tiếp.',
      },
      {
        target: 'crm-task-notes-panel',
        title: 'Bên trong: ghi chú, file, checklist',
        body: 'Sau khi mở: (1) Mô tả/hướng dẫn từ mẫu CRM nếu có. (2) Checklist — tick từng mục con, ghi chú/file riêng từng mục. (3) Ô ghi chú task — lưu trao đổi nội bộ về việc này. (4) Đính kèm — upload ảnh khảo sát, báo giá, hợp đồng… File/ghi chú hiện badge trên dòng task; đồng nghiệp mở cùng hồ sơ đều xem được.',
        advanceOn: 'next',
        ensureOpen: 'crm-task-expand-notes',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        placement: 'top',
        missingHint: 'Bấm icon kẹp giấy trên dòng task nếu khung chưa mở — hoặc Tiếp.',
      },
      {
        target: 'crm-task-assign',
        title: 'Gán nhân viên',
        body: 'Gán 1 hoặc nhiều người phụ trách task — họ nhận việc và có thể được nhắc trên Bình luận.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-tasks',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Chưa có task — Tiếp.',
      },
      {
        target: 'crm-task-verdict',
        title: 'Ghi chú nhanh Đủ / Chưa',
        body: 'Bật ô chọn nhanh «Đã đủ thông tin» hoặc «Chưa» (+ lý do) — tiện checklist deal trước khi chuyển cột.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-tasks',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Chưa có task — Tiếp.',
      },
      {
        target: 'crm-task-file-note',
        title: 'Ghi nhận đã có file/ghi chú',
        body: 'Đánh dấu đã bổ sung file hoặc ghi chú cho task (theo dõi đủ thông tin — không tự chặn chuyển giai đoạn).',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-tasks',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Chưa có task — Tiếp.',
      },
      {
        target: 'crm-task-edit',
        title: 'Sửa nhiệm vụ',
        body: 'Mở form chỉnh tiêu đề, mô tả, ưu tiên, người làm…',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-tasks',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Chưa có task — Tiếp.',
      },
      {
        target: 'crm-task-delete',
        title: 'Xóa nhiệm vụ',
        body: 'Xóa task khỏi hồ sơ — dùng khi tạo nhầm. Cẩn thận với task bắt buộc của giai đoạn.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-tasks',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Chưa có task — Tiếp.',
      },
      {
        target: 'lead-tab-shared',
        title: 'Tab Không gian chung',
        body: 'Phối hợp nhiều người/công ty trên một Deal: phân công thành viên, giao việc chéo. Dùng khi cần xưởng, kế toán hoặc sale khác cùng làm.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-shared',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Tab có thể ẩn theo cấu hình — Tiếp.',
      },
      {
        target: 'lead-tab-orders',
        title: 'Tab Đặt hàng',
        body: 'Theo dõi lệnh đặt hàng (PO) gắn Deal: trạng thái đặt vật tư/hàng. Chủ yếu dùng khi đã là Deal có phát sinh mua hàng; Lead ít dùng.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-orders',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Tab có thể trống — Tiếp.',
      },
      {
        target: 'lead-tab-documents',
        title: 'Tab Tài liệu',
        body: 'Kho file trên hồ sơ: bản vẽ, hợp đồng, ảnh khảo sát, báo giá… Upload để xưởng và đồng nghiệp xem ngay trong app (không cần gửi Zalo riêng).',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-documents',
        scroll: false,
        waitForPath: LEAD,
      },
      {
        target: 'lead-tab-drive',
        title: 'Tab Drive',
        body: 'File Google Drive đã gắn vào Lead/Deal — liên kết thư mục/file có sẵn hoặc tải lên Drive. Tiện khi team dùng Drive chung.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-drive',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Tab Drive có thể ẩn theo cấu hình — Tiếp.',
      },
      {
        target: 'lead-tab-notes',
        title: 'Tab Ghi chú & hoạt động',
        body: 'Nhật ký chăm sóc: ghi cuộc gọi, gặp mặt, Zalo với khách. Khác Bình luận: đây là ghi nhận sự kiện với khách; Bình luận là chat nội bộ team.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-notes',
        scroll: false,
        waitForPath: LEAD,
      },
      {
        target: 'lead-tab-team',
        title: 'Tab Thành viên',
        body: 'Ai đang tham gia hồ sơ (CRM / SX / VC). Xem số người theo khối; thêm thành viên để họ nhận thông báo và vào Bình luận/Không gian chung.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-team',
        scroll: false,
        waitForPath: LEAD,
      },
      {
        target: 'lead-tab-voice',
        title: 'Tab Ghi âm',
        body: 'Ghi âm cuộc gọi / ghi chú thoại gắn Lead/Deal — nghe lại khi bàn giao hoặc kiểm tra nội dung trao đổi với khách.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-voice',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Tab Ghi âm có thể chưa bật — Tiếp.',
      },
      {
        target: 'lead-tab-facebook',
        title: 'Tab Facebook',
        body: 'Hội thoại Messenger gắn lead (khi lead đến từ Facebook). Chỉ hiện nếu hồ sơ có kênh Facebook.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-facebook',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Lead/Deal này không từ Facebook — Tiếp.',
      },
      {
        target: 'lead-tab-zalo',
        title: 'Tab Zalo OA',
        body: 'Hội thoại Zalo OA gắn lead. Chỉ hiện khi hồ sơ có kênh Zalo.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-zalo',
        scroll: false,
        waitForPath: LEAD,
        optional: true,
        missingHint: 'Lead/Deal này không từ Zalo — Tiếp.',
      },
      {
        target: 'lead-tab-comments',
        title: 'Nhắc lại: dùng Bình luận',
        body: 'Khi cần hỏi sale, xưởng hay admin về hồ sơ này — vào Bình luận, @ người cần, đính file nếu có. Đây là kênh trao đổi chuẩn trên từng Lead/Deal.',
        advanceOn: 'next',
        ensureOpen: 'lead-tab-comments',
        scroll: false,
        waitForPath: LEAD,
      },
      {
        target: 'lead-detail-back',
        title: 'Kết thúc — về Kanban',
        body: 'Bạn đã nắm các tab. Ưu tiên Bình luận để trao đổi; Công việc để làm task; Tài liệu/Drive để lưu file. Sự kiện: nút Tạo sự kiện trên hồ sơ hoặc trang Sự kiện. Tiếp hoặc mũi tên để về Dashboard.',
        advanceOn: 'next',
        waitForPath: LEAD,
      },
    ],
  },

  'crm-events-page': {
    id: 'crm-events-page',
    title: 'Trang Sự kiện CRM',
    steps: [
      {
        target: 'nav-crm-events',
        title: 'Menu Sự kiện',
        body: 'Trên sidebar CRM (nhóm Tổng quan) — mục Sự kiện: lịch hẹn khảo sát, ký HĐ, lắp đặt… của cả team.',
        advanceOn: 'next',
        ensureOpen: 'crm-overview-menu',
        waitForPath: ['/crm', '/sx/events', '/vc/events'],
      },
      {
        target: 'nav-crm-events',
        title: 'Vào trang Sự kiện',
        body: 'Bấm «Sự kiện» để mở lịch / feed sự kiện.',
        advanceOn: 'target-click',
        ensureOpen: 'crm-overview-menu',
        waitForPath: ['/crm', '/sx/events', '/vc/events'],
      },
      {
        target: 'events-page-header',
        title: 'Trang Sự kiện',
        body: 'Đây là trung tâm lịch CRM: xem theo tháng, feed, hoặc bảng danh sách; lọc theo khối/công ty (admin).',
        advanceOn: 'next',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'events-view-toggle',
        title: 'Đổi cách xem',
        body: 'Lịch (tháng) · Feed (dòng thời gian) · Danh sách (bảng) · Loại (cấu hình loại sự kiện). Mặc định thường là Lịch.',
        advanceOn: 'next',
        ensureOpen: 'events-view-calendar',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'events-view-calendar',
        title: 'Chế độ Lịch',
        body: 'Xem sự kiện theo tháng — bấm ô ngày để tạo nhanh hoặc mở chi tiết sự kiện trên ô.',
        advanceOn: 'next',
        ensureOpen: 'events-view-calendar',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'events-toolbar',
        title: 'Thanh tìm & lọc',
        body: 'Gõ tên sự kiện / khách; mở Bộ lọc theo loại, trạng thái, thời gian, nhân viên…',
        advanceOn: 'next',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'events-search',
        title: 'Ô tìm sự kiện',
        body: 'Tìm theo tiêu đề hoặc thông tin liên quan — kết quả lọc ngay trên lịch/feed.',
        advanceOn: 'next',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'events-filter',
        title: 'Nút Bộ lọc',
        body: 'Lọc loại sự kiện, trạng thái (kế hoạch / đang làm / xong…), khoảng thời gian, người phụ trách.',
        advanceOn: 'next',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'events-board',
        title: 'Bảng lịch / danh sách',
        body: 'Vùng chính hiển thị sự kiện theo chế độ đang chọn. Sự kiện gắn Deal có nút mở nhanh hồ sơ CRM/SX/VC.',
        advanceOn: 'next',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'events-create-btn',
        title: 'Nút Tạo sự kiện',
        body: 'Tạo sự kiện không cần đang mở Lead — chọn lead/deal trong form. (Từ hồ sơ Lead/Deal cũng có nút Tạo sự kiện gắn sẵn.)',
        advanceOn: 'next',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'event-create-modal',
        title: 'Form tạo trên trang Sự kiện',
        body: 'Giống form từ hồ sơ: loại, tiêu đề, ngày giờ, địa điểm, liên kết Lead/Deal, phụ trách, người tham gia.',
        advanceOn: 'next',
        ensureOpen: 'events-create-modal',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'event-create-type',
        title: 'Loại sự kiện',
        body: 'Chọn loại phù hợp — tiêu đề có thể tự điền tiền tố. Admin cấu hình thêm loại ở tab «Loại».',
        advanceOn: 'next',
        ensureOpen: 'events-create-modal',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'event-create-datetime',
        title: 'Ngày giờ trên lịch',
        body: 'Đặt lịch 24h. Sau khi lưu, sự kiện xuất hiện đúng ngày trên lịch tháng.',
        advanceOn: 'next',
        ensureOpen: 'events-create-modal',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'event-create-links',
        title: 'Gắn Lead / Deal',
        body: 'Nên gắn lead/deal để đồng nghiệp mở đúng hồ sơ từ sự kiện. Không gắn vẫn tạo được sự kiện nội bộ.',
        advanceOn: 'next',
        ensureOpen: 'events-create-modal',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'event-create-save',
        title: 'Lưu hoặc đóng',
        body: 'Đủ thông tin thì «Tạo sự kiện». Tour không bắt buộc lưu — đóng form rồi Xong.',
        advanceOn: 'next',
        ensureOpen: 'events-create-modal',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
      {
        target: 'events-page-header',
        title: 'Xong — dùng Sự kiện hàng ngày',
        body: 'Vào đây để xem lịch team; tạo từ trang này hoặc từ nút trên hồ sơ Lead/Deal. Tiếp / Xong để kết thúc hướng dẫn.',
        advanceOn: 'next',
        ensureClose: 'event-create-modal',
        waitForPath: ['/crm/events', '/sx/events', '/vc/events'],
      },
    ],
  },

  'crm-assignments-page': {
    id: 'crm-assignments-page',
    title: 'Trang Giao việc CRM',
    steps: [
      {
        target: 'nav-crm-assignments',
        title: 'Menu Giao việc CRM',
        body: 'Trên sidebar CRM (nhóm Tổng quan) — mục Giao việc CRM: bảng việc độc lập với task gắn Lead/Deal.',
        advanceOn: 'next',
        ensureOpen: 'crm-overview-menu',
        waitForPath: ['/crm', '/crm/assignments', '/sx/assignments', '/vc/assignments'],
        optional: true,
        missingHint: 'Đang ở module SX/VC hoặc menu khác — Tiếp để học trên trang Giao việc.',
      },
      {
        target: 'nav-crm-assignments',
        title: 'Vào trang Giao việc',
        body: 'Bấm «Giao việc CRM» để mở Kanban giao việc.',
        advanceOn: 'target-click',
        ensureOpen: 'crm-overview-menu',
        waitForPath: ['/crm', '/crm/assignments'],
        optional: true,
        missingHint: 'Đã ở trang Giao việc hoặc đang xem bản SX/VC — Tiếp.',
      },
      {
        target: 'assign-page-header',
        title: 'Trang Giao việc',
        body: 'Trung tâm giao việc: xem việc được giao, tạo việc mới, lọc theo NV/trạng thái, đổi chế độ xem (Kanban / Trạng thái / Danh sách…).',
        advanceOn: 'next',
        ensureOpen: 'assign-tab-assignments',
        waitForPath: ASSIGN,
      },
      {
        target: 'assign-page-tabs',
        title: 'Hai tab chính',
        body: '«Giao việc» = bảng việc module này. «Không gian chung» = nhiệm vụ deal được giao cho bạn (gom theo deal).',
        advanceOn: 'next',
        ensureOpen: 'assign-tab-assignments',
        waitForPath: ASSIGN,
      },
      {
        target: 'assign-create-btn',
        title: 'Nút Giao việc',
        body: 'Tạo việc mới: tiêu đề, gắn deal (tuỳ chọn), chọn cột/hạn, giao một hoặc nhiều NV.',
        advanceOn: 'next',
        ensureOpen: 'assign-tab-assignments',
        waitForPath: ASSIGN,
        placement: 'bottom',
      },
      {
        target: 'assign-toolbar',
        title: 'Thanh tìm & chế độ xem',
        body: 'Hàng này gồm ô tìm (mã deal, khách, SĐT…), nút bộ lọc, và chuyển Kanban / các kiểu xem khác.',
        advanceOn: 'next',
        ensureOpen: 'assign-tab-assignments',
        waitForPath: ASSIGN,
      },
      {
        target: 'assign-search',
        title: 'Ô tìm kiếm',
        body: 'Gõ từ khóa — gợi ý deal hiện khi gõ ≥2 ký tự. Chọn dòng để lọc việc gắn deal đó.',
        advanceOn: 'next',
        waitForPath: ASSIGN,
      },
      {
        target: 'assign-filter',
        title: 'Nút bộ lọc',
        body: 'Biểu tượng phễu — mở panel lọc công ty, phòng ban, người nhận, ưu tiên, trạng thái…',
        advanceOn: 'next',
        waitForPath: ASSIGN,
        placement: 'bottom',
      },
      {
        target: 'assign-filter-panel',
        title: 'Panel Bộ lọc',
        body: 'Admin lọc theo công ty/phòng/NV; mọi người lọc ưu tiên & trạng thái. Đóng bằng X hoặc Tiếp.',
        advanceOn: 'next',
        ensureOpen: 'assign-filter-panel',
        waitForPath: ASSIGN,
        placement: 'left',
      },
      {
        target: 'assign-view-mode',
        title: 'Chế độ xem',
        body: 'Kanban là mặc định (cột tự tạo). Cạnh đó nút Thêm để chọn Trạng thái, Danh sách, Planner, Deadline.',
        advanceOn: 'next',
        ensureClose: 'assign-filter-panel',
        waitForPath: ASSIGN,
        placement: 'bottom',
      },
      {
        target: 'crm-view-mode-more',
        title: 'Chọn loại giao diện',
        body: 'Bấm Thêm để mở danh sách chế độ xem khác.',
        advanceOn: 'next',
        waitForPath: ASSIGN,
        placement: 'bottom',
      },
      {
        target: 'crm-view-mode-menu',
        title: 'Menu chế độ xem',
        body: 'Chọn một dòng để đổi giao diện. Tour giữ Kanban — xem các lựa chọn rồi Tiếp.',
        advanceOn: 'next',
        ensureOpen: 'crm-view-mode-menu',
        waitForPath: ASSIGN,
        placement: 'left',
      },
      {
        target: 'assign-kpis',
        title: 'Thẻ KPI',
        body: 'Tổng / chưa làm / đang / xong / quá hạn. Bấm một thẻ để nhảy sang chế độ xem tương ứng (VD: Quá hạn → Deadline).',
        advanceOn: 'next',
        ensureOpen: 'assign-view-kanban',
        waitForPath: ASSIGN,
      },
      {
        target: 'assign-kanban',
        title: 'Các cột Kanban',
        body: 'Mỗi cột = một nhóm việc. Kéo thẻ giữa các cột; thêm cột bằng nút «Thêm cột» cuối hàng.',
        advanceOn: 'next',
        ensureOpen: 'assign-view-kanban',
        waitForPath: ASSIGN,
      },
      {
        target: 'assign-card',
        title: 'Một thẻ việc',
        body: 'Thẻ hiện tiêu đề, ưu tiên, hạn, người nhận. Bấm thẻ để mở chi tiết (bình luận, file yêu cầu/nộp, đổi trạng thái).',
        advanceOn: 'next',
        ensureOpen: 'assign-view-kanban',
        waitForPath: ASSIGN,
        optional: true,
        missingHint: 'Chưa có việc trên bảng — tạo ở bước sau hoặc Tiếp.',
      },
      {
        target: 'assign-create-btn',
        title: 'Mở form giao việc',
        body: 'Bấm «Giao việc» để xem form tạo — tour tự mở nếu chưa thấy.',
        advanceOn: 'next',
        ensureOpen: 'assign-create-modal',
        waitForPath: ASSIGN,
        placement: 'bottom',
      },
      {
        target: 'assign-create-modal',
        title: 'Form giao việc mới',
        body: 'Trái: gắn deal, tiêu đề, mô tả, cột/hạn. Phải: chọn người nhận (một hoặc nhiều NV).',
        advanceOn: 'next',
        ensureOpen: 'assign-create-modal',
        waitForPath: ASSIGN,
      },
      {
        target: 'assign-create-title',
        title: 'Ô tiêu đề',
        body: 'Bắt buộc — mô tả rõ việc cần làm (VD: Gọi xác nhận khảo sát — Anh Minh).',
        advanceOn: 'next',
        ensureOpen: 'assign-create-modal',
        waitForPath: ASSIGN,
      },
      {
        target: 'assign-create-assignees',
        title: 'Chọn người nhận',
        body: 'Tìm NV / chọn cả phòng / cả khu vực. Phải chọn ≥1 người trước khi giao.',
        advanceOn: 'next',
        ensureOpen: 'assign-create-modal',
        waitForPath: ASSIGN,
        placement: 'left',
      },
      {
        target: 'assign-create-save',
        title: 'Nút giao / lưu',
        body: 'Khi đủ tiêu đề + người nhận — bấm giao. Tour không bắt buộc lưu — có thể Huỷ / đóng rồi Tiếp.',
        advanceOn: 'next',
        ensureOpen: 'assign-create-modal',
        waitForPath: ASSIGN,
        placement: 'top',
      },
      {
        target: 'assign-create-modal-close',
        title: 'Đóng form',
        body: 'Bấm X (hoặc Huỷ) để đóng form trước khi xem tab Không gian chung.',
        advanceOn: 'target-click',
        ensureOpen: 'assign-create-modal',
        waitForPath: ASSIGN,
        missingHint: 'Form đã đóng — bấm Tiếp.',
      },
      {
        target: 'assign-tab-private',
        title: 'Tab Không gian chung',
        body: 'Bấm tab này — xem nhiệm vụ deal được giao cho bạn, nhóm theo deal / trạng thái / deadline.',
        advanceOn: 'next',
        ensureClose: 'assign-create-modal',
        ensureOpen: 'assign-tab-private',
        waitForPath: ASSIGN,
      },
      {
        target: 'assign-private-board',
        title: 'Hộp thư deal',
        body: 'Danh sách nhiệm vụ từ Lead/Deal (và giao việc gắn deal). Đổi cách nhóm bằng chế độ xem trên thanh công cụ tab này.',
        advanceOn: 'next',
        ensureOpen: 'assign-tab-private',
        waitForPath: ASSIGN,
        optional: true,
        missingHint: 'Chưa có nhiệm vụ deal — bình thường nếu bạn chưa được giao. Tiếp.',
      },
      {
        target: 'assign-tab-assignments',
        title: 'Quay lại Giao việc',
        body: 'Bấm tab Giao việc để về Kanban chính — nơi tạo và theo dõi việc hàng ngày.',
        advanceOn: 'next',
        ensureOpen: 'assign-tab-assignments',
        waitForPath: ASSIGN,
      },
      {
        target: 'assign-page-header',
        title: 'Xong — dùng Giao việc hàng ngày',
        body: 'Tạo việc bằng nút xanh; kéo thẻ đổi cột; mở thẻ để bình luận & nộp file. Không gian chung để theo dõi việc gắn deal. Tiếp / Xong để kết thúc.',
        advanceOn: 'next',
        ensureOpen: 'assign-tab-assignments',
        waitForPath: ASSIGN,
      },
    ],
  },
};

export const CRM_EVENTS_PAGE_TOUR_ID = 'crm-events-page';
export const CRM_ASSIGNMENTS_PAGE_TOUR_ID = 'crm-assignments-page';

export const CRM_FAMILIAR_TOUR_ID = 'crm-familiar';
export const CRM_LEAD_DEAL_DETAIL_TOUR_ID = 'crm-lead-deal-detail';

export function getTour(tourId) {
  return TOURS[tourId] || null;
}

/** Chỉ số bước đầu tiên khớp path hiện tại (ưu tiên waitForPath dài nhất, vd. /crm/leads hơn /crm). */
export function resolveTourStartIndex(tourId, pathname) {
  const def = getTour(tourId);
  if (!def?.steps?.length) return 0;
  const path = String(pathname || '');
  let bestLen = -1;
  def.steps.forEach((s) => {
    if (!s.waitForPath) return;
    const prefixes = Array.isArray(s.waitForPath) ? s.waitForPath : [s.waitForPath];
    for (const p of prefixes) {
      if (p && path.startsWith(p) && String(p).length > bestLen) {
        bestLen = String(p).length;
      }
    }
  });
  if (bestLen < 0) return 0;
  const idx = def.steps.findIndex((s) => {
    if (!s.waitForPath) return false;
    const prefixes = Array.isArray(s.waitForPath) ? s.waitForPath : [s.waitForPath];
    return prefixes.some((p) => p && path.startsWith(p) && String(p).length === bestLen);
  });
  return idx >= 0 ? idx : 0;
}
